Repository ppy/osu, pull requests merged in 2018-03, with the labels that each got.

#2143 Don't use BufferedContainer for OsuLogo
  osu.Game/Screens/Menu/OsuLogo.cs
Labels: code quality, performance

#2144 Fix FastRandom using uint instead of int for NextDouble()
  osu.Game.Rulesets.Mania/MathUtils/FastRandom.cs
Labels: beatmap parsing, compatibility

#2095 Implement hitobject selection overlays in the editor
  osu.Game.Rulesets.Osu/Edit/Layers/Selection/OsuHitObjectOverlayLayer.cs
  osu.Game.Rulesets.Osu/Edit/Layers/Selection/Overlays/HitCircleOverlay.cs
  osu.Game.Rulesets.Osu/Edit/Layers/Selection/Overlays/SliderCircleOverlay.cs
  osu.Game.Rulesets.Osu/Edit/Layers/Selection/Overlays/SliderOverlay.cs
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/osu.Game.Rulesets.Osu.csproj
  osu.Game.Tests/Visual/TestCaseEditorSelectionLayer.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Edit/Layers/BorderLayer.cs
  osu.Game/Rulesets/Edit/Layers/Selection/HitObjectOverlay.cs
  osu.Game/Rulesets/Edit/Layers/Selection/HitObjectOverlayLayer.cs
  osu.Game/Rulesets/Edit/Layers/Selection/SelectionLayer.cs
  osu.Game/Rulesets/UI/ScalableContainer.cs
  osu.Game/osu.Game.csproj
Labels: editor, pending review

#2146 Fix HR not properly applying to sliders
  osu.Game.Rulesets.Osu/Mods/OsuModHardRock.cs
Labels: resolves issue

#2153 Implement an interface for beatmap conversion tests
  osu.Game.Rulesets.Catch/Resources/Testing/Beatmaps/basic-expected-conversion.json
  osu.Game.Rulesets.Catch/Resources/Testing/Beatmaps/basic.osu
  osu.Game.Rulesets.Catch/Tests/CatchBeatmapConversionTest.cs
  osu.Game.Rulesets.Catch/osu.Game.Rulesets.Catch.csproj
  osu.Game.Rulesets.Mania/Resources/Testing/Beatmaps/basic-expected-conversion.json
  osu.Game.Rulesets.Mania/Resources/Testing/Beatmaps/basic.osu
  osu.Game.Rulesets.Mania/Tests/ManiaBeatmapConversionTest.cs
  osu.Game.Rulesets.Mania/osu.Game.Rulesets.Mania.csproj
  osu.Game.Rulesets.Osu/Resources/Testing/Beatmaps/basic-expected-conversion.json
  osu.Game.Rulesets.Osu/Resources/Testing/Beatmaps/basic.osu
  osu.Game.Rulesets.Osu/Tests/OsuBeatmapConversionTest.cs
  osu.Game.Rulesets.Osu/osu.Game.Rulesets.Osu.csproj
  osu.Game.Rulesets.Taiko/Resources/Testing/Beatmaps/basic-expected-conversion.json
  osu.Game.Rulesets.Taiko/Resources/Testing/Beatmaps/basic.osu
  osu.Game.Rulesets.Taiko/Tests/TaikoBeatmapConversionTest.cs
  osu.Game.Rulesets.Taiko/osu.Game.Rulesets.Taiko.csproj
  osu.Game/Beatmaps/BeatmapConverter.cs
  osu.Game/Beatmaps/IBeatmapConverter.cs
  osu.Game/Tests/Beatmaps/BeatmapConversionTest.cs
  osu.Game/osu.Game.csproj
Labels: beatmap conversion, testing

#2155 Fix linear perfect curves not using the linear curve approximator
  osu.Game.Rulesets.Osu/Resources/Testing/Beatmaps/colinear-perfect-curve-expected-conversion.json
  osu.Game.Rulesets.Osu/Resources/Testing/Beatmaps/colinear-perfect-curve.osu
  osu.Game.Rulesets.Osu/Tests/OsuBeatmapConversionTest.cs
  osu.Game.Rulesets.Osu/osu.Game.Rulesets.Osu.csproj
  osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs
Labels: beatmap parsing, compatibility

#2142 Fix legacy catch replay input not being scaled to the playfield's width
  osu.Game.Rulesets.Catch/Replays/CatchReplayFrame.cs
Labels: resolves issue

#2166 Add legacy timing offsets
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Beatmaps/Formats/OsuJsonDecoderTest.cs
  osu.Game.Tests/Beatmaps/IO/OszArchiveReaderTest.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Tests/Beatmaps/BeatmapConversionTest.cs
Labels: audio, beatmap parsing, compatibility

#2161 Fix parallax container during rewinds
  osu.Game/Graphics/Containers/ParallaxContainer.cs
Labels: bug, pending review, user interface

#2163 Fix hard crash due to spinner spin requirement being zero
  osu.Game.Rulesets.Osu/Objects/Spinner.cs
Labels: resolves issue

#2162 Add rewind support for storyboards
  osu.Game/Storyboards/Drawables/DrawableStoryboard.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardAnimation.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardSprite.cs
Labels: pending review, storyboard

#2164 Fix skin file path lookup performance
  osu.Game/Skinning/LegacySkin.cs
Labels: pending review, performance, regression, skinning

#2171 Fix taiko drumrolls potentially getting incorrect judgements
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableDrumRoll.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Rulesets/UI/Scrolling/Visualisers/OverlappingSpeedChangeVisualiser.cs
  osu.Game/Rulesets/UI/Scrolling/Visualisers/SequentialSpeedChangeVisualiser.cs
Labels: gameplay, osu!taiko

#2167 Fix incorrect slider-to-drumroll conversions in taiko
  osu.Game.Rulesets.Taiko/Beatmaps/TaikoBeatmapConverter.cs
  osu.Game.Rulesets.Taiko/Resources/Testing/Beatmaps/slider-generating-drumroll-expected-conversion.json
  osu.Game.Rulesets.Taiko/Resources/Testing/Beatmaps/slider-generating-drumroll.osu
  osu.Game.Rulesets.Taiko/Tests/TaikoBeatmapConversionTest.cs
  osu.Game.Rulesets.Taiko/osu.Game.Rulesets.Taiko.csproj
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Beatmaps/Formats/OsuJsonDecoderTest.cs
  osu.Game/Beatmaps/BeatmapDifficulty.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Tests/Beatmaps/BeatmapConversionTest.cs
Labels: beatmap conversion

#2174 Fix left and right arrows keys in chat overlay not working
  osu.Game/Graphics/UserInterface/FocusedTextBox.cs
  osu.Game/Graphics/UserInterface/SearchTextBox.cs
Labels: resolves issue

#2176 Make LegacyID nullable
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game/Rulesets/Ruleset.cs
Labels: code quality, database

#2177 Fix arbitrary API request errors getting identified as timeouts
  osu.Game/Online/API/APIAccess.cs
Labels: bug, online

#2178 SliderTick transform improvements
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderTick.cs
Labels: code quality, gameplay, osu!

#2120 Add recent section to user profile
  osu.Game.Tests/Visual/TestCaseUserProfileRecentSection.cs
  osu.Game.Tests/osu.Game.Tests.csproj
  osu.Game/Graphics/Containers/LinkFlowContainer.cs
  osu.Game/Online/API/Requests/GetUserRecentActivitiesRequest.cs
  osu.Game/Online/Chat/MessageFormatter.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Profile/Sections/Recent/DrawableRecentActivity.cs
  osu.Game/Overlays/Profile/Sections/Recent/MedalIcon.cs
  osu.Game/Overlays/Profile/Sections/Recent/PaginatedRecentActivityContainer.cs
  osu.Game/Overlays/Profile/Sections/RecentSection.cs
  osu.Game/Overlays/UserProfileOverlay.cs
  osu.Game/osu.Game.csproj
Labels: online, pending review, user interface

#2183 Match HP drain harshness closer to stable
  osu.Game.Rulesets.Osu/Scoring/OsuScoreProcessor.cs
Labels: gameplay, osu!, pending review

#2186 Fix difficulty calculator regression when applying mods
  osu.Game/Beatmaps/DifficultyCalculator.cs
Labels: bug, gameplay, pending review

#2045 Allow previewing background adjustments at player loading screen
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/Screens/Play/ScreenWithBeatmapBackground.cs
  osu.Game/osu.Game.csproj
Labels: gameplay, pending review

#2194 Split out the slider head into a separate drawable hitobject
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderHead.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderTail.cs
  osu.Game.Rulesets.Osu/osu.Game.Rulesets.Osu.csproj
Labels: code quality, osu!

#2159 Make song select ensure current beatmap is always playable in the active ruleset
  osu.Game.Tests/Visual/TestCaseBeatmapCarousel.cs
  osu.Game/Screens/Select/BeatmapCarousel.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#2182 Remove judgements when deciding a new judgement for a HitObject
  osu.Game.Rulesets.Mania/UI/DrawableManiaJudgement.cs
  osu.Game.Rulesets.Mania/UI/ManiaStage.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuJudgement.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game.Rulesets.Taiko/UI/DrawableTaikoJudgement.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs
  osu.Game/Rulesets/Judgements/DrawableJudgement.cs
  osu.Game/Rulesets/UI/JudgementContainer.cs
  osu.Game/osu.Game.csproj
Labels: bug, gameplay, pending review

#2185 Add drawable to display (and update) relative dates
  osu.Game/Graphics/DrawableDate.cs
  osu.Game/Overlays/Profile/ProfileHeader.cs
  osu.Game/Overlays/Profile/Sections/Ranks/DrawableProfileScore.cs
  osu.Game/Overlays/Profile/Sections/Recent/DrawableRecentActivity.cs
  osu.Game/osu.Game.csproj
Labels: pending review, user interface

#2189 Interpolate ParallaxContainer's scale
  osu.Game/Graphics/Containers/ParallaxContainer.cs
Labels: gameplay, pending review, user interface

#2198 Fix login failure for users with no country rank
  osu.Game.Tests/Visual/TestCaseUserProfile.cs
  osu.Game/Overlays/Profile/RankGraph.cs
  osu.Game/Overlays/UserProfileOverlay.cs
  osu.Game/Users/UserStatistics.cs
Labels: resolves issue

#2197 Update ISSUE_TEMPLATE
  ISSUE_TEMPLATE.md
Labels: code quality

#2188 Add Mirror Mod for Mania
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModMirror.cs
  osu.Game.Rulesets.Mania/osu.Game.Rulesets.Mania.csproj
Labels: resolves issue

#2191 Rework decoders to be more flexible
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Beatmaps/Formats/LegacyStoryboardDecoderTest.cs
  osu.Game.Tests/Beatmaps/Formats/OsuJsonDecoderTest.cs
  osu.Game.Tests/Beatmaps/IO/OszArchiveReaderTest.cs
  osu.Game/Beatmaps/Beatmap.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/BeatmapManager_WorkingBeatmap.cs
  osu.Game/Beatmaps/Formats/Decoder.cs
  osu.Game/Beatmaps/Formats/JsonBeatmapDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyStoryboardDecoder.cs
  osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs
  osu.Game/Tests/Beatmaps/BeatmapConversionTest.cs
  osu.Game/Tests/Visual/TestCasePlayer.cs
Labels: beatmap parsing, code quality

#2124 Implement mania star difficulty calculation
  osu.Game.Rulesets.Mania/ManiaDifficultyCalculator.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Mania/Objects/ManiaHitObjectDifficulty.cs
  osu.Game.Rulesets.Mania/osu.Game.Rulesets.Mania.csproj
  osu.Game/Beatmaps/DifficultyCalculator.cs
  osu.Game/Rulesets/Scoring/PerformanceCalculator.cs
Labels: beatmap parsing, pending review

#2181 Add skin support for hit judgements
  osu.Game.Rulesets.Mania/UI/DrawableManiaJudgement.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuJudgement.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/ExplodePiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/FlashPiece.cs
  osu.Game/Rulesets/Judgements/DrawableJudgement.cs
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/Skinning/SkinnableDrawable.cs
Labels: pending review, skinning

#2205 Move test beatmap from TestCasePlayer into an instantiable class
  osu.Game.Rulesets.Catch/Tests/TestCaseBananaShower.cs
  osu.Game.Rulesets.Catch/Tests/TestCaseCatchStacker.cs
  osu.Game.Rulesets.Catch/Tests/TestCaseHyperdash.cs
  osu.Game/Tests/Beatmaps/TestBeatmap.cs
  osu.Game/Tests/Beatmaps/TestWorkingBeatmap.cs
  osu.Game/Tests/Visual/TestCasePlayer.cs
  osu.Game/osu.Game.csproj
Labels: code quality, testing

#2206 Create a base TestCaseEditor for rulesets to derive
  osu.Game.Rulesets.Osu/Tests/TestCaseEditor.cs
  osu.Game.Rulesets.Osu/osu.Game.Rulesets.Osu.csproj
  osu.Game.Tests/Visual/TestCaseEditor.cs
  osu.Game.Tests/osu.Game.Tests.csproj
  osu.Game/Tests/Visual/EditorTestCase.cs
  osu.Game/osu.Game.csproj
Labels: code quality, editor, testing

#2169 Make osu!mania conversions more in-line with osu!stable
  osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/DistanceObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/EndTimeObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/HitObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/PatternGenerator.cs
  osu.Game.Rulesets.Mania/Tests/ManiaBeatmapConversionTest.cs
Labels: resolves issue

#2195 Implement an interface for moving hitobjects in the editor
  osu.Game.Rulesets.Osu/Edit/Layers/Selection/OsuHitObjectOverlayLayer.cs
  osu.Game.Rulesets.Osu/Edit/Layers/Selection/Overlays/HitCircleMask.cs
  osu.Game.Rulesets.Osu/Edit/Layers/Selection/Overlays/SliderCircleMask.cs
  osu.Game.Rulesets.Osu/Edit/Layers/Selection/Overlays/SliderMask.cs
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/OsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Rulesets.Osu/Objects/SliderCircle.cs
  osu.Game.Rulesets.Osu/osu.Game.Rulesets.Osu.csproj
  osu.Game.Tests/Visual/TestCaseEditorSelectionLayer.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Edit/HitObjectMask.cs
  osu.Game/Rulesets/Edit/Layers/Selection/CaptureBox.cs
  osu.Game/Rulesets/Edit/Layers/Selection/HitObjectOverlay.cs
  osu.Game/Rulesets/Edit/Layers/Selection/SelectionBox.cs
  osu.Game/Rulesets/Edit/Types/IHasEditablePosition.cs
  osu.Game/Screens/Edit/Screens/Compose/Layers/BorderLayer.cs
  osu.Game/Screens/Edit/Screens/Compose/Layers/HitObjectMaskLayer.cs
  osu.Game/Screens/Edit/Screens/Compose/Layers/SelectionBox.cs
  osu.Game/Screens/Edit/Screens/Compose/Layers/SelectionLayer.cs
  osu.Game/Screens/Edit/Screens/EditorScreen.cs
  osu.Game/osu.Game.csproj
Labels: editor, pending review

#2078 Improve mouse-based load inhibition at player loading screen
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/Screens/Play/PlayerSettings/PlayerSettingsGroup.cs
Labels: pending review

#2215 Fix beatmap combo colours not being applied
  osu.Game.Rulesets.Catch/Beatmaps/CatchBeatmapProcessor.cs
  osu.Game.Rulesets.Osu/Beatmaps/OsuBeatmapProcessor.cs
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Beatmaps/Formats/OsuJsonDecoderTest.cs
  osu.Game/Beatmaps/Beatmap.cs
  osu.Game/Beatmaps/BeatmapConverter.cs
  osu.Game/Beatmaps/Formats/IHasComboColours.cs
  osu.Game/Beatmaps/Formats/IHasCustomColours.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyStoryboardDecoder.cs
  osu.Game/osu.Game.csproj
Labels: beatmap conversion, pending review, skinning

#2219 Improve mods description and adjust multipliers to match stable
  osu.Game.Rulesets.Catch/Mods/CatchModDaycore.cs
  osu.Game.Rulesets.Catch/Mods/CatchModEasy.cs
  osu.Game.Rulesets.Catch/Mods/CatchModHalfTime.cs
  osu.Game.Rulesets.Catch/Mods/CatchModHardRock.cs
  osu.Game.Rulesets.Catch/Mods/CatchModHidden.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModDaycore.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModDoubleTime.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModDualStages.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModEasy.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModFadeIn.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModFlashlight.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModHalfTime.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModHardRock.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModHidden.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModKey1.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModKey2.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModKey3.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModKey4.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModKey5.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModKey6.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModKey7.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModKey8.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModKey9.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModNightcore.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModRandom.cs
  osu.Game.Rulesets.Osu/Mods/OsuModDaycore.cs
  osu.Game.Rulesets.Osu/Mods/OsuModEasy.cs
  osu.Game.Rulesets.Osu/Mods/OsuModHalfTime.cs
  osu.Game.Rulesets.Osu/Mods/OsuModHardRock.cs
  osu.Game.Rulesets.Osu/Mods/OsuModHidden.cs
  osu.Game.Rulesets.Osu/Mods/OsuModRelax.cs
  osu.Game.Rulesets.Osu/Mods/OsuModSpunOut.cs
  osu.Game.Rulesets.Osu/Mods/OsuModTarget.cs
  osu.Game.Rulesets.Taiko/Mods/TaikoModDaycore.cs
  osu.Game.Rulesets.Taiko/Mods/TaikoModEasy.cs
  osu.Game.Rulesets.Taiko/Mods/TaikoModHalfTime.cs
  osu.Game.Rulesets.Taiko/Mods/TaikoModHardRock.cs
  osu.Game.Rulesets.Taiko/Mods/TaikoModHidden.cs
  osu.Game.Rulesets.Taiko/Mods/TaikoModRelax.cs
  osu.Game/Overlays/Mods/DifficultyIncreaseSection.cs
  osu.Game/Overlays/Mods/DifficultyReductionSection.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Overlays/Mods/SpecialSection.cs
  osu.Game/Rulesets/Mods/ModAutoplay.cs
  osu.Game/Rulesets/Mods/ModCinema.cs
  osu.Game/Rulesets/Mods/ModDaycore.cs
  osu.Game/Rulesets/Mods/ModDoubleTime.cs
  osu.Game/Rulesets/Mods/ModEasy.cs
  osu.Game/Rulesets/Mods/ModHalfTime.cs
  osu.Game/Rulesets/Mods/ModHardRock.cs
  osu.Game/Rulesets/Mods/ModNightcore.cs
  osu.Game/Rulesets/Mods/ModNoFail.cs
  osu.Game/Rulesets/Mods/ModPerfect.cs
  osu.Game/Rulesets/Mods/ModSuddenDeath.cs
  osu.Game/Rulesets/Mods/MultiMod.cs
  osu.Game/osu.Game.csproj
Labels: resolves issue

#2223 Make DrawableHitObject a CompositeDrawable
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableBananaShower.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableDroplet.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableFruit.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableJuiceStream.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableBarLine.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNote.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNoteTick.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableNote.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableRepeatPoint.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderTick.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableBarLine.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableBarLineMajor.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableDrumRollTick.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableHit.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableSwell.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableTaikoHitObject.cs
  osu.Game.Tests/Visual/TestCaseScrollingHitObjects.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: code quality, pending review

#2207 Fix autoplay button wrongly being active after a Ctrl-Enter play
  osu.Game/Overlays/Mods/ModSection.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Screens/Select/PlaySongSelect.cs
Labels: bug, songselect

#2243 Fix crash when attempting to select objects that don't have masks
  osu.Game/Screens/Edit/Screens/Compose/Layers/HitObjectMaskLayer.cs
Labels: bug, editor

#2226 Rewrite the way clocks are handled in the Editor
  osu.Game.Tests/Visual/TestCaseEditorCompose.cs
  osu.Game.Tests/Visual/TestCaseEditorSeekSnapping.cs
  osu.Game.Tests/Visual/TestCaseEditorSelectionLayer.cs
  osu.Game.Tests/Visual/TestCaseEditorSummaryTimeline.cs
  osu.Game.Tests/Visual/TestCasePlaybackControl.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Screens/Edit/Components/PlaybackControl.cs
  osu.Game/Screens/Edit/Components/TimeInfoContainer.cs
  osu.Game/Screens/Edit/Components/Timelines/Summary/Parts/MarkerPart.cs
  osu.Game/Screens/Edit/Components/Timelines/Summary/SummaryTimeline.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/Screens/Compose/Compose.cs
Labels: editor, pending review, regression

#2231 Fix juice stream droplets spawning in incorrect locations
  osu.Game.Rulesets.Catch/Objects/JuiceStream.cs
  osu.Game.Rulesets.Catch/Tests/CatchBeatmapConversionTest.cs
Labels: resolves issue

#2244 Add skin.ini parsing
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyDecoder.cs
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
  osu.Game/Skinning/DefaultSkin.cs
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/Skinning/LegacySkinDecoder.cs
  osu.Game/Skinning/Skin.cs
  osu.Game/Skinning/SkinConfiguration.cs
  osu.Game/Skinning/SkinInfo.cs
  osu.Game/Skinning/SkinManager.cs
  osu.Game/osu.Game.csproj
Labels: import, pending review, skinning

#2246 Hard bail on attempting to import an invalid archive format
  osu.Game/Database/ArchiveModelManager.cs
Labels: import, pending review

#2272 Fix osu! logo making hover beat sounds when not visible
  osu.Game/Screens/Menu/OsuLogo.cs
Labels: audio, bug, pending review

#2276 Don't hard-crash when an unknown section is encountered in a legacy file
  osu.Game/Beatmaps/Formats/LegacyDecoder.cs
Labels: beatmap parsing, bug, high priority

#2245 Make import notifications fail when any imports fail
  osu.Game/Database/ArchiveModelManager.cs
Labels: pending review, ux

#2262 Fix DummyRuleset getting selected after non-matching filter
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#2258 Update nuspec to include humanizer localisations
  osu.Desktop/osu.nuspec
Labels: resolves issue

#2252 Remove ComboColour from HitObjects
  osu.Game.Rulesets.Catch/Beatmaps/CatchBeatmapProcessor.cs
  osu.Game.Rulesets.Catch/Objects/BananaShower.cs
  osu.Game.Rulesets.Catch/Objects/CatchHitObject.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableDroplet.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableFruit.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableJuiceStream.cs
  osu.Game.Rulesets.Catch/Objects/JuiceStream.cs
  osu.Game.Rulesets.Catch/Tests/TestCaseFruitObjects.cs
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNote.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableManiaHitObject.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableNote.cs
  osu.Game.Rulesets.Osu/Beatmaps/OsuBeatmapProcessor.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBody.cs
  osu.Game.Rulesets.Osu/Objects/OsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Rulesets.Osu/Tests/TestCaseHitCircle.cs
  osu.Game.Rulesets.Osu/Tests/TestCaseSlider.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableDrumRoll.cs
  osu.Game/Beatmaps/BeatmapProcessor.cs
  osu.Game/Rulesets/Objects/Types/IHasComboInformation.cs
  osu.Game/osu.Game.csproj
Labels: beatmap parsing, pending review, skinning

#2253 Make Beatmaps decodable as Skins
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Beatmaps/Formats/OsuJsonDecoderTest.cs
  osu.Game.Tests/Visual/TestCasePlaySongSelect.cs
  osu.Game/Beatmaps/Beatmap.cs
  osu.Game/Beatmaps/BeatmapConverter.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/BeatmapManager_WorkingBeatmap.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Database/IHasFiles.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Skinning/LegacyBeatmapSkin.cs
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/Skinning/Skin.cs
  osu.Game/osu.Game.csproj
Labels: beatmap parsing, pending review, skinning

#2254 Add skin/beatmap lookup hierarchy
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableCatchHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/ExplodePiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/FlashPiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/GlowPiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/NumberPiece.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Rulesets/Objects/Types/IHasComboIndex.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Skinning/DefaultSkin.cs
  osu.Game/Skinning/ISkinSource.cs
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/Skinning/LocalSkinOverrideContainer.cs
  osu.Game/Skinning/Skin.cs
  osu.Game/Skinning/SkinManager.cs
  osu.Game/Skinning/SkinReloadableDrawable.cs
  osu.Game/Skinning/SkinnableDrawable.cs
  osu.Game/Skinning/SkinnableSound.cs
  osu.Game/osu.Game.csproj
Labels: beatmap parsing, pending review, skinning

#2279 Only allow settings or notifications to be visible at once
  osu.Game/OsuGame.cs
Labels: resolves issue

#2256 Add scale adjusts to bring legacy skins in-line with lazer sizing
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/Skinning/SkinnableDrawable.cs
Labels: pending review, skinning

#2247 Implement the editor's beat snap divisor
  osu.Game.Tests/Visual/TestCaseBeatDivisorControl.cs
  osu.Game.Tests/Visual/TestCaseEditorCompose.cs
  osu.Game.Tests/Visual/TestCaseEditorSeekSnapping.cs
  osu.Game.Tests/osu.Game.Tests.csproj
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Screens/Edit/Screens/Compose/BeatDivisorControl.cs
  osu.Game/Screens/Edit/Screens/Compose/BindableBeatDivisor.cs
  osu.Game/Screens/Edit/Screens/Compose/Compose.cs
  osu.Game/osu.Game.csproj
Labels: editor, pending review

#2280 Restore old auto-popout notification overlay behaviour
  osu.Game/Overlays/NotificationOverlay.cs
Labels: ux

#2257 Add the ability to skin the gameplay cursor
  osu.Game.Rulesets.Osu/UI/Cursor/GameplayCursor.cs
Labels: pending review, skinning

#2294 Fix volume glow being cut off
  osu.Game/Overlays/Volume/VolumeMeter.cs
Labels: resolves issue

#2255 Fix mod button sounds playing when mod overlay is not visible
  osu.Game/Overlays/Mods/ModButton.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
Labels: resolves issue

#2293 Fix API never stopping its thread
  osu.Game/Online/API/APIAccess.cs
Labels: code quality, performance

#2296 Fix beatmap background fade not being updated on retry
  osu.Game/Screens/Play/ScreenWithBeatmapBackground.cs
Labels: resolves issue

#2300 Move binding to LoadComplete
  osu.Game/Input/Bindings/DatabasedKeyBindingContainer.cs
  osu.Game/Skinning/LocalSkinOverrideContainer.cs
Labels: bug, regression

#2304 Fix @1x skin elements not being used
  osu.Game/Skinning/LegacySkin.cs
Labels: resolves issue

#2325 Fix mania playing the wrong/duplicated sounds on playfield keypress
  osu.Game.Rulesets.Catch/UI/CatchPlayfield.cs
  osu.Game.Rulesets.Mania/UI/Column.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs
  osu.Game/Rulesets/UI/HitObjectContainer.cs
Labels: resolves issue

#2333 Revert changes on hard rock mod
  osu.Game.Rulesets.Catch/Mods/CatchModHardRock.cs
  osu.Game.Rulesets.Osu/Mods/OsuModHardRock.cs
  osu.Game.Rulesets.Taiko/Mods/TaikoModHardRock.cs
  osu.Game/Rulesets/Mods/ModHardRock.cs
Labels: mods

#2320 Add ranked status and video marker to beatmap overlay and panels
  osu.Game.Tests/Visual/TestCaseBeatmapSetOverlay.cs
  osu.Game/Beatmaps/BeatmapSetOnlineInfo.cs
  osu.Game/Beatmaps/BeatmapSetOnlineStatus.cs
  osu.Game/Beatmaps/Drawables/BeatmapSetOnlineStatusPill.cs
  osu.Game/Online/API/Requests/APIResponseBeatmapSet.cs
  osu.Game/Overlays/BeatmapSet/Header.cs
  osu.Game/Overlays/Direct/DirectGridPanel.cs
  osu.Game/Overlays/Direct/IconPill.cs
Labels: user interface
