Repository ppy/osu, pull requests merged in 2018-08, with the labels that each got.

#3157 Switch deployable build to .net core on windows
  osu.Desktop/OsuGameDesktop.cs
  osu.Desktop/Program.cs
  osu.Desktop/Updater/SquirrelUpdateManager.cs
  osu.Desktop/osu.Desktop.csproj
  osu.Desktop/osu.nuspec
  osu.Game.Rulesets.Catch.Tests/osu.Game.Rulesets.Catch.Tests.csproj
  osu.Game.Rulesets.Mania.Tests/osu.Game.Rulesets.Mania.Tests.csproj
  osu.Game.Rulesets.Osu.Tests/osu.Game.Rulesets.Osu.Tests.csproj
  osu.Game.Rulesets.Taiko.Tests/osu.Game.Rulesets.Taiko.Tests.csproj
  osu.Game.Tests/osu.Game.Tests.csproj
  osu.Game/osu.Game.csproj
  osu.Game/osu.nuspec
Labels: tooling

#3156 Fix player loader not continuing when multiple mouse button is down
  osu.Game/Screens/Play/PlayerLoader.cs
Labels: resolves issue

#3150 Split out mods category sections
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Mania/Mods/ManiaKeyMod.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModDualStages.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModMirror.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModRandom.cs
  osu.Game.Rulesets.Osu/Mods/OsuModAutopilot.cs
  osu.Game.Rulesets.Osu/Mods/OsuModSpunOut.cs
  osu.Game.Rulesets.Osu/Mods/OsuModTarget.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game.Tests/Visual/TestCaseMods.cs
  osu.Game/Overlays/Mods/ModSection.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Overlays/Mods/Sections/AutomationSection.cs
  osu.Game/Overlays/Mods/Sections/ConversionSection.cs
  osu.Game/Overlays/Mods/Sections/DifficultyIncreaseSection.cs
  osu.Game/Overlays/Mods/Sections/DifficultyReductionSection.cs
  osu.Game/Overlays/Mods/Sections/FunSection.cs
  osu.Game/Overlays/Mods/SpecialSection.cs
  osu.Game/Rulesets/Mods/Mod.cs
  osu.Game/Rulesets/Mods/ModAutoplay.cs
  osu.Game/Rulesets/Mods/ModRelax.cs
  osu.Game/Rulesets/Mods/ModType.cs
  osu.Game/Rulesets/UI/ModIcon.cs
Labels: mods, songselect

#3163 Improve UX when adjusting visual settings at loading screen
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/Screens/Play/PlayerSettings/PlayerSettingsGroup.cs
  osu.Game/Screens/Play/ScreenWithBeatmapBackground.cs
Labels: ux

#3164 Fix discrepancies in how elements of play mode fade when restarting/e…
  osu.Game/Screens/Play/Player.cs
Labels: gameplay, ux

#2602 Initial implementation of osu!mania editor framework
  osu.Game.Rulesets.Mania.Tests/TestCaseEditor.cs
  osu.Game.Rulesets.Mania/Edit/Layers/Selection/Overlays/HoldNoteMask.cs
  osu.Game.Rulesets.Mania/Edit/Layers/Selection/Overlays/NoteMask.cs
  osu.Game.Rulesets.Mania/Edit/ManiaEditPlayfield.cs
  osu.Game.Rulesets.Mania/Edit/ManiaEditRulesetContainer.cs
  osu.Game.Rulesets.Mania/Edit/ManiaHitObjectComposer.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNote.cs
  osu.Game.Rulesets.Mania/UI/DrawableManiaJudgement.cs
  osu.Game.Rulesets.Mania/UI/ManiaPlayfield.cs
  osu.Game.Rulesets.Mania/UI/ManiaRulesetContainer.cs
  osu.Game.Rulesets.Mania/UI/ManiaScrollingInfo.cs
  osu.Game.Rulesets.Mania/UI/ManiaStage.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Edit/Tools/HitObjectCompositionTool.cs
  osu.Game/Rulesets/UI/Playfield.cs
  osu.Game/Screens/Edit/Screens/Compose/Layers/HitObjectMaskLayer.cs
Labels: editor, osu!mania

#3165 Add loading animation to player loader
  osu.Game.Tests/Visual/TestCasePlayerLoader.cs
  osu.Game/Screens/Play/PlayerLoader.cs
Labels: ux

#3187 Fix mania scroll direction not being initially set correctly
  osu.Game.Rulesets.Mania.Tests/ScrollingTestContainer.cs
  osu.Game.Rulesets.Mania.Tests/TestCaseNotes.cs
  osu.Game.Rulesets.Mania.Tests/TestCaseStage.cs
  osu.Game.Rulesets.Mania/UI/ManiaScrollingInfo.cs
Labels: osu!mania, regression

#3188 Fix mod re-selection
  osu.Game.Tests/Visual/TestCaseMods.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Screens/Select/PlaySongSelect.cs
Labels: regression, resolves issue

#3179 Reduce animations of osu!direct list mode
  osu.Game/Overlays/Direct/DirectListPanel.cs
  osu.Game/Overlays/Direct/DirectPanel.cs
Labels: online, ux

#3217 Fix new control points with same start time not replacing existing ones
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
Labels: resolves issue

#3218 Fix crash due to mods not being reset prior to ruleset changing
  osu.Game.Tests/Visual/TestCasePlaySongSelect.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#3221 Fix storyboard variables not supporting prefixes/suffixes
  osu.Game.Tests/Beatmaps/Formats/LegacyStoryboardDecoderTest.cs
  osu.Game.Tests/Resources/variable-with-suffix.osb
  osu.Game/Beatmaps/Formats/LegacyStoryboardDecoder.cs
Labels: resolves issue

#3222 Fix hitobject results not rewinding
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: gameplay, regression

#3220 Overflow mod select to account for parallax
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
Labels: resolves issue

#3223 Fix swells possibly being strong hitobjects
  osu.Game.Rulesets.Taiko/Beatmaps/TaikoBeatmapConverter.cs
  osu.Game.Rulesets.Taiko/Objects/Swell.cs
  osu.Game.Rulesets.Taiko/Objects/TaikoHitObject.cs
Labels: gameplay, osu!taiko, regression

#3232 Implement hitobject combo offsets
  osu.Game.Rulesets.Catch/Beatmaps/CatchBeatmapConverter.cs
  osu.Game.Rulesets.Catch/Objects/CatchHitObject.cs
  osu.Game.Rulesets.Osu/Beatmaps/OsuBeatmapConverter.cs
  osu.Game.Rulesets.Osu/Objects/OsuHitObject.cs
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Resources/hitobject-combo-offset.osu
  osu.Game/Beatmaps/BeatmapProcessor.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Rulesets/Objects/Legacy/Catch/ConvertHit.cs
  osu.Game/Rulesets/Objects/Legacy/Catch/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/Catch/ConvertSlider.cs
  osu.Game/Rulesets/Objects/Legacy/Catch/ConvertSpinner.cs
  osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectType.cs
  osu.Game/Rulesets/Objects/Legacy/Mania/ConvertHit.cs
  osu.Game/Rulesets/Objects/Legacy/Mania/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/Mania/ConvertSlider.cs
  osu.Game/Rulesets/Objects/Legacy/Osu/ConvertHit.cs
  osu.Game/Rulesets/Objects/Legacy/Osu/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/Osu/ConvertSlider.cs
  osu.Game/Rulesets/Objects/Legacy/Osu/ConvertSpinner.cs
  osu.Game/Rulesets/Objects/Legacy/Taiko/ConvertHit.cs
  osu.Game/Rulesets/Objects/Legacy/Taiko/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/Taiko/ConvertSlider.cs
  osu.Game/Rulesets/Objects/Types/IHasCombo.cs
Labels: resolves issue

#3235 Fix mania beatmaps ending too soon when hold notes are involved
  osu.Game.Rulesets.Mania/Objects/HoldNote.cs
Labels: osu!mania, regression

#3219 Softly-handle infinite loops in mania beatmap conversion
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/DistanceObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/EndTimeObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/HitObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/PatternGenerator.cs
Labels: beatmap conversion, osu!mania

#3169 Add sentry logging
  osu.Desktop/Program.cs
  osu.Game/OsuGame.cs
  osu.Game/Utils/RavenLogger.cs
  osu.Game/osu.Game.csproj
Labels: tooling

#3237 Fix notifiation stack trace output on mania conversion failure
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/PatternGenerator.cs
Labels: beatmap conversion, osu!mania

#3238 Don't forward errors to sentry for local builds
  osu.Game/Utils/RavenLogger.cs
Labels: testing

#3240 Fix multiple sentry reports arriving for similar exceptions
  osu.Desktop/Program.cs
  osu.Game/Utils/RavenLogger.cs
Labels: testing

#3243 Increase the maximum allowable iterations during mania conversion
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/PatternGenerator.cs
Labels: beatmap conversion, osu!mania

#3239 Fix spinners creating an extra combo
  osu.Game.Rulesets.Osu/Beatmaps/OsuBeatmapConverter.cs
  osu.Game.Rulesets.Osu/Beatmaps/OsuBeatmapProcessor.cs
  osu.Game.Rulesets.Osu/Objects/Spinner.cs
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Resources/hitobject-combo-offset.osu
  osu.Game/Rulesets/Objects/Legacy/Catch/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/Osu/ConvertHitObjectParser.cs
Labels: resolves issue

#3245 Output the currently importing model
  osu.Game/Database/ArchiveModelManager.cs
Labels: import

#3241 Fix mirror note generation never completing
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/HitObjectPatternGenerator.cs
Labels: beatmap conversion, osu!mania

#3253 Update framework
  osu.Game.Rulesets.Osu/UI/Cursor/CursorTrail.cs
  osu.Game/Graphics/ScreenshotManager.cs
  osu.Game/Screens/Select/SongSelect.cs
  osu.Game/osu.Game.csproj
Labels: framework fix required

#3263 Fix missed string interpolation
  osu.Desktop/Program.cs
Labels: bug

#3262 Fix crash when selecting mods after entering play mode
  osu.Game/Screens/Play/HUD/ModDisplay.cs
Labels: resolves issue

#3255 Catch OperationCanceledException in single file load sequence
  osu.Game/OsuGame.cs
Labels: regression

#3265 Slightly improve performance of beatmap/storyboard parsing
  osu.Game/Beatmaps/Formats/LegacyDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyStoryboardDecoder.cs
Labels: beatmap parsing, performance

#3266 Remove sliderball's ReceiveMouseInput override
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBall.cs
Labels: osu!

#3267 Fix hitobject stacking being applied too early
  osu.Game.Rulesets.Osu.Tests/StackingTest.cs
  osu.Game.Rulesets.Osu/Beatmaps/OsuBeatmapProcessor.cs
Labels: resolves issue

#3088 Refactor OsuButton and TriangleButton inheritance relation
  osu.Game/Graphics/UserInterface/OsuButton.cs
  osu.Game/Graphics/UserInterface/TriangleButton.cs
  osu.Game/Overlays/Settings/SidebarButton.cs
  osu.Game/Screens/Edit/Components/CircularButton.cs
Labels: editor, user interface

#3273 Fix taiko beatmap conversion attempting to make strong swells
  osu.Game.Rulesets.Taiko/Beatmaps/TaikoBeatmapConverter.cs
Labels: osu!taiko, regression

#3276 Fix invalid GC latency mode being set
  osu.Game/Overlays/Settings/Sections/Debug/GCSettings.cs
Labels: resolves issue

#3280 Handle invalid storyboard origins as Anchor.TopLeft
  osu.Game/Beatmaps/Formats/LegacyStoryboardDecoder.cs
Labels: resolves issue

#3283 Skip invalid hitobject types, log error instead
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs
Labels: resolves issue

#3287 Soft-handle errors when beatmap contains no objects
  osu.Game/Screens/Play/Player.cs
Labels: resolves issue

#3293 Allow 2B maps to be converted to mania
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/HitObjectPatternGenerator.cs
Labels: resolves issue

#3294 Log all files when no beatmap files in archive error occurs
  osu.Game/Beatmaps/BeatmapManager.cs
Labels: import

#3298 Fix operation cancelled exception when changing visual settings
  osu.Game/Skinning/LocalSkinOverrideContainer.cs
  osu.Game/Skinning/SkinReloadableDrawable.cs
Labels: resolves issue

#3308 Log the format line when a decoder isn't found
  osu.Game/Beatmaps/Formats/Decoder.cs
Labels: beatmap parsing

#3296 Fix notifications appearing too early in load process
  osu.Game/Overlays/NotificationOverlay.cs
  osu.Game/Screens/Loader.cs
  osu.Game/Screens/Menu/ButtonSystem.cs
Labels: ux

#3289 Add a second parallax layer to break overlay arrows
  osu.Game/Screens/Play/Break/BreakArrows.cs
Labels: gameplay, user interface

#2909 Add shake effect when clicking osu! hitobjects too early
  osu.Game.Rulesets.Osu.Tests/TestCaseHitCircle.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseShaking.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderHead.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBall.cs
  osu.Game.Tests/Visual/TestCasePreviewTrackManager.cs
  osu.Game/Graphics/Containers/ShakeContainer.cs
  osu.Game/osu.Game.csproj
Labels: gameplay, osu!, ux

#3312 Aggressively check for valid columns before iterating endlessly in mania conversion
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/DistanceObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/EndTimeObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/HitObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/PatternGenerator.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/PatternGenerator.cs
Labels: beatmap conversion, osu!mania

#3310 Softly handle errors when no beatmap file exists in archive
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Database/ArchiveModelManager.cs
Labels: resolves issue

#3330 Fix single file component loading not actually working correctly
  osu.Game/OsuGame.cs
Labels: bug

#3332 Fix DirectOverlay performing web requests on startup
  osu.Game/Overlays/DirectOverlay.cs
Labels: performance

#3341 Remove async logic in line with framework
  osu.Desktop/Overlays/VersionManager.cs
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/DefaultCirclePiece.cs
  osu.Game.Rulesets.Osu/UI/Cursor/CursorTrail.cs
  osu.Game.Rulesets.Taiko/UI/InputDrum.cs
  osu.Game/Beatmaps/Drawables/BeatmapSetCover.cs
  osu.Game/Graphics/Backgrounds/Background.cs
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
  osu.Game/Graphics/Cursor/MenuCursor.cs
  osu.Game/Graphics/ScreenshotManager.cs
  osu.Game/Graphics/SpriteIcon.cs
  osu.Game/Graphics/Sprites/OsuSpriteText.cs
  osu.Game/Graphics/UserInterface/HoverClickSounds.cs
  osu.Game/Graphics/UserInterface/HoverSounds.cs
  osu.Game/Graphics/UserInterface/OsuCheckbox.cs
  osu.Game/Graphics/UserInterface/OsuMenu.cs
  osu.Game/Graphics/UserInterface/OsuSliderBar.cs
  osu.Game/Overlays/MedalOverlay.cs
  osu.Game/Overlays/MedalSplash/DrawableMedal.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Overlays/Profile/Components/GradeBadge.cs
  osu.Game/Overlays/Profile/Header/BadgeContainer.cs
  osu.Game/Overlays/Profile/ProfileHeader.cs
  osu.Game/Overlays/Profile/Sections/Recent/MedalIcon.cs
  osu.Game/Screens/Backgrounds/BackgroundScreenBeatmap.cs
  osu.Game/Screens/Menu/Button.cs
  osu.Game/Screens/Menu/ButtonSystem.cs
  osu.Game/Screens/Menu/Intro.cs
  osu.Game/Screens/Menu/OsuLogo.cs
  osu.Game/Screens/OsuScreen.cs
  osu.Game/Screens/Play/KeyCounter.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/SkipOverlay.cs
  osu.Game/Screens/Ranking/ResultsPageScore.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselItem.cs
  osu.Game/Screens/Select/Leaderboards/DrawableRank.cs
  osu.Game/Screens/Select/PlaySongSelect.cs
  osu.Game/Screens/Select/SongSelect.cs
  osu.Game/Screens/Tournament/Components/VisualiserContainer.cs
  osu.Game/Screens/Tournament/Drawings.cs
  osu.Game/Screens/Tournament/Group.cs
  osu.Game/Screens/Tournament/ScrollingTeamContainer.cs
  osu.Game/Users/Avatar.cs
  osu.Game/Users/Country.cs
  osu.Game/Users/UserCoverBackground.cs
  osu.Game/osu.Game.csproj
Labels: performance
