Repository ppy/osu, pull requests merged in 2018-04, with the labels that each got.

#2335 Fix skin path being ignored in extension agnostic lookups
  osu.Game/Skinning/LegacySkin.cs
Labels: resolves issue

#2288 Fix Player trying to load DummyWorkingBeatmap and failing
  osu.Game/Screens/Play/Player.cs
Labels: bug, resolves issue

#2308 Set Correct values for addDelayedMovements() function
  osu.Game.Rulesets.Osu/Replays/OsuAutoGenerator.cs
Labels: code quality, replay

#2339 Fix ScalableContainer irrepairably altering content size
  osu.Game.Rulesets.Catch/UI/CatchPlayfield.cs
  osu.Game.Rulesets.Osu/Replays/OsuReplayInputHandler.cs
  osu.Game.Tests/Visual/TestCaseScrollingHitObjects.cs
  osu.Game/Input/Handlers/ReplayInputHandler.cs
  osu.Game/Rulesets/UI/RulesetContainer.cs
  osu.Game/Rulesets/UI/ScalableContainer.cs
Labels: resolves issue

#2331 Tab strip
  osu.Game.Tests/Visual/TestCaseBreadcrumbs.cs
  osu.Game/Graphics/UserInterface/BreadcrumbControl.cs
  osu.Game/Graphics/UserInterface/OsuTabControl.cs
  osu.Game/Overlays/Direct/Header.cs
  osu.Game/Overlays/SearchableList/SearchableListHeader.cs
  osu.Game/Overlays/Social/Header.cs
Labels: user interface

#2336 Implement Judgement Colours
  osu.Game/Rulesets/Judgements/DrawableJudgement.cs
Labels: gameplay, resolves issue

#2329 Rewrite editor selections to better handle selection and movement logic
  osu.Game.Rulesets.Osu/Edit/Layers/Selection/Overlays/HitCircleMask.cs
  osu.Game.Rulesets.Osu/Edit/Layers/Selection/Overlays/SliderCircleMask.cs
  osu.Game.Rulesets.Osu/Edit/Layers/Selection/Overlays/SliderMask.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/OsuHitObject.cs
  osu.Game.Tests/Visual/TestCaseHitObjectComposer.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Edit/HitObjectMask.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Screens/Edit/Screens/Compose/Layers/DragLayer.cs
  osu.Game/Screens/Edit/Screens/Compose/Layers/HitObjectMaskLayer.cs
  osu.Game/Screens/Edit/Screens/Compose/Layers/MaskContainer.cs
  osu.Game/Screens/Edit/Screens/Compose/Layers/MaskSelection.cs
  osu.Game/Screens/Edit/Screens/Compose/Layers/SelectionBox.cs
  osu.Game/Screens/Edit/Screens/Compose/Layers/SelectionLayer.cs
Labels: pending review, resolves issue

#2354 Create ManualInputManagerTestCase
  osu.Game.Tests/Visual/TestCaseCursors.cs
  osu.Game/Tests/Visual/ManualInputManagerTestCase.cs
Labels: testing

#2373 Fix all possible cases of crossthread import data races
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Overlays/BeatmapSet/Header.cs
  osu.Game/Overlays/DirectOverlay.cs
  osu.Game/Overlays/Music/PlaylistOverlay.cs
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
Labels: resolves issue

#2379 Fix regression causing hard crash
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
Labels: bug, regression

#2387 Fix OAuth token not saving often enough
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Online/API/OAuth.cs
Labels: online

#2376 Add xmldoc to some high-level classes to explain their separation
  osu.Game/OsuGame.cs
  osu.Game/OsuGameBase.cs
Labels: code quality

#2356 Move seeking logic into a custom editor clock
  osu.Game.Tests/Visual/TestCaseEditorCompose.cs
  osu.Game.Tests/Visual/TestCaseEditorSeekSnapping.cs
  osu.Game.Tests/Visual/TestCaseEditorSummaryTimeline.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Screens/Edit/Components/Timelines/Summary/Parts/MarkerPart.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/EditorClock.cs
  osu.Game/Screens/Edit/Screens/Compose/Compose.cs
  osu.Game/Tests/Visual/EditorClockTestCase.cs
Labels: code quality, editor

#2396 Remove composer from player loader
  osu.Game/Screens/Play/PlayerLoader.cs
Labels: design

#2394 Fix incorrect ordering of difficulties retrieved from API
  osu.Game/Overlays/BeatmapSet/BeatmapPicker.cs
  osu.Game/Overlays/Direct/DirectPanel.cs
Labels: resolves issue

#2332 Make beatmap carousel select a random beatmap when there was no previous selection
  osu.Game.Tests/Visual/TestCaseBeatmapCarousel.cs
  osu.Game/Screens/Select/BeatmapCarousel.cs
  osu.Game/Screens/Select/Carousel/CarouselGroupEagerSelect.cs
Labels: pending review, resolves issue

#2407 Add badges to ProfileHeader
  osu.Game.Tests/Visual/TestCaseBadgeContainer.cs
  osu.Game.Tests/Visual/TestCaseRankGraph.cs
  osu.Game.Tests/Visual/TestCaseUserProfile.cs
  osu.Game/Overlays/Profile/Header/BadgeContainer.cs
  osu.Game/Overlays/Profile/Header/RankGraph.cs
  osu.Game/Overlays/Profile/Header/SupporterIcon.cs
  osu.Game/Overlays/Profile/ProfileHeader.cs
  osu.Game/Users/Badge.cs
  osu.Game/Users/User.cs
  osu.Game/Users/UserPanel.cs
Labels: user interface

#2408 Fix various leaderboard data races
  osu.Game/Screens/Select/Leaderboards/Leaderboard.cs
Labels: resolves issue

#2400 Add support for replay mods
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game/Beatmaps/Legacy/LegacyMods.cs
  osu.Game/OsuGame.cs
  osu.Game/Rulesets/Ruleset.cs
  osu.Game/Rulesets/Scoring/Legacy/LegacyScoreParser.cs
Labels: mods, replay

#2366 Add HardRock position mangling for CatchTheBeat
  osu.Game.Rulesets.Catch/Mods/CatchModHardRock.cs
Labels: resolves issue

#2398 Add right click absolute scrolling in song select
  .gitattributes
  app.manifest
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Overlays/Settings/Sections/Gameplay/SongSelectSettings.cs
  osu.Game/Screens/Select/BeatmapCarousel.cs
Labels: resolves issue

#2422 Update profile header to match osu-web changes
  osu.Game/Graphics/Containers/LinkFlowContainer.cs
  osu.Game/Overlays/Profile/ProfileHeader.cs
  osu.Game/Users/User.cs
Labels: user interface, user profile

#2409 Fix hitobject lengths not being calculated for overlapping speed changes
  osu.Game/Rulesets/UI/Scrolling/ScrollingHitObjectContainer.cs
  osu.Game/Rulesets/UI/Scrolling/Visualisers/ISpeedChangeVisualiser.cs
  osu.Game/Rulesets/UI/Scrolling/Visualisers/OverlappingSpeedChangeVisualiser.cs
  osu.Game/Rulesets/UI/Scrolling/Visualisers/SequentialSpeedChangeVisualiser.cs
Labels: resolves issue

#2350 Add beatmap ID lookup to BeatmapSetOverlay
  osu.Game/Graphics/Containers/LinkFlowContainer.cs
  osu.Game/Online/API/Requests/GetBeatmapSetRequest.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/BeatmapSetOverlay.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmap.cs
Labels: online

#2431 Deploy improvements
  appveyor.yml
  appveyor_deploy.yml
  osu.Desktop.Deploy/Program.cs
  osu.Desktop.Deploy/osu.Desktop.Deploy.csproj
Labels: code quality

#2429 Add error handling on a per-line level in LegacyDecoder
  osu.Game/Beatmaps/Formats/Decoder.cs
  osu.Game/Beatmaps/Formats/JsonBeatmapDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyDecoder.cs
  osu.Game/Skinning/LegacySkinDecoder.cs
Labels: resolves issue

#2444 Fix new detections in rider 2018.1
  osu.Game/Online/API/Requests/GetMessagesRequest.cs
  osu.Game/Online/API/Requests/GetUserRequest.cs
  osu.Game/Screens/Edit/Screens/Compose/Layers/MaskContainer.cs
  osu.Game/Screens/Ranking/ResultsPageScore.cs
Labels: code quality

#2427 Fix BadgeContainer being unable to handle null badges
  osu.Game/Overlays/Profile/Header/BadgeContainer.cs
Labels: bug, user profile

#2426 Update to .NET 4.7.1
  .idea/.idea.osu/.idea/runConfigurations/RulesetTests__catch_.xml
  .idea/.idea.osu/.idea/runConfigurations/RulesetTests__mania_.xml
  .idea/.idea.osu/.idea/runConfigurations/RulesetTests__osu__.xml
  .idea/.idea.osu/.idea/runConfigurations/RulesetTests__taiko_.xml
  .idea/.idea.osu/.idea/runConfigurations/VisualTests__net471_.xml
  .idea/.idea.osu/.idea/runConfigurations/osu___net471_.xml
  .vscode/launch.json
  .vscode/tasks.json
  README.md
  appveyor.yml
  appveyor_deploy.yml
  osu.Desktop.Deploy/.vscode/launch.json
  osu.Desktop.Deploy/osu.Desktop.Deploy.csproj
  osu.Desktop/osu.Desktop.csproj
  osu.Game.Rulesets.Catch.Tests/.vscode/launch.json
  osu.Game.Rulesets.Catch.Tests/.vscode/tasks.json
  osu.Game.Rulesets.Catch.Tests/osu.Game.Rulesets.Catch.Tests.csproj
  osu.Game.Rulesets.Mania.Tests/.vscode/launch.json
  osu.Game.Rulesets.Mania.Tests/.vscode/tasks.json
  osu.Game.Rulesets.Mania.Tests/osu.Game.Rulesets.Mania.Tests.csproj
  osu.Game.Rulesets.Osu.Tests/.vscode/launch.json
  osu.Game.Rulesets.Osu.Tests/.vscode/tasks.json
  osu.Game.Rulesets.Osu.Tests/osu.Game.Rulesets.Osu.Tests.csproj
  osu.Game.Rulesets.Taiko.Tests/.vscode/launch.json
  osu.Game.Rulesets.Taiko.Tests/.vscode/tasks.json
  osu.Game.Rulesets.Taiko.Tests/osu.Game.Rulesets.Taiko.Tests.csproj
  osu.Game.Tests/Beatmaps/Formats/OsuJsonDecoderTest.cs
  osu.Game.Tests/osu.Game.Tests.csproj
  osu.Game/Screens/Edit/Screens/Compose/Layers/MaskContainer.cs
Labels: resolves issue

#2446 Fix some occasionally failing tests
  osu.Game.Tests/Visual/TestCaseBeatmapInfoWedge.cs
  osu.Game/Screens/Select/Carousel/CarouselGroup.cs
  osu.Game/Screens/Select/Carousel/CarouselItem.cs
Labels: bug, testing

#2432 Add toggles for beatmap skins and hitsounds
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Screens/Play/PlayerSettings/VisualSettings.cs
  osu.Game/Skinning/LocalSkinOverrideContainer.cs
Labels: settings, skinning
