Repository ppy/osu, pull requests merged in 2018-11, with the labels that each got.

#3655 Implement slider controlpoint visualisation
  osu.Game.Rulesets.Catch.Tests/TestCaseAutoJuiceStream.cs
  osu.Game.Rulesets.Catch/Beatmaps/CatchBeatmapConverter.cs
  osu.Game.Rulesets.Catch/Objects/JuiceStream.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseSlider.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseSliderSelectionMask.cs
  osu.Game.Rulesets.Osu/Beatmaps/OsuBeatmapConverter.cs
  osu.Game.Rulesets.Osu/Difficulty/Preprocessing/OsuDifficultyHitObject.cs
  osu.Game.Rulesets.Osu/Edit/Masks/SliderMasks/Components/PathControlPointPiece.cs
  osu.Game.Rulesets.Osu/Edit/Masks/SliderMasks/Components/PathControlPointVisualiser.cs
  osu.Game.Rulesets.Osu/Edit/Masks/SliderMasks/Components/SliderBodyPiece.cs
  osu.Game.Rulesets.Osu/Edit/Masks/SliderMasks/Components/SliderCirclePiece.cs
  osu.Game.Rulesets.Osu/Edit/Masks/SliderMasks/SliderSelectionMask.cs
  osu.Game.Rulesets.Osu/Mods/OsuModHardRock.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderHead.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderTail.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SnakingSliderBody.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game/Rulesets/Objects/Legacy/Catch/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/ConvertSlider.cs
  osu.Game/Rulesets/Objects/Legacy/Mania/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/Osu/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/Taiko/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/SliderPath.cs
  osu.Game/Rulesets/Objects/Types/IHasCurve.cs
  osu.Game/Rulesets/Objects/Types/PathType.cs
Labels: editor, osu!

#3663 Don't log disk space related IO errors
  osu.Game/Utils/RavenLogger.cs
Labels: resolves issue

#3668 Fix not being able to drag control points mid-snake
  osu.Game/Screens/Edit/Screens/Compose/Layers/HitObjectMaskLayer.cs
Labels: bug, editor

#3656 Implement spinner selections
  osu.Game.Rulesets.Osu.Tests/TestCaseSpinnerSelectionMask.cs
  osu.Game.Rulesets.Osu/Edit/Masks/SpinnerMasks/Components/SpinnerPiece.cs
  osu.Game.Rulesets.Osu/Edit/Masks/SpinnerMasks/SpinnerSelectionMask.cs
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs
  osu.Game.Rulesets.Osu/Objects/Spinner.cs
Labels: editor, osu!

#3657 Implement spinner placements
  osu.Game.Rulesets.Osu.Tests/TestCaseSpinnerPlacementMask.cs
  osu.Game.Rulesets.Osu/Edit/Masks/SpinnerMasks/SpinnerPlacementMask.cs
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game.Rulesets.Osu/Edit/SpinnerCompositionTool.cs
Labels: editor, osu!

#3678 Sort nested hitobjects post-creation
  osu.Game/Rulesets/Objects/HitObject.cs
Labels: resolves issue

#3680 Fix sample additions not falling back to non-addition bank
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Resources/hitobject-no-addition-bank.osu
  osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs
Labels: resolves issue

#3600 Fix sliders using the wrong samples
  osu.Game.Rulesets.Catch/Beatmaps/CatchBeatmapConverter.cs
  osu.Game.Rulesets.Catch/Objects/JuiceStream.cs
  osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/DistanceObjectPatternGenerator.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseSlider.cs
  osu.Game.Rulesets.Osu/Beatmaps/OsuBeatmapConverter.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Rulesets.Taiko/Beatmaps/TaikoBeatmapConverter.cs
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Resources/slider-samples.osu
  osu.Game/Rulesets/Objects/Legacy/Catch/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/ConvertSlider.cs
  osu.Game/Rulesets/Objects/Legacy/Mania/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/Osu/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/Taiko/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Types/IHasRepeats.cs
Labels: audio, gameplay, osu!

#3681 Update framework and other dependencies
  osu.Game.Rulesets.Catch.Tests/osu.Game.Rulesets.Catch.Tests.csproj
  osu.Game.Rulesets.Mania.Tests/osu.Game.Rulesets.Mania.Tests.csproj
  osu.Game.Rulesets.Osu.Tests/osu.Game.Rulesets.Osu.Tests.csproj
  osu.Game.Rulesets.Taiko.Tests/osu.Game.Rulesets.Taiko.Tests.csproj
  osu.Game.Tests/osu.Game.Tests.csproj
  osu.Game/osu.Game.csproj
Labels: libraries

#3683 Add executable flag to build.sh
  build.sh
Labels: tooling

#3690 Adjust some missed renames
  osu.Game.Rulesets.Mania/Edit/Blueprints/HoldNoteSelectionBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/NoteSelectionBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/ManiaHitObjectComposer.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseHitCirclePlacementBlueprint.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseHitCircleSelectionBlueprint.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseSliderPlacementBlueprint.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseSliderSelectionBlueprint.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseSpinnerPlacementBlueprint.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseSpinnerSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/HitCircles/Components/HitCirclePiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/HitCircles/HitCirclePlacementBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/HitCircles/HitCircleSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointPiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointVisualiser.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/SliderBodyPiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/SliderCirclePiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderCircleSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderPlacementBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderPosition.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Spinners/Components/SpinnerPiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Spinners/SpinnerPlacementBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Spinners/SpinnerSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/HitCircleCompositionTool.cs
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game.Rulesets.Osu/Edit/SliderCompositionTool.cs
  osu.Game.Rulesets.Osu/Edit/SpinnerCompositionTool.cs
  osu.Game.Tests/Visual/TestCaseHitObjectComposer.cs
  osu.Game/Tests/Visual/PlacementBlueprintTestCase.cs
  osu.Game/Tests/Visual/SelectionBlueprintTestCase.cs
Labels: code quality, editor

#3691 Fix hitobjects not updating IsMaskedAway after being judged
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: editor, osu!catch, osu!mania, osu!taiko, regression, replay

#3697 Fix compose mode not working
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
Labels: editor

#3684 Change .idea ignore rules to not ignore run configurations
  .gitignore
Labels: tooling

#3706 Make scroll algorithms not tied to drawable hitobjects
  osu.Game.Rulesets.Catch/UI/CatchPlayfield.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs
  osu.Game.Tests/Visual/TestCaseScrollingHitObjects.cs
  osu.Game/Configuration/ScrollVisualisationMethod.cs
  osu.Game/Rulesets/UI/Scrolling/Algorithms/ConstantScrollAlgorithm.cs
  osu.Game/Rulesets/UI/Scrolling/Algorithms/IScrollAlgorithm.cs
  osu.Game/Rulesets/UI/Scrolling/Algorithms/OverlappingScrollAlgorithm.cs
  osu.Game/Rulesets/UI/Scrolling/Algorithms/SequentialScrollAlgorithm.cs
  osu.Game/Rulesets/UI/Scrolling/ScrollingHitObjectContainer.cs
  osu.Game/Rulesets/UI/Scrolling/ScrollingPlayfield.cs
  osu.Game/Rulesets/UI/Scrolling/Visualisers/ConstantSpeedChangeVisualiser.cs
  osu.Game/Rulesets/UI/Scrolling/Visualisers/ISpeedChangeVisualiser.cs
  osu.Game/Rulesets/UI/Scrolling/Visualisers/OverlappingSpeedChangeVisualiser.cs
  osu.Game/Rulesets/UI/Scrolling/Visualisers/SequentialSpeedChangeVisualiser.cs
Labels: osu!mania

#3709 Implement IScrollAlgorithm.TimeAt()
  osu.Game.Tests/ScrollAlgorithms/ConstantScrollTest.cs
  osu.Game.Tests/ScrollAlgorithms/OverlappingScrollTest.cs
  osu.Game.Tests/ScrollAlgorithms/SequentialScrollTest.cs
  osu.Game/Rulesets/UI/Scrolling/Algorithms/ConstantScrollAlgorithm.cs
  osu.Game/Rulesets/UI/Scrolling/Algorithms/IScrollAlgorithm.cs
  osu.Game/Rulesets/UI/Scrolling/Algorithms/OverlappingScrollAlgorithm.cs
  osu.Game/Rulesets/UI/Scrolling/Algorithms/SequentialScrollAlgorithm.cs
Labels: osu!mania

#2371 Add framework for private messaging support
  osu.Game.Tests/Visual/TestCaseChannelTabControl.cs
  osu.Game.Tests/Visual/TestCaseChatDisplay.cs
  osu.Game.Tests/Visual/TestCaseChatLink.cs
  osu.Game/Graphics/Containers/LinkFlowContainer.cs
  osu.Game/Online/API/APIMessagesRequest.cs
  osu.Game/Online/API/Requests/CreateNewPrivateMessageRequest.cs
  osu.Game/Online/API/Requests/CreateNewPrivateMessageResponse.cs
  osu.Game/Online/Chat/Channel.cs
  osu.Game/Online/Chat/ChannelManager.cs
  osu.Game/Online/Chat/Message.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Chat/ChatLine.cs
  osu.Game/Overlays/Chat/DrawableChannel.cs
  osu.Game/Overlays/Chat/Selection/ChannelListItem.cs
  osu.Game/Overlays/Chat/Selection/ChannelSection.cs
  osu.Game/Overlays/Chat/Selection/ChannelSelectionOverlay.cs
  osu.Game/Overlays/Chat/Tabs/ChannelSelectorTabItem.cs
  osu.Game/Overlays/Chat/Tabs/ChannelTabControl.cs
  osu.Game/Overlays/Chat/Tabs/ChannelTabItem.cs
  osu.Game/Overlays/Chat/Tabs/PrivateChannelTabItem.cs
  osu.Game/Overlays/Chat/Tabs/TabCloseButton.cs
  osu.Game/Overlays/ChatOverlay.cs
Labels: resolves issue

#3710 Separate note selection mask into a note piece
  osu.Game.Rulesets.Mania/Edit/Blueprints/Components/EditNotePiece.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/NoteSelectionBlueprint.cs
Labels: editor, osu!mania

#3714 Hide the placement blueprint when cursor is outside the playfield
  osu.Game.Rulesets.Osu/Edit/Blueprints/Spinners/SpinnerPlacementBlueprint.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Edit/PlacementBlueprint.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
Labels: editor

#3686 Require holding back button to quit gameplay
  osu.Game.Tests/Visual/TestCaseHoldForMenuButton.cs
  osu.Game/Screens/Play/HUD/HoldForMenuButton.cs
  osu.Game/Screens/Play/HUDOverlay.cs
  osu.Game/Screens/Play/Player.cs
Labels: gameplay, ux

#3699 Use bindables for hitobject events
  osu.Game.Rulesets.Osu/Edit/Blueprints/HitCircles/Components/HitCirclePiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/HitObjectPiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/SliderPiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointVisualiser.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/SliderBodyPiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/SliderCirclePiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Spinners/Components/SpinnerPiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderHead.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderTail.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs
  osu.Game.Rulesets.Osu/Objects/OsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Rulesets.Osu/Objects/SliderTailCircle.cs
Labels: resolves issue

#3726 Fix taiko proxies not receiving the correct lifetimes
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableTaikoHitObject.cs
  osu.Game/Skinning/SkinnableSound.cs
Labels: osu!taiko, performance

#3741 Add squirrel update log output
  osu.Desktop/Updater/SquirrelUpdateManager.cs
  osu.Desktop/osu.Desktop.csproj
Labels: installation

#3742 Add support for all channel types
  osu.Game/Online/Chat/ChannelType.cs
  osu.Game/Overlays/Chat/Tabs/ChannelTabControl.cs
Labels: chat

#3748 Add private channel types
  osu.Game/Online/Chat/ChannelType.cs
Labels: chat

#3746 Fix crashes when importing/deleting from model managers
  osu.Game/Beatmaps/Drawables/BeatmapSetDownloader.cs
  osu.Game/Overlays/Direct/DirectPanel.cs
  osu.Game/Overlays/Music/PlaylistList.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
Labels: bug

#3754 Change for-loop inspection to match framework
  osu.sln.DotSettings
Labels: code quality

#3755 Hide playlist when MusicController is hidden
  osu.Game/Overlays/MusicController.cs
Labels: resolves issue

#3758 Fix leaderboard accessing drawables in a possibly invalid state
  osu.Game/Screens/Select/Leaderboards/Leaderboard.cs
Labels: resolves issue

#3749 Fix channel presence being handled incorrectly
  osu.Game/Online/Chat/ChannelManager.cs
  osu.Game/Overlays/ChatOverlay.cs
Labels: chat, resolves issue

#3761 Fix order of ChannelManager dependency caching
  osu.Game/OsuGame.cs
Labels: resolves issue

#3765 Correct typo in function name
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableFruit.cs
Labels: code quality

#3716 Implement mania selection blueprint movements
  osu.Game.Rulesets.Mania.Tests/ManiaSelectionBlueprintTestCase.cs
  osu.Game.Rulesets.Mania.Tests/TestCaseHoldNoteSelectionBlueprint.cs
  osu.Game.Rulesets.Mania.Tests/TestCaseNoteSelectionBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/HoldNoteSelectionBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/ManiaSelectionBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/NoteSelectionBlueprint.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableManiaHitObject.cs
Labels: editor, osu!mania

#3229 Multiplayer room settings
  osu.Game.Tests/Visual/TestCaseRoomSettings.cs
  osu.Game/Online/Multiplayer/GameType.cs
  osu.Game/Screens/Multi/Screens/Match/Match.cs
  osu.Game/Screens/Multi/Screens/Match/Settings/GameTypePicker.cs
  osu.Game/Screens/Multi/Screens/Match/Settings/RoomAvailabilityPicker.cs
  osu.Game/Screens/Multi/Screens/Match/Settings/RoomSettingsOverlay.cs
Labels: resolves issue

#3780 Fix taiko not completing to results screen
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: gameplay, osu!taiko, resolves issue

#3711 Implement mania note placement
  osu.Game.Rulesets.Mania.Tests/ManiaPlacementBlueprintTestCase.cs
  osu.Game.Rulesets.Mania.Tests/TestCaseColumn.cs
  osu.Game.Rulesets.Mania.Tests/TestCaseNotePlacementBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/ManiaPlacementBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/NotePlacementBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/IManiaHitObjectComposer.cs
  osu.Game.Rulesets.Mania/Edit/ManiaHitObjectComposer.cs
  osu.Game.Rulesets.Mania/Edit/NoteCompositionTool.cs
  osu.Game.Rulesets.Mania/UI/Column.cs
  osu.Game.Rulesets.Mania/UI/ManiaPlayfield.cs
  osu.Game.Rulesets.Mania/UI/ManiaRulesetContainer.cs
  osu.Game.Rulesets.Mania/UI/ManiaStage.cs
  osu.Game/Rulesets/Edit/EditRulesetContainer.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Edit/PlacementBlueprint.cs
  osu.Game/Tests/Visual/PlacementBlueprintTestCase.cs
  osu.Game/Tests/Visual/ScrollingTestContainer.cs
Labels: editor, osu!mania

#3738 Implement hold note placement
  osu.Game.Rulesets.Mania.Tests/TestCaseHoldNotePlacementBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/Components/EditBodyPiece.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/HoldNotePlacementBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/ManiaPlacementBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/NotePlacementBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/HoldNoteCompositionTool.cs
  osu.Game.Rulesets.Mania/Edit/ManiaHitObjectComposer.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/Pieces/BodyPiece.cs
Labels: editor, osu!mania

#3718 Allowing keypad enter to be used along with normal enter
  osu.Game/Input/Bindings/GlobalActionContainer.cs
Labels: resolves issue

#3787 Toggle pause in editor with spacebar
  osu.Game/Screens/Edit/Components/PlaybackControl.cs
Labels: editor, input

#3788 Add support for keyboard seeking in the editor
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/EditorClock.cs
Labels: editor, input

#3786 Display local scores in the leaderboard
  osu.Game.Rulesets.Catch/Replays/CatchAutoGenerator.cs
  osu.Game.Rulesets.Mania/Replays/ManiaAutoGenerator.cs
  osu.Game.Rulesets.Osu/Mods/OsuModAutoplay.cs
  osu.Game.Rulesets.Osu/Replays/OsuAutoGeneratorBase.cs
  osu.Game.Rulesets.Taiko/Replays/TaikoAutoGenerator.cs
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game.Tests/Visual/TestCaseReplay.cs
  osu.Game/Beatmaps/Drawables/BeatmapSetDownloader.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Database/MutableDatabaseBackedStore.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Direct/DirectPanel.cs
  osu.Game/Overlays/Music/PlaylistList.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
  osu.Game/Replays/Replay.cs
  osu.Game/Scoring/Legacy/LegacyScoreParser.cs
  osu.Game/Scoring/ScoreManager.cs
  osu.Game/Screens/Menu/MainMenu.cs
  osu.Game/Screens/OsuScreen.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/ReplayPlayer.cs
  osu.Game/Screens/Select/Leaderboards/Leaderboard.cs
  osu.Game/Screens/Select/PlaySongSelect.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: scoring

#3785 Save local scores when completing beatmaps
  osu.Game/Scoring/ScoreInfo.cs
Labels: scoring
