Repository ppy/osu, pull requests merged in 2018-10, with the labels that each got.

#3505 Move judgement text to internal container
  osu.Game.Rulesets.Mania/UI/DrawableManiaJudgement.cs
  osu.Game.Rulesets.Taiko/UI/DrawableTaikoJudgement.cs
  osu.Game/Rulesets/Judgements/DrawableJudgement.cs
Labels: code quality

#3521 Fix cursor not hiding in screenshots
  osu.Game/OsuGame.cs
Labels: resolves issue

#3318 Update LastVisit JSON property name
  osu.Game/Users/User.cs
Labels: blocked, online / API

#3533 Fix gameplay mouse button disable setting no longer having any effect
  osu.Game/Rulesets/UI/RulesetInputManager.cs
Labels: resolves issue

#3539 Fix last visit not supporting null values
  osu.Game/Overlays/Profile/ProfileHeader.cs
  osu.Game/Users/User.cs
Labels: online / API, regression, user profile

#3545 Fix colours with alpha components not being parsed
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Resources/Soleily - Renatus (Gamu) [Insane].osu
  osu.Game/Beatmaps/Formats/LegacyDecoder.cs
Labels: resolves issue

#3553 Handle non positional input only when opened
  osu.Game/Graphics/UserInterface/OsuDropdown.cs
Labels: resolves issue

#3437 Use consistent terminology format on settings
  osu.Game.Rulesets.Osu/OsuInputManager.cs
  osu.Game.Rulesets.Taiko/TaikoInputManager.cs
  osu.Game/Input/Bindings/GlobalActionContainer.cs
  osu.Game/Overlays/Settings/Sections/Audio/OffsetSettings.cs
  osu.Game/Overlays/Settings/Sections/Audio/VolumeSettings.cs
  osu.Game/Overlays/Settings/Sections/Input/KeyboardSettings.cs
  osu.Game/Overlays/Settings/Sections/Input/MouseSettings.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Rulesets/UI/Scrolling/ScrollingDirection.cs
  osu.Game/Screens/Edit/Components/PlaybackControl.cs
  osu.Game/Screens/Edit/Screens/Compose/Timeline/TimelineArea.cs
  osu.Game/Screens/Play/PlayerSettings/VisualSettings.cs
  osu.Game/Screens/Select/Filter/GroupMode.cs
  osu.Game/Screens/Select/PlaySongSelect.cs
  osu.Game/Screens/Select/SongSelect.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardSample.cs
Labels: localisation

#3442 Don't wiggle repeat points independently
  osu.Game.Rulesets.Osu/Mods/OsuModWiggle.cs
  osu.Game/Rulesets/Mods/IApplicableToDrawableHitObject.cs
Labels: resolves issue

#3568 Fix beatmap details not displaying
  osu.Game/Screens/Select/BeatmapDetails.cs
Labels: resolves issue

#3549 Stop ruleset selector from propagating positional input
  osu.Game/Overlays/Toolbar/ToolbarRulesetSelector.cs
Labels: resolves issue

#3574 Various performance improvements around hitobjects
  osu.Game/Rulesets/Objects/HitObject.cs
Labels: performance

#3546 Use the new SmoothedPath in sliders/user profile graph
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBody.cs
  osu.Game/Graphics/UserInterface/LineGraph.cs
  osu.Game/osu.Game.csproj
Labels: osu!, user profile

#3564 Make difficulty calculation closer match osu!stable
  osu.Game.Rulesets.Osu/Beatmaps/OsuBeatmapProcessor.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyCalculator.cs
  osu.Game.Rulesets.Osu/Difficulty/Preprocessing/OsuDifficultyBeatmap.cs
  osu.Game.Rulesets.Osu/Difficulty/Preprocessing/OsuDifficultyHitObject.cs
  osu.Game.Rulesets.Osu/Difficulty/Skills/Aim.cs
  osu.Game.Rulesets.Osu/Difficulty/Skills/Speed.cs
  osu.Game/Beatmaps/ControlPoints/TimingControlPoint.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyDifficultyCalculatorBeatmapDecoder.cs
Labels: difficulty

#3566 Debounce music controller seeks
  osu.Game/Overlays/MusicController.cs
Labels: resolves issue

#3513 Adjust scroll speeds to better match osu!stable
  osu.Game.Rulesets.Mania/Configuration/ManiaConfigManager.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs
Labels: resolves issue

#3466 Rework playfield scaling/aspect ratio adjustment
  osu.Game.Rulesets.Catch/UI/CatchPlayfield.cs
  osu.Game.Rulesets.Catch/UI/CatchRulesetContainer.cs
  osu.Game.Rulesets.Catch/UI/PlayfieldAdjustmentContainer.cs
  osu.Game.Rulesets.Mania/Edit/ManiaEditRulesetContainer.cs
  osu.Game.Rulesets.Mania/UI/Column.cs
  osu.Game.Rulesets.Mania/UI/Components/ColumnHitObjectArea.cs
  osu.Game.Rulesets.Mania/UI/ManiaPlayfield.cs
  osu.Game.Rulesets.Mania/UI/ManiaRulesetContainer.cs
  osu.Game.Rulesets.Mania/UI/ManiaScrollingPlayfield.cs
  osu.Game.Rulesets.Mania/UI/ManiaStage.cs
  osu.Game.Rulesets.Osu/Edit/OsuEditRulesetContainer.cs
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game.Rulesets.Osu/UI/OsuRulesetContainer.cs
  osu.Game.Rulesets.Osu/UI/PlayfieldAdjustmentContainer.cs
  osu.Game.Rulesets.Taiko/UI/PlayfieldAdjustmentContainer.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs
  osu.Game.Rulesets.Taiko/UI/TaikoRulesetContainer.cs
  osu.Game.Tests/Visual/TestCaseScrollingHitObjects.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/UI/HitObjectContainer.cs
  osu.Game/Rulesets/UI/Playfield.cs
  osu.Game/Rulesets/UI/RulesetContainer.cs
  osu.Game/Rulesets/UI/ScalableContainer.cs
  osu.Game/Rulesets/UI/Scrolling/ScrollingPlayfield.cs
Labels: gameplay

#3467 Adjust catcher size
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
Labels: gameplay, osu!catch

#3599 Reduce beatmap difficulty processing time
  osu.Game.Rulesets.Catch.Tests/TestCaseAutoJuiceStream.cs
  osu.Game.Rulesets.Catch/Objects/JuiceStream.cs
  osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/PatternGenerator.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseSlider.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyCalculator.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuPerformanceCalculator.cs
  osu.Game.Rulesets.Osu/Mods/OsuModHardRock.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Tests/Visual/TestCaseHitObjectComposer.cs
  osu.Game.props
  osu.Game/Beatmaps/Beatmap.cs
  osu.Game/Beatmaps/BeatmapConverter.cs
  osu.Game/Beatmaps/ControlPoints/ControlPointInfo.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyDecoder.cs
  osu.Game/Beatmaps/IBeatmap.cs
  osu.Game/Graphics/UserInterface/OsuDropdown.cs
  osu.Game/Graphics/UserInterface/OsuTabControl.cs
  osu.Game/Graphics/UserInterface/RollingCounter.cs
  osu.Game/Rulesets/Objects/BezierApproximator.cs
  osu.Game/Rulesets/Objects/CatmullApproximator.cs
  osu.Game/Rulesets/Objects/CircularArcApproximator.cs
  osu.Game/Rulesets/Objects/Legacy/Catch/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/ConvertSlider.cs
  osu.Game/Rulesets/Objects/Legacy/Mania/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/Osu/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/Taiko/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/SliderCurve.cs
  osu.Game/Rulesets/Objects/Types/IHasCurve.cs
  osu.Game/Storyboards/CommandTimeline.cs
Labels: difficulty, performance

#3595 Fix wrong number of slider ticks being generated
  osu.Game.Rulesets.Osu/Beatmaps/OsuBeatmapConverter.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Tests/Visual/TestCaseHitObjectComposer.cs
Labels: beatmap conversion, compatibility, osu!

#3608 Fix slider travel distances sometimes not being considered
  osu.Game.Rulesets.Osu/Difficulty/Preprocessing/OsuDifficultyHitObject.cs
Labels: difficulty

#3629 Update beatmap search API to match latest osu-web structure
  osu.Game/Online/API/Requests/SearchBeatmapSetsRequest.cs
  osu.Game/Online/API/Requests/SearchBeatmapSetsResponse.cs
  osu.Game/Overlays/DirectOverlay.cs
Labels: online / API

#3632 Fade MetadataSection back in if non-null Text is set
  osu.Game/Screens/Select/BeatmapDetails.cs
Labels: resolves issue

#3500 Implement a skinnable SpriteText
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/NumberPiece.cs
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/Skinning/LegacySkinDecoder.cs
  osu.Game/Skinning/SkinConfiguration.cs
  osu.Game/Skinning/SkinnableDrawable.cs
  osu.Game/Skinning/SkinnableSpriteText.cs
Labels: resolves issue

#3650 Fix mods being erroneously applied when entering editor from song select
  osu.Game/Screens/Select/PlaySongSelect.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#3649 Make mania dual stages mod properly apply two stages
  osu.Game.Rulesets.Mania/Mods/ManiaModDualStages.cs
  osu.Game/Rulesets/Mods/IApplicableToBeatmap.cs
  osu.Game/Rulesets/UI/RulesetContainer.cs
Labels: resolves issue

#3654 Separate snaking logic from base SliderBody
  osu.Game.Rulesets.Osu/Edit/Layers/Selection/Overlays/SliderMask.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/ManualSliderBody.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBody.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SnakingSliderBody.cs
  osu.Game/osu.Game.csproj
Labels: osu!

#3135 Use CakeBuild for building osu!
  .gitignore
  README.md
  appveyor.yml
  build.cake
  build.ps1
  build.sh
  cake.config
  tools/cakebuild.csproj
Labels: tooling

#3664 Fix placement masks handling scroll events
  osu.Game/Rulesets/Edit/PlacementMask.cs
Labels: editor, regression
