Repository ppy/osu, pull requests merged in 2018-06, with the labels that each got.

#2667 Centralise beatmap set cover update logic
  osu.Game/Beatmaps/Drawables/UpdateableBeatmapSetCover.cs
  osu.Game/Overlays/BeatmapSet/Header.cs
  osu.Game/Overlays/Direct/DirectPanel.cs
  osu.Game/Overlays/Profile/Sections/Historical/DrawableMostPlayedRow.cs
  osu.Game/Screens/Multi/Components/DrawableRoom.cs
  osu.Game/Screens/Multi/Components/RoomInspector.cs
Labels: code quality, pending review

#2669 Multiplayer shared logic encapsulation
  osu.Game/Screens/Multi/Components/BeatmapTitle.cs
  osu.Game/Screens/Multi/Components/BeatmapTypeInfo.cs
  osu.Game/Screens/Multi/Components/DrawableRoom.cs
  osu.Game/Screens/Multi/Components/ModeTypeInfo.cs
  osu.Game/Screens/Multi/Components/ParticipantCount.cs
  osu.Game/Screens/Multi/Components/RoomInspector.cs
Labels: code quality, multiplayer, pending review

#2703 Change Room.Participants to an IEnumerable
  osu.Game/Online/Multiplayer/Room.cs
  osu.Game/Screens/Multi/Components/DrawableRoom.cs
  osu.Game/Screens/Multi/Components/RoomInspector.cs
Labels: code quality, multiplayer

#2713 Fix song progress elapsed time rounding up on some cultures
  osu.Game/Screens/Play/SongProgressInfo.cs
Labels: resolves issue

#2702 Default ParticipantCount.Max to null
  osu.Game/Screens/Multi/Components/ParticipantCount.cs
Labels: multiplayer

#2716 Fix menu flashes not extending to the edge of screen during parallax
  osu.Game/Screens/Menu/MenuSideFlashes.cs
Labels: resolves issue

#2721 Fix web request failures not being correctly handled at an APIRequest level
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Online/API/APIRequest.cs
Labels: bug, online

#2683 Improve feel of initial loading osu! logo
  osu.Game.Tests/Visual/TestCaseLoaderAnimation.cs
  osu.Game/Screens/Loader.cs
  osu.Game/Screens/Menu/Intro.cs
  osu.Game/Screens/Menu/OsuLogo.cs
  osu.Game/Screens/OsuScreen.cs
Labels: resolves issue

#2705 Fix incorrect async logic in BeatmapInfoWedge
  osu.Game.Tests/Visual/TestCaseBeatmapInfoWedge.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#2698 Remove link colours from beatmap tags
  osu.Game/Overlays/BeatmapSet/Info.cs
  osu.Game/Screens/Select/BeatmapDetails.cs
Labels: design, overlays

#2727 Rewrite ScoreComponentLabel
  osu.Game/Screens/Select/Leaderboards/LeaderboardScore.cs
Labels: design, songselect

#2692 Always update children when the ruleset input manager is updated
  osu.Game/Rulesets/UI/RulesetInputManager.cs
Labels: resolves issue

#2201 Add a setting to increase visibility of the first object in "Hidden" mod
  osu.Game.Rulesets.Osu/Mods/OsuModHidden.cs
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Overlays/Settings/Sections/Gameplay/ModsSettings.cs
  osu.Game/Overlays/Settings/Sections/GameplaySection.cs
  osu.Game/Rulesets/Mods/IReadFromConfig.cs
  osu.Game/Rulesets/Mods/ModHidden.cs
  osu.Game/Rulesets/UI/RulesetContainer.cs
Labels: resolves issue

#2730 Fix ImportBeatmapTest not working on .net core
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
Labels: bug, testing

#2737 Remove osu.Desktop.Deploy project
  appveyor.yml
  appveyor_deploy.yml
  osu.Desktop.Deploy/App.config
  osu.Desktop.Deploy/GitHubObject.cs
  osu.Desktop.Deploy/GitHubRelease.cs
  osu.Desktop.Deploy/Program.cs
  osu.Desktop.Deploy/osu.Desktop.Deploy.csproj
  osu.sln
Labels: code quality, tooling

#2736 Fix beatmaps with subfolders importing incorrectly on windows
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/IO/Archives/LegacyFilesystemReader.cs
Labels: high priority, resolves issue

#2726 Fix multiple issues causing database reset to fail
  osu.Game/Database/DatabaseContextFactory.cs
  osu.Game/Database/OsuDbContext.cs
  osu.Game/OsuGameBase.cs
Labels: high priority, resolves issue

#2655 Apply platform universal offset in Player
  osu.Game.Tests/Beatmaps/IO/OszArchiveReaderTest.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Screens/Play/PauseContainer.cs
  osu.Game/Screens/Play/Player.cs
Labels: resolves issue

#2748 osu!mania visual improvements
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableBarLine.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNote.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNoteTick.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableManiaHitObject.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableNote.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/Pieces/BodyPiece.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/Pieces/NotePiece.cs
  osu.Game.Rulesets.Mania/UI/Column.cs
  osu.Game.Rulesets.Mania/UI/HitExplosion.cs
  osu.Game.Rulesets.Mania/UI/ManiaStage.cs
Labels: design, gameplay, osu!mania

#2753 Remove net471 build configurations
  .idea/.idea.osu/.idea/runConfigurations/RulesetTests__catch_.xml
  .idea/.idea.osu/.idea/runConfigurations/RulesetTests__mania_.xml
  .idea/.idea.osu/.idea/runConfigurations/RulesetTests__osu__.xml
  .idea/.idea.osu/.idea/runConfigurations/RulesetTests__taiko_.xml
  .idea/.idea.osu/.idea/runConfigurations/VisualTests__net471_.xml
  .idea/.idea.osu/.idea/runConfigurations/osu___net471_.xml
  .vscode/launch.json
  .vscode/tasks.json
Labels: tooling

#2746 Fix notifications not showing at main osu! logo on menu
  osu.Game/Screens/Menu/ButtonSystem.cs
Labels: bug, menu, ux

#2621 Retrieve bindable beatmap directly using DI
  osu.Game.Rulesets.Catch.Tests/TestCaseAutoJuiceStream.cs
  osu.Game.Rulesets.Mania.Tests/TestCaseManiaPlayfield.cs
  osu.Game.Rulesets.Osu/UI/Cursor/GameplayCursor.cs
  osu.Game.Tests/Visual/TestCaseAutoplay.cs
  osu.Game.Tests/Visual/TestCaseBeatmapInfoWedge.cs
  osu.Game.Tests/Visual/TestCaseChatLink.cs
  osu.Game.Tests/Visual/TestCaseEditorCompose.cs
  osu.Game.Tests/Visual/TestCaseEditorComposeTimeline.cs
  osu.Game.Tests/Visual/TestCaseEditorSeekSnapping.cs
  osu.Game.Tests/Visual/TestCaseEditorSummaryTimeline.cs
  osu.Game.Tests/Visual/TestCaseHitObjectComposer.cs
  osu.Game.Tests/Visual/TestCaseMusicController.cs
  osu.Game.Tests/Visual/TestCasePlaySongSelect.cs
  osu.Game.Tests/Visual/TestCasePlaybackControl.cs
  osu.Game.Tests/Visual/TestCasePlayerLoader.cs
  osu.Game.Tests/Visual/TestCaseReplay.cs
  osu.Game.Tests/Visual/TestCaseResults.cs
  osu.Game.Tests/Visual/TestCaseSettings.cs
  osu.Game.Tests/Visual/TestCaseStoryboard.cs
  osu.Game.Tests/Visual/TestCaseWaveform.cs
  osu.Game/Beatmaps/BindableBeatmap.cs
  osu.Game/Beatmaps/DummyWorkingBeatmap.cs
  osu.Game/Beatmaps/IBindableBeatmap.cs
  osu.Game/Graphics/Containers/BeatSyncedContainer.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/Music/PlaylistList.cs
  osu.Game/Overlays/Music/PlaylistOverlay.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Screens/Edit/Components/BottomBarContainer.cs
  osu.Game/Screens/Edit/Components/Timelines/Summary/Parts/TimelinePart.cs
  osu.Game/Screens/Edit/Components/Timelines/Summary/SummaryTimeline.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/EditorClock.cs
  osu.Game/Screens/Edit/Screens/Compose/Compose.cs
  osu.Game/Screens/Edit/Screens/Compose/Timeline/BeatmapWaveformGraph.cs
  osu.Game/Screens/Edit/Screens/Compose/Timeline/ScrollableTimeline.cs
  osu.Game/Screens/Edit/Screens/Compose/Timeline/ScrollingTimelineContainer.cs
  osu.Game/Screens/Edit/Screens/EditorScreen.cs
  osu.Game/Screens/Menu/Intro.cs
  osu.Game/Screens/Menu/LogoVisualisation.cs
  osu.Game/Screens/Menu/MenuSideFlashes.cs
  osu.Game/Screens/OsuScreen.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/Screens/Play/ScreenWithBeatmapBackground.cs
  osu.Game/Screens/Ranking/Results.cs
  osu.Game/Screens/Select/SongSelect.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardAnimation.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardSprite.cs
  osu.Game/Tests/Visual/EditorClockTestCase.cs
  osu.Game/Tests/Visual/EditorTestCase.cs
  osu.Game/Tests/Visual/OsuTestCase.cs
  osu.Game/Tests/Visual/TestCasePerformancePoints.cs
  osu.Game/Tests/Visual/TestCasePlayer.cs
  osu.Game/osu.Game.csproj
Labels: code quality, testing

#2755 Update EntityFramework libraries
  osu.Desktop/osu.Desktop.csproj
  osu.Game/osu.Game.csproj
  osu.TestProject.props
Labels: database, libraries

#2762 Fix volume control adjustment being extreme when precision scrolling
  osu.Game/Overlays/Volume/VolumeMeter.cs
Labels: input, ux

#2735 Centralise downloaded beatmap set logic
  osu.Game/Beatmaps/Drawables/BeatmapSetDownloader.cs
  osu.Game/Overlays/BeatmapSet/Buttons/DownloadButton.cs
  osu.Game/Overlays/BeatmapSet/Header.cs
  osu.Game/Overlays/Direct/DirectGridPanel.cs
  osu.Game/Overlays/Direct/DirectListPanel.cs
  osu.Game/Overlays/Direct/DirectPanel.cs
  osu.Game/Overlays/Direct/DownloadButton.cs
  osu.Game/Overlays/DirectOverlay.cs
Labels: code quality, online

#2607 Ensure profile badges are ordered correctly
  osu.Game/Overlays/Profile/Header/BadgeContainer.cs
Labels: pending review, user interface

#2763 Revert InputManager UpdateSubTree change
  osu.Game/Rulesets/UI/RulesetInputManager.cs
Labels: resolves issue

#2764 Update framework and other packages
  osu.Desktop/osu.Desktop.csproj
  osu.Game/osu.Game.csproj
  osu.TestProject.props
Labels: libraries

#2720 Add difficulty calculation mod combinations
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Mania/Difficulty/ManiaDifficultyCalculator.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Mania/Mods/ManiaKeyMod.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyCalculator.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoDifficultyCalculator.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game.Tests/NonVisual/DifficultyAdjustmentModCombinationsTest.cs
  osu.Game/Rulesets/Difficulty/DifficultyCalculator.cs
  osu.Game/Rulesets/Mods/ModType.cs
  osu.Game/Rulesets/Mods/MultiMod.cs
  osu.Game/Rulesets/Mods/NoModMod.cs
Labels: difficulty, pending review

#2741 Reverse order of exposed objects in HitObjectContainer
  osu.Game.Rulesets.Mania/UI/Column.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game/Rulesets/Mods/ModHidden.cs
  osu.Game/Rulesets/UI/HitObjectContainer.cs
Labels: resolves issue

#2757 Add setting to toggle standardised or classic scoring display
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Overlays/Settings/Sections/Gameplay/GeneralSettings.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Screens/Play/Player.cs
Labels: gameplay, pending review, settings

#2759 Reorganise API requests and response classes
  osu.Game.Tests/Visual/TestCaseBeatmapScoresContainer.cs
  osu.Game.Tests/Visual/TestCaseUserProfileRecentSection.cs
  osu.Game/Online/API/Requests/APIResponseBeatmapSet.cs
  osu.Game/Online/API/Requests/GetBeatmapDetailsRequest.cs
  osu.Game/Online/API/Requests/GetBeatmapSetRequest.cs
  osu.Game/Online/API/Requests/GetScoresRequest.cs
  osu.Game/Online/API/Requests/GetUserBeatmapsRequest.cs
  osu.Game/Online/API/Requests/GetUserMostPlayedBeatmapsRequest.cs
  osu.Game/Online/API/Requests/GetUserRecentActivitiesRequest.cs
  osu.Game/Online/API/Requests/GetUserScoresRequest.cs
  osu.Game/Online/API/Requests/GetUsersRequest.cs
  osu.Game/Online/API/Requests/Responses/APIBeatmap.cs
  osu.Game/Online/API/Requests/Responses/APIBeatmapMetrics.cs
  osu.Game/Online/API/Requests/Responses/APIBeatmapSet.cs
  osu.Game/Online/API/Requests/Responses/APIRecentActivity.cs
  osu.Game/Online/API/Requests/Responses/APIScore.cs
  osu.Game/Online/API/Requests/Responses/APIScores.cs
  osu.Game/Online/API/Requests/Responses/APIUser.cs
  osu.Game/Online/API/Requests/Responses/APIUserMostPlayedBeatmap.cs
  osu.Game/Online/API/Requests/SearchBeatmapSetsRequest.cs
  osu.Game/Overlays/BeatmapSet/Scores/DrawableScore.cs
  osu.Game/Overlays/BeatmapSet/Scores/DrawableTopScore.cs
  osu.Game/Overlays/BeatmapSet/Scores/ScoresContainer.cs
  osu.Game/Overlays/Profile/Sections/Ranks/PaginatedScoreContainer.cs
  osu.Game/Overlays/Profile/Sections/Recent/DrawableRecentActivity.cs
  osu.Game/Overlays/Profile/Sections/Recent/PaginatedRecentActivityContainer.cs
Labels: code quality

#2581 Rework the editor compose timeline
  osu.Game.Tests/Visual/TestCaseEditorComposeTimeline.cs
  osu.Game.Tests/Visual/TestCaseWaveform.cs
  osu.Game.Tests/Visual/TestCaseZoomableScrollContainer.cs
  osu.Game/Screens/Edit/Screens/Compose/Compose.cs
  osu.Game/Screens/Edit/Screens/Compose/Timeline/BeatmapWaveformGraph.cs
  osu.Game/Screens/Edit/Screens/Compose/Timeline/ScrollableTimeline.cs
  osu.Game/Screens/Edit/Screens/Compose/Timeline/ScrollingTimelineContainer.cs
  osu.Game/Screens/Edit/Screens/Compose/Timeline/Timeline.cs
  osu.Game/Screens/Edit/Screens/Compose/Timeline/TimelineArea.cs
  osu.Game/Screens/Edit/Screens/Compose/Timeline/ZoomableScrollContainer.cs
  osu.Game/osu.Game.csproj
Labels: code quality, editor, pending review

#2772 Allow ruleset settings to DI the ruleset's config manager
  osu.Game.Rulesets.Mania/Configuration/ManiaConfigManager.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Mania/UI/ManiaRulesetContainer.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Osu/UI/OsuSettings.cs
  osu.Game/Configuration/DatabasedConfigManager.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/Settings/RulesetSettingsSubsection.cs
  osu.Game/Rulesets/Configuration/RulesetConfigManager.cs
  osu.Game/Rulesets/Ruleset.cs
  osu.Game/Rulesets/RulesetConfigCache.cs
  osu.Game/Rulesets/UI/RulesetContainer.cs
Labels: settings

#2784 Always display the key counter during replay/autoplay
  osu.Game/Screens/Play/KeyCounterCollection.cs
  osu.Game/Screens/Play/Player.cs
Labels: resolves issue

#2789 Fix osu!taiko nightcore mod regression
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
Labels: bug, mods, osu!taiko, regression

#2749 Greatly increase the playfield scroll speed adjust step
  osu.Game/Rulesets/UI/Scrolling/ScrollingPlayfield.cs
Labels: osu!mania, settings, ux

#2791 Fix gameplay memory leak due to incorrect binding
  osu.Game.Rulesets.Osu/UI/Cursor/GameplayCursor.cs
  osu.Game/Tests/Visual/TestCasePlayer.cs
Labels: bug, high priority, performance, regression

#2801 Fix combos ending with JuiceStreams never leaving the catcher's plate
  osu.Game.Rulesets.Catch/Objects/JuiceStream.cs
Labels: resolves issue

#2806 Extend the testability of beatmap conversions
  osu.Game/Tests/Beatmaps/BeatmapConversionTest.cs
Labels: beatmap conversion, testing

#2807 Fix a few osu!mania beatmap conversion edge cases
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/DistanceObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/HitObjectPatternGenerator.cs
Labels: beatmap conversion, osu!mania, pending review

#2792 Fix pixellation of volume meter progress bars
  osu.Game.Tests/Visual/TestCaseVolumePieces.cs
  osu.Game/Overlays/Volume/VolumeMeter.cs
Labels: design, pending review

#2813 Fix music controller draggability
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
  osu.Game/Overlays/MusicController.cs
Labels: resolves issue

#2810 Remove custom migration exception
  osu.Game/Database/OsuDbContext.cs
Labels: code quality, high priority, pending review, testing

#2812 Fix droplets not bouncing off catcher's plate immediately
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableCatchHitObject.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableDroplet.cs
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
Labels: gameplay, osu!catch, pending review

#2775 Make sure taiko hitexplosions expire and get removed
  osu.Game.Rulesets.Mania/UI/HitExplosion.cs
  osu.Game.Rulesets.Taiko/UI/HitExplosion.cs
  osu.Game.Rulesets.Taiko/UI/KiaiHitExplosion.cs
Labels: resolves issue

#2802 Rework difficulty calculators to better support mods and attributes
  osu.Game.Rulesets.Catch.Tests/TestCasePerformancePoints.cs
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyCalculator.cs
  osu.Game.Rulesets.Mania.Tests/TestCasePerformancePoints.cs
  osu.Game.Rulesets.Mania/Difficulty/ManiaDifficultyCalculator.cs
  osu.Game.Rulesets.Mania/Difficulty/ManiaPerformanceCalculator.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Osu.Tests/TestCasePerformancePoints.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyAttributes.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyCalculator.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuPerformanceCalculator.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Taiko.Tests/TestCasePerformancePoints.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoDifficultyCalculator.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoPerformanceCalculator.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game.Tests/NonVisual/DifficultyAdjustmentModCombinationsTest.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/DummyWorkingBeatmap.cs
  osu.Game/Rulesets/Difficulty/DifficultyAttributes.cs
  osu.Game/Rulesets/Difficulty/DifficultyCalculator.cs
  osu.Game/Rulesets/Difficulty/PerformanceCalculator.cs
  osu.Game/Rulesets/Ruleset.cs
  osu.Game/Tests/Visual/TestCasePerformancePoints.cs
Labels: difficulty, pending review

#2617 Couple the editor waveform timeline to the audio
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game.Tests/Visual/TestCaseEditorComposeTimeline.cs
  osu.Game.Tests/Visual/TestCaseWaveform.cs
  osu.Game.Tests/WaveformTestBeatmap.cs
  osu.Game/Screens/Edit/Screens/Compose/Timeline/Timeline.cs
  osu.Game/Tests/Visual/EditorClockTestCase.cs
Labels: editor

#2777 Make taiko hitobjects properly unproxy when rewound
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableHit.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableSwell.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableTaikoHitObject.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs
Labels: resolves issue

#2804 Don't compute keymod difficulties for mania-specific beatmap
  osu.Game.Rulesets.Mania/Difficulty/ManiaDifficultyCalculator.cs
Labels: difficulty, pending review, performance

#2783 Make the editor timeline zoom on mouse scroll
  osu.Game.Tests/Visual/TestCaseZoomableScrollContainer.cs
  osu.Game/Screens/Edit/Screens/Compose/Timeline/Timeline.cs
  osu.Game/Screens/Edit/Screens/Compose/Timeline/ZoomableScrollContainer.cs
Labels: editor, pending review, ux

#2780 Add centre marker to the editor timeline
  osu.Game.Tests/Visual/TestCaseEditorComposeTimeline.cs
  osu.Game/Screens/Edit/Screens/Compose/Timeline/CentreMarker.cs
  osu.Game/Screens/Edit/Screens/Compose/Timeline/Timeline.cs
Labels: editor, pending review

#2631 Colourise the editor waveform
  osu.Game/Screens/Edit/Screens/Compose/Timeline/Timeline.cs
Labels: editor, user interface

#2833 Update rider configuration names
  .idea/.idea.osu/.idea/runConfigurations/VisualTests.xml
  .idea/.idea.osu/.idea/runConfigurations/osu_.xml
Labels: code quality

#2829 Fix reverse arrow displayed with incorrect angle
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableRepeatPoint.cs
Labels: resolves issue

#2836 Update framework
  osu.Desktop/Overlays/VersionManager.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBody.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Graphics/Containers/LinkFlowContainer.cs
  osu.Game/Graphics/UserInterface/ExternalLinkButton.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/osu.Game.csproj
Labels: code quality

#2838 RulesetContainer<TObject> cannot be derived
  osu.Game.Rulesets.Osu/UI/OsuRulesetContainer.cs
  osu.Game/Rulesets/UI/RulesetContainer.cs
Labels: resolves issue

#2831 Add padding to "show more" button
  osu.Game/Overlays/Profile/Sections/PaginatedContainer.cs
Labels: resolves issue

#2708 Multiplayer match screen
  osu.Game.Tests/Visual/TestCaseLounge.cs
  osu.Game.Tests/Visual/TestCaseMatch.cs
  osu.Game.Tests/Visual/TestCaseMatchHeader.cs
  osu.Game.Tests/Visual/TestCaseMatchInfo.cs
  osu.Game.Tests/Visual/TestCaseMatchParticipants.cs
  osu.Game/Screens/Multi/Screens/Lounge/Lounge.cs
  osu.Game/Screens/Multi/Screens/Match.cs
  osu.Game/Screens/Multi/Screens/Match/Header.cs
  osu.Game/Screens/Multi/Screens/Match/Info.cs
  osu.Game/Screens/Multi/Screens/Match/Match.cs
  osu.Game/Screens/Multi/Screens/Match/Participants.cs
  osu.Game/Screens/Multi/Screens/MatchCreate.cs
  osu.Game/Screens/Multi/Screens/MultiplayerScreen.cs
  osu.Game/Screens/Select/MatchSongSelect.cs
Labels: resolves issue

#2559 Add support for negative ParallaxAmount in ParallaxContainer
  osu.Game.Tests/Visual/TestCaseParallaxContainer.cs
  osu.Game/Graphics/Containers/ParallaxContainer.cs
  osu.Game/Tests/OsuTestBrowser.cs
Labels: low priority, user interface

#2593 Implement osu!catch star rating
  osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyAttributes.cs
  osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyCalculator.cs
  osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyHitObject.cs
  osu.Game.Rulesets.Catch/Objects/CatchHitObject.cs
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
Labels: difficulty, osu!catch, pending review

#2851 Remove vscode files from long-gone deploy project
  osu.Desktop.Deploy/.vscode/launch.json
  osu.Desktop.Deploy/.vscode/tasks.json
Labels: code quality, tooling

#2848 Improve log to notification forwarding
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Notifications/SimpleNotification.cs
Labels: high priority, ux

#2469 Centralise preview track handling
  osu.Game.Tests/Visual/TestCasePreviewTrackManager.cs
  osu.Game/Audio/IPreviewTrackOwner.cs
  osu.Game/Audio/PreviewTrack.cs
  osu.Game/Audio/PreviewTrackManager.cs
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/BeatmapSet/Buttons/PreviewButton.cs
  osu.Game/Overlays/BeatmapSet/Details.cs
  osu.Game/Overlays/BeatmapSetOverlay.cs
  osu.Game/Overlays/Direct/DirectPanel.cs
  osu.Game/Overlays/Direct/PlayButton.cs
  osu.Game/Overlays/DirectOverlay.cs
  osu.Game/Overlays/Profile/Sections/Beatmaps/PaginatedBeatmapContainer.cs
  osu.Game/Overlays/Profile/Sections/BeatmapsSection.cs
  osu.Game/Overlays/UserProfileOverlay.cs
Labels: resolves issue

#2815 Avoid errors being logged when importing beatmaps while logged out
  osu.Game/Beatmaps/BeatmapManager.cs
Labels: bug, import, online, pending review

#2744 Improve UX of volume controls
  osu.Game/Overlays/Volume/MuteButton.cs
  osu.Game/Overlays/Volume/VolumeMeter.cs
  osu.Game/Overlays/VolumeOverlay.cs
Labels: resolves issue

#2859 Add a simple Pull Request template
  .github/pull_request_template.md
Labels: tooling

#2850 Fix race condition in TestCaseLounge
  osu.Game.Tests/Visual/TestCaseLounge.cs
Labels: bug, testing

#2858 Update osu!-side code in line with input handling changes
  osu.Desktop/OsuGameDesktop.cs
  osu.Game.Rulesets.Catch/Replays/CatchFramedReplayInputHandler.cs
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
  osu.Game.Rulesets.Mania/Replays/ManiaFramedReplayInputHandler.cs
  osu.Game.Rulesets.Osu/Replays/OsuReplayInputHandler.cs
  osu.Game.Rulesets.Taiko/Replays/TaikoFramedReplayInputHandler.cs
  osu.Game/Input/Handlers/ReplayInputHandler.cs
  osu.Game/Rulesets/Replays/FramedReplayInputHandler.cs
  osu.Game/Rulesets/UI/RulesetInputManager.cs
  osu.Game/Screens/Play/HUD/QuitButton.cs
  osu.Game/Tests/Platform/TestStorage.cs
  osu.Game/Tests/Visual/ManualInputManagerTestCase.cs
  osu.Game/osu.Game.csproj
Labels: framework fix required

#2874 I guess you meant an "or" ?
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/DistanceObjectPatternGenerator.cs
Labels: bug, gameplay, osu!mania

#2877 Fix race condition causing TestCaseLounge to randomly fail
  osu.Game.Tests/Visual/TestCaseLounge.cs
Labels: bug, testing

#2878 Always proxy taiko hits when hit
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableHit.cs
Labels: resolves issue

#2873 Remove low BPM barline increase in taiko
  osu.Game.Rulesets.Taiko/UI/TaikoRulesetContainer.cs
Labels: gameplay, osu!taiko

#2773 Rework osu!mania drawables to support playfield directions
  osu.Game.Rulesets.Mania.Tests/ManiaInputTestCase.cs
  osu.Game.Rulesets.Mania.Tests/ScrollingTestContainer.cs
  osu.Game.Rulesets.Mania.Tests/TestCaseColumn.cs
  osu.Game.Rulesets.Mania.Tests/TestCaseManiaHitObjects.cs
  osu.Game.Rulesets.Mania.Tests/TestCaseManiaPlayfield.cs
  osu.Game.Rulesets.Mania.Tests/TestCaseNotes.cs
  osu.Game.Rulesets.Mania.Tests/TestCaseStage.cs
  osu.Game.Rulesets.Mania/Configuration/ManiaConfigManager.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Mania/ManiaSettingsSubsection.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNote.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableManiaHitObject.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableNote.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/Pieces/NotePiece.cs
  osu.Game.Rulesets.Mania/UI/Column.cs
  osu.Game.Rulesets.Mania/UI/Components/ColumnBackground.cs
  osu.Game.Rulesets.Mania/UI/Components/ColumnHitObjectArea.cs
  osu.Game.Rulesets.Mania/UI/Components/ColumnKeyArea.cs
  osu.Game.Rulesets.Mania/UI/HitExplosion.cs
  osu.Game.Rulesets.Mania/UI/IScrollingInfo.cs
  osu.Game.Rulesets.Mania/UI/ManiaPlayfield.cs
  osu.Game.Rulesets.Mania/UI/ManiaRulesetContainer.cs
  osu.Game.Rulesets.Mania/UI/ManiaScrollingDirection.cs
  osu.Game.Rulesets.Mania/UI/ManiaScrollingPlayfield.cs
  osu.Game.Rulesets.Mania/UI/ManiaStage.cs
  osu.Game.Tests/Visual/TestCaseScrollingHitObjects.cs
  osu.Game/Rulesets/UI/RulesetInputManager.cs
  osu.Game/Rulesets/UI/Scrolling/ScrollingHitObjectContainer.cs
  osu.Game/Rulesets/UI/Scrolling/ScrollingPlayfield.cs
  osu.Game/Rulesets/UI/Scrolling/Visualisers/SequentialSpeedChangeVisualiser.cs
Labels: osu!mania

#2628 Modify catch hyperdash behavior to match to stable
  osu.Game.Rulesets.Catch.Tests/TestCaseCatcherArea.cs
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
Labels: resolves issue

#2635 Use FastRandom for catch droplets and bananas positions
  osu.Game.Rulesets.Catch.Tests/CatchBeatmapConversionTest.cs
  osu.Game.Rulesets.Catch/Beatmaps/CatchBeatmapConverter.cs
  osu.Game.Rulesets.Catch/Beatmaps/CatchBeatmapProcessor.cs
  osu.Game.Rulesets.Catch/MathUtils/FastRandom.cs
  osu.Game.Rulesets.Catch/Objects/BananaShower.cs
  osu.Game.Rulesets.Catch/Objects/JuiceStream.cs
  osu.Game.Rulesets.Catch/Resources/Testing/Beatmaps/basic-expected-conversion.json
  osu.Game.Rulesets.Catch/Resources/Testing/Beatmaps/spinner-and-circles-expected-conversion.json
  osu.Game.Rulesets.Catch/Resources/Testing/Beatmaps/spinner-and-circles.osu
  osu.Game.Rulesets.Catch/Resources/Testing/Beatmaps/spinner-expected-conversion.json
  osu.Game.Rulesets.Catch/Resources/Testing/Beatmaps/spinner.osu
  osu.Game/Beatmaps/WorkingBeatmap.cs
Labels: resolves issue

#2883 Update framework and other nuget dependencies
  osu.Desktop/osu.Desktop.csproj
  osu.Game/Overlays/KeyBinding/KeyBindingRow.cs
  osu.Game/osu.Game.csproj
  osu.TestProject.props
Labels: pending review, tooling

#2860 Fix API getting stuck in an endless loop under a certain unauthorized scenario
  osu.Game/Online/API/APIAccess.cs
Labels: bug, online, pending review

#2827 Fix editor not always scrolling beyond timing point beats
  osu.Game.Tests/Visual/TestCaseEditorSeekSnapping.cs
  osu.Game/Screens/Edit/Screens/Compose/Timeline/Timeline.cs
Labels: bug, editor, pending review

#2857 Improve the visibility of the global loading animation
  osu.Game.Tests/Visual/TestCaseLoadingAnimation.cs
  osu.Game/Graphics/UserInterface/LoadingAnimation.cs
  osu.Game/Overlays/Direct/PlayButton.cs
Labels: design, pending review

#2889 Handle virtual beatmap tracks more gracefully
  osu.Game/Beatmaps/BeatmapManager_WorkingBeatmap.cs
  osu.Game/Beatmaps/DummyWorkingBeatmap.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Beatmaps/WorkingBeatmap_VirtualBeatmapTrack.cs
  osu.Game/Screens/Edit/Components/Timelines/Summary/Parts/MarkerPart.cs
  osu.Game/Screens/Edit/Components/Timelines/Summary/Parts/TimelinePart.cs
  osu.Game/Screens/Edit/Screens/Compose/Timeline/Timeline.cs
  osu.Game/Tests/Beatmaps/TestWorkingBeatmap.cs
Labels: resolves issue

#2897 Fix osu!supporter wording
  osu.Game.Tests/Visual/TestCaseLeaderboard.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Graphics/Containers/OsuTextFlowContainer.cs
  osu.Game/Overlays/Profile/Sections/Recent/DrawableRecentActivity.cs
  osu.Game/Screens/Select/Leaderboards/Leaderboard.cs
  osu.Game/Screens/Select/Leaderboards/LeaderboardScope.cs
  osu.Game/Screens/Select/Leaderboards/MessagePlaceholder.cs
  osu.Game/Screens/Select/Leaderboards/Placeholder.cs
  osu.Game/Screens/Select/Leaderboards/PlaceholderState.cs
  osu.Game/Screens/Select/Leaderboards/RetrievalFailurePlaceholder.cs
Labels: design, pending review, songselect

#2616 Make profile dates match style of website
  osu.Game/Graphics/DrawableDate.cs
  osu.Game/Overlays/Profile/Components/DrawableJoinDate.cs
  osu.Game/Overlays/Profile/Components/GradeBadge.cs
  osu.Game/Overlays/Profile/ProfileHeader.cs
Labels: resolves issue

#2913 Fix combo index being wrong
  osu.Game.Rulesets.Osu/Objects/OsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game/Rulesets/Objects/Types/IHasComboIndex.cs
Labels: resolves issue

#2778 Add judgements to osu!catch
  osu.Game.Rulesets.Catch.Tests/TestCaseFruitObjects.cs
  osu.Game.Rulesets.Catch/Beatmaps/CatchBeatmapProcessor.cs
  osu.Game.Rulesets.Catch/Judgements/CatchBananaJudgement.cs
  osu.Game.Rulesets.Catch/Judgements/CatchDropletJudgement.cs
  osu.Game.Rulesets.Catch/Judgements/CatchJudgement.cs
  osu.Game.Rulesets.Catch/Judgements/CatchTinyDropletJudgement.cs
  osu.Game.Rulesets.Catch/Objects/Banana.cs
  osu.Game.Rulesets.Catch/Objects/BananaShower.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableBanana.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableBananaShower.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableCatchHitObject.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableDroplet.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableTinyDroplet.cs
  osu.Game.Rulesets.Catch/Replays/CatchAutoGenerator.cs
  osu.Game.Rulesets.Catch/Scoring/CatchScoreProcessor.cs
  osu.Game.Rulesets.Catch/UI/CatchRulesetContainer.cs
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
  osu.Game.Rulesets.Mania/Judgements/HoldNoteJudgement.cs
  osu.Game.Rulesets.Osu/Judgements/OsuJudgement.cs
  osu.Game.Rulesets.Osu/Judgements/OsuSliderTailJudgement.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game/Rulesets/Judgements/Judgement.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Screens/Play/Player.cs
Labels: resolves issue

#2915 Revert SharpCompress library to fix delta patching regression
  osu.Game/osu.Game.csproj
Labels: pending review, regression

#2849 Fix dialog overlay playing double samples on show/hide
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
  osu.Game/Overlays/DialogOverlay.cs
Labels: audio, bug, overlays, pending review

#2884 Use dependency injection to access the current ruleset
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Direct/FilterControl.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Overlays/Toolbar/ToolbarModeSelector.cs
  osu.Game/Screens/OsuScreen.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
  osu.Game/Screens/Select/FilterControl.cs
  osu.Game/Screens/Select/Leaderboards/Leaderboard.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue
