Repository ppy/osu, pull requests merged in 2018-12, with the labels that each got.

#3809 Fix incorrect controlpoint being applied to samples
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Resources/controlpoint-custom-samplebank.osu
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Rulesets/Objects/HitObject.cs
Labels: resolves issue

#3807 Fix channel selector regression
  osu.Game/Overlays/Chat/ChatTabControl.cs
  osu.Game/Overlays/Chat/Tabs/ChannelSelectorTabItem.cs
Labels: resolves issue

#3811 Fix loading scores on profile pages potentially causing long blocking operations
  osu.Game/Overlays/Profile/Sections/Ranks/PaginatedScoreContainer.cs
Labels: overlays, performance, user profile

#3815 Add 1ms offset to controlpoint lookup times
  osu.Game/Rulesets/Objects/HitObject.cs
Labels: resolves issue

#3816 Fix home button being cancelled by mod select
  osu.Game/Screens/Select/PlaySongSelect.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#3817 Make hud overlay's content always present to fix input issues
  osu.Game/Screens/Play/HUDOverlay.cs
Labels: resolves issue

#3819 Fix GetWorkingBeatmap potentially loading same beatmap twice
  osu.Game/Beatmaps/BeatmapManager.cs
Labels: bug

#3822 Change statistics to be int for now
  osu.Game.Tests/Scores/IO/ImportScoreTest.cs
  osu.Game.Tests/Visual/TestCaseResults.cs
  osu.Game/Online/API/Requests/Responses/APIScoreInfo.cs
  osu.Game/Scoring/Legacy/LegacyScoreParser.cs
  osu.Game/Scoring/ScoreInfo.cs
  osu.Game/Screens/Ranking/ResultsPageScore.cs
Labels: code quality

#3830 Select channel selector when no channel is selected
  osu.Game.Tests/Visual/TestCaseChannelTabControl.cs
  osu.Game/Online/Chat/Channel.cs
  osu.Game/Online/Chat/ChannelManager.cs
  osu.Game/Overlays/Chat/Tabs/ChannelTabControl.cs
  osu.Game/Overlays/ChatOverlay.cs
Labels: chat, resolves issue

#3833 Update framework and other nuget packages
  osu.Desktop/osu.Desktop.csproj
  osu.Game.Rulesets.Catch.Tests/osu.Game.Rulesets.Catch.Tests.csproj
  osu.Game.Rulesets.Mania.Tests/osu.Game.Rulesets.Mania.Tests.csproj
  osu.Game.Rulesets.Osu.Tests/osu.Game.Rulesets.Osu.Tests.csproj
  osu.Game.Rulesets.Taiko.Tests/osu.Game.Rulesets.Taiko.Tests.csproj
  osu.Game.Tests/osu.Game.Tests.csproj
  osu.Game/Online/Chat/DrawableLinkCompiler.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Music/PlaylistItem.cs
  osu.Game/osu.Game.csproj
Labels: libraries

#3826 Move ModOverlay to SongSelect
  osu.Game/Screens/Select/PlaySongSelect.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: mods, songselect

#3849 Fix reverting to default skin via settings button causing a hard crash
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
Labels: resolves issue

#3838 Fix API getting stuck in connecting state on some exceptions
  osu.Game/Online/API/APIAccess.cs
Labels: online / API

#3850 Fix crash when changing beatmap toggles at loading screen
  osu.Game/Skinning/LocalSkinOverrideContainer.cs
Labels: resolves issue

#3848 Polling component
  .idea/.idea.osu/.idea/runConfigurations/osu_.xml
  osu.Game.Tests/Visual/TestCasePollingComponent.cs
  osu.Game/Online/Chat/ChannelManager.cs
  osu.Game/Online/PollingComponent.cs
  osu.Game/OsuGame.cs
Labels: online / API

#3823 Update projects to target .NET core 2.2
  osu.Desktop/osu.Desktop.csproj
  osu.Game.Rulesets.Catch.Tests/osu.Game.Rulesets.Catch.Tests.csproj
  osu.Game.Rulesets.Mania.Tests/osu.Game.Rulesets.Mania.Tests.csproj
  osu.Game.Rulesets.Osu.Tests/osu.Game.Rulesets.Osu.Tests.csproj
  osu.Game.Rulesets.Taiko.Tests/osu.Game.Rulesets.Taiko.Tests.csproj
  osu.Game.Tests/osu.Game.Tests.csproj
  osu.Game/osu.Game.csproj
Labels: distribution, libraries

#3865 Fix web requests not getting correctly handled on first connection
  osu.Game/Online/API/APIAccess.cs
Labels: resolves issue

#3875 Do not delete file on import failure
  osu.Game/Database/ArchiveModelManager.cs
Labels: import, resolves issue

#3872 Remove all retry logic and simplify overall handling of API requests
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Online/API/APIRequest.cs
  osu.Game/osu.Game.csproj
Labels: online / API

#3892 Various standalone chat display fixes
  osu.Game/Online/Chat/StandAloneChatDisplay.cs
Labels: chat

#3894 Fix extra hard-rock flipping for sliders
  osu.Game.Rulesets.Osu/Mods/OsuModHardRock.cs
Labels: mods, resolves issue

#3897 Clickable avatars
  osu.Game/Overlays/BeatmapSet/AuthorInfo.cs
  osu.Game/Overlays/Profile/ProfileHeader.cs
  osu.Game/Overlays/Toolbar/ToolbarUserButton.cs
  osu.Game/Users/Avatar.cs
  osu.Game/Users/UpdateableAvatar.cs
  osu.Game/Users/UserPanel.cs
Labels: user interface

#3861 Improve the way text search works at song select
  osu.Game/Screens/Select/Carousel/CarouselBeatmap.cs
  osu.Game/Screens/Select/FilterCriteria.cs
  osu.sln.DotSettings
Labels: songselect, ux

#3825 User registration
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
  osu.Game.Tests/Visual/TestCaseAccountCreationOverlay.cs
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
  osu.Game/Graphics/Containers/ShakeContainer.cs
  osu.Game/Graphics/UserInterface/LoadingAnimation.cs
  osu.Game/Graphics/UserInterface/ProcessingOverlay.cs
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Online/API/RegistrationRequest.cs
  osu.Game/OsuGame.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/AccountCreation/AccountCreationBackground.cs
  osu.Game/Overlays/AccountCreation/AccountCreationScreen.cs
  osu.Game/Overlays/AccountCreation/ErrorTextFlowContainer.cs
  osu.Game/Overlays/AccountCreation/ScreenEntry.cs
  osu.Game/Overlays/AccountCreation/ScreenWarning.cs
  osu.Game/Overlays/AccountCreation/ScreenWelcome.cs
  osu.Game/Overlays/AccountCreationOverlay.cs
  osu.Game/Overlays/Settings/Sections/General/LoginSettings.cs
  osu.Game/Screens/Menu/OsuLogo.cs
Labels: online / API

#3902 Disable avatar clicks in chat tabs
  osu.Game/Overlays/Chat/Tabs/PrivateChannelTabItem.cs
Labels: resolves issue

#3908 Implement MBMasher's FL change into osu!'s ppcalc
  osu.Game.Rulesets.Osu/Difficulty/OsuPerformanceCalculator.cs
Labels: difficulty

#3915 Add rider live templates
  osu.sln.DotSettings
Labels: tooling

#3916 Fix API get user request never failing
  osu.Game/Online/API/APIAccess.cs
Labels: online / API

#3921 Fix cancelling completed webrequests throwing exceptions
  osu.Game/Online/API/APIRequest.cs
Labels: online / API

#3930 Fix crash on startup when specifying --no-version-overlay
  osu.Desktop/OsuGameDesktop.cs
Labels: resolves issue

#3932 Always submit standardised scores
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Screens/Multi/Play/TimeshiftPlayer.cs
Labels: multiplayer

#3934 Populate statistics for all rulesets' scores
  osu.Game.Rulesets.Osu/Scoring/OsuScoreProcessor.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
Labels: resolves issue

#3936 Ensure mods are set prior to starting play
  osu.Game/Screens/Multi/Match/MatchSubScreen.cs
Labels: resolves issue

#3938 Use LargeTextureStore for online retrievals
  osu.Game/Beatmaps/Drawables/BeatmapSetCover.cs
Labels: performance

#3939 Fix plays with mods not submitting
  osu.Game/Screens/Play/Player.cs
Labels: mods, multiplayer

#3943 Fix ScoreProcessor's population
  osu.Game.Rulesets.Osu/Scoring/OsuScoreProcessor.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
Labels: regression, scoring

#3975 Fix incorrect newlines in ProfileHeader.
  osu.Game/Overlays/Profile/ProfileHeader.cs
Labels: resolves issue, user profile
