Repository ppy/osu, pull requests merged in 2019-06, with the labels that each got.

#4900 Disallow user from opening their own private channel.
  osu.Game/Online/Chat/ChannelManager.cs
  osu.Game/Overlays/Chat/ChatLine.cs
Labels: resolves issue

#4875 Update 'ShowMore' button in line with the web version
  osu.Game.Tests/Visual/Online/TestSceneShowMoreButton.cs
  osu.Game/Graphics/Containers/OsuHoverContainer.cs
  osu.Game/Overlays/Profile/Sections/Beatmaps/PaginatedBeatmapContainer.cs
  osu.Game/Overlays/Profile/Sections/Historical/PaginatedMostPlayedBeatmapContainer.cs
  osu.Game/Overlays/Profile/Sections/PaginatedContainer.cs
  osu.Game/Overlays/Profile/Sections/Ranks/PaginatedScoreContainer.cs
  osu.Game/Overlays/Profile/Sections/Recent/PaginatedRecentActivityContainer.cs
  osu.Game/Overlays/Profile/Sections/ShowMoreButton.cs
Labels: user profile

#4899 Fix tests potentially loading tracks upon disposal
  osu.Game/Tests/Visual/OsuTestScene.cs
Labels: testing

#4908 Fix incorrect testcase assertion
  osu.Game.Tests/Visual/UserInterface/TestSceneUpdateableBeatmapBackgroundSprite.cs
Labels: testing

#4909 Mark OsuButton as abstract
  osu.Game/Graphics/UserInterface/OsuButton.cs
Labels: code quality

#4907 Dim music volume when holding to confirm
  osu.Game/Overlays/HoldToConfirmOverlay.cs
Labels: audio, user interface

#4577 Update with framework-side front-to-back changes
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBody.cs
  osu.Game.Rulesets.Osu/UI/Cursor/CursorTrail.cs
  osu.Game/Graphics/Backgrounds/Triangles.cs
  osu.Game/Overlays/Settings/Sections/Debug/GeneralSettings.cs
  osu.Game/Rulesets/Mods/ModFlashlight.cs
  osu.Game/Screens/Menu/LogoVisualisation.cs
  osu.Game/osu.Game.csproj
Labels: overdue

#4898 Fix sizing of OsuAnimatedButton and OsuClickableContainer
  osu.Game.Tests/Visual/UserInterface/OsuGridTestScene.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneLoadingAnimation.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneOsuAnimatedButton.cs
  osu.Game/Graphics/Containers/OsuClickableContainer.cs
  osu.Game/Graphics/UserInterface/IconButton.cs
  osu.Game/Graphics/UserInterface/OsuAnimatedButton.cs
Labels: user interface

#4934 Fix cursor trail appearing glitched when pausing immediately after entering gameplay
  osu.Game.Rulesets.Osu/UI/Cursor/CursorTrail.cs
Labels: resolves issue

#4841 Add keyboard shortcuts to actuate mod select buttons
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
Labels: input, user interface

#4947 Fix file layout of ModSelectOverlay
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
Labels: code quality

#4944 Fix preview tracks muting themselves
  osu.Game/Audio/PreviewTrackManager.cs
Labels: resolves issue

#4945 Add an input source toggle on manual input test scenes
  osu.Game.Tests/Visual/UserInterface/TestSceneCursors.cs
  osu.Game/Tests/Visual/ManualInputManagerTestScene.cs
Labels: testing

#4946 Fix paginated layouts only showing one column even if enough space is available for more
  osu.Game/Overlays/Profile/Sections/PaginatedContainer.cs
Labels: resolves issue

#4943 Remove unnecessary manual autosize calculations in ToolbarRulesetSelector
  osu.Game/Overlays/Toolbar/ToolbarRulesetSelector.cs
Labels: code quality

#4906 Add animation on failing
  osu.Game.Tests/Visual/Gameplay/TestSceneFailAnimation.cs
  osu.Game.Tests/Visual/Gameplay/TestScenePause.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Screens/Play/FailAnimation.cs
  osu.Game/Screens/Play/Player.cs
Labels: gameplay, resolves issue

#4960 Update resources for iOS
  osu.iOS.props
Labels: resolves issue

#4954 Highlight major changes on the changelog overlay
  osu.Game/Online/API/Requests/Responses/APIChangelogEntry.cs
  osu.Game/Overlays/Changelog/ChangelogBuild.cs
Labels: resolves issue

#4971 Access WindowModes via IBindableList
  osu.Game/Overlays/Settings/Sections/Graphics/LayoutSettings.cs
Labels: code quality

#4967 Update rank graphics
  osu.Game.Tests/Visual/Online/TestSceneScoresContainer.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneLeaderboard.cs
  osu.Game/Overlays/BeatmapSet/Scores/TopScoreUserSection.cs
  osu.Game/Scoring/ScoreRank.cs
  osu.Game/osu.Game.csproj
Labels: design

#4990 Fix all "Maintainability" CodeFactor issues
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
  osu.Game.Rulesets.Osu/Beatmaps/OsuBeatmapProcessor.cs
  osu.Game.Rulesets.Osu/Mods/OsuModRelax.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneCursors.cs
  osu.Game/Graphics/Containers/HoldToConfirmContainer.cs
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Online/Chat/MessageFormatter.cs
  osu.Game/Overlays/ChatOverlay.cs
  osu.Game/Rulesets/Edit/SelectionBlueprint.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Scoring/Legacy/LegacyScoreParser.cs
Labels: code quality

#4970 Fix checkboxes with long labels overlapping nub
  osu.Game/Graphics/UserInterface/OsuCheckbox.cs
  osu.Game/Overlays/Settings/SettingsCheckbox.cs
Labels: settings, user interface

#4973 Tween track frequency on pause
  osu.Game.Tests/Visual/Gameplay/TestScenePause.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
Labels: audio, gameplay

#4983 Load results pages asynchronously
  osu.Game/Screens/Ranking/Results.cs
Labels: resolves issue

#4984 Fix incorrect xmldoc in OsuAnimatedButton
  osu.Game/Graphics/UserInterface/OsuAnimatedButton.cs
Labels: code quality

#4878 Expose skills in DifficultyAttributes
  osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyCalculator.cs
  osu.Game.Rulesets.Mania/Difficulty/ManiaDifficultyCalculator.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyCalculator.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoDifficultyCalculator.cs
  osu.Game/Rulesets/Difficulty/DifficultyAttributes.cs
  osu.Game/Rulesets/Difficulty/Skills/Skill.cs
Labels: difficulty

#4988 Update VisibilityContainer usage in line with framework
  osu.Desktop/OsuGameDesktop.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneResumeOverlay.cs
  osu.Game.Rulesets.Osu/UI/OsuResumeOverlay.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneFailAnimation.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneGameplayMenuOverlay.cs
  osu.Game.Tests/Visual/Gameplay/TestScenePause.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneStoryboard.cs
  osu.Game.Tests/Visual/Menus/TestSceneToolbar.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMatchSettingsOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneAccountCreationOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneChatDisplay.cs
  osu.Game.Tests/Visual/Settings/TestSceneSettings.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapInfoWedge.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneCursors.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneMusicController.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneNotificationOverlay.cs
  osu.Game.Tests/Visual/UserInterface/TestScenePopupDialog.cs
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
  osu.Game/Graphics/Containers/WaveContainer.cs
  osu.Game/Graphics/Cursor/MenuCursorContainer.cs
  osu.Game/Graphics/UserInterface/BreadcrumbControl.cs
  osu.Game/Graphics/UserInterface/ProcessingOverlay.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/AccountCreationOverlay.cs
  osu.Game/Overlays/BeatmapSetOverlay.cs
  osu.Game/Overlays/ChangelogOverlay.cs
  osu.Game/Overlays/ChatOverlay.cs
  osu.Game/Overlays/DialogOverlay.cs
  osu.Game/Overlays/DirectOverlay.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Overlays/Music/PlaylistOverlay.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Overlays/NotificationOverlay.cs
  osu.Game/Overlays/Settings/Sections/General/LoginSettings.cs
  osu.Game/Overlays/SettingsOverlay.cs
  osu.Game/Overlays/Toolbar/Toolbar.cs
  osu.Game/Overlays/Toolbar/ToolbarOverlayToggleButton.cs
  osu.Game/Overlays/VolumeOverlay.cs
  osu.Game/Rulesets/UI/GameplayCursorContainer.cs
  osu.Game/Screens/Menu/ButtonArea.cs
  osu.Game/Screens/Play/GameplayMenuOverlay.cs
  osu.Game/Screens/Play/HUD/PlayerSettingsOverlay.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/SkipOverlay.cs
  osu.Game/Screens/Play/SongProgress.cs
  osu.Game/Screens/Select/BeatmapDetails.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
  osu.Game/Screens/Select/SongSelect.cs
  osu.Game/osu.Game.csproj
  osu.sln
Labels: code quality, user interface

#4989 Allow fullscreen overlays to surface on subsequent show requests
  osu.Game.Tests/Visual/Online/TestSceneFullscreenOverlay.cs
  osu.Game/Overlays/FullscreenOverlay.cs
Labels: user interface

#4957 Add option to increase visibility of first object with grow mod
  osu.Game.Rulesets.Osu/Mods/OsuModGrow.cs
  osu.Game/Overlays/Settings/Sections/Gameplay/ModsSettings.cs
Labels: mods

#4872 Remove excessive selection updating for SongSelect
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
  osu.Game/Screens/Select/BeatmapCarousel.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#4978 Decouple online retrieval from import process
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game.Tests/Scores/IO/ImportScoreTest.cs
  osu.Game.Tests/Visual/Background/TestSceneBackgroundScreenBeatmap.cs
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneUpdateableBeatmapBackgroundSprite.cs
  osu.Game/Beatmaps/BeatmapInfo.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Database/ICanAcceptFiles.cs
  osu.Game/IO/FileStore.cs
  osu.Game/IPC/ArchiveImportIPCChannel.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/Notifications/ProgressNotification.cs
  osu.Game/Screens/Menu/Intro.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Select/SongSelect.cs
  osu.Game/Skinning/SkinManager.cs
Labels: resolves issue

#4884 Show changelog for current build when clicking on settings footer
  osu.Desktop/Overlays/VersionManager.cs
  osu.Game.Tests/Visual/Online/TestSceneChangelogOverlay.cs
  osu.Game.Tests/Visual/Settings/TestSceneSettingsPanel.cs
  osu.Game/Online/API/Requests/Responses/APIUpdateStream.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/Settings/SettingsFooter.cs
Labels: user interface

#4619 Split out user activity from user status
  osu.Game.Tests/Visual/Online/TestSceneUserPanel.cs
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Online/API/DummyAPIAccess.cs
  osu.Game/Online/API/IAPIProvider.cs
  osu.Game/Overlays/Settings/Sections/General/LoginSettings.cs
  osu.Game/Overlays/SocialOverlay.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/OsuScreen.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/Screens/Select/PlaySongSelect.cs
  osu.Game/Users/User.cs
  osu.Game/Users/UserActivity.cs
  osu.Game/Users/UserPanel.cs
  osu.Game/Users/UserStatus.cs
Labels: online / API

#5004 Improve model deletion notification text
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Database/ArchiveModelManager.cs
Labels: user interface

#5005 Fix abysmal load performance when showing the social overlay
  osu.Game/Users/UserCoverBackground.cs
  osu.Game/Users/UserPanel.cs
Labels: performance

#5014 Reset result time offset to 0 when rewound
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: replay

#5022 Fix IconButtons not being scaled correctly
  osu.Game.Tests/Visual/UserInterface/TestSceneIconButton.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneMusicController.cs
  osu.Game/Graphics/UserInterface/IconButton.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Screens/Edit/Compose/Components/BeatDivisorControl.cs
  osu.Game/Screens/Edit/Compose/Components/Timeline/TimelineButton.cs
Labels: regression, user interface

#5024 Fix potential songselect testcase failures
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
Labels: testing

#5012 Fix stacked objects shaking on rewind
  osu.Game.Tests/Visual/Gameplay/TestSceneGameplayRewinding.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: replay, resolves issue

#5023 Update ScrollContainer usages in line with framework changes
  osu.Game.Tests/Visual/Online/TestSceneHistoricalSection.cs
  osu.Game.Tests/Visual/Online/TestSceneUserProfileRecentSection.cs
  osu.Game.Tests/Visual/Online/TestSceneUserRanks.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneOsuIcon.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneUpdateableBeatmapBackgroundSprite.cs
  osu.Game/Graphics/Containers/OsuScrollContainer.cs
  osu.Game/Graphics/Containers/SectionsContainer.cs
  osu.Game/Online/Leaderboards/Leaderboard.cs
  osu.Game/Overlays/BeatmapSetOverlay.cs
  osu.Game/Overlays/ChangelogOverlay.cs
  osu.Game/Overlays/Chat/DrawableChannel.cs
  osu.Game/Overlays/Settings/Sidebar.cs
  osu.Game/Screens/Edit/Compose/Components/Timeline/ZoomableScrollContainer.cs
  osu.Game/Screens/Multi/Lounge/Components/RoomInspector.cs
  osu.Game/Screens/Multi/Lounge/LoungeSubScreen.cs
  osu.Game/Screens/Multi/Match/Components/MatchSettingsOverlay.cs
  osu.Game/Screens/Multi/Match/Components/Participants.cs
  osu.Game/Screens/Select/BeatmapDetails.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: code quality

#5016 Fix BeatmapSetOverlay not displaying Fails/Retries/Ratings
  osu.Game.Tests/Visual/Online/TestSceneBeatmapSetOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneBeatmapSetOverlayDetails.cs
  osu.Game.Tests/Visual/Online/TestSceneBeatmapSetOverlaySuccessRate.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapDetailArea.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapDetails.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneLeaderboard.cs
  osu.Game/Beatmaps/BeatmapMetrics.cs
  osu.Game/Beatmaps/BeatmapSetInfo.cs
  osu.Game/Beatmaps/BeatmapSetMetrics.cs
  osu.Game/Online/API/Requests/GetBeatmapDetailsRequest.cs
  osu.Game/Online/API/Requests/Responses/APIBeatmap.cs
  osu.Game/Online/API/Requests/Responses/APIBeatmapMetrics.cs
  osu.Game/Online/API/Requests/Responses/APIBeatmapSet.cs
  osu.Game/Overlays/BeatmapSet/BasicStats.cs
  osu.Game/Overlays/BeatmapSet/Details.cs
  osu.Game/Overlays/BeatmapSet/SuccessRate.cs
  osu.Game/Screens/Select/BeatmapDetails.cs
  osu.Game/Screens/Select/Details/UserRatings.cs
Labels: resolves issue

#5034 Fix multiplayer score submission failing silently
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Online/API/Requests/SubmitRoomScoreRequest.cs
Labels: multiplayer, regression

#5044 Fix typo in VersionNavigation class name
  osu.Game/Online/API/Requests/Responses/APIChangelogBuild.cs
Labels: code quality

#5047 Fade volume when game window becomes inactive
  osu.Game/OsuGame.cs
Labels: resolves issue

#5052 Make OsuButton non-abstract again
  osu.Game/Graphics/UserInterface/OsuButton.cs
Labels: code quality, user interface

#5055 Remove test which is failing due to magic numbers
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
Labels: resolves issue, testing

#5053 Remove unused property from chat message
  osu.Game/Online/Chat/Message.cs
Labels: chat, code quality

#5054 Unbind from previous bindable when rebinding a SettingsItem
  osu.Game/Overlays/Settings/SettingsItem.cs
Labels: code quality, settings

#5064 Fix startup crash if main menu does not load fast enough
  osu.Game/Screens/Menu/MainMenu.cs
Labels: bug, startup crash/issue

#5041 Fix audio being dimmed during multiplayer
  osu.Game/Screens/Multi/Multiplayer.cs
Labels: resolves issue

#5058 Show user online status in user overlay
  osu.Game.Tests/Visual/Online/TestSceneUserProfileHeader.cs
  osu.Game/Overlays/Profile/Header/BottomHeaderContainer.cs
  osu.Game/Users/User.cs
Labels: overlays, user profile

#5021 Hide empty categories in mod selector overlay
  osu.Game.Tests/Visual/UserInterface/TestSceneModSelectOverlay.cs
  osu.Game/Overlays/Mods/ModSection.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
Labels: songselect, user interface

#5067 Improve vertical flexibility of BeatmapSetOverlay's header
  osu.Game/Overlays/BeatmapSet/Header.cs
  osu.Game/Overlays/BeatmapSetOverlay.cs
Labels: overlays

#5074 Fix scores header is visible even with no scores
  osu.Game.Tests/Visual/Online/TestSceneScoresContainer.cs
  osu.Game/Overlays/BeatmapSet/Scores/ScoresContainer.cs
Labels: resolves issue

#5076 Remove osu!-side DebugUtils
  osu.Desktop/Overlays/VersionManager.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/Settings/SettingsFooter.cs
  osu.Game/Utils/DebugUtils.cs
Labels: code quality

#5083 Fix mod icons in ModSelect being loaded in a blocking fashion
  osu.Game.Tests/Visual/UserInterface/TestSceneModSelectOverlay.cs
  osu.Game/Overlays/Mods/ModSection.cs
Labels: performance, songselect

#5084 Remove necessity for MusicController to be always visible
  osu.Game/OsuGame.cs
  osu.Game/Overlays/MusicController.cs
Labels: code quality, performance

#5093 Fix position of gradient in beatmap carousel when scaling UI
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmapSet.cs
Labels: resolves issue

#5082 Improve chat startup and channel switching performance
  osu.Game/Online/Chat/StandAloneChatDisplay.cs
  osu.Game/Overlays/Chat/ChatLine.cs
  osu.Game/Overlays/Chat/DrawableChannel.cs
  osu.Game/Overlays/ChatOverlay.cs
Labels: chat, performance

#5081 Fix NotificationOverlay being always present
  osu.Game.Tests/Visual/UserInterface/TestSceneNotificationOverlay.cs
  osu.Game/Overlays/NotificationOverlay.cs
  osu.Game/Overlays/Notifications/ProgressNotification.cs
Labels: code quality, notifications

#5096 Add buttons to clear or cancel key binding
  osu.Game.Tests/Visual/Settings/TestSceneKeyBindingPanel.cs
  osu.Game/Overlays/KeyBinding/KeyBindingRow.cs
  osu.Game/Overlays/KeyBinding/KeyBindingsSubsection.cs
Labels: input, settings

#5098 Add some spacing between user profile ranks
  osu.Game/Overlays/Profile/Header/DetailHeaderContainer.cs
Labels: design, user profile

#5097 Fix chat being dismissed in test scene when it shouldn't
  osu.Game.Tests/Visual/Online/TestSceneChatOverlay.cs
  osu.Game/Overlays/ChatOverlay.cs
Labels: chat

#5078 Move NotificationSection strings to constructor
  osu.Game/Overlays/NotificationOverlay.cs
  osu.Game/Overlays/Notifications/NotificationSection.cs
Labels: code quality

#5046 Remove local implementation of bindable in OsuCheckbox
  osu.Game/Graphics/UserInterface/OsuCheckbox.cs
  osu.Game/Screens/Play/PlayerSettings/DiscussionSettings.cs
  osu.Game/Screens/Play/PlayerSettings/InputSettings.cs
  osu.Game/Screens/Play/PlayerSettings/VisualSettings.cs
Labels: code quality

#5095 Prevent non-combo affecting judgements from triggering sudden death
  osu.Game.Rulesets.Taiko.Tests/TestSceneTaikoSuddenDeath.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneFailAnimation.cs
  osu.Game/Rulesets/Mods/ModPerfect.cs
  osu.Game/Rulesets/Mods/ModSuddenDeath.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
Labels: resolves issue

#5049 Fix audio not dimming after race condition
  osu.Game/OsuGame.cs
Labels: resolves issue

#5113 Fix audio being dimmed on preview tracks
  osu.Game/Audio/PreviewTrackManager.cs
Labels: audio

#5123 Fix assert descriptions
  osu.Game.Tests/Visual/Components/TestSceneIdleTracker.cs
Labels: code quality, testing

#5122 Format tournament bracket output
  osu.Game.Tournament/TournamentGameBase.cs
Labels: tournament

#5131 Fix test timing regressions due to increased step count
  osu.Game.Tests/Visual/Components/TestSceneIdleTracker.cs
Labels: regression, testing

#5130 Fix dialog going off-screen when UI scaling is applied
  osu.Game/Overlays/Dialog/PopupDialog.cs
Labels: resolves issue

#5132 Fix multiplayer create button appearing in match song selection
  osu.Game/Screens/Multi/Multiplayer.cs
Labels: resolves issue

#5127 Allow customisation of the colour portion of the tournament logo header
  osu.Game.Tournament/Screens/Gameplay/Components/MatchHeader.cs
  osu.Game.Tournament/Screens/Showcase/TournamentLogo.cs
  osu.Game.Tournament/Screens/TeamIntro/TeamIntroScreen.cs
Labels: tournament

#5137 Add SkinnableSprite class
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/ApproachCircle.cs
  osu.Game/Skinning/SkinnableDrawable.cs
  osu.Game/Skinning/SkinnableSprite.cs
Labels: skinning

#5128 Add basic skinning capabilities to osu!catch catcher
  osu.Game.Rulesets.Catch.Tests/TestSceneCatcher.cs
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
  osu.Game.Rulesets.Catch/UI/CatcherSprite.cs
Labels: osu!catch, skinning

#2996 Add quick exit hotkey
  osu.Game/Input/Bindings/GlobalActionContainer.cs
  osu.Game/Screens/Play/HotkeyExitOverlay.cs
  osu.Game/Screens/Play/Player.cs
Labels: gameplay, input

#5135 Allow controlling music and effect volume via arrow keys when hovering
  osu.Game/Overlays/VolumeOverlay.cs
Labels: resolves issue

#5141 Fix bad wording in the readme
  README.md
Labels: code quality

#5112 Avoid displaying previous user avatar when showing new beatmap overlay
  osu.Game/Overlays/BeatmapSet/Scores/TopScoreUserSection.cs
  osu.Game/Users/Drawables/UpdateableAvatar.cs
  osu.Game/Users/Drawables/UpdateableFlag.cs
Labels: resolves issue

#5142 Remove unnecessary local item storage in SettingsDropdown
  osu.Game/Overlays/Settings/Sections/Audio/AudioDevicesSettings.cs
  osu.Game/Overlays/Settings/Sections/Graphics/LayoutSettings.cs
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
  osu.Game/Overlays/Settings/SettingsDropdown.cs
Labels: resolves issue

#5145 Fix cursor expansion state potentially being incorrect
  osu.Game.Rulesets.Osu/UI/Cursor/OsuCursorContainer.cs
Labels: resolves issue

#5146 Fix keybindings being offset incorrectly
  osu.Game/Input/Bindings/GlobalActionContainer.cs
Labels: regression, settings

#5144 Improve loading state of BeatmapSet header
  osu.Game/Overlays/BeatmapSet/Header.cs
Labels: overlays

#5147 Reduce background brightness at PlayerLoader
  osu.Game/Screens/Play/PlayerLoader.cs
Labels: resolves issue

#5094 Use OsuScrollContainer for osu menus
  osu.Game/Graphics/UserInterface/OsuDropdown.cs
  osu.Game/Graphics/UserInterface/OsuMenu.cs
Labels: user interface

#5150 Reduce size of dropdown chevron
  osu.Game/Graphics/UserInterface/OsuDropdown.cs
Labels: design, user interface

#5149 Re-use the back button game-wide
  osu.Game.Tests/Visual/UserInterface/TestSceneBackButton.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneTwoLayerButton.cs
  osu.Game/Graphics/UserInterface/BackButton.cs
  osu.Game/Graphics/UserInterface/TwoLayerButton.cs
  osu.Game/OsuGame.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/IOsuScreen.cs
  osu.Game/Screens/Loader.cs
  osu.Game/Screens/Menu/Intro.cs
  osu.Game/Screens/Menu/MainMenu.cs
  osu.Game/Screens/Multi/Multiplayer.cs
  osu.Game/Screens/OsuScreen.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Ranking/Results.cs
  osu.Game/Screens/ScreenWhiteBox.cs
  osu.Game/Screens/Select/Footer.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#5153 Disallow back button on disclaimer screen
  osu.Game/Screens/Menu/Disclaimer.cs
Labels: regression

#5154 Fix pause not correctly showing pause screen
  osu.Game.Tests/Visual/Gameplay/TestScenePause.cs
  osu.Game/Screens/Play/Player.cs
Labels: gameplay, regression

#5155 Add base class for startup screens
  osu.Game/Screens/Loader.cs
  osu.Game/Screens/Menu/Disclaimer.cs
  osu.Game/Screens/Menu/Intro.cs
  osu.Game/Screens/StartupScreen.cs
Labels: code quality

#5160 Shortcut checking for whether directories are files
  osu.Game/Beatmaps/BeatmapManager_WorkingBeatmap.cs
  osu.Game/Utils/ZipUtils.cs
Labels: performance, tooling

#4964 Refactor ToolbarRulesetSelector using TabControl
  osu.Game.Tests/Visual/Menus/TestSceneToolbar.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneToolbarRulesetSelector.cs
  osu.Game/Overlays/Toolbar/Toolbar.cs
  osu.Game/Overlays/Toolbar/ToolbarRulesetButton.cs
  osu.Game/Overlays/Toolbar/ToolbarRulesetSelector.cs
  osu.Game/Overlays/Toolbar/ToolbarRulesetTabButton.cs
  osu.Game/Rulesets/RulesetSelector.cs
  osu.Game/Screens/Multi/Match/MatchSubScreen.cs
Labels: code quality, user interface

#5158 Fix MusicController holding references to beatmaps while inactive
  osu.Game/Overlays/MusicController.cs
Labels: performance, regression

#5000 Create a generic archive download manager
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Database/DownloadableArchiveModelManager.cs
  osu.Game/Database/IModelDownloader.cs
  osu.Game/Database/IModelManager.cs
  osu.Game/Online/API/ArchiveDownloadRequest.cs
  osu.Game/Online/API/Requests/DownloadBeatmapSetRequest.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/Direct/DownloadTrackingComposite.cs
  osu.Game/Overlays/Music/PlaylistList.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
  osu.Game/Screens/Multi/Match/Components/ReadyButton.cs
  osu.Game/Screens/Multi/Match/MatchSubScreen.cs
  osu.Game/Screens/Select/BeatmapCarousel.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: code quality, database

#4986 Handle beatmaps with disabled download or missing content
  osu.Game.Tests/Visual/Online/TestSceneBeatmapAvailability.cs
  osu.Game.Tests/Visual/Online/TestSceneBeatmapSetOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneDirectDownloadButton.cs
  osu.Game.Tests/Visual/Online/TestSceneDirectPanel.cs
  osu.Game/Beatmaps/BeatmapSetOnlineInfo.cs
  osu.Game/Beatmaps/Drawables/UpdateableBeatmapSetCover.cs
  osu.Game/Online/API/Requests/Responses/APIBeatmapSet.cs
  osu.Game/Overlays/BeatmapSet/BeatmapAvailability.cs
  osu.Game/Overlays/BeatmapSet/Header.cs
  osu.Game/Overlays/BeatmapSetOverlay.cs
  osu.Game/Overlays/Direct/DirectListPanel.cs
  osu.Game/Overlays/Direct/DirectPanel.cs
  osu.Game/Overlays/Direct/DownloadButton.cs
Labels: resolves issue

#4910 Implement Ruleset Selector component for profile overlay
  osu.Game.Tests/Visual/Online/TestSceneProfileRulesetSelector.cs
  osu.Game/Overlays/Profile/Header/Components/ProfileRulesetSelector.cs
  osu.Game/Overlays/Profile/Header/Components/ProfileRulesetTabItem.cs
  osu.Game/Overlays/UserProfileOverlay.cs
Labels: online / API, user profile

#5162 Fix settings subpanels dimming main content
  osu.Game/Overlays/SettingsSubPanel.cs
Labels: bug, settings

#5167 Remove no longer necessary HandleInput overrides
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: code quality

#5170 Fix TestSceneHyperDash in test browser
  osu.Game.Rulesets.Catch.Tests/TestSceneHyperDash.cs
Labels: osu!catch, testing

#5171 Fix download buttons not finding existing downloads and already downloaded maps
  osu.Game.Tests/Visual/Online/TestSceneDirectDownloadButton.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Database/DownloadableArchiveModelManager.cs
Labels: database, regression

#5168 Fix ruleset selector line not moving on first display
  osu.Game.Tests/Visual/UserInterface/TestSceneToolbarRulesetSelector.cs
  osu.Game/Overlays/Toolbar/ToolbarRulesetSelector.cs
Labels: regression, user interface

#5178 Fix windows updater
  osu.Desktop/Updater/SquirrelUpdateManager.cs
Labels: bug

#5194 Allow exiting Editor again
  osu.Game/Screens/Edit/Editor.cs
Labels: editor

#5159 Add combo break sound
  osu.Game.Rulesets.Catch/Objects/JuiceStream.cs
  osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/DistanceObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/EndTimeObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/HitObjectPatternGenerator.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneSlider.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Rulesets.Taiko.Tests/TestSceneInputDrum.cs
  osu.Game.Rulesets.Taiko/Audio/DrumSampleMapping.cs
  osu.Game.Rulesets.Taiko/Beatmaps/TaikoBeatmapConverter.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableTaikoHitObject.cs
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Beatmaps/Formats/OsuJsonDecoderTest.cs
  osu.Game/Audio/HitSampleInfo.cs
  osu.Game/Audio/ISampleInfo.cs
  osu.Game/Audio/SampleInfo.cs
  osu.Game/Beatmaps/ControlPoints/SampleControlPoint.cs
  osu.Game/Beatmaps/Formats/LegacyDecoder.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Rulesets/Objects/HitObject.cs
  osu.Game/Rulesets/Objects/Legacy/Catch/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/ConvertSlider.cs
  osu.Game/Rulesets/Objects/Legacy/Mania/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/Osu/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/Taiko/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Types/IHasRepeats.cs
  osu.Game/Screens/Play/ComboEffects.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Skinning/LocalSkinOverrideContainer.cs
  osu.Game/Skinning/SkinnableSound.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: resolves issue
