Repository ppy/osu, pull requests merged in 2019-05, with the labels that each got.

#4691 Add number sign in front of profile rankings
  osu.Game/Overlays/Profile/Header/Components/RankGraph.cs
  osu.Game/Overlays/Profile/Header/DetailHeaderContainer.cs
Labels: user profile

#4655 Implement AdjustRank and Hidden mod grades (S+ and SS+)
  osu.Game.Rulesets.Osu/Mods/OsuModBlinds.cs
  osu.Game.Tests/Visual/Gameplay/TestCasePlayerLoader.cs
  osu.Game/Rulesets/Mods/IApplicableToScoreProcessor.cs
  osu.Game/Rulesets/Mods/ModFlashlight.cs
  osu.Game/Rulesets/Mods/ModHidden.cs
  osu.Game/Rulesets/Mods/ModSuddenDeath.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Screens/Play/Player.cs
Labels: mods

#4701 Fix mod equality checks not working as intended
  osu.Game/Online/API/Requests/Responses/APIMod.cs
  osu.Game/Rulesets/Mods/IMod.cs
  osu.Game/Rulesets/Mods/Mod.cs
  osu.Game/Scoring/ScoreInfo.cs
  osu.Game/Screens/Multi/Play/TimeshiftPlayer.cs
Labels: mods, multiplayer, regression

#4696 Fix hidden/expanded centre profile header information
  osu.Game/Overlays/Profile/Header/CentreHeaderContainer.cs
Labels: user profile

#4710 Improve skip boundary logic to be closer to expectations
  osu.Game/Screens/Play/SkipOverlay.cs
Labels: resolves issue

#4703 Add animation when collapsing or expanding the profile details section
  osu.Game/Overlays/Profile/Header/CentreHeaderContainer.cs
  osu.Game/Overlays/Profile/Header/DetailHeaderContainer.cs
  osu.Game/Overlays/Profile/ProfileHeader.cs
Labels: user profile

#4719 Fix beatmap import crashing during room creation
  osu.Game/Screens/Multi/Match/MatchSubScreen.cs
Labels: resolves issue

#4678 Don't play screen "back" sample when retrying
  osu.Game/Screens/OsuScreen.cs
  osu.Game/Screens/Play/PlayerLoader.cs
Labels: user interface

#4704 Pause via inactive activates hold-for-menu button directly
  osu.Game.Tests/Visual/Gameplay/TestCasePause.cs
  osu.Game/Screens/Play/HUD/HoldForMenuButton.cs
  osu.Game/Screens/Play/Player.cs
Labels: resolves issue

#4653 Fix rank display on break info display
  osu.Game/Online/Leaderboards/DrawableRank.cs
  osu.Game/Scoring/ScoreRank.cs
  osu.Game/Screens/Play/Break/BreakInfoLine.cs
Labels: resolves issue

#4723 Fix disposed beatmap backgrounds being loaded
  osu.Game.Tests/Visual/UserInterface/TestCaseUpdateableBeatmapBackgroundSprite.cs
  osu.Game/Beatmaps/Drawables/UpdateableBeatmapBackgroundSprite.cs
Labels: multiplayer

#4617 Implement dimming for sliding on sliders with flashlight mod
  osu.Game.Rulesets.Osu.Tests/TestCaseOsuFlashlight.cs
  osu.Game.Rulesets.Osu/Mods/OsuModFlashlight.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableRepeatPoint.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game/Rulesets/Mods/ModFlashlight.cs
  osu.Game/Tests/Visual/AllPlayersTestCase.cs
  osu.Game/Tests/Visual/PlayerTestCase.cs
  osu.Game/osu.Game.csproj
Labels: mods, resolves issue

#4616 Refactor song select footer buttons
  osu.Game/Screens/Play/HUD/ModDisplay.cs
  osu.Game/Screens/Select/Footer.cs
  osu.Game/Screens/Select/FooterButton.cs
  osu.Game/Screens/Select/FooterButtonMods.cs
  osu.Game/Screens/Select/FooterButtonOptions.cs
  osu.Game/Screens/Select/FooterButtonRandom.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#4733 Fix incorrect texture name usage for some rank icons
  osu.Game/Overlays/Profile/Header/DetailHeaderContainer.cs
Labels: resolves issue

#4735 Adjust testcase to avoid random failures
  osu.Game.Tests/Visual/UserInterface/TestCaseUpdateableBeatmapBackgroundSprite.cs
Labels: testing

#4738 Fix game pausing when made inactive while watching a replay
  osu.Game/Screens/Play/HUDOverlay.cs
Labels: resolves issue

#4730 Fix possible cross-thread config cache access
  osu.Game/Rulesets/RulesetConfigCache.cs
Labels: resolves issue

#4739 Add more asserts to pause test in an attempt to track down intermittent test failures
  osu.Game.Tests/Visual/Gameplay/TestCasePause.cs
Labels: testing

#4742 Fix user bindable being written to from background thread
  osu.Game/Online/API/APIAccess.cs
Labels: resolves issue

#4728 Fix ZoomableScrollContainer not getting initial width
  osu.Game.Tests/Visual/Editor/TestCaseZoomableScrollContainer.cs
  osu.Game/Screens/Edit/Compose/Components/Timeline/ZoomableScrollContainer.cs
Labels: resolves issue

#4744 Fix incorrect judgement counts for rewinding
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
Labels: resolves issue

#4745 Fix long skip performance
  osu.Game.Tests/Visual/Gameplay/TestCaseFrameStabilityContainer.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Rulesets/UI/FrameStabilityContainer.cs
Labels: resolves issue

#4751 Add cancellation support to storyboard/hitobject loading
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboard.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardLayer.cs
  osu.Game/Storyboards/Storyboard.cs
Labels: performance

#4752 Use nullable cancellation tokens
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboard.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardLayer.cs
Labels: regression, testing

#4743 Fix score deletion not considering ScoreManager ownership
  osu.Game/Beatmaps/BeatmapStore.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Scoring/ScoreManager.cs
Labels: database, high priority, regression, startup crash/issue

#4746 Allow song progress bar to show current position during a seek
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Rulesets/UI/FrameStabilityContainer.cs
  osu.Game/Screens/Play/HUDOverlay.cs
  osu.Game/Screens/Play/SongProgress.cs
  osu.Game/Screens/Play/SongProgressBar.cs
Labels: gameplay, user interface

#4720 Fix player loader testcase potentially failing
  osu.Game.Tests/Visual/Gameplay/TestCasePlayerLoader.cs
Labels: testing

#4760 Fix beatmap carousel overlapping beatmap info wedge
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#4761 Close beatmap options when suspending
  osu.Game/Screens/Select/SongSelect.cs
Labels: user interface

#4750 Fix pauses being triggered in unexpected scenarios
  osu.Game.Rulesets.Osu.Tests/TestCaseSliderInput.cs
  osu.Game.Tests/Visual/Background/TestCaseBackgroundScreenBeatmap.cs
  osu.Game.Tests/Visual/Gameplay/TestCaseAutoplay.cs
  osu.Game.Tests/Visual/Gameplay/TestCasePause.cs
  osu.Game.Tests/Visual/Gameplay/TestCasePlayerLoader.cs
  osu.Game.Tests/Visual/Gameplay/TestCaseReplay.cs
  osu.Game/Screens/Play/HUD/HoldForMenuButton.cs
  osu.Game/Screens/Play/HUDOverlay.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Tests/Visual/AllPlayersTestCase.cs
  osu.Game/Tests/Visual/PlayerTestCase.cs
  osu.Game/Tests/Visual/TestPlayer.cs
Labels: gameplay, regression

#4607 Don’t allow ResumeContainers to appear during breaks
  osu.Game/Beatmaps/Timing/BreakPeriod.cs
  osu.Game/Screens/Play/Player.cs
Labels: resolves issue

#4713 Fix slider border not reverting to default color
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
Labels: resolves issue

#4759 Fix clicking "+" tab showing an empty channel in some cases
  osu.Game.Tests/Visual/Online/TestCaseChannelTabControl.cs
  osu.Game/Online/Chat/ChannelManager.cs
  osu.Game/Overlays/Chat/Tabs/ChannelSelectorTabItem.cs
  osu.Game/Overlays/Chat/Tabs/ChannelTabControl.cs
  osu.Game/Overlays/ChatOverlay.cs
Labels: resolves issue

#4763 Fix game not always failing when minimum HP is hit
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
Labels: resolves issue

#4471 Implement skinning for slider border thickness
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBody.cs
  osu.Game/Skinning/LegacySkinDecoder.cs
  osu.Game/Skinning/SkinConfiguration.cs
Labels: resolves issue

#4767 Swap profile "play styles" and "last visit" positions to match web
  osu.Game/Overlays/Profile/Header/BottomHeaderContainer.cs
Labels: user profile

#4768 Use VolumeMute icon for mute button
  osu.Game/Overlays/Volume/MuteButton.cs
Labels: user interface

#4770 Fix order of nested hitobjects on 2B Catch maps
  osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyCalculator.cs
Labels: difficulty, osu!catch

#4776 Attempt to fix pause test failures by reducing steps
  osu.Game.Tests/Visual/Gameplay/TestCasePause.cs
Labels: testing

#4780 Fix iOS app entry for raw keyboard input
  osu.iOS/Application.cs
Labels: iOS

#4771 Add smoothing to flashlight movement
  osu.Game.Rulesets.Osu/Mods/OsuModFlashlight.cs
Labels: resolves issue

#4783 Reduce unnecessary allocations
  osu.Game/Storyboards/Drawables/DrawableStoryboardAnimation.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardSprite.cs
Labels: performance

#4788 Fix commented line check not working with whitespace
  osu.Game.Tests/Beatmaps/Formats/LegacyDecoderTest.cs
  osu.Game.Tests/Resources/comments.osu
  osu.Game/Beatmaps/Formats/LegacyDecoder.cs
Labels: resolves issue

#4774 Centralise caching of components at OsuGame level
  osu.Game.Tests/Visual/Settings/TestCaseKeyConfiguration.cs
  osu.Game.Tests/Visual/Settings/TestCaseSettings.cs
  osu.Game.Tests/Visual/TestCaseOsuGame.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/KeyBinding/KeyBindingsSubsection.cs
  osu.Game/Overlays/KeyBindingPanel.cs
  osu.Game/Overlays/MainSettings.cs
  osu.Game/Overlays/Settings/Sections/Input/KeyboardSettings.cs
  osu.Game/Overlays/Settings/Sections/InputSection.cs
  osu.Game/Overlays/Settings/SettingsButton.cs
  osu.Game/Overlays/Settings/SettingsHeader.cs
  osu.Game/Overlays/Settings/SettingsItem.cs
  osu.Game/Overlays/Settings/SettingsSection.cs
  osu.Game/Overlays/Settings/SettingsSubsection.cs
  osu.Game/Overlays/SettingsOverlay.cs
  osu.Game/Overlays/SettingsPanel.cs
  osu.Game/Overlays/Toolbar/ToolbarSettingsButton.cs
  osu.Game/Screens/Menu/MainMenu.cs
Labels: code quality

#4786 Centralise full screen overlay logic into a base class
  osu.Game.Tests/Visual/Online/TestCaseDirectOverlay.cs
  osu.Game.Tests/Visual/Online/TestCaseFullscreenOverlay.cs
  osu.Game.Tests/Visual/Online/TestCaseSocialOverlay.cs
  osu.Game.Tests/Visual/Online/TestCaseUserProfileHeader.cs
  osu.Game.Tests/Visual/Online/TestCaseUserProfileOverlay.cs
  osu.Game/Overlays/BeatmapSetOverlay.cs
  osu.Game/Overlays/DirectOverlay.cs
  osu.Game/Overlays/FullscreenOverlay.cs
  osu.Game/Overlays/SearchableList/SearchableListOverlay.cs
  osu.Game/Overlays/SocialOverlay.cs
  osu.Game/Overlays/UserProfileOverlay.cs
Labels: code quality

#4765 Hide music controller when exiting via Alt-F4
  osu.Game/OsuGame.cs
Labels: resolves issue

#4790 Increase loader animation wait time
  osu.Game.Tests/Visual/Menus/TestCaseLoaderAnimation.cs
Labels: testing

#4784 Remember FPS display state after changing via Ctrl+F11 hotkey
  osu.Game.Tests/Visual/UserInterface/TestCaseLoadingAnimation.cs
  osu.Game.Tests/Visual/UserInterface/TestCaseOsuIcon.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Tests/Visual/OsuTestCase.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: user interface

#4782 Fix hard crash if beatmap does not have any objects
  osu.Game.Rulesets.Osu/UI/DrawableOsuRuleset.cs
Labels: resolves issue

#4800 Move OsuScreenDependencies to GameBase
  osu.Game.Tests/Visual/TestCaseOsuGame.cs
  osu.Game/OsuGame.cs
  osu.Game/OsuGameBase.cs
Labels: code quality

#4798 Use framework-based Logger for squirrel update logs
  osu.Desktop/Updater/SquirrelUpdateManager.cs
Labels: resolves issue

#4801 Fix some missed instances of TestCase
  osu.Game.Tests/Chat/MessageFormatterTests.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneLoadingAnimation.cs
  osu.Game.Tests/WaveformTestBeatmap.cs
  osu.Game/Tests/Visual/OsuTestScene.cs
Labels: code quality

#2832 Add some default LengthLimit to OsuTextBox
  osu.Game/Graphics/UserInterface/OsuTextBox.cs
Labels: resolves issue

#4789 Remove a few custom user link implementations
  osu.Game/Overlays/Direct/DirectGridPanel.cs
  osu.Game/Overlays/Direct/DirectListPanel.cs
  osu.Game/Overlays/Profile/Sections/Historical/DrawableMostPlayedRow.cs
Labels: code quality

#4809 Fix race condition causing player to never restart
  osu.Game/Screens/Play/Player.cs
Labels: resolves issue

#4802 Fix crash on switching from main menu to gameplay too fast
  osu.Game/Screens/Menu/MainMenu.cs
Labels: resolves issue

#4815 Update NuGet packages
  osu.Game.Rulesets.Catch.Tests/osu.Game.Rulesets.Catch.Tests.csproj
  osu.Game.Rulesets.Mania.Tests/osu.Game.Rulesets.Mania.Tests.csproj
  osu.Game.Rulesets.Osu.Tests/osu.Game.Rulesets.Osu.Tests.csproj
  osu.Game.Rulesets.Taiko.Tests/osu.Game.Rulesets.Taiko.Tests.csproj
  osu.Game.Tests/osu.Game.Tests.csproj
  osu.Game/osu.Game.csproj
Labels: libraries

#4814 Update framework
  osu.Game.Tests/Visual/Gameplay/TestScenePlayerReferenceLeaking.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: libraries

#4829 Allow chaining of loadComponentSingleFile
  osu.Game/OsuGame.cs
Labels: code quality

#4835 Fix usages of SpriteText (instead of OsuSpriteText)
  osu.Game.Rulesets.Mania.Tests/TestSceneNotes.cs
  osu.Game.Tests/Visual/Background/TestSceneBackgroundScreenBeatmap.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneScoreCounter.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSkinReloadable.cs
  osu.Game.Tests/Visual/Online/TestSceneChannelTabControl.cs
  osu.Game.Tests/Visual/TestSceneOsuScreenStack.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneNotificationOverlay.cs
  osu.Game/Overlays/BeatmapSet/Scores/TopScoreUserSection.cs
Labels: code quality

#4831 Use OsuColour for profile overlay
  osu.Game/Graphics/OsuColour.cs
  osu.Game/Overlays/Profile/Header/BottomHeaderContainer.cs
  osu.Game/Overlays/Profile/Header/CentreHeaderContainer.cs
  osu.Game/Overlays/Profile/Header/Components/ExpandDetailsButton.cs
  osu.Game/Overlays/Profile/Header/Components/RankGraph.cs
  osu.Game/Overlays/Profile/Header/Components/SupporterIcon.cs
  osu.Game/Overlays/Profile/Header/DetailHeaderContainer.cs
  osu.Game/Overlays/Profile/Header/MedalHeaderContainer.cs
  osu.Game/Overlays/Profile/Header/TopHeaderContainer.cs
  osu.Game/Overlays/Profile/ProfileHeader.cs
Labels: code quality

#4830 Move TooltipText to OsuClickableContainer
  osu.Game/Graphics/Containers/OsuClickableContainer.cs
  osu.Game/Online/Chat/DrawableLinkCompiler.cs
  osu.Game/Overlays/BeatmapSet/AuthorInfo.cs
  osu.Game/Overlays/Profile/Header/Components/ProfileHeaderButton.cs
  osu.Game/Overlays/Profile/Sections/BeatmapMetadataContainer.cs
  osu.Game/Users/Avatar.cs
Labels: code quality

#4836 Consolidate loader animation tests
  osu.Game.Tests/Visual/Menus/TestSceneLoaderAnimation.cs
Labels: testing

#4729 Fix control points with same timestamp potentially being parsed incorrectly
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Resources/overlapping-control-points.osu
  osu.Game/Beatmaps/ControlPoints/ControlPoint.cs
  osu.Game/Beatmaps/ControlPoints/DifficultyControlPoint.cs
  osu.Game/Beatmaps/ControlPoints/EffectControlPoint.cs
  osu.Game/Beatmaps/ControlPoints/SampleControlPoint.cs
  osu.Game/Beatmaps/ControlPoints/TimingControlPoint.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyDecoder.cs
Labels: resolves issue

#4834 Allow custom icon specification in ScreenTitle
  osu.Game/Graphics/UserInterface/ScreenTitle.cs
Labels: code quality, user interface

#4832 Abstract profile header
  osu.Game.Tests/Visual/Online/TestSceneUserProfileHeader.cs
  osu.Game/Overlays/OverlayHeader.cs
  osu.Game/Overlays/OverlayHeaderTabControl.cs
  osu.Game/Overlays/Profile/ProfileHeader.cs
Labels: code quality

#4837 Update framework
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: libraries

#4844 Add ExpandingBar UI element
  osu.Game.Tests/Visual/UserInterface/TestSceneExpandingBar.cs
  osu.Game/Graphics/UserInterface/ExpandingBar.cs
  osu.Game/Overlays/OverlayHeaderTabControl.cs
Labels: design, user interface

#4846 Fix audio preview buttons not correctly handling load failure states
  osu.Game/Audio/PreviewTrack.cs
  osu.Game/Overlays/Direct/PlayButton.cs
Labels: audio, user interface

#4847 Fix UpdateableBeatmapBackgroundSprite displaying extra backgrounds
  osu.Game/Beatmaps/Drawables/UpdateableBeatmapBackgroundSprite.cs
Labels: bug, performance

#4859 Consolidate settings subpanel logic
  osu.Game/Overlays/KeyBindingPanel.cs
  osu.Game/Overlays/SettingsOverlay.cs
  osu.Game/Overlays/SettingsPanel.cs
  osu.Game/Overlays/SettingsSubPanel.cs
Labels: code quality

#4860 Isolate alpha usage in OsuCheckbox
  osu.Game/Graphics/UserInterface/OsuCheckbox.cs
Labels: code quality

#4861 Store databased settings based on string keys rather than ints
  osu.Game/Configuration/DatabasedConfigManager.cs
  osu.Game/Configuration/DatabasedSetting.cs
  osu.Game/Configuration/SettingsStore.cs
  osu.Game/Migrations/20180125143340_Settings.cs
  osu.Game/Migrations/OsuDbContextModelSnapshot.cs
Labels: configuration, database

#4880 Update Kudosu section inline with the web version
  osu.Game/Overlays/Profile/Sections/Kudosu/KudosuInfo.cs
Labels: user profile

#3074 Changelog overlay
  osu.Desktop/Overlays/VersionManager.cs
  osu.Game.Tests/Visual/Online/TestSceneChangelogOverlay.cs
  osu.Game/Graphics/OsuColour.cs
  osu.Game/Graphics/UserInterface/ScreenTitle.cs
  osu.Game/Online/API/Requests/GetChangelogBuildRequest.cs
  osu.Game/Online/API/Requests/GetChangelogRequest.cs
  osu.Game/Online/API/Requests/Responses/APIChangelogBuild.cs
  osu.Game/Online/API/Requests/Responses/APIChangelogEntry.cs
  osu.Game/Online/API/Requests/Responses/APIChangelogIndex.cs
  osu.Game/Online/API/Requests/Responses/APIChangelogUser.cs
  osu.Game/Online/API/Requests/Responses/APIUpdateStream.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Changelog/ChangelogBuild.cs
  osu.Game/Overlays/Changelog/ChangelogContent.cs
  osu.Game/Overlays/Changelog/ChangelogHeader.cs
  osu.Game/Overlays/Changelog/ChangelogListing.cs
  osu.Game/Overlays/Changelog/ChangelogSingleBuild.cs
  osu.Game/Overlays/Changelog/UpdateStreamBadge.cs
  osu.Game/Overlays/Changelog/UpdateStreamBadgeArea.cs
  osu.Game/Overlays/ChangelogOverlay.cs
  osu.Game/Overlays/Toolbar/Toolbar.cs
  osu.Game/Overlays/Toolbar/ToolbarChangelogButton.cs
Labels: resolves issue

#4882 Prevent logo idle state from being updated incorrectly
  osu.Game/Screens/Menu/ButtonSystem.cs
Labels: resolves issue
