Repository ppy/osu, pull requests merged in 2019-03, with the labels that each got.

#4367 Only display SupportedWindowModes in settings
  osu.Game/Overlays/Settings/Sections/Graphics/LayoutSettings.cs
  osu.Game/Overlays/Settings/SettingsDropdown.cs
Labels: settings

#4371 Fix song select blur potentially never being applied
  osu.Game/Screens/BlurrableBackgroundScreen.cs
Labels: regression, songselect

#4366 Add support for dual (co-op) mode in mania beatmap
  osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModDualStages.cs
  osu.Game.Rulesets.Mania/UI/ManiaRulesetContainer.cs
Labels: gameplay, osu!mania

#4379 Use style heuristics for method bodies
  osu.sln.DotSettings
Labels: code quality

#4378 Fix iOS builds not being able to read their deploy version
  osu.Game/OsuGameBase.cs
  osu.iOS/AppDelegate.cs
  osu.iOS/OsuGameIOS.cs
  osu.iOS/osu.iOS.csproj
Labels: iOS

#4000 Implement clear scores on beatmap
  osu.Game/Beatmaps/BeatmapStore.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Database/MutableDatabaseBackedStoreWithFileIncludes.cs
  osu.Game/Scoring/ScoreStore.cs
  osu.Game/Screens/Select/BeatmapClearScoresDialog.cs
  osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboard.cs
  osu.Game/Screens/Select/SongSelect.cs
  osu.Game/Skinning/SkinStore.cs
Labels: resolves issue

#4380 Add iOS build automation via fastlane
  .gitignore
  Gemfile
  Gemfile.lock
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/Pluginfile
  fastlane/README.md
  osu.iOS.props
  osu.iOS/Info.plist
Labels: tooling

#4390 Fix mod select overlay dimming itself
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
Labels: regression, resolves issue

#4387 Fix a few incorrect fonts
  osu.Game/Overlays/Chat/ChatLine.cs
  osu.Game/Screens/Menu/Disclaimer.cs
Labels: regression, user interface

#4369 Fade out taskbar tooltip after clicking
  osu.Game/Overlays/Toolbar/ToolbarButton.cs
Labels: resolves issue

#4332 Don't show the supporter text if the user already has supporter status
  osu.Game/Screens/Menu/Disclaimer.cs
Labels: user interface

#4250 Update difficulty color bracket thresholds
  osu.Game/Beatmaps/Drawables/DifficultyColouredContainer.cs
Labels: difficulty, proposal

#4392 Add 1/4th of a frame of grace time to hyperdash calculation
  osu.Game.Rulesets.Catch.Tests/TestCaseHyperDash.cs
  osu.Game.Rulesets.Catch/Beatmaps/CatchBeatmapProcessor.cs
Labels: resolves issue

#4407 Fix SquareGraph not correctly filling columns when loaded with a non-zero time
  osu.Game/Screens/Play/SquareGraph.cs
Labels: bug, user interface

#4398 Enforce max consecutive blank lines
  osu.Game/Graphics/UserInterface/RollingCounter.cs
  osu.sln.DotSettings
Labels: code quality

#4320 Ensure beatmap is not disabled before continuing with present
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Database/MutableDatabaseBackedStore.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Direct/DownloadTrackingComposite.cs
  osu.Game/Overlays/Music/PlaylistList.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
  osu.Game/Scoring/ScoreInfo.cs
  osu.Game/Screens/IOsuScreen.cs
  osu.Game/Screens/Multi/Match/Components/ReadyButton.cs
  osu.Game/Screens/Multi/Match/MatchSubScreen.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#4158 Show mods on player loading screen
  osu.Game/Screens/Play/PlayerLoader.cs
Labels: gameplay, user interface

#4374 Add beatmap status on direct list panels
  osu.Game.Tests/Visual/TestCaseDirectPanel.cs
  osu.Game/Overlays/Direct/DirectListPanel.cs
  osu.Game/Overlays/Direct/IconPill.cs
  osu.Game/Tests/Beatmaps/TestBeatmap.cs
Labels: online / API, user interface

#4411 Fix volume not being considered for file samples
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Resources/hitobject-file-samples.osu
  osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs
Labels: resolves issue

#4412 Fix local leaderboard not displaying when logged out
  osu.Game/Online/Leaderboards/Leaderboard.cs
Labels: resolves issue

#4408 Simplify gameplay clocks
  osu.Game.Tests/Visual/TestCaseBackgroundScreenBeatmap.cs
  osu.Game.Tests/Visual/TestCaseGameplayMenuOverlay.cs
  osu.Game.Tests/Visual/TestCaseSongProgress.cs
  osu.Game/Rulesets/UI/RulesetInputManager.cs
  osu.Game/Screens/Play/BreakOverlay.cs
  osu.Game/Screens/Play/GameplayClock.cs
  osu.Game/Screens/Play/HUDOverlay.cs
  osu.Game/Screens/Play/KeyCounter.cs
  osu.Game/Screens/Play/KeyCounterCollection.cs
  osu.Game/Screens/Play/PausableGameplayContainer.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/SkipOverlay.cs
  osu.Game/Screens/Play/SongProgress.cs
  osu.Game/Screens/Play/SongProgressInfo.cs
Labels: resolves issue

#4400 Use correct background display type for multiplayer lobby listing
  osu.Game/Beatmaps/Drawables/UpdateableBeatmapBackgroundSprite.cs
  osu.Game/Screens/Multi/Components/MultiplayerBackgroundSprite.cs
  osu.Game/Screens/Multi/Lounge/Components/DrawableRoom.cs
Labels: resolves issue

#4424 Fix crash on cancelling multiplayer song select when no existing song is selected
  osu.Game/Screens/Select/MatchSongSelect.cs
Labels: resolves issue

#4427 Fix inability to send messages to a newly created room
  osu.Game/Online/Multiplayer/Room.cs
  osu.Game/Screens/Multi/Match/Components/MatchChatDisplay.cs
Labels: resolves issue

#4423 Account for path width correctly in LineGraph
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointPiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBody.cs
  osu.Game/Graphics/UserInterface/LineGraph.cs
Labels: resolves issue

#4434 Fix replay tests not working
  osu.Game.Rulesets.Catch/Mods/CatchModAutoplay.cs
  osu.Game.Rulesets.Catch/Replays/CatchAutoGenerator.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModAutoplay.cs
  osu.Game.Rulesets.Mania/Replays/ManiaAutoGenerator.cs
  osu.Game.Rulesets.Osu/Mods/OsuModAutoplay.cs
  osu.Game.Rulesets.Osu/Replays/OsuAutoGenerator.cs
  osu.Game.Rulesets.Osu/Replays/OsuAutoGeneratorBase.cs
  osu.Game.Rulesets.Taiko/Mods/TaikoModAutoplay.cs
  osu.Game.Rulesets.Taiko/Replays/TaikoAutoGenerator.cs
  osu.Game.Tests/Visual/TestCaseReplay.cs
  osu.Game/Rulesets/Mods/ModAutoplay.cs
  osu.Game/Rulesets/Replays/AutoGenerator.cs
  osu.Game/Rulesets/Ruleset.cs
Labels: testing

#4437 Fix stuck r# inspection
  osu.Game/Utils/RavenLogger.cs
Labels: code quality

#4410 Fix menu cursor not displaying outside of gameplay scaling area
  osu.Game.Rulesets.Osu.Tests/TestCaseGameplayCursor.cs
  osu.Game.Rulesets.Osu/UI/Cursor/GameplayCursorContainer.cs
  osu.Game.Rulesets.Osu/UI/OsuRulesetContainer.cs
  osu.Game/Rulesets/UI/RulesetContainer.cs
  osu.Game/Screens/Play/Player.cs
Labels: bug, gameplay, resolves issue, user interface

#4418 Fix gameplay cursor discrepancies
  osu.Game.Rulesets.Osu/Edit/OsuEditRulesetContainer.cs
  osu.Game.Rulesets.Osu/UI/Cursor/GameplayCursorContainer.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game.Rulesets.Osu/UI/OsuRulesetContainer.cs
  osu.Game/Rulesets/UI/Playfield.cs
  osu.Game/Rulesets/UI/RulesetContainer.cs
  osu.Game/Screens/Play/Player.cs
Labels: resolves issue

#4436 Fix some non-async load scenarios
  osu.Game.Tests/Visual/TestCaseToolbar.cs
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Overlays/Toolbar/Toolbar.cs
Labels: performance

#4431 Simplify gameplay clock logic with a dedicated container
  osu.Game/Screens/Play/GameplayClockContainer.cs
  osu.Game/Screens/Play/HUD/PlayerSettingsOverlay.cs
  osu.Game/Screens/Play/HUDOverlay.cs
  osu.Game/Screens/Play/PausableGameplayContainer.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/PlayerSettings/PlaybackSettings.cs
Labels: resolves issue

#4157 Add "Wind Up" and "Wind Down" mods
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game/Rulesets/Mods/ModDoubleTime.cs
  osu.Game/Rulesets/Mods/ModHalfTime.cs
  osu.Game/Rulesets/Mods/ModTimeRamp.cs
  osu.Game/Rulesets/Mods/ModWindDown.cs
  osu.Game/Rulesets/Mods/ModWindUp.cs
Labels: gameplay, mods

#4438 Extract slider tick creation so it can be shared with osu!catch
  osu.Game.Rulesets.Catch.Tests/CatchDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Catch/Objects/JuiceStream.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseOsuPlayer.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Rulesets.Osu/Objects/SliderTailCircle.cs
  osu.Game/Rulesets/Objects/SliderEventGenerator.cs
Labels: code quality, resolves issue

#4457 Fix HoldForMenuButton getting stuck in a confirming state
  osu.Game/Screens/Play/HUD/HoldForMenuButton.cs
Labels: resolves issue

#4456 Fix osu!direct firing excess queries during initial search characters
  osu.Game/Overlays/DirectOverlay.cs
Labels: code quality, online / API, overlays

#4453 Ensure import continues if an existing item's online IDs are in a bad state
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Database/ArchiveModelManager.cs
Labels: database, import

#4445 Fix direct panel stats being misaligned by one pixel
  osu.Game/Overlays/Direct/DirectGridPanel.cs
  osu.Game/Overlays/Direct/DirectListPanel.cs
Labels: design, overlays

#4461 Fix mania miss judgement animations disappearing too quickly
  osu.Game.Rulesets.Mania/UI/DrawableManiaJudgement.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuJudgement.cs
  osu.Game.Rulesets.Taiko/UI/DrawableTaikoJudgement.cs
  osu.Game/Rulesets/Judgements/DrawableJudgement.cs
Labels: gameplay, resolves issue

#4458 Fix "wind" mods adjusting rate twice
  osu.Game/Rulesets/Mods/ModDaycore.cs
  osu.Game/Rulesets/Mods/ModDoubleTime.cs
  osu.Game/Rulesets/Mods/ModHalfTime.cs
  osu.Game/Rulesets/Mods/ModNightcore.cs
  osu.Game/Rulesets/Mods/ModTimeAdjust.cs
  osu.Game/Rulesets/Mods/ModTimeRamp.cs
  osu.Game/Rulesets/Mods/ModWindDown.cs
  osu.Game/Rulesets/Mods/ModWindUp.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
  osu.Game/Tests/Visual/RateAdjustedBeatmapTestCase.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: resolves issue

#4462 Increase validation performed on .osu files to avoid hard crashes
  osu.Game.Tests/Beatmaps/Formats/ParsingTest.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Beatmaps/Formats/Parsing.cs
  osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs
Labels: resolves issue

#4470 Fix catch difficulty calculator not providing adjustment mods
  osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyCalculator.cs
Labels: osu!catch

#4472 Address styling issues on CodeFactor
  osu.Game/Migrations/20180628011956_RemoveNegativeSetIDs.cs
  osu.iOS/Application.cs
Labels: code quality

#4433 Don't perform lookup of beatmap stats unless an online id is present
  osu.Game.Tests/Visual/TestCaseBeatmapDetailArea.cs
  osu.Game/Beatmaps/DummyWorkingBeatmap.cs
  osu.Game/Screens/Select/BeatmapDetails.cs
Labels: online / API, songselect

#4468 Fix ticks not being generated at the minimum tick distance
  osu.Game/Rulesets/Objects/SliderEventGenerator.cs
Labels: resolves issue

#4475 Extract RulesetInputManager's timing logic to FrameStabilityContainer
  osu.Game/Rulesets/UI/FrameStabilityContainer.cs
  osu.Game/Rulesets/UI/RulesetContainer.cs
  osu.Game/Rulesets/UI/RulesetInputManager.cs
Labels: code quality, gameplay

#4465 Use interface to access API
  osu.Game.Tests/Visual/TestCaseMatchLeaderboard.cs
  osu.Game.Tests/Visual/TestCaseUpdateableBeatmapBackgroundSprite.cs
  osu.Game.Tests/Visual/TestCaseUserProfile.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Online/API/APIRequest.cs
  osu.Game/Online/API/DummyAPIAccess.cs
  osu.Game/Online/API/IAPIProvider.cs
  osu.Game/Online/API/IOnlineComponent.cs
  osu.Game/Online/Leaderboards/Leaderboard.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/AccountCreation/ScreenEntry.cs
  osu.Game/Overlays/AccountCreation/ScreenWarning.cs
  osu.Game/Overlays/AccountCreationOverlay.cs
  osu.Game/Overlays/BeatmapSet/Buttons/DownloadButton.cs
  osu.Game/Overlays/BeatmapSet/Scores/ScoresContainer.cs
  osu.Game/Overlays/BeatmapSetOverlay.cs
  osu.Game/Overlays/DirectOverlay.cs
  osu.Game/Overlays/Profile/Sections/PaginatedContainer.cs
  osu.Game/Overlays/Profile/Sections/Recent/DrawableRecentActivity.cs
  osu.Game/Overlays/Settings/Sections/General/LoginSettings.cs
  osu.Game/Overlays/SocialOverlay.cs
  osu.Game/Overlays/Toolbar/ToolbarUserButton.cs
  osu.Game/Overlays/UserProfileOverlay.cs
  osu.Game/Screens/Menu/ButtonSystem.cs
  osu.Game/Screens/Menu/Disclaimer.cs
  osu.Game/Screens/Multi/Lounge/Components/RoomInspector.cs
  osu.Game/Screens/Multi/Multiplayer.cs
  osu.Game/Screens/Multi/Play/TimeshiftPlayer.cs
  osu.Game/Screens/Multi/RoomManager.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Select/BeatmapDetails.cs
  osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboard.cs
Labels: online / API, testing

#4484 Fix storyboards not having the correct gameplay clock
  osu.Game/Storyboards/Drawables/DrawableStoryboard.cs
Labels: resolves issue

#4486 Fix catch HR inaccuracies
  osu.Game.Rulesets.Catch/Mods/CatchModHardRock.cs
Labels: mods, osu!catch

#4467 Disclaimer support text
  osu.Game.Tests/Visual/TestCaseDisclaimer.cs
  osu.Game/Screens/Menu/Disclaimer.cs
Labels: blocked, user interface

#4489 Fix difficulty calculation using the pre-mod catcher size
  osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyCalculator.cs
Labels: difficulty, osu!catch

#4460 Remove unnecessary early return for maching beatmap IDs
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game/Beatmaps/BeatmapManager.cs
Labels: code quality, database

#4455 Fix screen background performance
  osu.Game/Screens/BackgroundScreenStack.cs
  osu.Game/Screens/Backgrounds/BackgroundScreenBeatmap.cs
  osu.Game/Screens/Backgrounds/BackgroundScreenDefault.cs
  osu.Game/Screens/BlurrableBackgroundScreen.cs
  osu.Game/Screens/Menu/MainMenu.cs
  osu.Game/Screens/Play/ScreenWithBeatmapBackground.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: performance, user interface

#4493 Further fixes to catch HR application
  osu.Game.Rulesets.Catch/Mods/CatchModHardRock.cs
Labels: gameplay, mods, osu!catch

#4485 Increase flexibility of player test cases
  osu.Game.Rulesets.Catch.Tests/TestCaseAutoJuiceStream.cs
  osu.Game.Rulesets.Catch.Tests/TestCaseBananaShower.cs
  osu.Game.Rulesets.Catch.Tests/TestCaseCatchPlayer.cs
  osu.Game.Rulesets.Catch.Tests/TestCaseCatchStacker.cs
  osu.Game.Rulesets.Catch.Tests/TestCaseHyperDash.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseHitCircleLongCombo.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseOsuPlayer.cs
  osu.Game.Tests/Visual/TestCaseAllPlayers.cs
  osu.Game.Tests/Visual/TestCaseAutoplay.cs
  osu.Game.Tests/Visual/TestCasePlayerReferenceLeaking.cs
  osu.Game.Tests/Visual/TestCaseReplay.cs
  osu.Game/Tests/Visual/AllPlayersTestCase.cs
  osu.Game/Tests/Visual/PlayerTestCase.cs
Labels: gameplay, testing

#4495 Fix catch spinners not being allowed for conversion
  osu.Game/Rulesets/Objects/Legacy/Catch/ConvertSpinner.cs
Labels: osu!catch

#4496 Fix mods being reused for difficulty calculation
  osu.Game/Rulesets/Difficulty/DifficultyCalculator.cs
  osu.Game/Rulesets/Mods/Mod.cs
Labels: mods

#4466 Move user blurring logic into UserDimContainer
  osu.Game.Tests/Visual/TestCaseBackgroundScreenBeatmap.cs
  osu.Game/Graphics/Containers/UserDimContainer.cs
  osu.Game/Screens/Backgrounds/BackgroundScreenBeatmap.cs
  osu.Game/Screens/Backgrounds/BackgroundScreenDefault.cs
  osu.Game/Screens/BlurrableBackgroundScreen.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/Screens/Play/ScreenWithBeatmapBackground.cs
  osu.Game/Screens/Ranking/Results.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#4497 Fix gameplay cursor showing in editor
  osu.Game.Rulesets.Osu/Edit/DrawableOsuEditRuleset.cs
Labels: editor, regression

#4504 Fix song select bindable crashes
  osu.Game/Screens/Select/BeatmapCarousel.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#4505 Fix random select crashing
  osu.Game/Screens/Select/BeatmapCarousel.cs
Labels: resolves issue

#4508 Bring nuget packages up to date
  osu.Desktop/osu.Desktop.csproj
  osu.Game.Rulesets.Catch.Tests/osu.Game.Rulesets.Catch.Tests.csproj
  osu.Game.Rulesets.Mania.Tests/osu.Game.Rulesets.Mania.Tests.csproj
  osu.Game.Rulesets.Osu.Tests/osu.Game.Rulesets.Osu.Tests.csproj
  osu.Game.Rulesets.Taiko.Tests/osu.Game.Rulesets.Taiko.Tests.csproj
  osu.Game.Tests/osu.Game.Tests.csproj
  osu.Game/osu.Game.csproj
Labels: libraries

#4511 Fix AccountCreationOverlay tests and better complete dummy api's behaviour
  osu.Game.Tests/Visual/TestCaseAccountCreationOverlay.cs
  osu.Game.Tests/Visual/TestCaseDisclaimer.cs
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Online/API/DummyAPIAccess.cs
Labels: online / API, testing

#4487 Simplify and centralise pause logic
  osu.Game.Tests/Visual/TestCaseBackgroundScreenBeatmap.cs
  osu.Game.Tests/Visual/TestCaseGameplayMenuOverlay.cs
  osu.Game.Tests/Visual/TestCasePause.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
  osu.Game/Screens/Play/PausableGameplayContainer.cs
  osu.Game/Screens/Play/PauseOverlay.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Tests/Visual/TestCasePlayer.cs
Labels: code quality, gameplay

#4451 Centralise BackgroundScreenStack handling
  osu.Game.Tests/Visual/Background/TestCaseBackgroundScreenBeatmap.cs
  osu.Game.Tests/Visual/Gameplay/TestCasePlayerLoader.cs
  osu.Game.Tests/Visual/Multiplayer/TestCaseMultiHeader.cs
  osu.Game.Tests/Visual/TestCaseOsuScreenStack.cs
  osu.Game.Tests/Visual/UserInterface/TestCaseScreenBreadcrumbControl.cs
  osu.Game/OsuGame.cs
  osu.Game/Screens/Multi/Multiplayer.cs
  osu.Game/Screens/OsuScreenStack.cs
  osu.Game/Tests/Visual/AllPlayersTestCase.cs
  osu.Game/Tests/Visual/EditorTestCase.cs
  osu.Game/Tests/Visual/PlayerTestCase.cs
  osu.Game/Tests/Visual/ScreenTestCase.cs
Labels: multiplayer

#4525 Make the scaling background customisable to current skin background
  osu.Game/Graphics/Containers/ScalingContainer.cs
Labels: resolves issue

#4538 Fix TestWorkingBeatmap not running for times below zero
  osu.Game/Tests/Beatmaps/TestWorkingBeatmap.cs
Labels: bug, testing

#4541 Fix TestCaseBackgroundScreenBeatmap getting stuck
  osu.Game.Tests/Visual/Background/TestCaseBackgroundScreenBeatmap.cs
Labels: resolves issue, testing

#4547 Fix slider ball not always receiving position in time
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBall.cs
Labels: bug, gameplay, osu!

#4528 Add safety against accidental clearing of DrawableHitObject children
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableBananaShower.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableDroplet.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableFruit.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableJuiceStream.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNote.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNoteTick.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableNote.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableBarLine.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableTaikoHitObject.cs
  osu.Game.Tests/Visual/Gameplay/TestCaseScrollingHitObjects.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: code quality, gameplay

#4531 Add ManualInputManager to screen tests
  osu.Game.Tests/Visual/Multiplayer/TestCaseLoungeRoomsContainer.cs
  osu.Game.Tests/Visual/Tournament/TestCaseDrawings.cs
  osu.Game/Tests/Visual/ManualInputManagerTestCase.cs
  osu.Game/Tests/Visual/PlayerTestCase.cs
  osu.Game/Tests/Visual/ScreenTestCase.cs
Labels: testing

#4534 Don't update gameplay loop while paused
  osu.Game/Rulesets/UI/FrameStabilityContainer.cs
  osu.Game/Screens/Play/GameplayClock.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
Labels: gameplay

#4535 Add base gameplay cursor class to retrieve true visibility state
  osu.Game.Rulesets.Osu.Tests/TestCaseGameplayCursor.cs
  osu.Game.Rulesets.Osu/Edit/DrawableOsuEditRuleset.cs
  osu.Game.Rulesets.Osu/UI/Cursor/OsuCursorContainer.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Rulesets/UI/GameplayCursorContainer.cs
  osu.Game/Rulesets/UI/Playfield.cs
Labels: gameplay

#4536 Rename KeyCounterCollection -> KeyCounterDisplay
  osu.Game.Tests/Visual/Gameplay/TestCaseKeyCounter.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Rulesets/UI/RulesetInputManager.cs
  osu.Game/Screens/Play/HUDOverlay.cs
  osu.Game/Screens/Play/KeyCounterDisplay.cs
Labels: code quality

#4533 Move all playfield adjustments to universal PlayfieldAdjustmentContainer
  osu.Game.Rulesets.Catch/UI/CatchPlayfield.cs
  osu.Game.Rulesets.Catch/UI/CatchPlayfieldAdjustmentContainer.cs
  osu.Game.Rulesets.Catch/UI/DrawableCatchRuleset.cs
  osu.Game.Rulesets.Mania/UI/DrawableManiaRuleset.cs
  osu.Game.Rulesets.Mania/UI/ManiaPlayfield.cs
  osu.Game.Rulesets.Mania/UI/ManiaPlayfieldAdjustmentContainer.cs
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game.Rulesets.Osu/UI/DrawableOsuRuleset.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfieldAdjustmentContainer.cs
  osu.Game.Rulesets.Taiko/UI/DrawableTaikoRuleset.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfieldAdjustmentContainer.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Rulesets/UI/Playfield.cs
  osu.Game/Rulesets/UI/PlayfieldAdjustmentContainer.cs
Labels: gameplay

#4156 Correctly loop from preview point in song select
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#4543 Fix WedgeBackground bleeding into other elements
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#4020 Add Catch PerformanceCalculator
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Catch/Difficulty/CatchPerformanceCalculator.cs
  osu.Game/Scoring/Legacy/LegacyScoreInfo.cs
  osu.Game/Scoring/Legacy/LegacyScoreParser.cs
Labels: difficulty, osu!catch

#4542 Fix incorrect statistics being shown in results
  osu.Game.Tests/Visual/SongSelect/TestCaseBeatmapScoresContainer.cs
  osu.Game/Online/API/Requests/GetScoresRequest.cs
  osu.Game/Online/API/Requests/GetUserScoresRequest.cs
  osu.Game/Online/API/Requests/Responses/APILegacyScoreInfo.cs
  osu.Game/Online/API/Requests/Responses/APILegacyScores.cs
  osu.Game/Overlays/BeatmapSet/Scores/DrawableScore.cs
  osu.Game/Overlays/BeatmapSet/Scores/DrawableTopScore.cs
  osu.Game/Overlays/BeatmapSet/Scores/ScoresContainer.cs
Labels: online / API

#4548 Fix FramedReplayInputHandler frame handling
  osu.Game.Rulesets.Catch/Replays/CatchFramedReplayInputHandler.cs
  osu.Game.Rulesets.Mania/Replays/ManiaFramedReplayInputHandler.cs
  osu.Game.Rulesets.Osu/Replays/OsuFramedReplayInputHandler.cs
  osu.Game.Rulesets.Taiko/Replays/TaikoFramedReplayInputHandler.cs
  osu.Game.Tests/NonVisual/FramedReplayinputHandlerTest.cs
  osu.Game/Rulesets/Replays/FramedReplayInputHandler.cs
Labels: replay, testing

#4539 Remove read/write player flags
  osu.Game.Rulesets.Osu.Tests/TestCaseSliderInput.cs
  osu.Game.Tests/Visual/Background/TestCaseBackgroundScreenBeatmap.cs
  osu.Game.Tests/Visual/Gameplay/TestCaseAutoplay.cs
  osu.Game.Tests/Visual/Gameplay/TestCasePlayerLoader.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/ReplayPlayer.cs
  osu.Game/Tests/Visual/AllPlayersTestCase.cs
  osu.Game/Tests/Visual/PlayerTestCase.cs
Labels: code quality

#4521 Fix DrawableRuleset drawable creation method's name
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableBananaShower.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableJuiceStream.cs
  osu.Game.Rulesets.Catch/UI/CatchPlayfield.cs
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
  osu.Game.Rulesets.Catch/UI/DrawableCatchRuleset.cs
  osu.Game.Rulesets.Mania/UI/DrawableManiaRuleset.cs
  osu.Game.Rulesets.Osu/UI/DrawableOsuRuleset.cs
  osu.Game.Rulesets.Taiko/UI/DrawableTaikoRuleset.cs
  osu.Game/Rulesets/Edit/DrawableEditRuleset.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
Labels: code quality

#4537 Add stable storyboard element ordering
  osu.Game.Tests/Beatmaps/Formats/LegacyStoryboardDecoderTest.cs
  osu.Game/Beatmaps/Formats/LegacyStoryboardDecoder.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardSample.cs
  osu.Game/Storyboards/IStoryboardElement.cs
  osu.Game/Storyboards/StoryboardLayer.cs
  osu.Game/Storyboards/StoryboardSample.cs
Labels: storyboard

#4546 Fix offset of music controller when toolbar is hidden
  osu.Game/OsuGame.cs
  osu.Game/Overlays/MusicController.cs
Labels: user interface

#4443 Add ScreenTitle class
  osu.Game/Graphics/UserInterface/ScreenTitle.cs
  osu.Game/Screens/Multi/Header.cs
Labels: multiplayer, user interface

#4554 Rework TestCaseLoaderAnimation to avoid timing issues
  osu.Game.Tests/Visual/Menus/TestCaseLoaderAnimation.cs
  osu.Game/Tests/Visual/ScreenTestCase.cs
Labels: resolves issue

#4561 Fix stable import failing
  osu.Desktop/OsuGameDesktop.cs
Labels: import, regression

#4564 Add ability to sort by favourites on osu!direct
  osu.Game/Overlays/Direct/FilterControl.cs
Labels: online / API
