Repository ppy/osu, pull requests merged in 2019-10, with the labels that each got.

#6289 Hide unnecessary profile sections for bots
  osu.Game.Tests/Visual/Online/TestSceneUserProfileOverlay.cs
  osu.Game/Overlays/UserProfileOverlay.cs
  osu.Game/Users/User.cs
Labels: size/S, user profile

#6348 Fix username overlap timestamp in match chatroom
  osu.Game.Tests/Visual/Online/TestSceneStandAloneChatDisplay.cs
  osu.Game/Online/Chat/StandAloneChatDisplay.cs
  osu.Game/Overlays/Chat/ChatLine.cs
Labels: resolves issue, size/S

#6359 Change HoldForMenu slider precision to 50
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Graphics/Containers/HoldToConfirmContainer.cs
  osu.Game/Overlays/Settings/Sections/Graphics/UserInterfaceSettings.cs
  osu.Game/Screens/Menu/MainMenu.cs
  osu.Game/Screens/Play/HUD/HoldForMenuButton.cs
Labels: size/S

#6351 Simplify exit logic of screens with textboxes using back button receptor
  osu.Game/Graphics/UserInterface/BackButton.cs
  osu.Game/Graphics/UserInterface/FocusedTextBox.cs
  osu.Game/Graphics/UserInterface/OsuTextBox.cs
  osu.Game/Online/Chat/StandAloneChatDisplay.cs
  osu.Game/Overlays/Chat/Selection/ChannelSelectionOverlay.cs
  osu.Game/Overlays/ChatOverlay.cs
  osu.Game/Overlays/Music/FilterControl.cs
  osu.Game/Overlays/Music/PlaylistOverlay.cs
  osu.Game/Overlays/SearchableList/SearchableListOverlay.cs
  osu.Game/Overlays/SettingsPanel.cs
  osu.Game/Screens/Multi/Lounge/LoungeSubScreen.cs
  osu.Game/Screens/Multi/Match/MatchSubScreen.cs
  osu.Game/Screens/Select/FilterControl.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: size/M

#6344 Fix memory leaks due to audio track recycle order
  osu.Game/Beatmaps/BindableBeatmap.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Tests/Visual/OsuTestScene.cs
Labels: memory, size/M

#6363 Only lock the database for the duration of a deletion
  osu.Game/Database/ArchiveModelManager.cs
Labels: database, resolves issue, size/S

#6375 Fix random failures on BeatmapCarousel filter test
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs
Labels: size/S, testing

#6126 Show notification when volume is muted
  osu.Game.Tests/Visual/Gameplay/TestScenePlayerLoader.cs
  osu.Game/Configuration/SessionStatics.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/VolumeOverlay.cs
  osu.Game/Screens/Play/PlayerLoader.cs
Labels: audio, size/L, ux

#6379 Fix possible nullref in MusicController
  osu.Game/Overlays/MusicController.cs
Labels: size/XS, testing

#6390 Update lazer default combo colours to match stable
  osu.Game/Skinning/DefaultSkinConfiguration.cs
Labels: gameplay, resolves issue, size/XS

#6250 Truncate long metadata on beatmap info wedge
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapInfoWedge.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: size/M, song select

#6257 Add the new switch button + labelled switch button
  osu.Game.Tests/Visual/UserInterface/TestSceneLabelledSwitchButton.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneSwitchButton.cs
  osu.Game/Graphics/UserInterfaceV2/LabelledSwitchButton.cs
  osu.Game/Graphics/UserInterfaceV2/SwitchButton.cs
Labels: size/L, user interface

#6369 Fix Alt-F4 being blocked during gameplay
  osu.Game.Tests/Visual/Gameplay/TestScenePause.cs
  osu.Game/Screens/Play/Player.cs
Labels: resolves issue, size/S, ux

#6117 Add fallback decoder option for badly-headered files
  osu.Game.Rulesets.Osu.Tests/StackingTest.cs
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Beatmaps/Formats/LegacyDecoderTest.cs
  osu.Game.Tests/Beatmaps/Formats/LegacyStoryboardDecoderTest.cs
  osu.Game.Tests/Beatmaps/Formats/OsuJsonDecoderTest.cs
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game.Tests/Beatmaps/IO/LineBufferedReaderTest.cs
  osu.Game.Tests/Beatmaps/IO/OszArchiveReaderTest.cs
  osu.Game.Tests/Resources/corrupted-header.osu
  osu.Game.Tests/Resources/empty-line-instead-of-header.osu
  osu.Game.Tests/Resources/empty-lines-at-start.osu
  osu.Game.Tests/Resources/missing-header.osu
  osu.Game.Tests/Resources/no-empty-line-after-header.osu
  osu.Game.Tests/Skins/LegacySkinDecoderTest.cs
  osu.Game.Tests/WaveformTestBeatmap.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/BeatmapManager_WorkingBeatmap.cs
  osu.Game/Beatmaps/Formats/Decoder.cs
  osu.Game/Beatmaps/Formats/JsonBeatmapDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyDifficultyCalculatorBeatmapDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyStoryboardDecoder.cs
  osu.Game/IO/LineBufferedReader.cs
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/Tests/Beatmaps/BeatmapConversionTest.cs
  osu.Game/Tests/Beatmaps/DifficultyCalculatorTest.cs
  osu.Game/Tests/Beatmaps/TestBeatmap.cs
Labels: beatmap parsing, resolves issue, size/L

#6374 Fix key counters appearing negative on intense beatmaps
  osu.Game/Rulesets/UI/FrameStabilityContainer.cs
  osu.Game/Rulesets/UI/RulesetInputManager.cs
Labels: replay, resolves issue, size/M

#6373 Add StartTimeChanged event to EditorBeatmap and add tests
  osu.Game.Tests/Beatmaps/EditorBeatmapTest.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Objects/HitObject.cs
  osu.Game/Screens/Edit/EditorBeatmap.cs
Labels: editor, size/L

#6400 Fix keybinding order of beatmap options
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapOptionsOverlay.cs
  osu.Game/Screens/Select/Options/BeatmapOptionsOverlay.cs
  osu.Game/Screens/Select/PlaySongSelect.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue, size/XS, song select

#6396 Allow fallback decoder overwrite
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game/Beatmaps/Formats/Decoder.cs
Labels: beatmap parsing, size/S

#6406 Resume music to same position when exiting gameplay
  osu.Game/Screens/Select/SongSelect.cs
Labels: audio, resolves issue, size/S

#6377 Move placement blueprint movement logic to a higher level
  osu.Game.Rulesets.Mania/Edit/Blueprints/HoldNotePlacementBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/ManiaPlacementBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/HitCircles/HitCirclePlacementBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderPlacementBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Spinners/SpinnerPlacementBlueprint.cs
  osu.Game/Rulesets/Edit/PlacementBlueprint.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
  osu.Game/Tests/Visual/PlacementBlueprintTestScene.cs
Labels: editor

#6378 Fix mania placing hitobjects offset from the mouse position
  osu.Game.Rulesets.Mania.Tests/ManiaPlacementBlueprintTestScene.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/ManiaPlacementBlueprint.cs
Labels: editor, osu!mania, size/M

#6288 Fix cursor trail appearing regardless of the setting in replays
  osu.Game.Rulesets.Osu/UI/Cursor/OsuCursorContainer.cs
Labels: replay, resolves issue, size/XS

#6414 Fix beatmap carousel including filtered items in sort calculations
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs
  osu.Game/Screens/Select/Carousel/CarouselBeatmapSet.cs
  osu.Game/Screens/Select/Carousel/CarouselGroup.cs
Labels: resolves issue, size/L, song select

#6407 Autoscroll playlist on song change
  osu.Game/Overlays/Music/PlaylistList.cs
  osu.Game/Overlays/Settings/Sections/AudioSection.cs
Labels: resolves issue, size/M, user interface, ux

#6411 Fix tab controls overflowing right content at max ui scale
  osu.Game/Overlays/Chat/Tabs/ChannelTabControl.cs
  osu.Game/Overlays/ChatOverlay.cs
  osu.Game/Overlays/SearchableList/SearchableListFilterControl.cs
  osu.Game/Screens/Select/BeatmapDetailArea.cs
  osu.Game/Screens/Select/BeatmapDetailAreaTabControl.cs
Labels: resolves issue, size/M, user interface

#6425 Fix editor defaulting to 0.5x playback speed
  osu.Game/Screens/Edit/Components/PlaybackControl.cs
Labels: editor, size/XS

#6426 Fix skins not being displayed correctly in the editor
  osu.Game/Screens/Edit/Compose/ComposeScreen.cs
  osu.Game/Skinning/SkinProvidingContainer.cs
Labels: editor, resolves issue, size/S

#6424 Avoid excess background updates in playlist overlay
  osu.Game/Overlays/Music/PlaylistList.cs
Labels: performance, size/XS

#6291 Rework osu! selection blueprint updates
  osu.Game.Rulesets.Mania.Tests/TestSceneHoldNoteSelectionBlueprint.cs
  osu.Game.Rulesets.Mania.Tests/TestSceneNoteSelectionBlueprint.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneHitCircleSelectionBlueprint.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneSliderSelectionBlueprint.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneSpinnerSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/BlueprintPiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/HitCircles/Components/HitCirclePiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/HitCircles/HitCirclePlacementBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/HitCircles/HitCircleSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/HitObjectPiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/OsuSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/SliderPiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointPiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointVisualiser.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/SliderBodyPiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/SliderCirclePiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderCircleSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderPlacementBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Spinners/Components/SpinnerPiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Spinners/SpinnerPlacementBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Spinners/SpinnerSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game/Tests/Visual/SelectionBlueprintTestScene.cs
Labels: editor, size/L

#6430 Move WaveContainer test out of editor namespace
  osu.Game.Tests/Visual/UserInterface/TestSceneWaveContainer.cs
Labels: testing

#6428 Fix ignored song select test
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
Labels: size/XS, testing

#6429 Add todo in slider tail to avoid confusion
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderTail.cs
Labels: code quality, size/XS

#6427 Better signify under construction screens in editor
  osu.Game/Screens/Edit/Compose/ComposeScreen.cs
  osu.Game/Screens/Edit/Design/DesignScreen.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/Setup/SetupScreen.cs
  osu.Game/Screens/Edit/Timing/TimingScreen.cs
  osu.Game/Screens/ScreenWhiteBox.cs
Labels: editor, size/L, ux

#6423 Fix song select not correctly playing tracks in some cases
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue, size/S, song select

#6444 Add abstract implementation for editor screens which display a timeline
  osu.Game.Tests/Visual/Editor/TestSceneComposeScreen.cs
  osu.Game/Screens/Edit/Compose/ComposeScreen.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/EditorScreen.cs
  osu.Game/Screens/Edit/EditorScreenWithTimeline.cs
Labels: editor, size/L

#6445 Use empty HitWindows to fix editor slider display
  osu.Game.Rulesets.Catch/Objects/CatchHitObject.cs
  osu.Game.Rulesets.Mania/Objects/HoldNote.cs
  osu.Game.Rulesets.Mania/Objects/HoldNoteTick.cs
  osu.Game.Rulesets.Osu/Objects/RepeatPoint.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Rulesets.Osu/Objects/SliderTailCircle.cs
  osu.Game.Rulesets.Osu/Objects/SliderTick.cs
  osu.Game.Rulesets.Osu/Objects/Spinner.cs
  osu.Game.Rulesets.Taiko/Objects/DrumRoll.cs
  osu.Game.Rulesets.Taiko/Objects/DrumRollTick.cs
  osu.Game.Rulesets.Taiko/Objects/StrongHitObject.cs
  osu.Game.Rulesets.Taiko/Objects/Swell.cs
  osu.Game.Rulesets.Taiko/Objects/SwellTick.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Rulesets/Objects/HitObject.cs
  osu.Game/Rulesets/Objects/Legacy/Mania/ConvertHit.cs
  osu.Game/Rulesets/Objects/Legacy/Mania/ConvertHold.cs
  osu.Game/Rulesets/Objects/Legacy/Mania/ConvertSlider.cs
  osu.Game/Rulesets/Objects/Legacy/Mania/ConvertSpinner.cs
  osu.Game/Rulesets/Objects/Legacy/Osu/ConvertHit.cs
  osu.Game/Rulesets/Objects/Legacy/Osu/ConvertSlider.cs
  osu.Game/Rulesets/Objects/Legacy/Osu/ConvertSpinner.cs
  osu.Game/Rulesets/Objects/Legacy/Taiko/ConvertHit.cs
  osu.Game/Rulesets/Objects/Legacy/Taiko/ConvertSlider.cs
  osu.Game/Rulesets/Objects/Legacy/Taiko/ConvertSpinner.cs
  osu.Game/Rulesets/Scoring/HitWindows.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Screens/Play/HUD/HitErrorDisplay.cs
Labels: code quality, editor, gameplay, resolves issue, size/L

#6219 Move common logic to IntroScreen
  osu.Game/Screens/Menu/IntroCircles.cs
  osu.Game/Screens/Menu/IntroScreen.cs
  osu.Game/Screens/Menu/IntroTriangles.cs
Labels: code quality, menu, size/L

#6458 Update to .NET core 3.0
  .idea/.idea.osu/.idea/runConfigurations/CatchRuleset__Tests_.xml
  .idea/.idea.osu/.idea/runConfigurations/ManiaRuleset__Tests_.xml
  .idea/.idea.osu/.idea/runConfigurations/OsuRuleset__Tests_.xml
  .idea/.idea.osu/.idea/runConfigurations/TaikoRuleset__Tests_.xml
  .idea/.idea.osu/.idea/runConfigurations/Tournament.xml
  .idea/.idea.osu/.idea/runConfigurations/osu_.xml
  .idea/.idea.osu/.idea/runConfigurations/osu___Tests_.xml
  .vscode/launch.json
  .vscode/tasks.json
  README.md
  appveyor.yml
  appveyor_deploy.yml
  build.ps1
  build.sh
  build/build.cake
  build/cakebuild.csproj
  osu.Android.props
  osu.Desktop/osu.Desktop.csproj
  osu.Game.Rulesets.Catch.Tests/.vscode/launch.json
  osu.Game.Rulesets.Catch.Tests/osu.Game.Rulesets.Catch.Tests.csproj
  osu.Game.Rulesets.Mania.Tests/.vscode/launch.json
  osu.Game.Rulesets.Mania.Tests/osu.Game.Rulesets.Mania.Tests.csproj
  osu.Game.Rulesets.Osu.Tests/.vscode/launch.json
  osu.Game.Rulesets.Osu.Tests/osu.Game.Rulesets.Osu.Tests.csproj
  osu.Game.Rulesets.Taiko.Tests/.vscode/launch.json
  osu.Game.Rulesets.Taiko.Tests/osu.Game.Rulesets.Taiko.Tests.csproj
  osu.Game.Tests/osu.Game.Tests.csproj
  osu.Game.Tournament.Tests/osu.Game.Tournament.Tests.csproj
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: libraries, size/L

#6467 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#6461 Fix platform dependency in buffered reader test
  osu.Game.Tests/Beatmaps/IO/LineBufferedReaderTest.cs
Labels: code quality, compatibility, size/M, testing

#6469 Revert nativelibs update
  osu.iOS.props
Labels: size/XS

#6470 Update fastlane
  Gemfile.lock
Labels: size/S

#6471 Remove unnecessary local assignment
  osu.Game/Screens/Select/SongSelect.cs
Labels: code quality, size/XS

#6466 Update ranking display to handle new osu-web request format
  osu.Game/Online/API/Requests/GetUsersRequest.cs
  osu.Game/Online/API/Requests/GetUsersResponse.cs
  osu.Game/Online/API/Requests/ResponseWithCursor.cs
  osu.Game/Online/API/Requests/SearchBeatmapSetsResponse.cs
  osu.Game/Overlays/SocialOverlay.cs
Labels: online / API, resolves issue, size/M

#6431 Move editor selections relative to hitobject start positions
  osu.Game.Rulesets.Mania/Edit/Blueprints/ManiaSelectionBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/ManiaSelectionHandler.cs
  osu.Game.Rulesets.Osu/Edit/OsuSelectionHandler.cs
  osu.Game/Rulesets/Edit/SelectionBlueprint.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
  osu.Game/Screens/Edit/Compose/Components/MoveSelectionEvent.cs
  osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs
Labels: editor, size/L

#6475 Fix build scripts not passing arguments to cake
  build.ps1
  build.sh
Labels: size/M, tooling

#6451 Fix audio playback position being reset after resuming to song select
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game.Tests/Resources/TestResources.cs
  osu.Game.Tests/Visual/Menus/TestSceneScreenNavigation.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: audio, resolves issue, size/L, song select

#6473 Implement abstract class and structure for editor grids
  osu.Game.Tests/Visual/Editor/TestSceneBeatSnapGrid.cs
  osu.Game/Screens/Edit/Compose/Components/BeatSnapGrid.cs
Labels: editor, size/L

#6457 Implement CommentsHeader component
  osu.Game.Tests/Visual/Online/TestSceneCommentsHeader.cs
  osu.Game/Overlays/Comments/CommentsHeader.cs
  osu.Game/Overlays/Comments/HeaderButton.cs
  osu.Game/Overlays/Comments/SortTabControl.cs
Labels: size/L, user interface

#6514 Make OverlayContainers with no blocking input VisibilityContainers
  osu.Desktop/Overlays/VersionManager.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Music/PlaylistOverlay.cs
  osu.Game/Overlays/Toolbar/Toolbar.cs
  osu.Game/Overlays/VolumeOverlay.cs
  osu.Game/Screens/Play/ResumeOverlay.cs
  osu.Game/Screens/Play/SkipOverlay.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
Labels: code quality, size/S

#6501 Don't automatically return to gameplay from map pool if no picks are made
  osu.Game.Tournament/Screens/MapPool/MapPoolScreen.cs
Labels: resolves issue, size/XS, tournament

#6504 Implement CommentsContainer component
  osu.Game.Tests/Visual/Online/TestSceneCommentsContainer.cs
  osu.Game.Tests/Visual/Online/TestSceneShowMoreButton.cs
  osu.Game/Graphics/UserInterface/ShowMoreButton.cs
  osu.Game/Online/API/Requests/GetCommentsRequest.cs
  osu.Game/Online/API/Requests/Responses/Comment.cs
  osu.Game/Online/API/Requests/Responses/CommentBundle.cs
  osu.Game/Overlays/Comments/CommentsContainer.cs
  osu.Game/Overlays/Comments/CommentsShowMoreButton.cs
  osu.Game/Overlays/Comments/DeletedChildrenPlaceholder.cs
  osu.Game/Overlays/Comments/DrawableComment.cs
  osu.Game/Overlays/Comments/ShowChildrenButton.cs
  osu.Game/Overlays/Profile/Sections/PaginatedContainer.cs
  osu.Game/Overlays/Profile/Sections/ProfileShowMoreButton.cs
Labels: size/XXL, user interface

#6515 Make RulesetStore initialise at construction time
  osu.Game.Tests/Visual/Background/TestSceneUserDimContainer.cs
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Rulesets/RulesetStore.cs
Labels: code quality, size/M

#6522 Fix incorrect beatmap set info equality check for local beatmapsets
  osu.Game.Tests/NonVisual/BeatmapSetInfoEqualityTest.cs
  osu.Game/Beatmaps/BeatmapSetInfo.cs
Labels: size/XS

#6534 Make BeginPlacement() set the hitobject start time
  osu.Game.Rulesets.Mania/Edit/Blueprints/ManiaPlacementBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/HitCircles/HitCirclePlacementBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderPlacementBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Spinners/SpinnerPlacementBlueprint.cs
  osu.Game/Rulesets/Edit/PlacementBlueprint.cs
Labels: code quality, editor, size/S

#6474 Implement osu!'s beat snapping grid
  osu.Game.Rulesets.Osu.Tests/TestSceneOsuDistanceSnapGrid.cs
  osu.Game.Rulesets.Osu/Edit/OsuDistanceSnapGrid.cs
  osu.Game.Rulesets.Osu/Objects/OsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Tests/Visual/Editor/TestSceneDistanceSnapGrid.cs
  osu.Game/Screens/Edit/Compose/Components/CircularDistanceSnapGrid.cs
  osu.Game/Screens/Edit/Compose/Components/DistanceSnapGrid.cs
Labels: editor, size/XL

#6528 Fix mania hitobject selections not moving correctly
  osu.Game.Rulesets.Mania/Edit/ManiaSelectionHandler.cs
Labels: editor, osu!mania, size/S

#6536 Remove a weird unicode charcter from file
  osu.Game/Overlays/AccountCreation/ScreenWarning.cs
Labels: code quality, size/XS

#6537 Fix hitobject combo colour potentially not getting adjusted
  osu.Game.Tests/Gameplay/TestSceneHitObjectAccentColour.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: bug, gameplay, size/L

#6538 Fix editor's clock not being processed unless composer is loaded
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Screens/Edit/Editor.cs
Labels: editor, size/XS

#6510 Fix incorrect current directory on Android
  osu.Android/OsuGameActivity.cs
Labels: android, resolves issue, size/L

#6435 Fix cursor size trail scaling
  osu.Game.Rulesets.Osu/UI/Cursor/OsuCursor.cs
  osu.Game.Rulesets.Osu/UI/Cursor/OsuCursorContainer.cs
  osu.Game.Rulesets.Osu/UI/OsuResumeOverlay.cs
Labels: gameplay, resolves issue, size/M, user interface

#6554 Fix selection blueprints not respecting stacking
  osu.Game.Rulesets.Osu.Tests/TestSceneHitCircleSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/BlueprintPiece.cs
Labels: editor, resolves issue, size/XS

#6527 Implement nested drawable hitobject reconstruction
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableBananaShower.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableJuiceStream.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/HoldNoteSelectionBlueprint.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNote.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableDrumRoll.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableSwell.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableTaikoHitObject.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: editor, gameplay, size/XL

#6560 Ensure DrawableHitObject's HitObject is not null
  osu.Game.Rulesets.Taiko.Tests/TestSceneTaikoPlayfield.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: size/XS

#6557 Fix hitcircle selection area being too large
  osu.Game.Rulesets.Mania/Edit/Blueprints/HoldNoteSelectionBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/ManiaSelectionBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/NoteSelectionBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/ManiaSelectionHandler.cs
  osu.Game.Rulesets.Mania/Edit/Masks/ManiaSelectionBlueprint.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneHitCircleSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/HitCircles/HitCircleSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/OsuSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game/Rulesets/Edit/SelectionBlueprint.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
  osu.Game/Screens/Edit/Compose/Components/MoveSelectionEvent.cs
  osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs
Labels: editor, osu!, regression, size/L

#6539 Integrate osu! distance snapping grid
  osu.Game.Rulesets.Osu/Edit/OsuDistanceSnapGrid.cs
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Rulesets/Objects/HitObject.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
  osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs
Labels: editor, osu!, size/XL

#6523 Make most textbox carets movable
  osu.Game/Graphics/UserInterface/SearchTextBox.cs
  osu.Game/Graphics/UserInterface/SeekLimitedSearchTextBox.cs
  osu.Game/Overlays/SettingsPanel.cs
  osu.Game/Screens/Select/FilterControl.cs
Labels: resolves issue, size/S, ux

#6569 Implement day divider for chat
  osu.Game.Tests/Visual/Online/TestSceneStandAloneChatDisplay.cs
  osu.Game/Online/Chat/StandAloneChatDisplay.cs
  osu.Game/Overlays/Chat/DrawableChannel.cs
Labels: chat, resolves issue, size/L, user interface

#6574 Fix registration textboxes always focusing after pressing escape
  osu.Game/Overlays/AccountCreation/ScreenEntry.cs
Labels: resolves issue, size/S, ux

#6575 Apply adjustments for framework changes
  osu.Android.props
  osu.Game/Graphics/Containers/WaveContainer.cs
  osu.Game/Graphics/UserInterface/OsuSliderBar.cs
  osu.Game/Overlays/Settings/SettingsSlider.cs
  osu.Game/Screens/Edit/BindableBeatDivisor.cs
  osu.Game/Screens/Play/PlayerSettings/PlayerSliderBar.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/S

#6535 Update WaveContainer to support framework changes
  osu.Game/Graphics/Containers/WaveContainer.cs
Labels: size/S

#6556 Fix sliders not moving with stacking changes
  osu.Game.Rulesets.Osu.Tests/TestSceneSlider.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneSliderSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/OsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Rulesets.Osu/Resources/Testing/Beatmaps/old-stacking-expected-conversion.json
Labels: editor, osu!, size/M

#6581 Fix distance snapping grid not updating on scroll
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
Labels: editor, size/XS

#6582 Show centre point of distance snap grid
  osu.Game.Rulesets.Osu.Tests/TestSceneOsuDistanceSnapGrid.cs
  osu.Game/Screens/Edit/Compose/Components/CircularDistanceSnapGrid.cs
  osu.Game/Screens/Edit/Compose/Components/DistanceSnapGrid.cs
Labels: editor, size/M

#6580 Don't snap slider control point placement
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderPlacementBlueprint.cs
Labels: editor, osu!, size/S

#6588 Refactor blueprint movement and selection events
  osu.Game/Rulesets/Edit/SelectionBlueprint.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
  osu.Game/Screens/Edit/Compose/Components/DragBox.cs
Labels: editor, size/L

#6589 Fix drag box being incorrectly positioned for 1 frame
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
  osu.Game/Screens/Edit/Compose/Components/DragBox.cs
Labels: bug, editor, size/L

#6598 Fix DateTime display sizing on results screen
  osu.Game/Screens/Ranking/Pages/ScoreResultsPage.cs
Labels: resolves issue, size/M, user interface

#6591 Add support for Markdown inline links
  osu.Game.Tests/Chat/MessageFormatterTests.cs
  osu.Game/Online/Chat/MessageFormatter.cs
Labels: size/M, user interface

#6529 Implement working VotePill for CommentsContainer
  osu.Game.Tests/Visual/Online/TestSceneCommentsContainer.cs
  osu.Game/Graphics/UserInterface/LoadingButton.cs
  osu.Game/Graphics/UserInterface/ShowMoreButton.cs
  osu.Game/Online/API/Requests/CommentVoteRequest.cs
  osu.Game/Online/API/Requests/Responses/Comment.cs
  osu.Game/Online/API/Requests/Responses/CommentBundle.cs
  osu.Game/Overlays/Comments/DrawableComment.cs
  osu.Game/Overlays/Comments/VotePill.cs
Labels: size/L, user interface

#6600 Fix not being able to drag non-snaked sliders
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderSelectionBlueprint.cs
Labels: bug, editor, osu!, size/XS

#6599 Refactor distance snapping to be handled by HitObjectComposer
  osu.Game.Rulesets.Osu.Tests/TestSceneOsuDistanceSnapGrid.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointPiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointVisualiser.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderPlacementBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/OsuDistanceSnapGrid.cs
  osu.Game.Tests/Editor/TestSceneHitObjectComposerDistanceSnapping.cs
  osu.Game.Tests/Visual/Editor/TestSceneDistanceSnapGrid.cs
  osu.Game.Tests/Visual/Editor/TestSceneHitObjectComposer.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Edit/IDistanceSnapProvider.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
  osu.Game/Screens/Edit/Compose/Components/CircularDistanceSnapGrid.cs
  osu.Game/Screens/Edit/Compose/Components/DistanceSnapGrid.cs
Labels: editor, size/XL

#6614 Add temporary mobile report moratorium issue template
  .github/ISSUE_TEMPLATE/mobile-issues.md
Labels: size/XS

#6601 Replace local Equatable implementations with abstract EquivalentTo
  osu.Game/Beatmaps/ControlPoints/ControlPoint.cs
  osu.Game/Beatmaps/ControlPoints/DifficultyControlPoint.cs
  osu.Game/Beatmaps/ControlPoints/EffectControlPoint.cs
  osu.Game/Beatmaps/ControlPoints/SampleControlPoint.cs
  osu.Game/Beatmaps/ControlPoints/TimingControlPoint.cs
  osu.Game/Beatmaps/Formats/LegacyDecoder.cs
Labels: code quality, size/M

#6633 Remove unused logger provider class
  osu.Game/Database/OsuDbContext.cs
Labels: size/S

#6630 Fix beatmap carousel sorting instability
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs
  osu.Game/Screens/Select/Carousel/CarouselGroup.cs
Labels: resolves issue, size/M, song select

#6644 Fix game-wide performance drop when triangles intro is used
  osu.Game/Screens/Menu/IntroSequence.cs
Labels: performance, size/XS

#6637 Expose Current bindable in LabelledComponents
  osu.Game.Tests/Visual/UserInterface/TestSceneLabelledDrawable.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneLabelledTextBox.cs
  osu.Game.Tournament/Screens/SetupScreen.cs
  osu.Game/Graphics/UserInterfaceV2/LabelledComponent.cs
  osu.Game/Graphics/UserInterfaceV2/LabelledDrawable.cs
  osu.Game/Graphics/UserInterfaceV2/LabelledSwitchButton.cs
  osu.Game/Graphics/UserInterfaceV2/LabelledTextBox.cs
Labels: user interface

#6639 Fix download tracking components getting stuck on import failures
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Database/DownloadableArchiveModelManager.cs
Labels: import, size/S

#6641 Fix PlayerSettingsOverlay being shown by default
  osu.Game.Tests/Visual/Gameplay/TestSceneReplaySettingsOverlay.cs
  osu.Game/Screens/Play/HUD/PlayerSettingsOverlay.cs
Labels: bug, user interface

#6640 Fix song progress not displaying correctly
  osu.Game/Screens/Play/SongProgress.cs
Labels: bug, size/XS, user interface

#6655 Fix loader animation tests failing occasionally
  osu.Game.Tests/Visual/Menus/TestSceneLoaderAnimation.cs
Labels: size/S, testing

#6649 Fix chat not always scrolling to the bottom
  osu.Android.props
  osu.Game.Tests/Visual/Online/TestSceneStandAloneChatDisplay.cs
  osu.Game/Online/Chat/Channel.cs
  osu.Game/Overlays/Chat/DrawableChannel.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: chat, size/M, testing

#6656 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#6653 Fix day separators never being removed from chat history
  osu.Game.Tests/Visual/Online/TestSceneStandAloneChatDisplay.cs
  osu.Game/Overlays/Chat/DrawableChannel.cs
Labels: chat, size/L

#6662 Add feedback to user when sign in form isn't filled
  osu.Game/Overlays/Settings/Sections/General/LoginSettings.cs
Labels: size/S, user interface, ux

#6636 Make OsuButton correctly block hover events
  osu.Game/Graphics/UserInterface/OsuButton.cs
Labels: size/XS, user interface

#6658 Fix 1x1 white pixel appearing in the centre of hitcircles on default skin
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/NumberPiece.cs
Labels: gameplay, osu!, size/XS

#6635 Bindable control point properties
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Resources/controlpoint-difficulty-multiplier.osu
  osu.Game/Beatmaps/ControlPoints/DifficultyControlPoint.cs
  osu.Game/Beatmaps/ControlPoints/EffectControlPoint.cs
  osu.Game/Beatmaps/ControlPoints/SampleControlPoint.cs
  osu.Game/Beatmaps/ControlPoints/TimingControlPoint.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyDifficultyCalculatorBeatmapDecoder.cs
Labels: size/L

#6632 Bindable control points
  osu.Game.Rulesets.Catch.Tests/TestSceneDrawableHitObjects.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneOsuDistanceSnapGrid.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneSlider.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneSliderInput.cs
  osu.Game.Rulesets.Taiko.Tests/TestSceneTaikoPlayfield.cs
  osu.Game.Rulesets.Taiko/Audio/DrumSampleMapping.cs
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Editor/TestSceneHitObjectComposerDistanceSnapping.cs
  osu.Game.Tests/NonVisual/ControlPointInfoTest.cs
  osu.Game.Tests/Resources/timingpoint-speedmultiplier-reset.osu
  osu.Game.Tests/Visual/Editor/TestSceneDistanceSnapGrid.cs
  osu.Game.Tests/Visual/Editor/TestSceneEditorSeekSnapping.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneDrawableScrollingRuleset.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneBeatSyncedContainer.cs
  osu.Game/Beatmaps/ControlPoints/ControlPoint.cs
  osu.Game/Beatmaps/ControlPoints/ControlPointGroup.cs
  osu.Game/Beatmaps/ControlPoints/ControlPointInfo.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Graphics/Containers/BeatSyncedContainer.cs
  osu.Game/Screens/Edit/EditorClock.cs
Labels: size/XL

#6667 Simplify EditorClock.Seek method
  osu.Game/Screens/Edit/EditorClock.cs
Labels: size/S

#6666 Fix crash when quickly exiting multiplayer after joining a room
  osu.Game/Screens/Multi/Multiplayer.cs
  osu.Game/Screens/Multi/RoomManager.cs
Labels: multiplayer, resolves issue, size/S

#6393 Implement beatmap ruleset selector component
  osu.Game.Tests/Visual/Online/TestSceneBeatmapRulesetSelector.cs
  osu.Game/Overlays/BeatmapSet/BeatmapRulesetSelector.cs
  osu.Game/Overlays/BeatmapSet/BeatmapRulesetTabItem.cs
Labels: size/L, user interface
