Repository ppy/osu, pull requests merged in 2019-07, with the labels that each got.

#5185 Fix Relax mod not working with osu! ruleset
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
Labels: resolves issue

#5201 Disable Hidden mod for osu!taiko (until it is implemented)
  osu.Game.Rulesets.Taiko/Mods/TaikoModHidden.cs
Labels: mods

#5156 Fix screen dimming permanently when chat opened with no channel joined
  osu.Game.Tests/Visual/Online/TestSceneChatOverlay.cs
  osu.Game/Overlays/Chat/Selection/ChannelSelectionOverlay.cs
  osu.Game/Overlays/Chat/Tabs/ChannelTabControl.cs
  osu.Game/Overlays/ChatOverlay.cs
Labels: chat, resolves issue

#5196 Change song select initialisation to promote database context sharing
  osu.Game/Screens/Select/BeatmapCarousel.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: database, performance, songselect

#5202 Add support for legacy skins which use animation frames to hide elements
  osu.Game/Skinning/LegacySkin.cs
Labels: skinning

#5163 Add weak WorkingBeatmap cache
  osu.Game.Tests/WaveformTestBeatmap.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/OsuGame.cs
  osu.Game/Tests/Visual/OsuTestScene.cs
Labels: database, performance

#5212 Avoid using a BufferedContainer for backgrounds unless required
  osu.Game/Graphics/Backgrounds/Background.cs
Labels: menu, performance

#5211 Avoid Intro screen holding references to the intro beatmap
  osu.Game/Screens/Menu/Intro.cs
Labels: code quality

#5209 Centralise SocialOverlay's scheduling logic
  osu.Game/Overlays/SocialOverlay.cs
Labels: code quality, online / API

#5208 Add database statistics to GlobalStatistics
  osu.Game/Database/DatabaseContextFactory.cs
  osu.Game/Database/OsuDbContext.cs
Labels: database

#5200 Remove all non-transform LogoVisualisation per-frame allocations
  osu.Game/Screens/Menu/LogoVisualisation.cs
Labels: performance

#5133 Load beatmap content asynchronously in the background
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/OsuGame.cs
Labels: regression

#5189 Add ability to download and watch replays
  osu.Game.Tests/Visual/Gameplay/TestSceneReplayDownloadButton.cs
  osu.Game.Tests/Visual/Online/TestSceneBeatmapSetOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneDirectDownloadButton.cs
  osu.Game/Graphics/UserInterface/DownloadButton.cs
  osu.Game/Online/API/Requests/DownloadReplayRequest.cs
  osu.Game/Online/API/Requests/Responses/APILegacyScoreInfo.cs
  osu.Game/Online/DownloadTrackingComposite.cs
  osu.Game/OsuGame.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/BeatmapSet/Buttons/HeaderDownloadButton.cs
  osu.Game/Overlays/BeatmapSet/Header.cs
  osu.Game/Overlays/Direct/DirectGridPanel.cs
  osu.Game/Overlays/Direct/DirectListPanel.cs
  osu.Game/Overlays/Direct/DownloadButton.cs
  osu.Game/Overlays/Direct/PanelDownloadButton.cs
  osu.Game/Scoring/ScoreInfo.cs
  osu.Game/Scoring/ScoreManager.cs
  osu.Game/Screens/Play/ReplayDownloadButton.cs
  osu.Game/Screens/Ranking/Pages/ScoreResultsPage.cs
Labels: online / API, replay

#5192 Use actual drawables instead of texture in DrawableRank
  osu.Game/Online/Leaderboards/DrawableRank.cs
  osu.Game/Online/Leaderboards/UpdateableRank.cs
Labels: user interface

#5176 Implement Hidden mod for osu!catch
  osu.Game.Rulesets.Catch.Tests/TestSceneDrawableHitObjects.cs
  osu.Game.Rulesets.Catch.Tests/TestSceneDrawableHitObjectsHidden.cs
  osu.Game.Rulesets.Catch/Mods/CatchModHidden.cs
  osu.Game.Rulesets.Catch/Objects/CatchHitObject.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableCatchHitObject.cs
Labels: resolves issue

#5218 Fix layout of profile top header to match web
  osu.Game/Overlays/Profile/Header/TopHeaderContainer.cs
Labels: overlays

#4021 Add android compatibility
  .gitignore
  osu.Android.props
  osu.Android.sln
  osu.Android.sln.DotSettings
  osu.Android/OsuGameActivity.cs
  osu.Android/OsuGameAndroid.cs
  osu.Android/Properties/AndroidManifest.xml
  osu.Android/Resources/drawable/lazer.png
  osu.Android/bass.dll
  osu.Android/lib/arm64-v8a/libbass.so
  osu.Android/lib/arm64-v8a/libbass_fx.so
  osu.Android/lib/armeabi-v7a/libbass.so
  osu.Android/lib/armeabi-v7a/libbass_fx.so
  osu.Android/lib/x86/libbass.so
  osu.Android/lib/x86/libbass_fx.so
  osu.Android/osu.Android.csproj
  osu.Game.Rulesets.Catch.Tests.Android/MainActivity.cs
  osu.Game.Rulesets.Catch.Tests.Android/Properties/AndroidManifest.xml
  osu.Game.Rulesets.Catch.Tests.Android/osu.Game.Rulesets.Catch.Tests.Android.csproj
  osu.Game.Rulesets.Catch/Properties/AssemblyInfo.cs
  osu.Game.Rulesets.Mania.Tests.Android/MainActivity.cs
  osu.Game.Rulesets.Mania.Tests.Android/Properties/AndroidManifest.xml
  osu.Game.Rulesets.Mania.Tests.Android/osu.Game.Rulesets.Mania.Tests.Android.csproj
  osu.Game.Rulesets.Mania/Properties/AssemblyInfo.cs
  osu.Game.Rulesets.Osu.Tests.Android/MainActivity.cs
  osu.Game.Rulesets.Osu.Tests.Android/Properties/AndroidManifest.xml
  osu.Game.Rulesets.Osu.Tests.Android/osu.Game.Rulesets.Osu.Tests.Android.csproj
  osu.Game.Rulesets.Osu/Properties/AssemblyInfo.cs
  osu.Game.Rulesets.Taiko.Tests.Android/MainActivity.cs
  osu.Game.Rulesets.Taiko.Tests.Android/Properties/AndroidManifest.xml
  osu.Game.Rulesets.Taiko.Tests.Android/osu.Game.Rulesets.Taiko.Tests.Android.csproj
  osu.Game.Rulesets.Taiko/Properties/AssemblyInfo.cs
  osu.Game.Tests.Android/MainActivity.cs
  osu.Game.Tests.Android/Properties/AndroidManifest.xml
  osu.Game.Tests.Android/osu.Game.Tests.Android.csproj
  osu.Game/Properties/AssemblyInfo.cs
Labels: compatibility

#3365 Add "Deflate" mod
  osu.Game.Rulesets.Osu/Mods/OsuModDeflate.cs
  osu.Game.Rulesets.Osu/Mods/OsuModGrow.cs
  osu.Game.Rulesets.Osu/Mods/OsuModeObjectScaleTween.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
Labels: mods, proposal

#5226 Fix local beatmap leaderboard displaying scores from all game modes
  osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboard.cs
Labels: database, songselect

#5210 Fix WaveOverlayContainer being always present
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
  osu.Game/Graphics/Containers/WaveContainer.cs
  osu.Game/Overlays/WaveOverlayContainer.cs
Labels: overlays, performance

#5229 Fix update notification not correctly restarting the game
  osu.Desktop/Updater/SquirrelUpdateManager.cs
Labels: resolves issue

#5222 Fix logo visualisation trying to catch up after being off-screen
  osu.Game/Screens/Menu/LogoVisualisation.cs
Labels: resolves issue

#5230 Remove unused bass.dll from android project
  osu.Android.props
  osu.Android/bass.dll
Labels: code quality

#5255 Fix beatmap leaderboards requiring supporter when signed out
  osu.Game/Online/Leaderboards/Leaderboard.cs
  osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboard.cs
Labels: online / API, songselect

#5256 Fix initial colour of leaderboard mod filter
  osu.Game/Graphics/UserInterface/OsuTabControlCheckbox.cs
Labels: songselect

#5251 Remove unused EditSongSelect file
  osu.Game/Screens/Select/EditSongSelect.cs
Labels: code quality

#5249 Bump android TargetFrameworkVersion
  osu.Android.props
Labels: android

#5242 Fade out volume on game exiting
  osu.Game/Screens/Menu/Intro.cs
Labels: resolves issue

#5243 Lock WorkingBeatmap cache to avoid threading issues
  osu.Game/Beatmaps/BeatmapManager.cs
Labels: resolves issue

#5260 Add a check if the locally available score has files
  osu.Game/Scoring/ScoreManager.cs
  osu.Game/Screens/Play/ReplayDownloadButton.cs
Labels: database, replay

#5072 Add local score import from stable
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/GeneralSettings.cs
  osu.Game/Scoring/ScoreManager.cs
  osu.Game/Screens/Select/ImportFromStablePopup.cs
  osu.Game/Screens/Select/SongSelect.cs
  osu.Game/Skinning/SkinManager.cs
Labels: database, resolves issue

#5244 Add messaging telling users how to leave changelog comments
  osu.Game.Tests/Visual/Online/TestSceneChangelogOverlay.cs
  osu.Game/Online/API/Requests/Responses/APIChangelogBuild.cs
  osu.Game/Overlays/Changelog/ChangelogSingleBuild.cs
  osu.Game/Overlays/Changelog/Comments.cs
Labels: changelog

#5253 Make mods filter on beatmap leaderboards functional
  osu.Game/Online/API/Requests/GetScoresRequest.cs
  osu.Game/Screens/Select/BeatmapDetailArea.cs
  osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboard.cs
Labels: online / API, songselect

#5270 Add missing wait step in TestScenePlayerLoader
  osu.Game.Tests/Visual/Gameplay/TestScenePlayerLoader.cs
Labels: testing

#5273 Remove unnecessary fading in UpdateableBeatmapBackgroundSprite
  osu.Game/Beatmaps/Drawables/UpdateableBeatmapBackgroundSprite.cs
Labels: code quality

#4813 Fix logo animation stuttering when entering mode from initial state
  osu.Game.Tests/Visual/UserInterface/TestSceneButtonSystem.cs
  osu.Game/Screens/Menu/ButtonSystem.cs
  osu.Game/Screens/Menu/MainMenu.cs
Labels: resolves issue

#5187 Add option to hide health bar when mod disallows failing
  osu.Game.Rulesets.Osu/Mods/OsuModRelax.cs
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Overlays/Settings/Sections/Gameplay/GeneralSettings.cs
  osu.Game/Rulesets/Mods/IApplicableToHUD.cs
  osu.Game/Rulesets/Mods/ModBlockFail.cs
  osu.Game/Rulesets/Mods/ModNoFail.cs
  osu.Game/Rulesets/Mods/ModRelax.cs
  osu.Game/Screens/Play/HUDOverlay.cs
  osu.Game/Screens/Play/Player.cs
Labels: resolves issue

#5259 Fix unranked beatmap leaderboards showing "no records" placeholder
  osu.Game.Tests/Visual/SongSelect/TestSceneLeaderboard.cs
  osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboard.cs
Labels: resolves issue

#5293 Fix mods not being reset when leaving a replay
  osu.Game/OsuGame.cs
  osu.Game/Screens/Play/ReplayPlayerLoader.cs
Labels: replay, resolves issue

#5306 Fix iOS visual tests not supporting raw keyboard handler
  osu.Game.Rulesets.Catch.Tests.iOS/Application.cs
  osu.Game.Rulesets.Mania.Tests.iOS/Application.cs
  osu.Game.Rulesets.Osu.Tests.iOS/Application.cs
  osu.Game.Rulesets.Taiko.Tests.iOS/Application.cs
  osu.Game.Tests.iOS/Application.cs
Labels: iOS, testing

#5289 Remember user's selected pause state when changing game screens
  osu.Game/Overlays/MusicController.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Menu/MainMenu.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: audio, resolves issue

#5295 Fix a few inspections from EAP r#
  osu.Game.Tests/Visual/Online/TestSceneChannelTabControl.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneBackButton.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneScreenBreadcrumbControl.cs
Labels: code quality

#5326 Use the correct property to retrieve the milliseconds for online length
  osu.Game/Online/API/Requests/Responses/APIBeatmap.cs
Labels: regression

#5297 Add ablity to see user's top score in beatmap overlay
  osu.Game.Tests/Visual/Online/TestSceneScoresContainer.cs
  osu.Game/Online/API/Requests/GetScoresRequest.cs
  osu.Game/Online/API/Requests/Responses/APILegacyScores.cs
  osu.Game/Overlays/BeatmapSet/Scores/DrawableTopScore.cs
  osu.Game/Overlays/BeatmapSet/Scores/ScoreTable.cs
  osu.Game/Overlays/BeatmapSet/Scores/ScoresContainer.cs
  osu.Game/Overlays/BeatmapSet/Scores/TopScoreUserSection.cs
  osu.Game/Overlays/BeatmapSetOverlay.cs
Labels: overlays, scoring

#5296 Fix track transfer not running when beatmap is retrieved from cache
  osu.Game/Beatmaps/BeatmapManager.cs
Labels: resolves issue

#5269 Force SQLite to multithreading mode
  osu.Game/Database/OsuDbContext.cs
Labels: database

#5316 Disable frame accurate replay playback
  osu.Game.Tests/NonVisual/FramedReplayInputHandlerTest.cs
  osu.Game/Rulesets/Replays/FramedReplayInputHandler.cs
Labels: performance, replay

#5245 Fix skip button not being clickable after fade out
  osu.Game.Tests/Visual/Gameplay/TestSceneSkipOverlay.cs
  osu.Game/Screens/Play/SkipOverlay.cs
Labels: resolves issue

#5299 Fix toggling storyboard after first load not getting correct clock
  osu.Game.Tests/Visual/Background/TestSceneUserDimContainer.cs
  osu.Game/Graphics/Containers/UserDimContainer.cs
  osu.Game/Screens/Backgrounds/BackgroundScreenBeatmap.cs
  osu.Game/Screens/Play/DimmableStoryboard.cs
  osu.Game/Screens/Play/Player.cs
Labels: resolves issue, storyboard

#5349 Fix logo masking not being applied correctly for showcase/win screens
  osu.Game.Tournament/Screens/Showcase/ShowcaseScreen.cs
  osu.Game.Tournament/Screens/TeamWin/TeamWinScreen.cs
Labels: tournament

#5363 Fix rulesets not matching in dictionary lookups due to missing GetHashCode implementation
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Toolbar/ToolbarRulesetSelector.cs
  osu.Game/Rulesets/RulesetInfo.cs
  osu.Game/Rulesets/RulesetStore.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: bug, database

#5370 Improve performance when entering gameplay by delaying hitobject updates
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: gameplay, performance

#5371 Fix song select iterating over all beatmaps in database unnecessarily
  osu.Game/Screens/Select/SongSelect.cs
Labels: database, performance

#5374 Remove cursor trail draw-time allocations
  osu.Game.Rulesets.Osu/UI/Cursor/CursorTrail.cs
Labels: resolves issue

#5380 Fix crashes when presenting replays
  osu.Game/Screens/Select/FooterButtonMods.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: bug

#5033 Fix 0-length sliders not getting correct lengths
  osu.Game.Rulesets.Osu.Tests/OsuDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Osu/Resources/Testing/Beatmaps/zero-length-sliders.osu
  osu.Game/Rulesets/Objects/Legacy/Catch/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/Mania/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/Osu/ConvertHitObjectParser.cs
  osu.Game/Rulesets/Objects/Legacy/Taiko/ConvertHitObjectParser.cs
Labels: beatmap parsing, osu!, osu!catch, osu!mania, osu!taiko

#5381 Fix potential crash when displaying leaderbaords
  osu.Game/Online/Leaderboards/Leaderboard.cs
Labels: bug, songselect

#5362 Fix Background blur thread-safety
  osu.Game/Graphics/Backgrounds/Background.cs
  osu.Game/Screens/Backgrounds/BackgroundScreenBeatmap.cs
Labels: performance

#5385 Fix judgement disposals causing huge LOH pressure
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game/Skinning/LocalSkinOverrideContainer.cs
Labels: performance

#5383 Recycle slider paths when the parenting slider dies
  osu.Android.props
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBody.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Rulesets/UI/HitObjectContainer.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: performance

#5403 Reduce Triangle drawnode overhead by ~90%
  osu.Android.props
  osu.Game/Graphics/Backgrounds/Triangles.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: performance

#5401 Fix loading animation is no longer present for scores in BeatmapSetOverlay
  osu.Game/Overlays/BeatmapSet/Scores/ScoresContainer.cs
Labels: user interface

#5415 Check if the current leaderboard scope requires API
  osu.Game/Online/Leaderboards/Leaderboard.cs
  osu.Game/Screens/Multi/Match/Components/MatchLeaderboard.cs
  osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboard.cs
Labels: online / API

#5423 Fix WorkingBeatmap disposal potentially null-refing
  osu.Game/Beatmaps/WorkingBeatmap.cs
Labels: regression

#5422 Centralise osu! circle radius specification
  osu.Game.Rulesets.Osu/Edit/Blueprints/HitCircles/Components/HitCirclePiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/SliderBodyPiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/CirclePiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/ExplodePiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/FlashPiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/RingPiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBall.cs
  osu.Game.Rulesets.Osu/Objects/OsuHitObject.cs
Labels: code quality

#5396 Set "Title" as the default grouping/sorting modes in song select
  osu.Game/Screens/Select/FilterControl.cs
Labels: regression, songselect

#5412 Fix TriangleDrawNode crash when required triangles is zero
  osu.Game/Graphics/Backgrounds/Triangles.cs
Labels: regression

#5426 Retrieve the actual favourite value for beatmaps
  osu.Game/Beatmaps/BeatmapSetOnlineInfo.cs
  osu.Game/Online/API/Requests/Responses/APIBeatmapSet.cs
  osu.Game/Overlays/BeatmapSet/Buttons/FavouriteButton.cs
  osu.Game/Overlays/BeatmapSet/Header.cs
Labels: online / API

#4879 Update MostPlayedBeatmaps section in line with the web version
  osu.Game.Tests/Visual/Online/TestSceneHistoricalSection.cs
  osu.Game/Overlays/Profile/Sections/BeatmapMetadataContainer.cs
  osu.Game/Overlays/Profile/Sections/Historical/DrawableMostPlayedBeatmap.cs
  osu.Game/Overlays/Profile/Sections/Historical/DrawableMostPlayedRow.cs
  osu.Game/Overlays/Profile/Sections/Historical/PaginatedMostPlayedBeatmapContainer.cs
  osu.Game/Overlays/Profile/Sections/Ranks/DrawableProfileScore.cs
Labels: user profile

#5433 Simplify line move logic in ToolbarRulesetSelector
  osu.Game/Overlays/Toolbar/ToolbarRulesetSelector.cs
Labels: code quality

#5418 Separate GlowingSpriteText from LeaderboardScore into it's own class
  osu.Game/Graphics/Sprites/GlowingSpriteText.cs
  osu.Game/Online/Leaderboards/LeaderboardScore.cs
Labels: code quality

#5435 Move TouchDevice mod to "system" type
  osu.Game.Rulesets.Osu/Mods/OsuModTouchDevice.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game/Rulesets/Mods/ModType.cs
Labels: resolves issue

#5438 Fix toolbar ruleset selector potentially null-refing
  osu.Game/Overlays/Toolbar/ToolbarRulesetSelector.cs
Labels: regression

#5437 Fix flashlight potentially not correctly blocking vision
  osu.Game/Graphics/OpenGL/Vertices/PositionAndColourVertex.cs
  osu.Game/Rulesets/Mods/ModFlashlight.cs
Labels: resolves issue

#5372 Ignore shift-delete PlatformAction in SearchTextBox
  osu.Game/Graphics/UserInterface/SearchTextBox.cs
Labels: resolves issue

#5439 Remove text shadow in chat
  osu.Game/Overlays/Chat/ChatLine.cs
Labels: chat, performance

#5436 Allow multiple instances of osu! when running under debug
  osu.Desktop/Program.cs
  osu.Game/OsuGame.cs
Labels: testing

#5420 Make AccentColour a bindable
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableCatchHitObject.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableDroplet.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableFruit.cs
  osu.Game.Rulesets.Mania.Tests/TestSceneHoldNoteSelectionBlueprint.cs
  osu.Game.Rulesets.Mania.Tests/TestSceneNotes.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNote.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNoteTick.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableNote.cs
  osu.Game.Rulesets.Mania/UI/Column.cs
  osu.Game.Rulesets.Mania/UI/HitExplosion.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderTick.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: code quality, gameplay, skinning

#5424 Move DrawableHitObject automatic state logic to base class
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableCatchHitObject.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableManiaHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableRepeatPoint.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderTick.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableHit.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableTaikoHitObject.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: code quality

#5470 Use IReadOnlyList for break period list
  osu.Game/Screens/Play/BreakOverlay.cs
Labels: code quality

#5445 Add iOS file import support
  osu.iOS/AppDelegate.cs
  osu.iOS/Info.plist
Labels: iOS, import

#5472 Fix font weight of leaderboard mod filter when unchecked
  osu.Game/Graphics/UserInterface/OsuTabControlCheckbox.cs
Labels: user interface

#5469 Force snaking slider paths to retain a fixed size
  osu.Android.props
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBody.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SnakingSliderBody.cs
  osu.Game/Graphics/UserInterface/LineGraph.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: gameplay, osu!, performance

#5456 Fix beatmap present failing directly after an import
  osu.Game/Screens/Select/BeatmapCarousel.cs
Labels: resolves issue

#5471 Reduce notification span during beatmap imports
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/OsuGame.cs
Labels: import, resolves issue, ux

#5484 Fix transforming mods not working properly
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: mods, resolves issue

#5487 Adjust tournament map pool layout to allow for larger pools
  osu.Game.Tournament/Screens/MapPool/MapPoolScreen.cs
Labels: tournament

#5468 Resize BeatmapCarousel and confine its PositionalInput
  osu.Game/Screens/Select/BeatmapCarousel.cs
  osu.Game/Screens/Select/FilterControl.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue, songselect

#5440 Fix BackButton handling escape before all other elements
  osu.Game/OsuGame.cs
  osu.Game/Screens/Select/Footer.cs
Labels: resolves issue, user interface

#3464 Add "Spin In" Mod
  osu.Game.Rulesets.Osu/Mods/OsuModHidden.cs
  osu.Game.Rulesets.Osu/Mods/OsuModSpinIn.cs
  osu.Game.Rulesets.Osu/Mods/OsuModeObjectScaleTween.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
Labels: mods

#5488 Truncate long usernames in private chat tab
  osu.Game.Tests/Visual/Online/TestSceneChatOverlay.cs
  osu.Game/Overlays/Chat/Tabs/ChannelSelectorTabItem.cs
  osu.Game/Overlays/Chat/Tabs/ChannelTabItem.cs
  osu.Game/Overlays/Chat/Tabs/PrivateChannelTabItem.cs
Labels: chat, resolves issue

#5498 Fix Multiplayer crash if attempting to exit with no screens in inner screen stack
  osu.Game/Screens/Multi/Multiplayer.cs
Labels: multiplayer

#5503 Fix zero-length hash models incorrectly creating a unique hash
  osu.Game/Database/ArchiveModelManager.cs
Labels: database

#5421 Skin scaling modes
  osu.Game.Rulesets.Osu/Objects/Drawables/Connections/FollowPoint.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableRepeatPoint.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderTick.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/NumberPiece.cs
  osu.Game.Rulesets.Osu/UI/Cursor/OsuCursor.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSkinReloadable.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSkinnableDrawable.cs
  osu.Game/Rulesets/Judgements/DrawableJudgement.cs
  osu.Game/Skinning/SkinnableDrawable.cs
  osu.Game/Skinning/SkinnableSprite.cs
  osu.Game/Skinning/SkinnableSpriteText.cs
Labels: skinning

#5453 Start exploding animation earlier (don't wait for flash)
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
Labels: gameplay

#5454 Remove unnecessary type specification from SkinnableDrawable
  osu.Game/Skinning/SkinnableDrawable.cs
  osu.Game/Skinning/SkinnableSprite.cs
  osu.Game/Skinning/SkinnableSpriteText.cs
Labels: code quality

#5507 Don't report delta patch failures to sentry
  osu.Desktop/Updater/SquirrelUpdateManager.cs
Labels: installer / updater, resolves issue

#5461 Fix SkinChanged events triggering after disposal
  osu.Game/Skinning/SkinReloadableDrawable.cs
Labels: bug, skinning

#5463 Cache DrawableHitObject for skinnables to access
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: skinning

#5275 Improve testability of intro sequence
  osu.Desktop/OsuGameDesktop.cs
  osu.Game.Tests/Visual/Menus/IntroTestScene.cs
  osu.Game.Tests/Visual/Menus/TestSceneIntroCircles.cs
  osu.Game.Tests/Visual/Menus/TestSceneIntroSequence.cs
  osu.Game/OsuGame.cs
  osu.Game/Screens/Loader.cs
  osu.Game/Screens/Menu/Disclaimer.cs
  osu.Game/Screens/Menu/IntroCircles.cs
  osu.Game/Screens/Menu/IntroScreen.cs
  osu.Game/Screens/Menu/MainMenu.cs
Labels: testing

#5508 Fix legacy scores with no online ID being imported with a non-null ID
  osu.Game/Scoring/Legacy/LegacyScoreParser.cs
Labels: database

#5509 Recalculate path size when path radius changes
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBody.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SnakingSliderBody.cs
Labels: osu!, regression

#5519 Fix tournament tests not running
  osu.Game.Tournament.Tests/Components/TestSceneDrawableTournamentMatch.cs
  osu.Game.Tournament.Tests/LadderTestScene.cs
  osu.Game.Tournament.Tests/Screens/TestSceneGameplayScreen.cs
  osu.Game.Tournament.Tests/Screens/TestSceneScheduleScreen.cs
  osu.Game.Tournament.Tests/Screens/TestSceneShowcaseScreen.cs
  osu.Game.Tournament.Tests/TestSceneTournamentSceneManager.cs
  osu.Game.Tournament.Tests/TournamentTestScene.cs
  osu.Game.Tournament/TournamentGameBase.cs
Labels: resolves issue, testing

#5518 Fix right mouse drag at song select seeking incorrectly with many beatmaps loaded
  osu.Game/Graphics/Containers/OsuScrollContainer.cs
Labels: resolves issue, song select

#5517 Fix scores without an online ID not always presenting correctly
  osu.Game/OsuGame.cs
Labels: database, import, resolves issue, scoring

#5521 Don't report stable storage missing to sentry
  osu.Desktop/OsuGameDesktop.cs
  osu.Game/Utils/RavenLogger.cs
Labels: import

#5512 Fix version overlay displaying briefly before it should
  osu.Desktop/OsuGameDesktop.cs
Labels: user interface

#5502 Move database isolation logic to OsuTestScene for easier reuse
  osu.Game.Tests/Visual/Background/TestSceneUserDimContainer.cs
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
  osu.Game/Tests/Visual/OsuTestScene.cs
Labels: testing

#5528 Don't forward timeout exceptions to sentry
  osu.Game/Utils/RavenLogger.cs
Labels: resolves issue

#5531 Add maximum height to settings skin dropdown
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
Labels: settings

#5504 Add a basic skin line-up test scene
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/approachcircle@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hit300k@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hitcircle@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hitcircleoverlay@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/metrics-skin/hitcircle@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/metrics-skin/hitcircleoverlay@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/special-skin/approachcircle@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/special-skin/hitcircle@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/special-skin/hitcircleoverlay@2x.png
  osu.Game.Rulesets.Osu.Tests/SkinnableTestScene.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneHitCircle.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneShaking.cs
  osu.Game/Skinning/SkinManager.cs
  osu.Game/Tests/Visual/OsuGridTestScene.cs
Labels: skinning, testing

#5464 Add legacy skin hit animations
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/CirclePiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/DefaultCirclePiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/MainCirclePiece.cs
  osu.Game/Skinning/LegacySkin.cs
Labels: osu!, skinning

#5466 Fix slider ball sizing when legacy skin falls back to default
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBall.cs
  osu.Game/Skinning/LegacySkin.cs
Labels: osu!, skinning

#5397 Update follower count API source
  osu.Game/Overlays/Profile/Header/Components/AddFriendButton.cs
  osu.Game/Users/User.cs
Labels: blocked, online / API

#5465 Add support for legacy skin "cursormiddle" display
  osu.Game.Rulesets.Osu/UI/Cursor/OsuCursor.cs
  osu.Game/Skinning/LegacySkin.cs
Labels: osu!, skinning

#5546 Apply mod multipliers to the score
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
Labels: resolves issue, scoring
