Repository ppy/osu, pull requests merged in 2019-02, with the labels that each got.

#4193 Fix slider tail evaluation in osu difficulty calculator
  osu.Game.Rulesets.Osu/Difficulty/Preprocessing/OsuDifficultyHitObject.cs
Labels: difficulty, osu!

#3992 Fix imported replays having excess statistics
  osu.Game.Rulesets.Catch/Scoring/CatchScoreProcessor.cs
  osu.Game.Rulesets.Mania/Scoring/ManiaScoreProcessor.cs
  osu.Game.Rulesets.Osu/Scoring/OsuScoreProcessor.cs
  osu.Game.Rulesets.Taiko/Scoring/TaikoScoreProcessor.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Scoring/Legacy/LegacyScoreParser.cs
Labels: resolves issue

#4192 Add PlaylistItemHandle.HandlePositionalInput override
  osu.Game/Overlays/Music/PlaylistItem.cs
Labels: resolves issue

#4205 Fix background not being faded correctly
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#4203 Use sidebar in key bindings overlay
  osu.Game/Overlays/KeyBinding/GlobalKeyBindingsSection.cs
  osu.Game/Overlays/KeyBinding/RulesetBindingsSection.cs
  osu.Game/Overlays/KeyBindingOverlay.cs
  osu.Game/Overlays/MainSettings.cs
Labels: input, settings, user interface

#4209 Fix combo colour fallbacks when skin is not providing any
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableCatchHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Tests/Resources/skin-empty.ini
  osu.Game.Tests/Resources/skin.ini
  osu.Game.Tests/Skins/LegacySkinDecoderTest.cs
  osu.Game/Skinning/DefaultSkin.cs
  osu.Game/Skinning/LocalSkinOverrideContainer.cs
  osu.Game/Skinning/SkinConfiguration.cs
Labels: resolves issue

#4207 Fix background being cut off at the top of the screen
  osu.Game/Screens/BackgroundScreenStack.cs
Labels: resolves issue

#4227 Fix potential nullref when exiting multiplayer
  osu.Game/Screens/Multi/Multiplayer.cs
Labels: resolves issue

#4228 Fix nullref during room creation
  osu.Game/Screens/Multi/Match/Components/ReadyButton.cs
Labels: resolves issue

#4226 Use CachedModelDependencyContainer for multiplayer
  osu.Game.Tests/Visual/TestCaseLoungeRoomsContainer.cs
  osu.Game.Tests/Visual/TestCaseMatchHeader.cs
  osu.Game.Tests/Visual/TestCaseMatchInfo.cs
  osu.Game.Tests/Visual/TestCaseMatchLeaderboard.cs
  osu.Game.Tests/Visual/TestCaseMatchParticipants.cs
  osu.Game.Tests/Visual/TestCaseMatchResults.cs
  osu.Game.Tests/Visual/TestCaseMatchSettingsOverlay.cs
  osu.Game/Online/Multiplayer/Room.cs
  osu.Game/Screens/Multi/Components/BeatmapTitle.cs
  osu.Game/Screens/Multi/Components/BeatmapTypeInfo.cs
  osu.Game/Screens/Multi/Components/ModeTypeInfo.cs
  osu.Game/Screens/Multi/Components/MultiplayerBackgroundSprite.cs
  osu.Game/Screens/Multi/Components/ParticipantCount.cs
  osu.Game/Screens/Multi/Components/RoomStatusInfo.cs
  osu.Game/Screens/Multi/Components/StatusColouredContainer.cs
  osu.Game/Screens/Multi/IRoomManager.cs
  osu.Game/Screens/Multi/Lounge/Components/DrawableRoom.cs
  osu.Game/Screens/Multi/Lounge/Components/FilterControl.cs
  osu.Game/Screens/Multi/Lounge/Components/ParticipantInfo.cs
  osu.Game/Screens/Multi/Lounge/Components/RoomInspector.cs
  osu.Game/Screens/Multi/Lounge/Components/RoomsContainer.cs
  osu.Game/Screens/Multi/Lounge/LoungeSubScreen.cs
  osu.Game/Screens/Multi/Match/Components/Header.cs
  osu.Game/Screens/Multi/Match/Components/Info.cs
  osu.Game/Screens/Multi/Match/Components/MatchChatDisplay.cs
  osu.Game/Screens/Multi/Match/Components/MatchLeaderboard.cs
  osu.Game/Screens/Multi/Match/Components/MatchSettingsOverlay.cs
  osu.Game/Screens/Multi/Match/Components/MatchTabControl.cs
  osu.Game/Screens/Multi/Match/Components/Participants.cs
  osu.Game/Screens/Multi/Match/Components/ReadyButton.cs
  osu.Game/Screens/Multi/Match/MatchSubScreen.cs
  osu.Game/Screens/Multi/Multiplayer.cs
  osu.Game/Screens/Multi/MultiplayerComposite.cs
  osu.Game/Screens/Multi/Play/TimeshiftPlayer.cs
  osu.Game/Screens/Multi/Ranking/MatchResults.cs
  osu.Game/Screens/Multi/Ranking/Pages/RoomLeaderboardPage.cs
  osu.Game/Screens/Multi/Ranking/Types/RoomLeaderboardPageInfo.cs
  osu.Game/Screens/Multi/RoomBindings.cs
  osu.Game/Screens/Multi/RoomManager.cs
  osu.Game/Tests/Visual/MultiplayerTestCase.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: resolves issue

#4191 Add screen leased bindables via DependencyContainer
  osu.Game.Rulesets.Osu/UI/Cursor/GameplayCursor.cs
  osu.Game.Tests/Visual/TestCaseEditorComposeTimeline.cs
  osu.Game.Tests/Visual/TestCaseMatchResults.cs
  osu.Game.Tests/Visual/TestCasePlayerLoader.cs
  osu.Game/Beatmaps/BindableBeatmap.cs
  osu.Game/Beatmaps/Drawables/UpdateableBeatmapBackgroundSprite.cs
  osu.Game/Beatmaps/IBindableBeatmap.cs
  osu.Game/Graphics/Containers/BeatSyncedContainer.cs
  osu.Game/Online/Multiplayer/PlaylistItem.cs
  osu.Game/Online/Multiplayer/Room.cs
  osu.Game/OsuGame.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/Music/PlaylistList.cs
  osu.Game/Overlays/Music/PlaylistOverlay.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Edit/PlacementBlueprint.cs
  osu.Game/Rulesets/UI/Playfield.cs
  osu.Game/Screens/Edit/Components/BottomBarContainer.cs
  osu.Game/Screens/Edit/Components/Timelines/Summary/Parts/TimelinePart.cs
  osu.Game/Screens/Edit/Compose/Components/Timeline/Timeline.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/EditorScreen.cs
  osu.Game/Screens/IOsuScreen.cs
  osu.Game/Screens/Menu/Intro.cs
  osu.Game/Screens/Menu/LogoVisualisation.cs
  osu.Game/Screens/Menu/MenuSideFlashes.cs
  osu.Game/Screens/Multi/Components/BeatmapTitle.cs
  osu.Game/Screens/Multi/Components/BeatmapTypeInfo.cs
  osu.Game/Screens/Multi/Components/ModeTypeInfo.cs
  osu.Game/Screens/Multi/Components/MultiplayerBackgroundSprite.cs
  osu.Game/Screens/Multi/Lounge/LoungeSubScreen.cs
  osu.Game/Screens/Multi/Match/Components/Header.cs
  osu.Game/Screens/Multi/Match/Components/Info.cs
  osu.Game/Screens/Multi/Match/Components/ReadyButton.cs
  osu.Game/Screens/Multi/Match/Components/ViewBeatmapButton.cs
  osu.Game/Screens/Multi/Match/MatchSubScreen.cs
  osu.Game/Screens/Multi/Multiplayer.cs
  osu.Game/Screens/Multi/MultiplayerComposite.cs
  osu.Game/Screens/Multi/MultiplayerSubScreen.cs
  osu.Game/Screens/OsuScreen.cs
  osu.Game/Screens/OsuScreenDependencies.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/Screens/Play/ReplayPlayer.cs
  osu.Game/Screens/Play/ScreenWithBeatmapBackground.cs
  osu.Game/Screens/Play/SoloResults.cs
  osu.Game/Screens/Ranking/Results.cs
  osu.Game/Screens/Select/MatchSongSelect.cs
  osu.Game/Screens/Select/PlaySongSelect.cs
  osu.Game/Screens/Select/SongSelect.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardAnimation.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardSample.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardSprite.cs
  osu.Game/Tests/Visual/OsuTestCase.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
  osu.sln.DotSettings
Labels: resolves issue

#4246 Don't revert beatmap on exiting leased state
  osu.Game/Screens/OsuScreenDependencies.cs
Labels: resolves issue

#4255 Fix MultiplayerTestCase not being abstract
  osu.Game/Tests/Visual/MultiplayerTestCase.cs
Labels: testing

#4258 Fix account creation overlay not working
  osu.Game/Overlays/AccountCreationOverlay.cs
Labels: overlays, regression

#4259 Fix mouse cursor appearing prematurely during startup
  osu.Game/OsuGame.cs
  osu.Game/Screens/Loader.cs
Labels: user interface

#4264 Add support for the HitCircleOverlap property of legacy skins
  osu.Game.Rulesets.Osu.Tests/TestCaseHitCircleLongCombo.cs
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/Skinning/LegacySkinDecoder.cs
  osu.Game/Skinning/SkinConfiguration.cs
Labels: resolves issue

#4265 Fix screen tests
  osu.Game.Tests/Visual/TestCaseDisclaimer.cs
  osu.Game.Tests/Visual/TestCaseDrawings.cs
  osu.Game.Tests/Visual/TestCaseMatchResults.cs
  osu.Game.Tests/Visual/TestCaseMultiScreen.cs
  osu.Game.Tests/Visual/TestCaseOsuGame.cs
  osu.Game.Tests/Visual/TestCaseParallaxContainer.cs
  osu.Game.Tests/Visual/TestCasePlaySongSelect.cs
  osu.Game.Tests/Visual/TestCaseResults.cs
  osu.Game/Tests/OsuTestBrowser.cs
  osu.Game/Tests/Visual/MultiplayerTestCase.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: testing

#4268 Fix nullref when entering multiplayer
  osu.Game/Screens/Multi/Multiplayer.cs
Labels: multiplayer, regression

#4256 Add difficulty calculator tests
  osu.Game.Rulesets.Catch.Tests/CatchDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Catch/Resources/Testing/Beatmaps/diffcalc-test.osu
  osu.Game.Rulesets.Mania.Tests/ManiaDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Mania/Resources/Testing/Beatmaps/diffcalc-test.osu
  osu.Game.Rulesets.Osu.Tests/OsuDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Osu/Resources/Testing/Beatmaps/diffcalc-test.osu
  osu.Game.Rulesets.Taiko.Tests/TaikoDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Taiko/Resources/Testing/Beatmaps/diffcalc-test-strong.osu
  osu.Game.Rulesets.Taiko/Resources/Testing/Beatmaps/diffcalc-test.osu
  osu.Game/Tests/Beatmaps/DifficultyCalculatorTest.cs
Labels: difficulty, testing

#4266 Improve the build script (and move to a better location)
  .gitignore
  .vscode/launch.json
  build.ps1
  build.sh
  build/build.cake
  build/cakebuild.csproj
Labels: tooling

#4187 Add "Grow" mod
  osu.Game.Rulesets.Osu/Mods/OsuModGrow.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
Labels: mods, osu!

#4289 Fix test dlls being loaded as actual rulesets (and failing)
  osu.Game/Rulesets/RulesetStore.cs
Labels: testing

#4277 Implement new difficulty calculator structure
  osu.Game.Rulesets.Catch.Tests/CatchDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Catch/Difficulty/CatchLegacyDifficultyCalculator.cs
  osu.Game.Rulesets.Mania.Tests/ManiaDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Mania/Difficulty/ManiaLegacyDifficultyCalculator.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Osu.Tests/OsuDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuLegacyDifficultyCalculator.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Taiko.Tests/TaikoDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoLegacyDifficultyCalculator.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game.Tests/NonVisual/DifficultyAdjustmentModCombinationsTest.cs
  osu.Game.Tests/NonVisual/LimitedCapacityStackTest.cs
  osu.Game/Beatmaps/DummyWorkingBeatmap.cs
  osu.Game/Rulesets/Difficulty/DifficultyAttributes.cs
  osu.Game/Rulesets/Difficulty/DifficultyCalculator.cs
  osu.Game/Rulesets/Difficulty/LegacyDifficultyCalculator.cs
  osu.Game/Rulesets/Difficulty/Preprocessing/DifficultyHitObject.cs
  osu.Game/Rulesets/Difficulty/Skills/Skill.cs
  osu.Game/Rulesets/Difficulty/Utils/LimitedCapacityStack.cs
  osu.Game/Rulesets/Ruleset.cs
  osu.Game/Tests/Beatmaps/DifficultyCalculatorTest.cs
Labels: difficulty

#4281 Migrate osu to use the new difficulty calculator structure
  osu.Game.Rulesets.Osu.Tests/OsuDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyAttributes.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyCalculator.cs
  osu.Game.Rulesets.Osu/Difficulty/Preprocessing/OsuDifficultyBeatmap.cs
  osu.Game.Rulesets.Osu/Difficulty/Preprocessing/OsuDifficultyHitObject.cs
  osu.Game.Rulesets.Osu/Difficulty/Skills/Aim.cs
  osu.Game.Rulesets.Osu/Difficulty/Skills/Skill.cs
  osu.Game.Rulesets.Osu/Difficulty/Skills/Speed.cs
  osu.Game.Rulesets.Osu/Difficulty/Utils/History.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game/Rulesets/Difficulty/DifficultyCalculator.cs
Labels: difficulty, osu!

#4294 Remove PopulateAttributes() from DifficultyCalculator
  osu.Game/Rulesets/Difficulty/DifficultyCalculator.cs
Labels: code quality, difficulty

#4279 Migrate catch to use the new difficulty calculator structure
  osu.Game.Rulesets.Catch.Tests/CatchDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyAttributes.cs
  osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyCalculator.cs
  osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyHitObject.cs
  osu.Game.Rulesets.Catch/Difficulty/CatchLegacyDifficultyCalculator.cs
  osu.Game.Rulesets.Catch/Difficulty/Preprocessing/CatchDifficultyHitObject.cs
  osu.Game.Rulesets.Catch/Difficulty/Skills/Movement.cs
Labels: difficulty, osu!catch

#4278 Migrate mania to use the new difficulty calculator structure
  osu.Game.Rulesets.Mania.Tests/ManiaDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Mania/Difficulty/ManiaDifficultyAttributes.cs
  osu.Game.Rulesets.Mania/Difficulty/ManiaDifficultyCalculator.cs
  osu.Game.Rulesets.Mania/Difficulty/ManiaLegacyDifficultyCalculator.cs
  osu.Game.Rulesets.Mania/Difficulty/Preprocessing/ManiaDifficultyHitObject.cs
  osu.Game.Rulesets.Mania/Difficulty/Skills/Individual.cs
  osu.Game.Rulesets.Mania/Difficulty/Skills/Overall.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Mania/Objects/ManiaHitObjectDifficulty.cs
  osu.Game/Rulesets/Difficulty/Skills/Skill.cs
Labels: difficulty, osu!mania

#4280 Migrate taiko to use the new difficulty calculator structure
  osu.Game.Rulesets.Taiko.Tests/TaikoDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Taiko/Difficulty/Preprocessing/TaikoDifficultyHitObject.cs
  osu.Game.Rulesets.Taiko/Difficulty/Skills/Strain.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoDifficultyAttributes.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoDifficultyCalculator.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoLegacyDifficultyCalculator.cs
  osu.Game.Rulesets.Taiko/Objects/TaikoHitObjectDifficulty.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game.Rulesets.Taiko/osu.Game.Rulesets.Taiko.csproj
Labels: difficulty, osu!taiko

#4254 Add tooltip to key configuration button
  osu.Game/Graphics/UserInterface/TriangleButton.cs
  osu.Game/Overlays/Settings/Sections/Input/KeyboardSettings.cs
  osu.Game/Overlays/Settings/SettingsButton.cs
Labels: resolves issue

#4298 Fix position not being set for the first hitobject
  osu.Game.Rulesets.Catch.Tests/CatchDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Catch/Difficulty/Preprocessing/CatchDifficultyHitObject.cs
  osu.Game.Rulesets.Catch/Difficulty/Skills/Movement.cs
Labels: difficulty, osu!catch

#4190 Fix Catch DifficultyCalculator being off
  osu.Game.Rulesets.Catch.Tests/CatchDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyCalculator.cs
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
Labels: bug, difficulty, osu!catch

#4290 Give TestWorkingBeatmap a reference clock
  osu.Game.Rulesets.Taiko.Tests/TestCaseTaikoPlayfield.cs
  osu.Game.Tests/Visual/TestCaseEditorCompose.cs
  osu.Game.Tests/Visual/TestCaseEditorSeekSnapping.cs
  osu.Game.Tests/Visual/TestCaseEditorSummaryTimeline.cs
  osu.Game.Tests/Visual/TestCasePlaybackControl.cs
  osu.Game/Tests/Beatmaps/TestWorkingBeatmap.cs
  osu.Game/Tests/Visual/EditorTestCase.cs
  osu.Game/Tests/Visual/TestCasePlayer.cs
Labels: testing

#4301 Fix non-conforming filename
  osu.Game.Rulesets.Osu/Replays/OsuFramedReplayInputHandler.cs
  osu.Game.Rulesets.Osu/UI/OsuRulesetContainer.cs
Labels: code quality

#4302 Remove LegacyDifficultyCalculator
  osu.Game.Rulesets.Catch.Tests/CatchDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Mania.Tests/ManiaDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Osu.Tests/OsuDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Taiko.Tests/TaikoDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game.Tests/NonVisual/DifficultyAdjustmentModCombinationsTest.cs
  osu.Game/Beatmaps/DummyWorkingBeatmap.cs
  osu.Game/Rulesets/Difficulty/DifficultyCalculator.cs
  osu.Game/Rulesets/Difficulty/LegacyDifficultyCalculator.cs
  osu.Game/Rulesets/Ruleset.cs
  osu.Game/Tests/Beatmaps/DifficultyCalculatorTest.cs
Labels: resolves issue

#4299 Fix osu! logo traveling in a weird direction on entering gameplay
  osu.Game/Screens/Menu/Intro.cs
  osu.Game/Screens/OsuScreen.cs
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#4306 Add ToString for Judgements to ease debugging
  osu.Game/Rulesets/Judgements/Judgement.cs
  osu.Game/Rulesets/Judgements/JudgementResult.cs
Labels: code quality

#4308 Disable TestInstantPolling
  osu.Game.Tests/Visual/TestCasePollingComponent.cs
Labels: testing

#4314 Revert some more instances of 'e' variable names
  osu.Game.Rulesets.Mania/Objects/Drawables/Pieces/NotePiece.cs
  osu.Game.Rulesets.Mania/UI/Column.cs
  osu.Game.Rulesets.Mania/UI/Components/ColumnBackground.cs
  osu.Game.Rulesets.Mania/UI/Components/ColumnHitObjectArea.cs
  osu.Game.Rulesets.Mania/UI/Components/ColumnKeyArea.cs
  osu.Game.Rulesets.Mania/UI/ManiaRulesetContainer.cs
  osu.Game.Rulesets.Mania/UI/ManiaStage.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/HitCircles/Components/HitCirclePiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/SliderBodyPiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Spinners/Components/SpinnerPiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs
  osu.Game.Tests/Visual/TestCaseIdleTracker.cs
  osu.Game/Beatmaps/Drawables/UpdateableBeatmapBackgroundSprite.cs
  osu.Game/Graphics/UserInterface/OsuAnimatedButton.cs
  osu.Game/Graphics/UserInterface/OsuSliderBar.cs
  osu.Game/Online/Chat/ChannelManager.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/BeatmapSet/Buttons/DownloadButton.cs
  osu.Game/Overlays/BeatmapSet/Header.cs
  osu.Game/Overlays/Direct/DownloadButton.cs
  osu.Game/Overlays/Direct/DownloadProgressBar.cs
  osu.Game/Overlays/Direct/DownloadTrackingComposite.cs
  osu.Game/Overlays/Settings/Sections/Debug/GCSettings.cs
  osu.Game/Overlays/Settings/Sections/Graphics/LayoutSettings.cs
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
  osu.Game/Screens/Edit/Compose/Components/Timeline/Timeline.cs
  osu.Game/Screens/Multi/Components/BeatmapTitle.cs
  osu.Game/Screens/Multi/Components/BeatmapTypeInfo.cs
  osu.Game/Screens/Multi/Components/ModeTypeInfo.cs
  osu.Game/Screens/Multi/Components/MultiplayerBackgroundSprite.cs
  osu.Game/Screens/Multi/Components/ParticipantCount.cs
  osu.Game/Screens/Multi/Components/RoomStatusInfo.cs
  osu.Game/Screens/Multi/Components/StatusColouredContainer.cs
  osu.Game/Screens/Multi/Lounge/Components/ParticipantInfo.cs
  osu.Game/Screens/Multi/Lounge/Components/RoomInspector.cs
  osu.Game/Screens/Multi/Match/Components/Header.cs
  osu.Game/Screens/Multi/Match/Components/HostInfo.cs
  osu.Game/Screens/Multi/Match/Components/Info.cs
  osu.Game/Screens/Multi/Match/Components/MatchLeaderboard.cs
  osu.Game/Screens/Multi/Match/Components/MatchSettingsOverlay.cs
  osu.Game/Screens/Multi/Match/Components/MatchTabControl.cs
  osu.Game/Screens/Multi/Match/Components/Participants.cs
  osu.Game/Screens/Multi/Match/Components/ReadyButton.cs
  osu.Game/Screens/Multi/Match/Components/ViewBeatmapButton.cs
  osu.Game/Screens/Multi/Match/MatchSubScreen.cs
  osu.Game/Screens/Multi/Multiplayer.cs
  osu.Game/Screens/Ranking/Results.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
Labels: code quality

#4321 Fix regression causing playback rate to display incorrectly
  osu.Game/Screens/Play/PlayerSettings/PlaybackSettings.cs
Labels: resolves issue

#4318 Avoid fatal exceptions being thrown on download failure
  osu.Game/Beatmaps/BeatmapManager.cs
Labels: resolves issue

#4324 Remove limitation stopping search updates when no query present in direct
  osu.Game/Overlays/DirectOverlay.cs
Labels: resolves issue

#4102 Fix slider button tracks and general replay accuracy
  osu.Game.Rulesets.Osu.Tests/TestCaseSliderInput.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/CirclePiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBall.cs
  osu.Game/Rulesets/UI/RulesetInputManager.cs
  osu.Game/Tests/Visual/RateAdjustedBeatmapTestCase.cs
  osu.Game/Tests/Visual/TestCasePlayer.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: resolves issue

#4331 Fix song select background not being exited in time for main menu
  osu.Game/Screens/Menu/MainMenu.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#3732 Use `Track.Completed` event
  osu.Game/Audio/PreviewTrack.cs
  osu.Game/Overlays/MusicController.cs
Labels: audio

#4334 Fix scores being stored as ints
  osu.Game/Migrations/OsuDbContextModelSnapshot.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Scoring/ScoreInfo.cs
Labels: resolves issue

#4240 Improve layout of beatmap details pane when source is unknown
  osu.Game.Tests/Visual/TestCaseBeatmapDetails.cs
  osu.Game/Screens/Select/BeatmapDetails.cs
Labels: installation, resolves issue

#3851 Do less work for dead drawables in gameplay
  osu.Game.Rulesets.Osu/Objects/Drawables/Connections/ConnectionRenderer.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Connections/FollowPointRenderer.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/ApproachCircle.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Rulesets/UI/HitObjectContainer.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardLayer.cs
Labels: gameplay, osu!, pending review, performance

#4343 Fix crossthread access + music looping not working
  osu.Game/Audio/PreviewTrack.cs
  osu.Game/Overlays/MusicController.cs
Labels: resolves issue

#4346 Avoid redundant (synchronous) skin change
  osu.Game.Tests/Visual/TestCaseSkinReloadable.cs
  osu.Game/Skinning/LocalSkinOverrideContainer.cs
Labels: performance, skinning

#4348 Clear delegate list rather than relying on unbinds
  osu.Game/Skinning/LocalSkinOverrideContainer.cs
Labels: gameplay, performance

#4340 Fix home button being cancelled by mod select again
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue

#4347 Reduce square graph overhead
  osu.Game.Tests/Visual/TestCaseSongProgress.cs
  osu.Game/Screens/Play/SquareGraph.cs
Labels: gameplay, performance

#4335 Fix OsuGame test case not working
  osu.Game.Tests/Visual/TestCaseOsuGame.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Direct/DownloadTrackingComposite.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: testing

#4356 Use pattern matching wherever possible
  osu.Desktop/OsuGameDesktop.cs
  osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs
  osu.Game.Rulesets.Osu/Difficulty/Preprocessing/OsuDifficultyHitObject.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game/Graphics/UserInterface/OsuDropdown.cs
  osu.Game/Graphics/UserInterface/OsuTabControl.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/NotificationOverlay.cs
  osu.Game/Rulesets/Mods/ModDaycore.cs
  osu.Game/Rulesets/Mods/ModNightcore.cs
  osu.Game/Screens/Play/HUDOverlay.cs
  osu.Game/Storyboards/StoryboardSprite.cs
  osu.sln.DotSettings
Labels: code quality

#4341 Better beatmap deletion handling while in multiplayer song select
  osu.Game/Screens/Multi/Match/Components/ReadyButton.cs
  osu.Game/Screens/Multi/Match/MatchSubScreen.cs
  osu.Game/Screens/Multi/Play/TimeshiftPlayer.cs
  osu.Game/Screens/Select/MatchSongSelect.cs
Labels: resolves issue

#4353 Conditionally add some UI elements only on desktop
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Overlays/Settings/Sections/General/UpdateSettings.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/GeneralSettings.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: mobile, user interface

#4364 Fix race condition during game load + disposal
  osu.Game/OsuGame.cs
Labels: regression, testing

#4365 Refactor BeatmapSetOverlay to use chained bindables
  osu.Game/Overlays/BeatmapSet/Info.cs
  osu.Game/Overlays/BeatmapSetOverlay.cs
Labels: code quality

#4257 Move user dim logic into new UserDimContainer
  osu.Game.Tests/Visual/TestCaseBackgroundScreenBeatmap.cs
  osu.Game.Tests/Visual/TestCasePlayerLoader.cs
  osu.Game/Graphics/Containers/UserDimContainer.cs
  osu.Game/Screens/Backgrounds/BackgroundScreenBeatmap.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/Screens/Play/ScreenWithBeatmapBackground.cs
Labels: resolves issue, user interface
