Repository ppy/osu, pull requests merged in 2019-09, with the labels that each got.

#5936 Fix rank graph tooltip flying around
  osu.Game/Overlays/Profile/Header/Components/RankGraph.cs
Labels: size/XS

#5927 Fix some spelling mistakes on code comments
  osu.Game/Screens/Menu/IntroCircles.cs
  osu.Game/Screens/Menu/LogoVisualisation.cs
  osu.Game/Screens/Menu/OsuLogo.cs
Labels: code quality, size/XS

#5947 Fix resume overlay being drawn below cursor
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Screens/Play/Player.cs
Labels: gameplay, resolves issue, size/S

#5941 Allow searching channels by topics
  osu.Game/Overlays/Chat/Selection/ChannelListItem.cs
Labels: chat, resolves issue, size/XS

#5894 Move beat divisor colour retrieval to BindableBeatDivisor
  osu.Game/Screens/Edit/BindableBeatDivisor.cs
  osu.Game/Screens/Edit/Compose/Components/BeatDivisorControl.cs
Labels: code quality, editor, size/M

#5949 Fix taiko swell tick judgements having non-zero time offsets
  osu.Game.Rulesets.Taiko.Tests/TestSceneSwellJudgements.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableSwellTick.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Tests/Visual/PlayerTestScene.cs
Labels: resolves issue, size/M

#5950 Hide taiko swell ticks
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableSwellTick.cs
Labels: gameplay, osu!taiko, size/XS

#5334 Add genre and language sections to beatmapset overlay
  osu.Game.Tests/Visual/Online/TestSceneBeatmapSetOverlay.cs
  osu.Game/Beatmaps/BeatmapSetOnlineInfo.cs
  osu.Game/Online/API/Requests/Responses/APIBeatmapSet.cs
  osu.Game/Overlays/BeatmapSet/Info.cs
Labels: overlays, size/M

#5951 Delay initial hitobject state computation
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Rulesets/UI/Scrolling/ScrollingHitObjectContainer.cs
Labels: resolves issue, size/M

#5934 Ensure playing track of beatmap selected only if a track change occurred
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue, size/XS, song select

#5778 Add kudosu history to UserProfileOverlay
  osu.Game.Tests/Visual/Online/TestSceneKudosuHistory.cs
  osu.Game/Online/API/Requests/GetUserKudosuHistoryRequest.cs
  osu.Game/Online/API/Requests/Responses/APIKudosuHistory.cs
  osu.Game/Overlays/Profile/Sections/Kudosu/DrawableKudosuHistoryItem.cs
  osu.Game/Overlays/Profile/Sections/Kudosu/PaginatedKudosuHistoryContainer.cs
  osu.Game/Overlays/Profile/Sections/KudosuSection.cs
Labels: size/XL, user profile

#5948 Fix OsuLegacySkin fallback logic being incorrect
  osu.Game.Rulesets.Osu/Skinning/OsuLegacySkin.cs
Labels: resolves issue, skinning

#5728 Add other sample functions to SkinnableSound
  osu.Game/Skinning/SkinnableSound.cs
Labels: size/S

#5953 Fix potential null reference on DirectPanel unbind
  osu.Game/Overlays/Direct/DirectPanel.cs
Labels: size/XS

#5892 Introduce the concept of SkinComponents
  osu.Game.Rulesets.Catch.Tests/TestSceneCatcher.cs
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Catch/CatchSkinComponent.cs
  osu.Game.Rulesets.Catch/CatchSkinComponents.cs
  osu.Game.Rulesets.Catch/UI/CatcherSprite.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Mania/ManiaSkinComponent.cs
  osu.Game.Rulesets.Mania/ManiaSkinComponents.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneSkinFallbacks.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Connections/FollowPoint.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableRepeatPoint.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderTick.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/ApproachCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/ExplodePiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/FlashPiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/GlowPiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/NumberPiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/RingPiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBall.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Osu/OsuSkinComponent.cs
  osu.Game.Rulesets.Osu/OsuSkinComponents.cs
  osu.Game.Rulesets.Osu/Skinning/LegacyMainCirclePiece.cs
  osu.Game.Rulesets.Osu/Skinning/OsuLegacySkin.cs
  osu.Game.Rulesets.Osu/UI/Cursor/OsuCursor.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game.Rulesets.Taiko/TaikoSkinComponent.cs
  osu.Game.Rulesets.Taiko/TaikoSkinComponents.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSkinnableDrawable.cs
  osu.Game/Rulesets/Judgements/DrawableJudgement.cs
  osu.Game/Skinning/BeatmapSkinProvidingContainer.cs
  osu.Game/Skinning/DefaultSkin.cs
  osu.Game/Skinning/ISkin.cs
  osu.Game/Skinning/ISkinComponent.cs
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/Skinning/PlaySkinComponent.cs
  osu.Game/Skinning/Skin.cs
  osu.Game/Skinning/SkinManager.cs
  osu.Game/Skinning/SkinProvidingContainer.cs
  osu.Game/Skinning/SkinnableDrawable.cs
  osu.Game/Skinning/SkinnableSprite.cs
  osu.Game/Skinning/SkinnableSpriteText.cs
Labels: skinning

#5961 Add a 60bpm beat when no beatmap is playing
  osu.Game.Tests/Visual/UserInterface/TestSceneBeatSyncedContainer.cs
  osu.Game/Graphics/Containers/BeatSyncedContainer.cs
Labels: size/M

#5893 Rename "play" resources to "gameplay"
  osu.Android.props
  osu.Game.Rulesets.Catch.Tests/TestSceneCatcher.cs
  osu.Game.Rulesets.Catch/CatchSkinComponent.cs
  osu.Game.Rulesets.Mania/ManiaSkinComponent.cs
  osu.Game.Rulesets.Osu/Mods/OsuModBlinds.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/CirclePiece.cs
  osu.Game.Rulesets.Osu/OsuSkinComponent.cs
  osu.Game.Rulesets.Taiko/TaikoSkinComponent.cs
  osu.Game.Rulesets.Taiko/UI/InputDrum.cs
  osu.Game/Rulesets/Judgements/DrawableJudgement.cs
  osu.Game/Skinning/GameplaySkinComponent.cs
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: code quality, size/M, skinning

#5952 Don't display hit errors for non-timed hitobjects
  osu.Game.Rulesets.Mania/Difficulty/ManiaDifficultyCalculator.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNote.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableNote.cs
  osu.Game.Rulesets.Mania/Objects/HoldNote.cs
  osu.Game.Rulesets.Mania/Objects/HoldNoteTick.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneDrawableJudgement.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneShaking.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyCalculator.cs
  osu.Game.Rulesets.Osu/Judgements/OsuJudgementResult.cs
  osu.Game.Rulesets.Osu/Mods/OsuModRelax.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Rulesets.Osu/Objects/SliderTick.cs
  osu.Game.Rulesets.Osu/Objects/Spinner.cs
  osu.Game.Rulesets.Osu/Replays/OsuAutoGenerator.cs
  osu.Game.Rulesets.Osu/Scoring/OsuScoreProcessor.cs
  osu.Game.Rulesets.Taiko.Tests/TestSceneTaikoPlayfield.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoDifficultyCalculator.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableHit.cs
  osu.Game.Rulesets.Taiko/Objects/DrumRoll.cs
  osu.Game.Rulesets.Taiko/Objects/DrumRollTick.cs
  osu.Game.Rulesets.Taiko/Objects/StrongHitObject.cs
  osu.Game.Rulesets.Taiko/Objects/Swell.cs
  osu.Game.Rulesets.Taiko/Objects/SwellTick.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneBarHitErrorMeter.cs
  osu.Game/Rulesets/Judgements/JudgementResult.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Rulesets/Objects/HitObject.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Screens/Play/HUD/HitErrorDisplay.cs
  osu.Game/Screens/Play/HUDOverlay.cs
Labels: gameplay, size/M

#5956 Center icon and text using anchor and origin instead of margin
  osu.Game/Overlays/Chat/Selection/ChannelListItem.cs
  osu.Game/Overlays/Direct/DirectPanel.cs
  osu.Game/Overlays/Music/PlaylistItem.cs
Labels: size/S

#5963 Fix ring glow lookup being incorrect
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/GlowPiece.cs
Labels: regression, skinning

#5957 Add spacing to difficulty icons on direct panels
  osu.Game/Overlays/Direct/DirectGridPanel.cs
  osu.Game/Overlays/Direct/DirectListPanel.cs
  osu.Game/Overlays/Direct/DirectPanel.cs
Labels: size/XS, user interface

#5964 Fix catch catcher lookups
  osu.Android.props
  osu.Game.Rulesets.Catch/CatchSkinComponent.cs
  osu.Game.Rulesets.Catch/CatchSkinComponents.cs
  osu.Game.Rulesets.Catch/UI/CatcherSprite.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/ApproachCircle.cs
  osu.Game/Skinning/SkinnableSprite.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: regression, size/S, skinning

#5928 Fix inconsistent sound effects on mod buttons
  osu.Game/Graphics/UserInterface/HoverClickSounds.cs
  osu.Game/Overlays/Mods/ModButton.cs
Labels: size/M, user interface

#5875 Fix gameplay menu button initial hover animation
  osu.Game.Tests/Visual/Gameplay/TestSceneGameplayMenuOverlay.cs
  osu.Game/Screens/Play/GameplayMenuOverlay.cs
Labels: resolves issue, size/XS, user interface

#5983 HoverClickSounds should handle click event instead of MouseUp
  osu.Game/Graphics/UserInterface/HoverClickSounds.cs
Labels: regression, resolves issue, size/XS

#5973 Fix two more cases of judgements appearing on hit error display when they shouldn't
  osu.Game.Rulesets.Osu/Objects/RepeatPoint.cs
  osu.Game.Rulesets.Osu/Objects/SliderTailCircle.cs
Labels: gameplay, size/XS

#5979 Fix bracket and parenthesis handling in existing link formats
  osu.Game.Tests/Chat/MessageFormatterTests.cs
  osu.Game.Tests/Visual/Online/TestSceneChatLink.cs
  osu.Game/Online/Chat/MessageFormatter.cs
Labels: size/L

#5968 Add test for changing of a source
  osu.Game.Tests/Visual/Gameplay/TestSceneSkinnableDrawable.cs
Labels: size/M, skinning, testing

#5994 Fix databased config save performance
  osu.Game/Configuration/DatabasedConfigManager.cs
Labels: performance, resolves issue, settings, size/S

#5990 Fix unavailable rulesets crashing at song select
  osu.Game/Beatmaps/Drawables/DifficultyIcon.cs
  osu.Game/Rulesets/RulesetInfo.cs
Labels: size/S, song select

#5989 Fix tests crashing if a ruleset doesn't provide a NoFail mod
  osu.Game/Tests/Visual/PlayerTestScene.cs
Labels: size/XS, testing

#5988 Add automatic resource mapping for rulesets to their own dll
  osu.Game/Rulesets/Ruleset.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Skinning/SkinnableSound.cs
Labels: gameplay, size/M

#5972 Fix storyboard samples not stopping on exit
  osu.Game/Storyboards/Drawables/DrawableStoryboardSample.cs
Labels: resolves issue, size/XS, storyboard

#5550 Use DummyAPIAccess for non-online tests
  osu.Game.Tests/Visual/Menus/TestSceneDisclaimer.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMatchLeaderboard.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiScreen.cs
  osu.Game.Tests/Visual/Online/TestSceneAccountCreationOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneBeatmapSetOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneChangelogOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneDirectOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneHistoricalSection.cs
  osu.Game.Tests/Visual/Online/TestSceneSocialOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneUserProfileHeader.cs
  osu.Game.Tests/Visual/Online/TestSceneUserProfileOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneUserRanks.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneUpdateableBeatmapBackgroundSprite.cs
  osu.Game/Tests/Visual/OsuTestScene.cs
Labels: resolves issue, testing

#5987 Don't redraw certain buffered containers on scale change
  osu.Android.props
  osu.Game/Graphics/Backgrounds/Background.cs
  osu.Game/Graphics/Sprites/GlowingSpriteText.cs
  osu.Game/Overlays/NowPlayingOverlay.cs
  osu.Game/Screens/Play/SquareGraph.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmapSet.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: performance, size/S

#6002 Fix pause menu keyboard navigation being affected by initial cursor hover
  osu.Game.Tests/Visual/Gameplay/TestSceneGameplayMenuOverlay.cs
  osu.Game/Screens/Play/GameplayMenuOverlay.cs
Labels: gameplay, size/S, ux

#5969 Refactor skin configuration lookups to be more flexible
  osu.Game.Rulesets.Catch.Tests/TestSceneCatcher.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneSkinFallbacks.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBall.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Osu/Skinning/LegacySliderBall.cs
  osu.Game.Rulesets.Osu/Skinning/OsuLegacySkinTransformer.cs
  osu.Game.Rulesets.Osu/Skinning/OsuSkinColour.cs
  osu.Game.Rulesets.Osu/Skinning/OsuSkinConfiguration.cs
  osu.Game.Rulesets.Osu/UI/Cursor/OsuCursor.cs
  osu.Game.Tests/Resources/skin.ini
  osu.Game.Tests/Skins/LegacySkinDecoderTest.cs
  osu.Game.Tests/Skins/TestSceneSkinConfigurationLookup.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSkinnableDrawable.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Screens/Menu/LogoVisualisation.cs
  osu.Game/Screens/Menu/MenuSideFlashes.cs
  osu.Game/Skinning/DefaultLegacySkin.cs
  osu.Game/Skinning/DefaultSkin.cs
  osu.Game/Skinning/DefaultSkinConfiguration.cs
  osu.Game/Skinning/GameplaySkinComponent.cs
  osu.Game/Skinning/GlobalSkinColour.cs
  osu.Game/Skinning/GlobalSkinConfiguration.cs
  osu.Game/Skinning/ISkin.cs
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/Skinning/LegacySkinDecoder.cs
  osu.Game/Skinning/Skin.cs
  osu.Game/Skinning/SkinConfigManager.cs
  osu.Game/Skinning/SkinConfiguration.cs
  osu.Game/Skinning/SkinCustomColourLookup.cs
  osu.Game/Skinning/SkinManager.cs
  osu.Game/Skinning/SkinProvidingContainer.cs
  osu.Game/Skinning/SkinUtils.cs
Labels: size/L, skinning

#6010 Dispose config managers ahead of time to avoid database errors
  osu.Game/OsuGameBase.cs
  osu.Game/Rulesets/RulesetConfigCache.cs
Labels: database, resolves issue, size/XS

#6008 Add back missing sample fallback to default skin
  osu.Game/Rulesets/UI/DrawableRuleset.cs
Labels: size/M

#6009 Fix fallback to default combo colours not working
  osu.Game/Skinning/DefaultSkin.cs
Labels: size/S

#5986 Remove judgementOccurred from DrawableHitObject
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: gameplay, resolves issue, size/S

#5958 Use float types for cursor sizes
  osu.Game.Rulesets.Osu/UI/Cursor/OsuCursor.cs
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Graphics/Cursor/MenuCursor.cs
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
Labels: code quality, size/S

#5960 Use float types for chat overlay height
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Overlays/ChatOverlay.cs
Labels: code quality, size/S

#5637 Disallow adding to score after the player has failed
  osu.Game.Rulesets.Osu/Scoring/OsuScoreProcessor.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneFailJudgement.cs
  osu.Game/Rulesets/Judgements/JudgementResult.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
Labels: gameplay

#6022 Fix dragging from inside to outside an overlay incorrectly hiding
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
Labels: resolves issue, user interface

#6020 Allow global actions to propagate through pause screen
  osu.Game/Screens/Play/GameplayMenuOverlay.cs
Labels: gameplay, size/S, user interface

#6033 Add android configuration defaults to props
  osu.Android.props
Labels: android, size/XS

#6031 Fix results screen pushed at the beginning of a gameplay
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
Labels: gameplay, size/XS

#6044 Make SkinnabbleTestScene use the stored classic skin
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/approachcircle@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/cursor@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/cursormiddle@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hit0@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hit100@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hit100k@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hit300@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hit300g@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hit300k@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hit50@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hitcircle@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hitcircleoverlay@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb-nd@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb-spec@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb0@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb1@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb2@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb3@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb4@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb5@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb6@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb7@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb8@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb9@2x.png
  osu.Game.Rulesets.Osu.Tests/SkinnableTestScene.cs
Labels: code quality, testing

#6045 Improve gameplay cursor test scene + refactor
  osu.Game.Rulesets.Osu.Tests/TestSceneGameplayCursor.cs
  osu.Game.Rulesets.Osu/UI/Cursor/CursorTrail.cs
Labels: code quality, size/L, testing

#6038 Open login overlay if user isn't signed in after intro sequence
  osu.Game/Screens/Menu/MainMenu.cs
Labels: size/S, user interface

#6053 Mark AutoGeneration tests as headless
  osu.Game.Rulesets.Mania.Tests/TestSceneAutoGeneration.cs
Labels: size/XS

#6023 Truncate long usernames in chat
  osu.Android.props
  osu.Game.Tests/Visual/Online/TestSceneChatLineTruncation.cs
  osu.Game/Overlays/Chat/ChatLine.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: chat, resolves issue, size/L, user interface

#6050 Use TestWorkingBeatmap in BeatmapDetailsArea tests
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapDetailArea.cs
Labels: size/M

#5999 Add "please select a beatmap!" leaderboard placeholder state
  osu.Game.Tests/Visual/SongSelect/TestSceneLeaderboard.cs
  osu.Game/Online/Leaderboards/Leaderboard.cs
  osu.Game/Online/Leaderboards/PlaceholderState.cs
  osu.Game/Screens/Select/BeatmapDetailArea.cs
  osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboard.cs
Labels: size/S

#6059 Fix hitcircle font prefix not being read for legacy skins
  osu.Game.Rulesets.Osu/Skinning/OsuLegacySkinTransformer.cs
  osu.Game.Rulesets.Osu/Skinning/OsuSkinConfiguration.cs
Labels: resolves issue, size/XS, skinning

#6055 Fix mania notes test scene not visually displaying
  osu.Game.Rulesets.Mania.Tests/TestSceneNotes.cs
Labels: size/S

#6054 Centralise and share bar line generation code between rulesets
  osu.Game.Rulesets.Mania.Tests/TestSceneStage.cs
  osu.Game.Rulesets.Mania/Objects/BarLine.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableBarLine.cs
  osu.Game.Rulesets.Mania/UI/DrawableManiaRuleset.cs
  osu.Game.Rulesets.Mania/UI/ManiaPlayfield.cs
  osu.Game.Rulesets.Mania/UI/ManiaStage.cs
  osu.Game.Rulesets.Taiko/Objects/BarLine.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableBarLine.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableBarLineMajor.cs
  osu.Game.Rulesets.Taiko/UI/DrawableTaikoRuleset.cs
  osu.Game/Rulesets/Objects/BarLine.cs
  osu.Game/Rulesets/Objects/BarLineGenerator.cs
Labels: code quality, gameplay, size/L

#6063 Fix osu! hitcircle font textures being incorrectly sized
  osu.Game.Rulesets.Osu/Skinning/OsuLegacySkinTransformer.cs
  osu.Game/Skinning/LegacySpriteText.cs
Labels: resolves issue, size/S, skinning

#6062 Adjust osu!mania scroll speed defaults to be more sane
  osu.Game.Rulesets.Mania/Configuration/ManiaRulesetConfigManager.cs
Labels: osu!mania, size/XS

#6046 Implement disjoint (old style) cursor trail
  osu.Game.Rulesets.Osu.Tests/TestSceneCursorTrail.cs
  osu.Game.Rulesets.Osu/OsuSkinComponents.cs
  osu.Game.Rulesets.Osu/Skinning/LegacyCursorTrail.cs
  osu.Game.Rulesets.Osu/Skinning/OsuLegacySkinTransformer.cs
  osu.Game.Rulesets.Osu/UI/Cursor/CursorTrail.cs
  osu.Game.Rulesets.Osu/UI/Cursor/OsuCursorContainer.cs
Labels: osu!, size/L, skinning

#6064 Fix follow points not displaying on some skins
  osu.Game.Rulesets.Osu/Skinning/OsuLegacySkinTransformer.cs
Labels: size/XS, skinning

#5475 Fix overlays not being blocked when disabled
  osu.Android.props
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: overlays, resolves issue, size/XS

#6068 Fix osu!mania minor barline alpha not being respected
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableBarLine.cs
Labels: osu!mania, size/XS

#6081 Implement RankingsRulesetSelector component for rankings overlay
  osu.Game.Tests/Visual/Online/TestSceneRankingsRulesetSelector.cs
  osu.Game/Graphics/UserInterface/PageTabControl.cs
  osu.Game/Overlays/Rankings/RankingsRulesetSelector.cs
Labels: size/L, user interface

#6067 Make osu!mania hit explosions more explodey
  osu.Game.Rulesets.Mania.Tests/TestSceneHitExplosion.cs
  osu.Game.Rulesets.Mania/UI/Column.cs
  osu.Game.Rulesets.Mania/UI/HitExplosion.cs
Labels: osu!mania, size/L

#6066 Change some osu!mania metrics for better playability
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableNote.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/Pieces/NotePiece.cs
  osu.Game.Rulesets.Mania/UI/Column.cs
  osu.Game.Rulesets.Mania/UI/Components/ColumnBackground.cs
  osu.Game.Rulesets.Mania/UI/Components/ColumnHitObjectArea.cs
Labels: osu!mania, size/M

#6078 Fix dialog overlay playing double samples on show/hide
  osu.Game.Tests/Visual/UserInterface/TestSceneDialogOverlay.cs
  osu.Game.Tests/Visual/UserInterface/TestScenePopupDialog.cs
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
  osu.Game/Overlays/Dialog/PopupDialog.cs
  osu.Game/Overlays/DialogOverlay.cs
Labels: size/M, user interface

#6093 Fix player not correctly restarting after an unpause
  osu.Game.Tests/Visual/Gameplay/TestScenePause.cs
  osu.Game/Screens/Play/Player.cs
Labels: gameplay, resolves issue, size/S

#6076 Implement HeaderTitle component for rankings overlay
  osu.Game.Tests/Visual/Online/TestSceneRankingsHeaderTitle.cs
  osu.Game/Overlays/Rankings/HeaderTitle.cs
Labels: size/L

#6082 Implement RankingsHeader component for rankings overlay
  osu.Game.Tests/Visual/Online/TestSceneRankingsHeader.cs
  osu.Game.Tests/Visual/Online/TestSceneRankingsScopeSelector.cs
  osu.Game/Graphics/UserInterface/GradientLineTabControl.cs
  osu.Game/Overlays/Rankings/HeaderTitle.cs
  osu.Game/Overlays/Rankings/RankingsHeader.cs
  osu.Game/Overlays/Rankings/Spotlight.cs
Labels: size/L, user interface

#6028 Reset DrawableHitObject lifetimes on state change
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableCatchHitObject.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableManiaHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableRepeatPoint.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderTick.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableDrumRoll.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableDrumRollTick.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableHit.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableSwell.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: gameplay, size/XS

#6086 Improve how osu!catch stores and replays key actions
  osu.Game.Rulesets.Catch/Replays/CatchAutoGenerator.cs
  osu.Game.Rulesets.Catch/Replays/CatchFramedReplayInputHandler.cs
  osu.Game.Rulesets.Catch/Replays/CatchReplayFrame.cs
  osu.Game.Rulesets.Mania/Replays/ManiaReplayFrame.cs
  osu.Game.Rulesets.Osu/Replays/OsuReplayFrame.cs
  osu.Game.Rulesets.Taiko/Replays/TaikoReplayFrame.cs
  osu.Game/Rulesets/Replays/Types/IConvertibleReplayFrame.cs
  osu.Game/Scoring/Legacy/LegacyScoreParser.cs
Labels: osu!catch, replay, size/L

#6095 Fix incorrect DI usage of IAPIProvider in many tests
  osu.Game.Tests/Visual/Menus/TestSceneDisclaimer.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMatchLeaderboard.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiScreen.cs
  osu.Game.Tests/Visual/Online/TestSceneAccountCreationOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneBeatmapSetOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneChangelogOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneDirectOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneHistoricalSection.cs
  osu.Game.Tests/Visual/Online/TestSceneSocialOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneUserProfileHeader.cs
  osu.Game.Tests/Visual/Online/TestSceneUserProfileOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneUserRanks.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneUpdateableBeatmapBackgroundSprite.cs
  osu.Game/Overlays/ChangelogOverlay.cs
  osu.Game/Tests/Visual/OsuTestScene.cs
Labels: size/M, testing

#6032 Fix osu!catch rewind handling
  osu.Game.Rulesets.Catch.Tests/TestSceneHyperDash.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableCatchHitObject.cs
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
Labels: gameplay, osu!catch, size/L

#6097 Change osu!catch key trigger to occur on frame before positional change
  osu.Game.Rulesets.Catch/Replays/CatchReplayFrame.cs
  osu.Game.Rulesets.Mania/Replays/ManiaReplayFrame.cs
  osu.Game.Rulesets.Osu/Replays/OsuReplayFrame.cs
  osu.Game.Rulesets.Taiko/Replays/TaikoReplayFrame.cs
  osu.Game/Rulesets/Replays/Types/IConvertibleReplayFrame.cs
  osu.Game/Scoring/Legacy/LegacyScoreParser.cs
Labels: osu!catch, replay, size/M

#6098 Recreate beatmap video on each consumption
  osu.Game/Beatmaps/WorkingBeatmap.cs
Labels: size/XS

#6106 Fix RankingsHeader dropdown can be clickable when not visible
  osu.Game/Overlays/Rankings/RankingsHeader.cs
Labels: size/XS

#6116 Fix DrawableFlag not showing fallback texture if no flag is available
  osu.Game.Tests/Visual/Online/TestSceneRankingsHeader.cs
  osu.Game/Users/Drawables/DrawableFlag.cs
Labels: size/XS, user interface

#6112 Wait for cursor hiding using ManualResetEventSlim
  osu.Game/Graphics/ScreenshotManager.cs
Labels: code quality, size/S

#6105 Fix aspect ratio of video not being enforced
  osu.Game/Screens/Play/DimmableVideo.cs
  osu.Game/Screens/Play/Player.cs
Labels: size/S, storyboard

#6127 Specify Rider analysis rules explicitly
  osu.Android.sln.DotSettings
  osu.iOS.sln.DotSettings
  osu.sln.DotSettings
Labels: code quality, size/M

#6128 Fix Perfect/SuddenDeath legacy mod conversion during score import
  osu.Game.Rulesets.Catch.Tests/CatchLegacyModConversionTest.cs
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Mania.Tests/ManiaLegacyModConversionTest.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Osu.Tests/OsuLegacyModConversionTest.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Taiko.Tests/TaikoLegacyModConversionTest.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game/Tests/Beatmaps/LegacyModConversionTest.cs
Labels: import, resolves issue, size/L

#6138 Debounce user-requested replay seeks
  osu.Game/Screens/Play/SongProgressBar.cs
Labels: performance, resolves issue, size/XS

#6137 Fix disclaimer potentially pushing a null screen
  osu.Game/Screens/Menu/Disclaimer.cs
Labels: size/XS, testing

#6142 Move menu cursor rotation to more appropriate settings section
  osu.Game/Overlays/Settings/Sections/Graphics/DetailSettings.cs
  osu.Game/Overlays/Settings/Sections/Graphics/UserInterfaceSettings.cs
  osu.Game/Overlays/Settings/Sections/GraphicsSection.cs
Labels: code quality, settings, size/S, ux

#6146 Fix HitCircleLongCombo test stacking off-screen
  osu.Game.Rulesets.Osu.Tests/TestSceneHitCircleLongCombo.cs
Labels: osu!, size/XS, testing

#6087 Key counter improvements
  osu.Game.Rulesets.Catch/Replays/CatchAutoGenerator.cs
  osu.Game.Rulesets.Mania.Tests/TestSceneAutoGeneration.cs
  osu.Game.Rulesets.Mania/Replays/ManiaAutoGenerator.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneAutoplay.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneGameplayRewinding.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneKeyCounter.cs
  osu.Game/Rulesets/UI/RulesetInputManager.cs
  osu.Game/Screens/Play/GameplayClock.cs
  osu.Game/Screens/Play/HUDOverlay.cs
  osu.Game/Screens/Play/KeyCounter.cs
  osu.Game/Screens/Play/KeyCounterAction.cs
  osu.Game/Screens/Play/KeyCounterDisplay.cs
  osu.Game/Screens/Play/KeyCounterKeyboard.cs
  osu.Game/Screens/Play/KeyCounterMouse.cs
  osu.Game/Tests/Visual/OsuTestScene.cs
Labels: gameplay, size/L, user interface

#6041 Remove unnecessary AndroidNativeLibrary specification
  osu.Android.props
Labels: android, size/XS

#6141 Randomise beatmap playback order on startup
  osu.Game/Overlays/Music/PlaylistList.cs
  osu.Game/Overlays/Music/PlaylistOverlay.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Overlays/NowPlayingOverlay.cs
Labels: audio, resolves issue, size/M

#6151 Always update drawable hitobject state on skin change
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: blocked, gameplay, size/S, skinning

#6165 Add back combo colours for osu!classic
  osu.Game/Skinning/DefaultLegacySkin.cs
Labels: size/XS, skinning

#6162 Disallow failing for replay players
  osu.Game.Tests/Visual/Gameplay/TestSceneFailJudgement.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneReplay.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/ReplayPlayer.cs
Labels: size/M

#3569 Traceable mod
  osu.Game.Rulesets.Osu/Mods/OsuModHidden.cs
  osu.Game.Rulesets.Osu/Mods/OsuModSpinIn.cs
  osu.Game.Rulesets.Osu/Mods/OsuModTraceable.cs
  osu.Game.Rulesets.Osu/Mods/OsuModeObjectScaleTween.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
Labels: mods, osu!, proposal, size/L

#6161 Add query-based filter modes to song select search field
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Screens/Select/Carousel/CarouselBeatmap.cs
  osu.Game/Screens/Select/FilterControl.cs
  osu.Game/Screens/Select/FilterCriteria.cs
Labels: resolves issue, size/L, song select

#6159 Add auto-restart functionality to sudden death and perfect mods
  osu.Game.Rulesets.Osu/Mods/OsuModAutopilot.cs
  osu.Game/Rulesets/Mods/IApplicableFailOverride.cs
  osu.Game/Rulesets/Mods/ModAutoplay.cs
  osu.Game/Rulesets/Mods/ModBlockFail.cs
  osu.Game/Rulesets/Mods/ModSuddenDeath.cs
  osu.Game/Screens/Play/Player.cs
Labels: mods, size/S

#6144 Add hit lighting
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuJudgement.cs
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Overlays/Settings/Sections/Graphics/DetailSettings.cs
  osu.Game/Rulesets/Judgements/DrawableJudgement.cs
Labels: gameplay, osu!, size/M

#6145 Fix judgement sizes not matching legacy skins
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game/Rulesets/Judgements/DrawableJudgement.cs
Labels: size/XS, skinning

#6170 Fix importing archives which are nested in a single folder within a zip
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Database/ArchiveModelManager.cs
Labels: import, size/M

#5355 Show personal best on song select
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapLeaderboard.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneUserTopScoreContainer.cs
  osu.Game/Online/Leaderboards/Leaderboard.cs
  osu.Game/Online/Leaderboards/LeaderboardScore.cs
  osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboard.cs
  osu.Game/Screens/Select/Leaderboards/UserTopScoreContainer.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: scoring, size/L, song select

#6166 Add setting to adjust hold-to-confirm activation time
  osu.Game.Tests/Visual/UserInterface/TestSceneHoldToConfirmOverlay.cs
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Graphics/Containers/HoldToConfirmContainer.cs
  osu.Game/Overlays/DialogOverlay.cs
  osu.Game/Overlays/HoldToConfirmOverlay.cs
  osu.Game/Overlays/Settings/Sections/Graphics/UserInterfaceSettings.cs
  osu.Game/Screens/Menu/ExitConfirmOverlay.cs
  osu.Game/Screens/Menu/MainMenu.cs
Labels: settings, size/M, ux

#6175 Always show exit confirmation when closing via alt-f4 or window control
  osu.Game/Screens/Menu/MainMenu.cs
Labels: size/S, ux

#6179 Reduce ambiguity of leaderboard mod filter button
  osu.Game/Screens/Select/BeatmapDetailAreaTabControl.cs
Labels: resolves issue, size/XS

#6185 Checksum before skip copy
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game/IO/FileStore.cs
Labels: import, resolves issue, size/M

#6191 Remove unused CORNER_RADIUS
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableNote.cs
Labels: size/XS

#6194 Fix typo in CreateResourceStore method name
  osu.Game/Rulesets/Ruleset.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
Labels: code quality, size/XS

#6196 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#6178 Fix escaped html strings not being unescaped in changelog entries.
  osu.Game.Tests/Visual/Online/TestSceneChangelogOverlay.cs
  osu.Game/Overlays/Changelog/ChangelogBuild.cs
Labels: size/XS

#6181 Implement skin slider ball tinting
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Skinning/OsuSkinConfiguration.cs
Labels: size/S, skinning

#6177 Add support for "additions" in changelog
  osu.Game/Online/API/Requests/Responses/APIChangelogEntry.cs
  osu.Game/Overlays/Changelog/ChangelogBuild.cs
Labels: changelog, size/S

#6190 Fix scores importing with deleted beatmap sets
  osu.Game.Tests/Scores/IO/ImportScoreTest.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Scoring/Legacy/DatabasedLegacyScoreParser.cs
Labels: database, resolves issue, size/M

#6192 Specify model name on initialize and fail import notification messages
  osu.Game/Database/ArchiveModelManager.cs
Labels: import, size/XS

#6187 Add a base class for all future labelled components
  osu.Game.Tests/Visual/UserInterface/TestSceneLabelledComponent.cs
  osu.Game/Screens/Edit/Setup/Components/LabelledComponents/LabelledComponent.cs
Labels: user interface

#6206 Song select filter improvements
  osu.Game.Tests/NonVisual/Filtering/FilterMatchingTest.cs
  osu.Game.Tests/NonVisual/Filtering/FilterQueryParserTest.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs
  osu.Game/Screens/Select/Carousel/CarouselBeatmap.cs
  osu.Game/Screens/Select/FilterControl.cs
  osu.Game/Screens/Select/FilterCriteria.cs
  osu.Game/Screens/Select/FilterQueryParser.cs
Labels: resolves issue, size/XL, song select

#6220 Fix incorrect icon margin in ChangelogOverlay
  osu.Game/Overlays/Changelog/ChangelogBuild.cs
Labels: size/S

#6210 Allow top-level menu key pressed to progress the osu! logo
  osu.Game/Screens/Menu/Button.cs
  osu.Game/Screens/Menu/ButtonSystem.cs
Labels: menu, resolves issue, size/S

#6211 Add an onboarding screen for tournament client
  osu.Game.Tournament.Tests/Screens/TestSceneSetupScreen.cs
  osu.Game.Tournament/IPC/FileBasedIPC.cs
  osu.Game.Tournament/Screens/SetupScreen.cs
  osu.Game.Tournament/TournamentSceneManager.cs
  osu.Game/Overlays/Settings/Sections/General/LoginSettings.cs
Labels: size/L, tournament, ux

#6237 Make LabelledComponent generic
  osu.Game.Tests/Visual/UserInterface/TestSceneLabelledComponent.cs
  osu.Game.Tournament/Screens/SetupScreen.cs
  osu.Game/Screens/Edit/Setup/Components/LabelledComponents/LabelledComponent.cs
Labels: code quality, size/S

#6234 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#6188 Make LabelledTextBox use the new LabelledComponent class
  osu.Game.Tests/Visual/UserInterface/TestSceneLabelledComponent.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneLabelledTextBox.cs
  osu.Game.Tournament/Screens/SetupScreen.cs
  osu.Game/Graphics/UserInterfaceV2/LabelledComponent.cs
  osu.Game/Graphics/UserInterfaceV2/LabelledTextBox.cs
  osu.Game/Screens/Edit/Setup/Components/LabelledComponents/LabelledTextBox.cs
Labels: size/L, user interface

#6240 Mark configuration lookup test headless
  osu.Game.Tests/Skins/TestSceneSkinConfigurationLookup.cs
Labels: size/XS

#6249 Fix mania bar line alignment
  osu.Game.Rulesets.Mania.Tests/TestSceneStage.cs
  osu.Game.Rulesets.Mania/Objects/BarLine.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableBarLine.cs
  osu.Game.Rulesets.Mania/UI/DrawableManiaRuleset.cs
  osu.Game.Rulesets.Mania/UI/ManiaPlayfield.cs
  osu.Game.Rulesets.Mania/UI/ManiaStage.cs
  osu.Game.Rulesets.Taiko.Tests/TestSceneTaikoPlayfield.cs
  osu.Game.Rulesets.Taiko/Objects/BarLine.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableBarLineMajor.cs
  osu.Game.Rulesets.Taiko/UI/DrawableTaikoRuleset.cs
  osu.Game/Rulesets/Objects/BarLine.cs
  osu.Game/Rulesets/Objects/BarLineGenerator.cs
  osu.Game/Rulesets/Objects/IBarLine.cs
Labels: size/M

#6238 Move post-update notification logic to UpdateManager base class
  osu.Desktop/OsuGameDesktop.cs
  osu.Desktop/Overlays/VersionManager.cs
  osu.Desktop/Updater/SquirrelUpdateManager.cs
  osu.Game/Updater/SimpleUpdateManager.cs
  osu.Game/Updater/UpdateManager.cs
Labels: code quality, installer / updater, size/L

#6243 Update beatmap carousel tests code style
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs
  osu.Game/Screens/Select/BeatmapCarousel.cs
Labels: size/L, testing

#6256 Fix invalid cursor trail parts being drawn
  osu.Game.Rulesets.Osu/UI/Cursor/CursorTrail.cs
Labels: resolves issue, size/S, user interface

#5793 Add android build automation via fastlane
  Gemfile.lock
  README.md
  fastlane/Fastfile
  fastlane/README.md
  osu.Android/OsuGameAndroid.cs
  osu.Game/Updater/SimpleUpdateManager.cs
Labels: android, size/L

#6236 Fix mania scrolling speed not including beatmap slider multiplier
  osu.Game.Tests/Visual/Gameplay/TestSceneDrawableScrollingRuleset.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Rulesets/UI/Scrolling/DrawableScrollingRuleset.cs
  osu.Game/Rulesets/UI/Scrolling/ScrollingHitObjectContainer.cs
Labels: osu!mania, resolves issue, size/S

#5501 Fix BackButton handling input before all other UI elements
  osu.Game.Tests/Visual/Menus/TestSceneScreenNavigation.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneBackButton.cs
  osu.Game/Graphics/UserInterface/BackButton.cs
  osu.Game/Online/API/APIRequest.cs
  osu.Game/OsuGame.cs
  osu.Game/OsuGameBase.cs
Labels: resolves issue, user interface

#6040 Decrease Spinner Disc Rotation on Rewind
  osu.Game.Rulesets.Osu.Tests/TestSceneSpinnerRotation.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SpinnerDisc.cs
Labels: size/S

#6275 Add bindable versions of IHasComboInformation properties
  osu.Game.Rulesets.Catch/Objects/CatchHitObject.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneHitCircleComboChange.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneSlider.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneSliderComboChange.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/MainCirclePiece.cs
  osu.Game.Rulesets.Osu/Objects/OsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Rulesets.Osu/Skinning/LegacyMainCirclePiece.cs
  osu.Game/Beatmaps/BeatmapProcessor.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Rulesets/Objects/HitObject.cs
  osu.Game/Rulesets/Objects/Types/IHasComboInformation.cs
  osu.Game/Skinning/SkinReloadableDrawable.cs
Labels: editor, size/L

#6270 Replace menu button text with "press for menu" on 0ms activation delay
  osu.Game/Screens/Play/HUD/HoldForMenuButton.cs
Labels: resolves issue, size/S

#6299 Fix track-adjusting mods not applying after resuming from another screen
  osu.Game/Overlays/MusicController.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: mods, resolves issue, size/XS

#6216 Add session-wide storage as a safer alternative to statics
  osu.Game/Configuration/InMemoryConfigManager.cs
  osu.Game/Configuration/SessionStatics.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Screens/Menu/MainMenu.cs
Labels: settings, size/S

#6308 Migrate beatmap carousel test to AddUntilStep
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs
Labels: size/XS, testing

#6310 Add the ability to choose a random intro sequence each startup
  osu.Game/Configuration/IntroSequence.cs
  osu.Game/Screens/Loader.cs
Labels: menu, size/XS

#6312 Handle potential null case
  osu.Game/Overlays/MusicController.cs
Labels: size/XS, testing

#6329 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS
