Repository ppy/osu, pull requests merged in 2019-08, with the labels that each got.

#5553 Remove generics from IApplicableToBeatmap
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModMirror.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModRandom.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game/Rulesets/Mods/IApplicableToBeatmap.cs
  osu.Game/Rulesets/Mods/ModTimeRamp.cs
  osu.Game/Rulesets/Mods/ModWindDown.cs
  osu.Game/Rulesets/Mods/ModWindUp.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
Labels: code quality, mods

#5554 Move IApplicableToBeatmap application to WorkingBeatmap
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
Labels: code quality

#5559 Fix ticks in repeat spans being returned in reverse order
  osu.Game.Rulesets.Osu.Tests/OsuBeatmapConversionTest.cs
  osu.Game.Rulesets.Osu/Resources/Testing/Beatmaps/repeat-slider-expected-conversion.json
  osu.Game.Rulesets.Osu/Resources/Testing/Beatmaps/repeat-slider.osu
  osu.Game.Rulesets.Osu/Resources/Testing/Beatmaps/uneven-repeat-slider-expected-conversion.json
  osu.Game.Rulesets.Osu/Resources/Testing/Beatmaps/uneven-repeat-slider.osu
  osu.Game.Tests/Beatmaps/SliderEventGenerationTest.cs
  osu.Game/Rulesets/Objects/SliderEventGenerator.cs
Labels: beatmap conversion, osu!, testing

#5566 Update cake to resolve CI issues
  build/cakebuild.csproj
Labels: tooling

#5548 Fix Music Controller skipping more than once
  osu.Game/OsuGame.cs
Labels: menu, resolves issue

#5558 Revert iOS import changes causing crash
  osu.iOS/Info.plist
Labels: iOS

#5580 Add hover click sounds to leaderboard mod filter
  osu.Game/Graphics/UserInterface/OsuTabControlCheckbox.cs
Labels: user interface

#5596 Move DimmedLoadingLayer to its own file
  osu.Game/Graphics/UserInterface/DimmedLoadingLayer.cs
  osu.Game/Screens/Select/BeatmapDetails.cs
Labels: code quality

#5588 Update Entity Framework Core
  osu.Desktop/osu.Desktop.csproj
  osu.Game/osu.Game.csproj
Labels: database, libraries

#5594 Update heart colour of supporter icon
  osu.Game/Overlays/Profile/Header/Components/SupporterIcon.cs
Labels: user profile

#5597 Refactor profile ruleset selector
  osu.Game.Tests/Visual/Online/TestSceneProfileRulesetSelector.cs
  osu.Game/Overlays/Profile/Header/Components/ProfileRulesetSelector.cs
Labels: code quality

#5590 Fix settings sidebar showing scrollbar at max ui scale
  osu.Game/Overlays/Settings/Sidebar.cs
  osu.Game/Overlays/SettingsPanel.cs
Labels: settings

#5555 Refactor beatmap conversion testing
  osu.Game.Rulesets.Mania.Tests/ManiaBeatmapConversionTest.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Tests/Beatmaps/BeatmapConversionTest.cs
Labels: code quality, testing

#5576 Update osu!direct categories sorting with web changes
  osu.Game/Online/API/Requests/SearchBeatmapSetsRequest.cs
  osu.Game/Overlays/Direct/FilterControl.cs
  osu.Game/Overlays/SearchableList/SearchableListFilterControl.cs
  osu.Game/Overlays/Social/FilterControl.cs
  osu.Game/Screens/Multi/Lounge/Components/FilterControl.cs
Labels: online / API

#5556 Support mods for beatmap conversion tests
  osu.Game.Rulesets.Catch.Tests/CatchBeatmapConversionTest.cs
  osu.Game.Rulesets.Mania.Tests/ManiaBeatmapConversionTest.cs
  osu.Game.Rulesets.Osu.Tests/OsuBeatmapConversionTest.cs
  osu.Game.Rulesets.Taiko.Tests/TaikoBeatmapConversionTest.cs
  osu.Game/Tests/Beatmaps/BeatmapConversionTest.cs
Labels: testing

#5561 Fix catch hardrock mod not using the correct RNG
  osu.Game.Rulesets.Catch.Tests/CatchBeatmapConversionTest.cs
  osu.Game.Rulesets.Catch/Beatmaps/CatchBeatmapProcessor.cs
  osu.Game.Rulesets.Catch/MathUtils/FastRandom.cs
  osu.Game.Rulesets.Catch/Mods/CatchModHardRock.cs
  osu.Game.Rulesets.Catch/Objects/CatchHitObject.cs
  osu.Game.Rulesets.Catch/Resources/Testing/Beatmaps/hardrock-repeat-slider-expected-conversion.json
  osu.Game.Rulesets.Catch/Resources/Testing/Beatmaps/hardrock-repeat-slider.osu
  osu.Game.Rulesets.Catch/Resources/Testing/Beatmaps/hardrock-spinner-expected-conversion.json
  osu.Game.Rulesets.Catch/Resources/Testing/Beatmaps/hardrock-spinner.osu
  osu.Game.Rulesets.Catch/Resources/Testing/Beatmaps/hardrock-stream-expected-conversion.json
  osu.Game.Rulesets.Catch/Resources/Testing/Beatmaps/hardrock-stream.osu
Labels: beatmap conversion, mods, osu!catch

#5606 Fix memory leaks from download buttons
  osu.Game/Online/DownloadTrackingComposite.cs
Labels: memory

#5598 Move RankHistoryData to User Statistics
  osu.Game.Tests/Visual/Online/TestSceneRankGraph.cs
  osu.Game.Tests/Visual/Online/TestSceneUserProfileOverlay.cs
  osu.Game/Overlays/Profile/Header/Components/RankGraph.cs
  osu.Game/Overlays/Profile/Header/DetailHeaderContainer.cs
  osu.Game/Users/User.cs
  osu.Game/Users/UserStatistics.cs
Labels: code quality, online / API

#5607 Fix drawable channels remaining in memory after being closed
  osu.Game/Overlays/ChatOverlay.cs
Labels: memory

#5617 Fix player completion action potentially being executed twice
  osu.Game/Screens/Play/Player.cs
Labels: code quality

#5625 Remove now unnecessary .gitmodules and .travis.yml
  .gitmodules
  .travis.yml
Labels: code quality

#5612 Fix footer button hover sounds playing in unclickable area
  osu.Game/Screens/Select/Footer.cs
  osu.Game/Screens/Select/FooterButton.cs
  osu.Game/Screens/Select/FooterButtonMods.cs
Labels: design, song select

#5613 Fix back button hover sounds playing in unclickable area
  osu.Game/Graphics/UserInterface/BackButton.cs
  osu.Game/Graphics/UserInterface/TwoLayerButton.cs
Labels: design

#5626 Fix Beatmap overlay trying to fetch scores even if beatmap has no leaderboard
  osu.Game/Overlays/BeatmapSet/Scores/ScoresContainer.cs
Labels: online / API

#5621 Expand GetUser and GetUserScores requests by adding RulesetInfo parameter
  osu.Game.Tests/Visual/Online/TestSceneUserRequest.cs
  osu.Game/Online/API/Requests/GetUserRequest.cs
  osu.Game/Online/API/Requests/GetUserScoresRequest.cs
Labels: online / API

#5630 Dispose flashlight quad batch
  osu.Game/Rulesets/Mods/ModFlashlight.cs
Labels: code quality

#5631 Fix cursor scale not matching osu-stable
  osu.Game.Rulesets.Osu/UI/OsuPlayfieldAdjustmentContainer.cs
  osu.Game/Skinning/LegacySkin.cs
Labels: resolves issue, skinning

#5632 Fix incorrect implementation of old stacking algorithm
  osu.Game.Rulesets.Osu.Tests/OsuBeatmapConversionTest.cs
  osu.Game.Rulesets.Osu/Beatmaps/OsuBeatmapProcessor.cs
  osu.Game.Rulesets.Osu/Resources/Testing/Beatmaps/old-stacking-expected-conversion.json
  osu.Game.Rulesets.Osu/Resources/Testing/Beatmaps/old-stacking.osu
Labels: beatmap parsing, resolves issue

#5467 Add a bindable for checking if the gameplay is currently in a break
  osu.Game.Tests/Visual/Gameplay/TestSceneBreakOverlay.cs
  osu.Game/Beatmaps/Timing/BreakPeriod.cs
  osu.Game/Screens/Play/BreakOverlay.cs
Labels: gameplay

#5642 Remove unused direct placeholder screen
  osu.Game/Screens/Direct/OnlineListing.cs
  osu.Game/Screens/Menu/MainMenu.cs
Labels: code quality

#5641 Remove linq usage in BreakOverlay update
  osu.Game/Screens/Play/BreakOverlay.cs
Labels: performance

#5635 Use bindable break time for checking to instant resume
  osu.Game/Screens/Play/Player.cs
Labels: code quality

#5602 Add chat /join command
  osu.Game/Online/Chat/ChannelManager.cs
Labels: chat

#5647 Don't share single scheduler across all model managers
  osu.Game/Database/ArchiveModelManager.cs
Labels: database, resolves issue

#5611 Log error for invalid beatmap/storyboard events instead of throwing
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Resources/invalid-events.osu
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyStoryboardDecoder.cs
  osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs
Labels: beatmap parsing, resolves issue

#5664 Adjust slider snaking and hitcircle fading to match stable
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SnakingSliderBody.cs
  osu.Game.Rulesets.Osu/Objects/OsuHitObject.cs
Labels: gameplay, osu!, size/XS

#5666 Update framework (with cached changes)
  osu.Android.props
  osu.Game.Rulesets.Mania/Objects/Drawables/Pieces/BodyPiece.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Tournament/Screens/Ladder/LadderScreen.cs
  osu.Game/Graphics/Backgrounds/Triangles.cs
  osu.Game/Graphics/UserInterface/LineGraph.cs
  osu.Game/Rulesets/UI/Scrolling/ScrollingHitObjectContainer.cs
  osu.Game/Screens/Play/SquareGraph.cs
  osu.Game/Screens/Select/BeatmapCarousel.cs
  osu.Game/Storyboards/CommandTimeline.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/M

#5669 Add ScreenTitleIcon class to allow code reuse of overlay header icons
  osu.Game/Graphics/UserInterface/ScreenTitle.cs
  osu.Game/Graphics/UserInterface/ScreenTitleTextureIcon.cs
  osu.Game/Overlays/Changelog/ChangelogHeader.cs
Labels: code quality, size/L, user interface

#5680 Add more detail to log output when beatmap parsing errors occur
  osu.Game/Beatmaps/Beatmap.cs
  osu.Game/Beatmaps/Formats/LegacyDecoder.cs
Labels: import, resolves issue, size/XS

#5638 Fix storyboard not showing when user dim is disabled
  osu.Game.Tests/Visual/Background/TestSceneUserDimContainer.cs
  osu.Game/Graphics/Containers/UserDimContainer.cs
  osu.Game/Screens/Play/DimmableStoryboard.cs
Labels: code quality, size/M, storyboard

#4762 Implement osu! autopilot mod
  osu.Game.Rulesets.Osu/Mods/OsuModAutopilot.cs
  osu.Game.Rulesets.Osu/OsuInputManager.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneModSelectOverlay.cs
Labels: mods, osu!, size/M

#5691 Fix mod multiplier not being applied for multiplayer
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
Labels: scoring

#5627 Implement LeaderboardScopeSelector
  osu.Game.Tests/Visual/Online/TestSceneLeaderboardScopeSelector.cs
  osu.Game/Graphics/UserInterface/OsuTabControl.cs
  osu.Game/Graphics/UserInterface/PageTabControl.cs
  osu.Game/Overlays/BeatmapSet/LeaderboardScopeSelector.cs
  osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboardScope.cs
Labels: overlays, user interface

#5267 Refactor OnScreenDisplay to allow displaying on custom messages
  osu.Game.Tests/Visual/UserInterface/TestSceneOnScreenDisplay.cs
  osu.Game/Overlays/OSD/Toast.cs
  osu.Game/Overlays/OSD/TrackedSettingToast.cs
  osu.Game/Overlays/OnScreenDisplay.cs
Labels: settings, size/L, user interface

#5695 Add note to README about ffmpeg requirement on linux
  README.md
Labels: size/XS

#5563 Implement PreviousUsernames for use in the profile overlay
  osu.Game.Tests/Visual/Online/TestSceneUserProfilePreviousUsernames.cs
  osu.Game/Overlays/Profile/Header/Components/PreviousUsernames.cs
  osu.Game/Users/User.cs
Labels: overlays, size/L, user profile

#5663 Add new "triangles" intro
  osu.Game.Tests/Visual/Menus/TestSceneIntroTriangles.cs
  osu.Game/Configuration/IntroSequence.cs
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Overlays/Settings/Sections/Audio/MainMenuSettings.cs
  osu.Game/Screens/BackgroundScreen.cs
  osu.Game/Screens/Backgrounds/BackgroundScreenDefault.cs
  osu.Game/Screens/Loader.cs
  osu.Game/Screens/Menu/IntroTriangles.cs
Labels: menu, size/XL

#5696 Split visual component out of MusicController
  osu.Game.Tests/Visual/Gameplay/TestSceneStoryboard.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneBeatSyncedContainer.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneNowPlayingOverlay.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Overlays/NowPlayingOverlay.cs
  osu.Game/Overlays/Toolbar/ToolbarMusicButton.cs
Labels: code quality, overlays, size/XL

#5268 Add game-wide keybindings for music playback
  osu.Game/Input/Bindings/GlobalActionContainer.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/KeyBinding/GlobalKeyBindingsSection.cs
  osu.Game/Overlays/MusicController.cs
Labels: resolves issue, size/XXL, ux

#5665 Update osu! iOS/Android native references
  osu.Android.props
  osu.Android/lib/arm64-v8a/libbass.so
  osu.Android/lib/arm64-v8a/libbass_fx.so
  osu.Android/lib/armeabi-v7a/libbass.so
  osu.Android/lib/armeabi-v7a/libbass_fx.so
  osu.Android/lib/x86/libbass.so
  osu.Android/lib/x86/libbass_fx.so
  osu.Game.Rulesets.Catch.Tests.iOS/osu.Game.Rulesets.Catch.Tests.iOS.csproj
  osu.Game.Rulesets.Mania.Tests.iOS/osu.Game.Rulesets.Mania.Tests.iOS.csproj
  osu.Game.Rulesets.Osu.Tests.iOS/osu.Game.Rulesets.Osu.Tests.iOS.csproj
  osu.Game.Rulesets.Taiko.Tests.iOS/osu.Game.Rulesets.Taiko.Tests.iOS.csproj
  osu.Game.Tests.iOS/osu.Game.Tests.iOS.csproj
  osu.iOS.props
  osu.iOS/libbass.a
  osu.iOS/libbass_fx.a
  osu.iOS/osu.iOS.csproj
Labels: mobile

#5697 Hide NotificationOverlay when clicking on UpdateCompleteNotification
  osu.Desktop/Overlays/VersionManager.cs
Labels: size/XS

#5643 Add beatmap panel to multiplayer match screen
  osu.Game.Tests/Visual/Multiplayer/TestSceneMatchBeatmapPanel.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMatchInfo.cs
  osu.Game/Screens/Multi/Match/Components/Header.cs
  osu.Game/Screens/Multi/Match/Components/Info.cs
  osu.Game/Screens/Multi/Match/Components/MatchBeatmapPanel.cs
  osu.Game/Screens/Multi/Match/Components/ViewBeatmapButton.cs
  osu.Game/Screens/Multi/Match/MatchSubScreen.cs
Labels: multiplayer, resolves issue

#5705 Attempt to appease apple with some plist keys
  osu.iOS/Info.plist
Labels: iOS, size/XS

#5709 Fix chat context menus displaying out-of-bounds
  osu.Game/Overlays/Chat/DrawableChannel.cs
Labels: chat, resolves issue, size/S

#5710 Disable music controls when beatmap is disabled
  osu.Game/Overlays/MusicController.cs
Labels: overlays, regression

#5732 Fix newlines being considered in user profile content
  osu.Game/Overlays/Profile/Header/BottomHeaderContainer.cs
Labels: resolves issue, size/XS, user profile

#5730 Fix song select context menus displaying off-screen
  osu.Game/Screens/Select/BeatmapCarousel.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: resolves issue, size/S, user interface

#5733 Reduce delay for hold-to-confirm controls
  osu.Game.Tests/Visual/Gameplay/TestSceneHoldForMenuButton.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneHoldToConfirmOverlay.cs
  osu.Game/Graphics/Containers/HoldToConfirmContainer.cs
Labels: size/XS

#5738 Update fastlane and dependencies
  Gemfile.lock
  fastlane/Fastfile
  fastlane/README.md
Labels: libraries, size/M

#5731 Fix checkbox sounds playing too often
  osu.Android.props
  osu.Game/Graphics/UserInterface/OsuCheckbox.cs
  osu.Game/Overlays/Profile/Header/Components/RankGraph.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: resolves issue, size/S, user interface

#5734 Disable frame-stable playback in the editor
  osu.Game/Rulesets/Edit/DrawableEditRuleset.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Rulesets/UI/FrameStabilityContainer.cs
Labels: editor, resolves issue, size/S

#5758 Add support for /users/ profile URLs
  osu.Game/Online/Chat/MessageFormatter.cs
Labels: online / API, size/XS

#5744 Replace DifficultyColouredContainer with a more scalable solution
  osu.Game/Beatmaps/BeatmapInfo.cs
  osu.Game/Beatmaps/DifficultyRating.cs
  osu.Game/Beatmaps/Drawables/DifficultyColouredContainer.cs
  osu.Game/Beatmaps/Drawables/DifficultyIcon.cs
  osu.Game/Graphics/OsuColour.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
Labels: code quality, design, size/L

#5763 Fix osu! default tooltips not displaying
  osu.Game/Graphics/Cursor/OsuTooltipContainer.cs
Labels: resolves issue, size/S, user interface

#5764 Unpause music when changing selection at song select
  osu.Game/Overlays/MusicController.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: pending review, size/S

#5768 Centre beatmap panels in profile overlay
  osu.Game/Overlays/Profile/Sections/Beatmaps/PaginatedBeatmapContainer.cs
Labels: resolves issue, size/XS, user profile

#5036 Add tooltips to difficulty icons with extra details
  osu.Game/Beatmaps/Drawables/DifficultyIcon.cs
  osu.Game/Overlays/BeatmapSet/BeatmapPicker.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmap.cs
Labels: size/L, user interface

#5779 Disallow adding bonus judgements to statistics
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
Labels: size/S

#5775 Fix LegacySkin not checking for @2x hitcircle when deciding sizing
  osu.Game/Skinning/LegacySkin.cs
Labels: regression, size/XS, skinning

#5497 Make legacy skins animatable
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hit0@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hit100@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hit100k@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hit300@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hit300g@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/hit50@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/metrics-skin/hit0@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/metrics-skin/hit100@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/metrics-skin/hit300@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/metrics-skin/hit50@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/special-skin/hit0-0@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/special-skin/hit0-1@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/special-skin/hit100-0@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/special-skin/hit100-1@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/special-skin/hit300-0@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/special-skin/hit300-1@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/special-skin/hit50-0@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/special-skin/hit50-1@2x.png
  osu.Game.Rulesets.Osu.Tests/SkinnableTestScene.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneDrawableJudgement.cs
  osu.Game/Skinning/LegacySkin.cs
Labels: resolves issue, skinning

#5759 Prevent beatmap change during intro playback
  osu.Game/Screens/Menu/IntroScreen.cs
Labels: menu, size/XS

#5776 Add slider ball animation support
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb-nd@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb-spec@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb0@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb1@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb2@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb3@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb4@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb5@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb6@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb7@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb8@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/sliderb9@2x.png
  osu.Game.Rulesets.Osu.Tests/TestSceneSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBall.cs
  osu.Game/Skinning/LegacySkin.cs
Labels: skinning

#5783 Update framework
  osu.Android.props
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableFruit.cs
  osu.Game.Rulesets.Catch/Objects/Drawable/Pieces/Pulp.cs
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/Pieces/BodyPiece.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/Pieces/LaneGlowPiece.cs
  osu.Game.Rulesets.Mania/UI/Components/ColumnBackground.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Connections/FollowPoint.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableRepeatPoint.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/CirclePiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/ExplodePiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/FlashPiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/GlowPiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SliderBall.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableSwell.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/Pieces/CirclePiece.cs
  osu.Game.Rulesets.Taiko/UI/InputDrum.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneCursors.cs
  osu.Game.Tournament/Components/TournamentBeatmapPanel.cs
  osu.Game/Beatmaps/Drawables/DifficultyIcon.cs
  osu.Game/Beatmaps/Formats/LegacyStoryboardDecoder.cs
  osu.Game/Graphics/Containers/OsuScrollContainer.cs
  osu.Game/Graphics/Cursor/MenuCursor.cs
  osu.Game/Graphics/Sprites/GlowingSpriteText.cs
  osu.Game/Graphics/UserInterface/DialogButton.cs
  osu.Game/Graphics/UserInterface/OsuAnimatedButton.cs
  osu.Game/Graphics/UserInterface/OsuButton.cs
  osu.Game/Overlays/Profile/Header/Components/RankGraph.cs
  osu.Game/Overlays/Toolbar/ToolbarButton.cs
  osu.Game/Overlays/Toolbar/ToolbarOverlayToggleButton.cs
  osu.Game/Screens/Edit/Components/RadioButtons/DrawableRadioButton.cs
  osu.Game/Screens/Edit/Compose/Components/BeatDivisorControl.cs
  osu.Game/Screens/Menu/Button.cs
  osu.Game/Screens/Menu/IntroTriangles.cs
  osu.Game/Screens/Menu/LogoVisualisation.cs
  osu.Game/Screens/Menu/MenuSideFlashes.cs
  osu.Game/Screens/Menu/OsuLogo.cs
  osu.Game/Screens/Multi/Match/Components/HeaderButton.cs
  osu.Game/Screens/ScreenWhiteBox.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselItem.cs
  osu.Game/Screens/Select/Options/BeatmapOptionsButton.cs
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/Storyboards/CommandTimelineGroup.cs
  osu.Game/Storyboards/Drawables/DrawablesExtensions.cs
  osu.Game/Storyboards/StoryboardSprite.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: libraries, size/L

#5777 Apply osu! SpriteText text builder changes
  osu.Game/Skinning/LegacySkin.cs
Labels: size/M

#5792 Simplify IPreviewTrackOwner caching in OsuFocusedOverlayContainer
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
Labels: code quality, size/XS

#5796 Fix a few icon spacing regressions
  osu.Game/Overlays/SettingsSubPanel.cs
  osu.Game/Rulesets/UI/ModIcon.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmapSet.cs
Labels: size/XS, user interface

#5801 Fix video decoding loop running permanently in the background
  osu.Game/Screens/Menu/IntroTriangles.cs
Labels: performance, size/S

#5807 Remove bottom margin from show more button
  osu.Game/Overlays/Profile/Sections/ShowMoreButton.cs
Labels: size/XS, user interface

#5808 Fix crash on closing game
  osu.Game/Screens/Menu/IntroTriangles.cs
Labels: regression

#5809 Fix alignment and size of mute button
  osu.Game/Overlays/Volume/MuteButton.cs
Labels: size/XS

#5821 Fix difficulty icons not wrapping correctly in beatmap set overlay
  osu.Game.Tests/Visual/Online/TestSceneBeatmapSetOverlay.cs
  osu.Game/Overlays/BeatmapSet/BeatmapPicker.cs
Labels: size/M, user interface

#5822 Allow for difficulty icon to have content added near the icon
  osu.Game/Beatmaps/Drawables/DifficultyIcon.cs
Labels: size/S

#5823 Implement grouped difficulty icons
  osu.Game.Tests/Visual/Online/TestSceneDirectPanel.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs
  osu.Game/Beatmaps/Drawables/GroupedDifficultyIcon.cs
  osu.Game/Overlays/Direct/DirectGridPanel.cs
  osu.Game/Overlays/Direct/DirectListPanel.cs
  osu.Game/Overlays/Direct/DirectPanel.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmapSet.cs
Labels: size/L, song select

#5832 Don't return DefaultSkin on beatmap skin parsing failure
  osu.Game/Beatmaps/BeatmapManager_WorkingBeatmap.cs
Labels: bug, size/XS, skinning

#5725 Fix autoplay missing very dense notes on Taiko and Mania
  osu.Game.Rulesets.Mania/Replays/ManiaAutoGenerator.cs
  osu.Game.Rulesets.Taiko/Replays/TaikoAutoGenerator.cs
  osu.Game/Rulesets/Replays/AutoGenerator.cs
Labels: replay, resolves issue, size/M

#5838 Fx component lookups being incorrect for non-databased legacy skins
  osu.Game.Rulesets.Osu.Tests/Resources/metrics-skin/approachcircle@2x.png
  osu.Game/Skinning/LegacySkin.cs
Labels: skinning

#5834 Add nullref safety to FrameStablePlayback boolean
  osu.Game/Rulesets/UI/DrawableRuleset.cs
Labels: code quality, size/S

#5835 Allow RulesetConfigCache to return null configs
  osu.Game/Rulesets/RulesetConfigCache.cs
Labels: configuration, size/XS

#5837 Add a sane default lifetime end for scrolling hitobjects
  osu.Game/Rulesets/UI/Scrolling/ScrollingHitObjectContainer.cs
Labels: resolves issue, size/S

#5840 Fix filtered grouped difficulty items in DrawableCarouselBeatmapSet aren't hidden on first load
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmapSet.cs
Labels: size/XS

#5842 Use automatic state logic for catch ruleset
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableCatchHitObject.cs
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
Labels: osu!catch, size/S

#5844 Use automatic state logic for mania ruleset
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableBarLine.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNote.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableManiaHitObject.cs
Labels: size/M

#5816 Save user's group and sort filter choices
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Screens/Select/FilterControl.cs
Labels: size/M, song select

#5848 Use automatic state logic for taiko ruleset
  osu.Game.Rulesets.Taiko.Tests/TestSceneTaikoPlayfield.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableBarLine.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableDrumRoll.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableDrumRollTick.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableHit.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableStrongNestedHit.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableSwell.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableSwellTick.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableTaikoHitObject.cs
Labels: code quality, size/L

#5855 Fix skin sample reading failing
  osu.Game/Skinning/LegacySkin.cs
Labels: regression, resolves issue, size/M, skinning

#5853 Obsolete legacy UpdateState() method
  osu.Game.Tests/Visual/Gameplay/TestSceneScrollingHitObjects.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: code quality, size/S

#5850 Fix taiko proxies being removed on rewind
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableTaikoHitObject.cs
Labels: osu!taiko, size/S

#5860 Fix hitsounds not updating immediately after switching skins
  osu.Game/Skinning/SkinnableSound.cs
Labels: size/XS, skinning

#5795 Try retrieving samples without bank names
  osu.Game.Rulesets.Catch.Tests/TestSceneCatcher.cs
  osu.Game.Tests/Beatmaps/Formats/LegacyStoryboardDecoderTest.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSkinnableDrawable.cs
  osu.Game/Beatmaps/Formats/LegacyStoryboardDecoder.cs
  osu.Game/Skinning/DefaultSkin.cs
  osu.Game/Skinning/ISkin.cs
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/Skinning/LocalSkinOverrideContainer.cs
  osu.Game/Skinning/Skin.cs
  osu.Game/Skinning/SkinManager.cs
  osu.Game/Skinning/SkinnableSound.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardSample.cs
  osu.Game/Storyboards/StoryboardSample.cs
Labels: size/S

#5858 Refactor PaginatedContainer to avoid code duplication
  osu.Game/Overlays/Profile/Sections/Beatmaps/PaginatedBeatmapContainer.cs
  osu.Game/Overlays/Profile/Sections/Historical/PaginatedMostPlayedBeatmapContainer.cs
  osu.Game/Overlays/Profile/Sections/PaginatedContainer.cs
  osu.Game/Overlays/Profile/Sections/Ranks/PaginatedScoreContainer.cs
  osu.Game/Overlays/Profile/Sections/Recent/PaginatedRecentActivityContainer.cs
Labels: size/L

#5856 Update in line with framework changes
  osu.Android.props
  osu.Game/Graphics/ScreenshotManager.cs
  osu.Game/Input/Bindings/GlobalActionContainer.cs
  osu.Game/Input/IdleTracker.cs
  osu.Game/Overlays/Volume/VolumeControlReceptor.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/S

#5863 Make taiko proxy containers use LifetimeManagementContainer
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs
Labels: osu!taiko, performance, size/S

#5865 Fix osu! approach circles fading in too late
  osu.Game.Rulesets.Catch/Objects/Drawable/DrawableCatchHitObject.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableManiaHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableTaikoHitObject.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: gameplay, osu!, size/S

#5530 Add a fallback for humanizer localization lookup failures
  osu.Game/Graphics/DrawableDate.cs
  osu.Game/Overlays/BeatmapSet/Scores/TopScoreUserSection.cs
  osu.Game/Utils/HumanizerUtils.cs
Labels: android, resolves issue

#5836 Implement relative timing point scaling for scrolling rulesets
  osu.Game.Rulesets.Mania/UI/DrawableManiaRuleset.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneDrawableScrollingRuleset.cs
  osu.Game/Beatmaps/ControlPoints/TimingControlPoint.cs
  osu.Game/Beatmaps/Formats/LegacyDifficultyCalculatorBeatmapDecoder.cs
  osu.Game/Rulesets/Timing/MultiplierControlPoint.cs
  osu.Game/Rulesets/UI/Scrolling/DrawableScrollingRuleset.cs
Labels: osu!mania, resolves issue, size/L

#5876 Fix drags outside of overlay container bounds not hiding overlay
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
Labels: regression, size/S, user interface

#5878 Encapsulate editor hitobject additions/removals
  osu.Game.Tests/Visual/Editor/TestSceneHitObjectComposer.cs
  osu.Game/Beatmaps/Beatmap.cs
  osu.Game/Beatmaps/IBeatmap.cs
  osu.Game/Rulesets/Edit/DrawableEditRuleset.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
  osu.Game/Screens/Edit/Compose/ComposeScreen.cs
  osu.Game/Screens/Edit/EditorBeatmap.cs
  osu.Game/Screens/Edit/IEditorBeatmap.cs
Labels: code quality, editor, size/L

#5880 Refactor HitObjectComposer for readability
  osu.Game.Rulesets.Mania/Edit/ManiaHitObjectComposer.cs
  osu.Game/Rulesets/Edit/DrawableEditRulesetWrapper.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
Labels: code quality, editor, size/L

#5881 Add EditorWorkingBeatmap to support reuse of the playable beatmap
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Catch/UI/DrawableCatchRuleset.cs
  osu.Game.Rulesets.Mania/Edit/DrawableManiaEditRuleset.cs
  osu.Game.Rulesets.Mania/Edit/ManiaHitObjectComposer.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Mania/UI/DrawableManiaRuleset.cs
  osu.Game.Rulesets.Osu/Edit/DrawableOsuEditRuleset.cs
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Osu/UI/DrawableOsuRuleset.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game.Rulesets.Taiko/UI/DrawableTaikoRuleset.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneDrawableScrollingRuleset.cs
  osu.Game/Beatmaps/DummyWorkingBeatmap.cs
  osu.Game/Beatmaps/IWorkingBeatmap.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Ruleset.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Rulesets/UI/Scrolling/DrawableScrollingRuleset.cs
  osu.Game/Screens/Edit/EditorWorkingBeatmap.cs
Labels: code quality, editor, size/L

#5879 Add "osu!classic" as a bundled skin choice
  osu.Android.props
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/OsuGame.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Skinning/DefaultLegacySkin.cs
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/Skinning/SkinInfo.cs
  osu.Game/Skinning/SkinManager.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/M, skinning

#5833 Add ruleset-level legacy skin provider
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/cursor@2x.png
  osu.Game.Rulesets.Osu.Tests/Resources/default-skin/cursormiddle@2x.png
  osu.Game.Rulesets.Osu.Tests/SkinnableTestScene.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneGameplayCursor.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneSkinFallbacks.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Osu/Skinning/LegacyCursor.cs
  osu.Game.Rulesets.Osu/Skinning/LegacyMainCirclePiece.cs
  osu.Game.Rulesets.Osu/Skinning/LegacySliderBall.cs
  osu.Game.Rulesets.Osu/Skinning/NonPlayfieldSprite.cs
  osu.Game.Rulesets.Osu/Skinning/OsuLegacySkin.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSkinnableDrawable.cs
  osu.Game/Beatmaps/BeatmapManager_WorkingBeatmap.cs
  osu.Game/Beatmaps/IWorkingBeatmap.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Rulesets/Ruleset.cs
  osu.Game/Screens/Edit/EditorWorkingBeatmap.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Skinning/BeatmapSkinProvidingContainer.cs
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/Skinning/LegacySkinExtensions.cs
  osu.Game/Skinning/LegacySkinResourceStore.cs
  osu.Game/Skinning/LegacySpriteText.cs
  osu.Game/Skinning/SkinProvidingContainer.cs
  osu.Game/Skinning/SkinnableDrawable.cs
  osu.Game/Tests/Visual/PlayerTestScene.cs
  osu.Game/Tests/Visual/TestPlayer.cs
Labels: resolves issue, size/XL, skinning

#5753 Add hit error display
  osu.Game.Tests/Visual/Gameplay/TestSceneBarHitErrorMeter.cs
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Configuration/ScoreMeterType.cs
  osu.Game/Overlays/Settings/Sections/Gameplay/GeneralSettings.cs
  osu.Game/Rulesets/Objects/HitWindows.cs
  osu.Game/Screens/Play/HUD/HitErrorDisplay.cs
  osu.Game/Screens/Play/HUD/HitErrorMeters/BarHitErrorMeter.cs
  osu.Game/Screens/Play/HUD/HitErrorMeters/HitErrorMeter.cs
  osu.Game/Screens/Play/HUDOverlay.cs
Labels: gameplay, size/XL

#5909 Fix vertical alignment of hit error display ticks
  osu.Game/Screens/Play/HUD/HitErrorMeters/BarHitErrorMeter.cs
Labels: gameplay, size/XS

#5911 Fix ruleset skins incorrectly providing configuration defaults
  osu.Game.Rulesets.Osu/Skinning/OsuLegacySkin.cs
  osu.Game/Skinning/DefaultSkin.cs
  osu.Game/Skinning/DefaultSkinConfiguration.cs
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/Skinning/LegacySkinDecoder.cs
  osu.Game/Skinning/SkinConfiguration.cs
Labels: regression, size/M, skinning

#5910 Fix legacy skin text reading from the wrong source
  osu.Game.Rulesets.Osu/Skinning/OsuLegacySkin.cs
Labels: regression, skinning
