Repository ppy/osu, pull requests merged in 2019-04, with the labels that each got.

#4563 Fix replay handler nullref crashes
  osu.Game.Rulesets.Osu/Replays/OsuFramedReplayInputHandler.cs
  osu.Game.Tests/NonVisual/FramedReplayinputHandlerTest.cs
  osu.Game/Rulesets/Replays/FramedReplayInputHandler.cs
Labels: bug, replay

#4562 Fix editor blueprints being misplaced
  osu.Game.Rulesets.Catch/UI/DrawableCatchRuleset.cs
  osu.Game.Rulesets.Mania/UI/DrawableManiaRuleset.cs
  osu.Game.Rulesets.Osu/Edit/DrawableOsuEditRuleset.cs
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game.Rulesets.Osu/UI/DrawableOsuRuleset.cs
  osu.Game.Rulesets.Taiko/UI/DrawableTaikoRuleset.cs
  osu.Game/Rulesets/Edit/DrawableEditRuleset.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
Labels: editor, regression

#4569 Fix replays being parsed with incorrect cultures
  osu.Game/Scoring/Legacy/LegacyScoreParser.cs
Labels: replay

#4566 Make main menu elements colorable by skin
  osu.Game/Screens/Menu/LogoVisualisation.cs
  osu.Game/Screens/Menu/MenuSideFlashes.cs
Labels: skinning

#4529 Add osu! click-to-resume support
  osu.Game.Rulesets.Osu.Tests/TestCaseResumeOverlay.cs
  osu.Game.Rulesets.Osu/UI/Cursor/OsuCursor.cs
  osu.Game.Rulesets.Osu/UI/Cursor/OsuCursorContainer.cs
  osu.Game.Rulesets.Osu/UI/DrawableOsuRuleset.cs
  osu.Game.Rulesets.Osu/UI/OsuResumeOverlay.cs
  osu.Game.Tests/Visual/Gameplay/TestCasePause.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Rulesets/UI/Playfield.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/ResumeOverlay.cs
Labels: gameplay, user interface

#4582 Correctly handle nvika/inspectcode return codes
  build/build.cake
Labels: testing

#4581 Avoid presenting beatmap when already at requested beatmap
  osu.Game/OsuGame.cs
Labels: resolves issue

#4585 Hides "Details" button when OnlineBeatmapID is null
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmap.cs
Labels: resolves issue

#4133 Add setting to toggle gameplay cursor trail
  osu.Game.Rulesets.Osu/Configuration/OsuRulesetConfigManager.cs
  osu.Game.Rulesets.Osu/UI/Cursor/OsuCursorContainer.cs
  osu.Game.Rulesets.Osu/UI/OsuSettingsSubsection.cs
Labels: osu!, settings

#4211 Update beatmap scores design
  osu.Game.Tests/Visual/Online/TestCaseBeatmapSetOverlay.cs
  osu.Game.Tests/Visual/Online/TestCaseScoresContainer.cs
  osu.Game.Tests/Visual/SongSelect/TestCaseBeatmapScoresContainer.cs
  osu.Game/Graphics/Containers/LinkFlowContainer.cs
  osu.Game/Graphics/Containers/OsuHoverContainer.cs
  osu.Game/Online/API/Requests/Responses/APILegacyScores.cs
  osu.Game/Overlays/BeatmapSet/Scores/ClickableUsername.cs
  osu.Game/Overlays/BeatmapSet/Scores/DrawableScore.cs
  osu.Game/Overlays/BeatmapSet/Scores/DrawableTopScore.cs
  osu.Game/Overlays/BeatmapSet/Scores/ScoreTable.cs
  osu.Game/Overlays/BeatmapSet/Scores/ScoreTableRowBackground.cs
  osu.Game/Overlays/BeatmapSet/Scores/ScoresContainer.cs
  osu.Game/Overlays/BeatmapSet/Scores/TopScoreStatisticsSection.cs
  osu.Game/Overlays/BeatmapSet/Scores/TopScoreUserSection.cs
  osu.Game/Screens/Multi/Components/BeatmapTypeInfo.cs
  osu.Game/Screens/Multi/Lounge/Components/ParticipantInfo.cs
  osu.Game/Screens/Multi/Match/Components/HostInfo.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: design, overlays

#4589 Fix visual issue with rapidly switching between menu button states
  osu.Game/Screens/Menu/Button.cs
Labels: resolves issue

#4555 Fix volume overlay being blocked by other floating overlays
  osu.Game/OsuGame.cs
Labels: resolves issue

#4596 Fix local scores not being sorted correctly on leaderboard
  osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboard.cs
Labels: scoring, songselect

#4603 Switch NotificationOverlay and LoginOverlay depth order
  osu.Game/OsuGame.cs
  osu.Game/Screens/Menu/ButtonSystem.cs
Labels: resolves issue

#4612 Fix OsuScreenDependencies using the incorrect parent
  osu.Game/Screens/OsuScreen.cs
Labels: bug

#4583 Fix gameplay offset handling on seeks
  osu.Game/Screens/Play/GameplayClockContainer.cs
Labels: resolves issue

#4613 Remove mods from WorkingBeatmap
  osu.Game.Rulesets.Catch.Tests/TestCaseAutoJuiceStream.cs
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Catch/UI/DrawableCatchRuleset.cs
  osu.Game.Rulesets.Mania.Tests/ManiaPlacementBlueprintTestCase.cs
  osu.Game.Rulesets.Mania.Tests/TestCaseColumn.cs
  osu.Game.Rulesets.Mania.Tests/TestCaseStage.cs
  osu.Game.Rulesets.Mania/Edit/DrawableManiaEditRuleset.cs
  osu.Game.Rulesets.Mania/Edit/ManiaHitObjectComposer.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Mania/UI/DrawableManiaRuleset.cs
  osu.Game.Rulesets.Osu.Tests/StackingTest.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseHitCircle.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseHitCircleHidden.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseSlider.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseSliderHidden.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseSpinner.cs
  osu.Game.Rulesets.Osu.Tests/TestCaseSpinnerHidden.cs
  osu.Game.Rulesets.Osu/Edit/DrawableOsuEditRuleset.cs
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Osu/UI/DrawableOsuRuleset.cs
  osu.Game.Rulesets.Taiko.Tests/TestCaseTaikoPlayfield.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game.Rulesets.Taiko/UI/DrawableTaikoRuleset.cs
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Visual/Background/TestCaseBackgroundScreenBeatmap.cs
  osu.Game.Tests/Visual/Gameplay/TestCaseAutoplay.cs
  osu.Game.Tests/Visual/Gameplay/TestCaseReplay.cs
  osu.Game.Tests/Visual/Gameplay/TestCaseScrollingHitObjects.cs
  osu.Game.Tests/Visual/SongSelect/TestCasePlaySongSelect.cs
  osu.Game.Tests/Visual/UserInterface/TestCaseMods.cs
  osu.Game/Beatmaps/DummyWorkingBeatmap.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Rulesets/Difficulty/DifficultyCalculator.cs
  osu.Game/Rulesets/Difficulty/PerformanceCalculator.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Ruleset.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Rulesets/UI/Playfield.cs
  osu.Game/Rulesets/UI/Scrolling/DrawableScrollingRuleset.cs
  osu.Game/Screens/Multi/Match/Components/Header.cs
  osu.Game/Screens/Multi/Match/MatchSubScreen.cs
  osu.Game/Screens/Multi/Play/TimeshiftPlayer.cs
  osu.Game/Screens/OsuScreen.cs
  osu.Game/Screens/OsuScreenDependencies.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
  osu.Game/Screens/Play/HUD/ModDisplay.cs
  osu.Game/Screens/Play/HUDOverlay.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
  osu.Game/Screens/Select/MatchSongSelect.cs
  osu.Game/Screens/Select/PlaySongSelect.cs
  osu.Game/Screens/Select/SongSelect.cs
  osu.Game/Tests/Visual/AllPlayersTestCase.cs
  osu.Game/Tests/Visual/OsuTestCase.cs
  osu.Game/Tests/Visual/PlayerTestCase.cs
Labels: resolves issue

#4624 Fix replay rewinding not respecting 60fps playback
  osu.Game/Rulesets/UI/FrameStabilityContainer.cs
Labels: bug, replay

#4540 Implement FacadeContainer for tracking logo positions in other containers
  osu.Game.Tests/Visual/UserInterface/TestCaseButtonSystem.cs
  osu.Game.Tests/Visual/UserInterface/TestCaseLogoTrackingContainer.cs
  osu.Game/Graphics/Containers/LogoTrackingContainer.cs
  osu.Game/Screens/Menu/ButtonArea.cs
  osu.Game/Screens/Menu/ButtonSystem.cs
  osu.Game/Screens/Menu/FlowContainerWithOrigin.cs
  osu.Game/Screens/Menu/OsuLogo.cs
  osu.Game/Screens/Play/PlayerLoader.cs
Labels: resolves issue

#4614 Reinstantiate mods for each player instance
  osu.Game.Tests/Visual/Gameplay/TestCasePlayerLoader.cs
  osu.Game/Screens/Play/Player.cs
Labels: resolves issue

#4661 Fix pause tests and cursor visibility
  osu.Game/Rulesets/UI/Playfield.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
Labels: gameplay, testing

#4660 Standardise health adjustment process across all rulesets
  osu.Game.Rulesets.Catch/Judgements/CatchBananaJudgement.cs
  osu.Game.Rulesets.Catch/Judgements/CatchDropletJudgement.cs
  osu.Game.Rulesets.Catch/Judgements/CatchJudgement.cs
  osu.Game.Rulesets.Catch/Judgements/CatchTinyDropletJudgement.cs
  osu.Game.Rulesets.Catch/Scoring/CatchScoreProcessor.cs
  osu.Game.Rulesets.Mania/Judgements/HoldNoteTickJudgement.cs
  osu.Game.Rulesets.Mania/Judgements/ManiaJudgement.cs
  osu.Game.Rulesets.Mania/Scoring/ManiaScoreProcessor.cs
  osu.Game.Rulesets.Osu/Judgements/OsuJudgement.cs
  osu.Game.Rulesets.Osu/Scoring/OsuScoreProcessor.cs
  osu.Game.Rulesets.Taiko/Scoring/TaikoScoreProcessor.cs
  osu.Game/Rulesets/Judgements/Judgement.cs
  osu.Game/Rulesets/Judgements/JudgementResult.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
Labels: gameplay, osu!, osu!catch, osu!mania, osu!taiko

#4663 Fix possible exit from non-current screen
  osu.Game/Screens/Multi/Multiplayer.cs
Labels: bug, multiplayer

#4667 Fix gameplay cursor being hidden in tests/replays
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Tests/Visual/ManualInputManagerTestCase.cs
Labels: regression, replay, testing

#4673 Amend FrameStabilityContainer's initial seek behaviour
  osu.Game.Tests/Visual/Gameplay/TestCaseFrameStabilityContainer.cs
  osu.Game/Rulesets/UI/FrameStabilityContainer.cs
Labels: gameplay, testing

#4675 Prevent PlayerLoader from tracking the logo after it has been exited.
  osu.Game/Screens/Play/PlayerLoader.cs
Labels: resolves issue

#4674 Fix lead-in time being too short
  osu.Game.Rulesets.Osu/UI/DrawableOsuRuleset.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
  osu.Game/Tests/Beatmaps/TestWorkingBeatmap.cs
Labels: resolves issue

#4659 Improve waveform graph testing
  osu.Game.Tests/Visual/Editor/TestCaseWaveform.cs
Labels: testing
