Repository ppy/osu, pull requests merged in 2020-05, with the labels that each got.

#8914 Fix undo/redo behaving poorly with simultaneous objects
  osu.Game.Tests/Editing/LegacyEditorBeatmapPatcherTest.cs
  osu.Game/Screens/Edit/EditorBeatmap.cs
  osu.Game/Screens/Edit/LegacyEditorBeatmapPatcher.cs
Labels: area:editor, size/M

#8623 Use DisplayModes rather than AvailableResolutions
  osu.Android.props
  osu.Game/Overlays/Settings/Sections/Graphics/LayoutSettings.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/S

#8919 Truncate beatmap title and artist on score panel
  osu.Game.Tests/Visual/Ranking/TestSceneExpandedPanelMiddleContent.cs
  osu.Game/Screens/Ranking/Expanded/ExpandedPanelMiddleContent.cs
  osu.Game/Screens/Ranking/ScorePanel.cs
Labels: area:results, size/S, type:UI

#8925 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#8924 Add local beatmap lookup cache to improve performance of imports
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/BeatmapManager_BeatmapOnlineLookupQueue.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/osu.Game.csproj
Labels: area:database, size/L, type:performance

#8701 Implement period-tracking component
  osu.Game.Tests/NonVisual/PeriodTrackerTest.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneAutoplay.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneBreakTracker.cs
  osu.Game/Screens/Play/BreakTracker.cs
  osu.Game/Utils/PeriodTracker.cs
Labels: size/L

#8932 Fix song select tests potentially failing due to difficulty panels not yet displayed
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
  osu.Game/Beatmaps/BeatmapManager.cs
Labels: size/S, type:testing

#8933 Fix hard crash when changing ruleset while presenting a score
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
  osu.Game/Screens/Select/PlaySongSelect.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: area:song-select, size/M, type:reliability

#8944 Fix typo and add spaces to comments
  osu.Desktop/Updater/SquirrelUpdateManager.cs
  osu.Game.Rulesets.Catch/Mods/CatchModRelax.cs
  osu.Game.Rulesets.Catch/Replays/CatchAutoGenerator.cs
  osu.Game.Rulesets.Osu/Beatmaps/OsuBeatmapProcessor.cs
  osu.Game.Rulesets.Osu/Mods/OsuModTransform.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/MainCirclePiece.cs
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game.Tests/NonVisual/ControlPointInfoTest.cs
  osu.Game.Tests/NonVisual/FramedReplayInputHandlerTest.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Graphics/Backgrounds/Triangles.cs
  osu.Game/Graphics/Containers/OsuScrollContainer.cs
  osu.Game/IPC/ArchiveImportIPCChannel.cs
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Online/API/APIRequest.cs
  osu.Game/Online/Chat/Channel.cs
  osu.Game/Online/Chat/MessageFormatter.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/BeatmapListing/Panels/GridBeatmapPanel.cs
  osu.Game/Overlays/BeatmapSet/Header.cs
  osu.Game/Overlays/ChatOverlay.cs
  osu.Game/Overlays/DialogOverlay.cs
  osu.Game/Overlays/Music/PlaylistItem.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Overlays/News/NewsArticleCover.cs
  osu.Game/Overlays/Notifications/ProgressNotification.cs
  osu.Game/Overlays/NowPlayingOverlay.cs
  osu.Game/Overlays/OSD/Toast.cs
  osu.Game/Overlays/Profile/Header/Components/OverlinedInfoContainer.cs
  osu.Game/Overlays/Profile/Header/MedalHeaderContainer.cs
  osu.Game/Overlays/SearchableList/SearchableListFilterControl.cs
  osu.Game/Overlays/Toolbar/ToolbarButton.cs
  osu.Game/Overlays/VolumeOverlay.cs
  osu.Game/Rulesets/Replays/FramedReplayInputHandler.cs
  osu.Game/Rulesets/RulesetStore.cs
  osu.Game/Screens/BackgroundScreen.cs
  osu.Game/Screens/Menu/IntroScreen.cs
  osu.Game/Screens/Menu/LogoVisualisation.cs
  osu.Game/Screens/Menu/MainMenu.cs
  osu.Game/Screens/OsuScreen.cs
  osu.Game/Screens/Play/BreakOverlay.cs
  osu.Game/Screens/Play/HUD/PlayerSettingsOverlay.cs
  osu.Game/Screens/Play/KeyCounter.cs
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/Screens/Select/BeatmapCarousel.cs
  osu.Game/Screens/Select/BeatmapDetailAreaTabControl.cs
  osu.Game/Screens/Select/BeatmapDetails.cs
  osu.Game/Screens/Select/Details/AdvancedStats.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: size/L, type:code-quality

#8934 Implement Sorcerer's osu!catch difficulty calculation adjustments
  osu.Game.Rulesets.Catch.Tests/CatchDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyCalculator.cs
  osu.Game.Rulesets.Catch/Difficulty/CatchPerformanceCalculator.cs
  osu.Game.Rulesets.Catch/Difficulty/Preprocessing/CatchDifficultyHitObject.cs
  osu.Game.Rulesets.Catch/Difficulty/Skills/Movement.cs
  osu.Game/Rulesets/Scoring/HitResult.cs
  osu.Game/Scoring/Legacy/ScoreInfoExtensions.cs
Labels: area:difficulty, ruleset:osu!catch, size/L

#8960 Fix date tooltip not showing in 24-hour format
  osu.Game/Graphics/DrawableDate.cs
Labels: size/XS, type:UI

#8961 Add support for 3v3 tournament chroma key layout
  osu.Game.Tournament/Models/LadderInfo.cs
  osu.Game.Tournament/Screens/Gameplay/GameplayScreen.cs
Labels: area:tournament, size/M

#8959 Fix catch crashing when finishing maps
  osu.Game/Scoring/Legacy/ScoreInfoExtensions.cs
Labels: area:results, ruleset:osu!catch, size/M

#8958 Fix potential nullref in song select filtering
  osu.Game/Beatmaps/BeatmapInfo.cs
  osu.Game/Screens/Select/Carousel/CarouselBeatmap.cs
Labels: area:song-select, size/S

#8966 Update framework
  osu.Android.props
  osu.Desktop/OsuGameDesktop.cs
  osu.Game.Tournament/IPC/FileBasedIPC.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/L

#8968 Commit autogenerated rider VCS settings update
  .idea/.idea.osu.Desktop/.idea/projectSettingsUpdater.xml
Labels: size/XS

#8969 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#8971 Revert "Commit autogenerated rider VCS settings update"
  .idea/.idea.osu.Desktop/.idea/projectSettingsUpdater.xml
Labels: size/XS

#8970 Fix android usage of obsoleted VersionCode
  osu.Android/OsuGameAndroid.cs
Labels: platform:android, size/XS

#8972 Fix loading a ruleset with a new version specification causing a crash
  osu.Game/Rulesets/RulesetInfo.cs
  osu.Game/Rulesets/RulesetStore.cs
Labels: size/S, type:reliability

#8980 Check local availability of beatmap before disabling download buttons
  osu.Game/Overlays/BeatmapListing/Panels/BeatmapPanelDownloadButton.cs
  osu.Game/Overlays/BeatmapSet/Header.cs
Labels: area:overlay-beatmap, size/S, type:UX

#8982 Fix null reference causing hard freeze if game is forcefully closed during disclaimer
  osu.Game/OsuGame.cs
Labels: size/XS, type:reliability

#8973 Fix hold note selection pieces disappearing on movement
  osu.Game.Rulesets.Mania.Tests/TestSceneManiaHitObjectComposer.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneOutOfOrderHits.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Connections/FollowPointConnection.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Rulesets/Objects/HitObject.cs
  osu.Game/Rulesets/UI/Scrolling/ScrollingHitObjectContainer.cs
  osu.Game/Screens/Edit/EditorBeatmap.cs
Labels: area:editor, ruleset:osu!mania, size/L

#8945 Add ability for a ruleset to disable gameplay overlays from displaying
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Screens/Play/Player.cs
Labels: area:gameplay, size/S, type:UI

#8920 Add taiko scroller
  osu.Game.Rulesets.Taiko.Tests/Resources/metrics-skin/taiko-slider-fail@2x.png
  osu.Game.Rulesets.Taiko.Tests/Resources/metrics-skin/taiko-slider@2x.png
  osu.Game.Rulesets.Taiko.Tests/Resources/old-skin/taiko-slider-fail@2x.png
  osu.Game.Rulesets.Taiko.Tests/Resources/old-skin/taiko-slider@2x.png
  osu.Game.Rulesets.Taiko.Tests/Resources/special-skin/taiko-slider-fail.png
  osu.Game.Rulesets.Taiko.Tests/Resources/special-skin/taiko-slider.png
  osu.Game.Rulesets.Taiko.Tests/Skinning/TestSceneTaikoPlayfield.cs
  osu.Game.Rulesets.Taiko.Tests/Skinning/TestSceneTaikoScroller.cs
  osu.Game.Rulesets.Taiko/Skinning/LegacyTaikoScroller.cs
  osu.Game.Rulesets.Taiko/Skinning/TaikoLegacySkinTransformer.cs
  osu.Game.Rulesets.Taiko/TaikoSkinComponents.cs
  osu.Game.Rulesets.Taiko/UI/DrawableTaikoRuleset.cs
  osu.Game/Screens/Play/GameplayBeatmap.cs
  osu.Game/Screens/Play/Player.cs
Labels: area:skinning, ruleset:osu!taiko

#8935 Add basic custom data directory support
  osu.Game.Tests/NonVisual/CustomDataDirectoryTest.cs
  osu.Game/Configuration/StorageConfigManager.cs
  osu.Game/IO/OsuStorage.cs
  osu.Game/IO/WrappedStorage.cs
  osu.Game/OsuGameBase.cs
Labels: area:settings, size/L

#8988 Don't timeout on long beatmap load when debugging
  osu.Game/Beatmaps/WorkingBeatmap.cs
Labels: size/S, type:testing

#8990 Fix hardrock potentially taking a long time to load
  osu.Game.Rulesets.Osu/Mods/OsuModHardRock.cs
Labels: area:mods, ruleset:osu!, size/XS, type:performance

#8989 Fix taiko sample mapping for strong hits
  osu.Game.Rulesets.Taiko/Beatmaps/TaikoBeatmapConverter.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableHit.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableTaikoHitObject.cs
Labels: area:beatmap, ruleset:osu!taiko, size/M

#8993 Refactor beatmap encoder test to be a bit easier to understand
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapEncoderTest.cs
Labels: size/M, type:code-quality, type:testing

#8986 Implement midi keybindings
  osu.Android.props
  osu.Game/Overlays/KeyBinding/KeyBindingRow.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/M, type:input

#9000 Fix version-dependent skin elements looking incorrect when beatmap skins are enabled
  osu.Game.Tests/Skins/TestSceneSkinConfigurationLookup.cs
  osu.Game/Skinning/LegacyBeatmapSkin.cs
Labels: area:skinning, size/S

#9001 Fix null reference in difficulty recommender
  osu.Game/Screens/Select/DifficultyRecommender.cs
Labels: area:song-select, size/XS, type:reliability

#8981 Use strongly-typed JsonConverter
  osu.Game/IO/Serialization/Converters/TypedListConverter.cs
  osu.Game/IO/Serialization/Converters/Vector2Converter.cs
Labels: size/M, type:code-quality

#9002 Use CacheAs for caching game-wide components
  osu.Game/OsuGame.cs
Labels: size/S, type:code-quality

#9009 Fix crashes when pressing right-click while placing hold notes
  osu.Game.Rulesets.Mania/Edit/Blueprints/HoldNotePlacementBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/ManiaPlacementBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/NotePlacementBlueprint.cs
Labels: area:editor, ruleset:osu!mania, size/S

#8962 Storage directory migration support
  osu.Game.Tests/NonVisual/CustomDataDirectoryTest.cs
  osu.Game/Database/DatabaseContextFactory.cs
  osu.Game/IO/OsuStorage.cs
  osu.Game/IO/WrappedStorage.cs
  osu.Game/OsuGameBase.cs
Labels: area:database, size/L

#8857 Add taiko mascot display for legacy skins
  osu.Game.Rulesets.Taiko.Tests/Skinning/TestSceneDrawableTaikoMascot.cs
  osu.Game.Rulesets.Taiko.Tests/Skinning/TestSceneTaikoScroller.cs
  osu.Game.Rulesets.Taiko/Skinning/TaikoLegacySkinTransformer.cs
  osu.Game.Rulesets.Taiko/TaikoSkinComponents.cs
  osu.Game.Rulesets.Taiko/UI/DrawableTaikoMascot.cs
  osu.Game.Rulesets.Taiko/UI/DrawableTaikoRuleset.cs
  osu.Game.Rulesets.Taiko/UI/TaikoMascotAnimation.cs
  osu.Game.Rulesets.Taiko/UI/TaikoMascotAnimationState.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs
Labels: area:skinning, ruleset:osu!taiko, size/XL

#8448 Add support for custom hyper-dash catcher colouring
  osu.Game.Rulesets.Catch.Tests/TestSceneCatcher.cs
  osu.Game.Rulesets.Catch.Tests/TestSceneHyperDashColouring.cs
  osu.Game.Rulesets.Catch/UI/Catcher.cs
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
  osu.Game.Rulesets.Catch/UI/CatcherTrailDisplay.cs
Labels: area:skinning, ruleset:osu!catch, size/L

#8622 Add test for osu!catch skin configuration colour decoding
  osu.Game.Rulesets.Catch.Tests/CatchSkinColourDecodingTest.cs
  osu.Game.Rulesets.Catch.Tests/Resources/special-skin/skin.ini
  osu.Game.Rulesets.Catch/Skinning/CatchLegacySkinTransformer.cs
Labels: area:skinning, ruleset:osu!catch, size/M

#9011 Add a basic directory chooser component
  osu.Game.Tests/Visual/Settings/TestSceneDirectorySelector.cs
  osu.Game/Graphics/UserInterfaceV2/DirectorySelector.cs
Labels: size/L, type:UI

#8999 BeatmapListingOverlay auto-pagination reimplementation
  osu.Game/Extensions/WebRequestExtensions.cs
  osu.Game/Online/API/Requests/Cursor.cs
  osu.Game/Online/API/Requests/ResponseWithCursor.cs
  osu.Game/Online/API/Requests/SearchBeatmapSetsRequest.cs
  osu.Game/Overlays/BeatmapListing/BeatmapListingFilterControl.cs
  osu.Game/Overlays/BeatmapListingOverlay.cs
Labels: area:overlay-beatmap-listing, size/L, type:UI

#9003 Fix taiko scroller not correctly adhering to gameplay time movement
  osu.Android.props
  osu.Game.Rulesets.Taiko.Tests/Skinning/TestSceneTaikoScroller.cs
  osu.Game.Rulesets.Taiko/Skinning/LegacyTaikoScroller.cs
  osu.Game.Rulesets.Taiko/UI/DrawableTaikoRuleset.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: area:skinning, ruleset:osu!taiko, size/M

#9005 Reposition taiko playfield closer to top of screen
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfieldAdjustmentContainer.cs
Labels: area:gameplay, ruleset:osu!taiko, size/M, size/S

#9007 Fix mod failure checks executing actual game logic
  osu.Game.Rulesets.Osu/Mods/OsuModAutopilot.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneReplay.cs
  osu.Game/Rulesets/Mods/IApplicableFailOverride.cs
  osu.Game/Rulesets/Mods/ModAutoplay.cs
  osu.Game/Rulesets/Mods/ModBlockFail.cs
  osu.Game/Rulesets/Mods/ModEasy.cs
  osu.Game/Rulesets/Mods/ModSuddenDeath.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/ReplayPlayer.cs
  osu.Game/Tests/Visual/ModPerfectTestScene.cs
  osu.Game/Tests/Visual/ModTestScene.cs
Labels: size/M, type:code-quality, type:reliability

#9024 Use unique video in map pool scene of tournament client
  osu.Game.Tournament/Screens/Editors/SeedingEditorScreen.cs
  osu.Game.Tournament/Screens/MapPool/MapPoolScreen.cs
Labels: area:tournament, size/S

#9029 Fix mute button falling off the screen when UI scaling is used
  osu.Game/Overlays/VolumeOverlay.cs
Labels: size/S, type:UI

#9027 Add more safeties to storage migration
  osu.Game.Tests/NonVisual/CustomDataDirectoryTest.cs
  osu.Game/IO/OsuStorage.cs
Labels: size/M, type:reliability

#9020 Add ability to change data folder path
  osu.Game.Tests/Visual/Settings/TestSceneMigrationScreens.cs
  osu.Game/Graphics/UserInterfaceV2/DirectorySelector.cs
  osu.Game/IO/OsuStorage.cs
  osu.Game/Overlays/Settings/Sections/General/UpdateSettings.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/MigrationRunScreen.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/MigrationSelectScreen.cs
Labels: area:settings, size/L

#9036 Fix applied platform/user offsets being incorrect when rate adjust mods are active
  osu.Game/Screens/Play/GameplayClockContainer.cs
Labels: size/S, type:audio

#9031 Avoid disabling a host-level bindable from osu! code
  osu.Game/Overlays/Settings/Sections/Input/MouseSettings.cs
Labels: size/S, type:testing

#9041 Add a back button to sub screens in the Tournament Client
  osu.Game.Tournament.Tests/Screens/TestSceneSeedingEditorScreen.cs
  osu.Game.Tournament/Screens/Editors/SeedingEditorScreen.cs
  osu.Game.Tournament/Screens/Editors/TeamEditorScreen.cs
  osu.Game.Tournament/Screens/Editors/TournamentEditorScreen.cs
  osu.Game/Graphics/UserInterface/BackButton.cs
Labels: area:tournament, size/M, type:UI

#9052 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#9048 Disallow catch-specific judgements in mania
  osu.Game.Rulesets.Mania/Scoring/ManiaHitWindows.cs
Labels: area:results, ruleset:osu!mania, size/S

#9053 Fix possible exceptions in performance calculators
  osu.Game.Rulesets.Catch/Difficulty/CatchPerformanceCalculator.cs
  osu.Game.Rulesets.Mania/Difficulty/ManiaPerformanceCalculator.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuPerformanceCalculator.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoPerformanceCalculator.cs
Labels: area:tooling, ruleset:osu!, ruleset:osu!catch, ruleset:osu!mania, ruleset:osu!taiko, size/M, type:reliability

#9023 Fix overlay section display highlighting wrong section
  osu.Game/Graphics/Containers/SectionsContainer.cs
Labels: area:overlay-user-profile, size/S, type:UI

#9055 Unify number types in performance calculators
  osu.Game.Rulesets.Catch/Difficulty/CatchPerformanceCalculator.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuPerformanceCalculator.cs
Labels: size/M

#9061 Fix being able to press enter to create matches
  osu.Game.Tests/Visual/Multiplayer/TestSceneMatchSettingsOverlay.cs
  osu.Game/Screens/Multi/Match/Components/MatchSettingsOverlay.cs
Labels: area:multiplayer, size/S

#9018 Allow disabling SkipOverlay through AllowGameplayOverlays.
  osu.Game.Tests/Visual/Gameplay/TestSceneSkipOverlay.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/SkipOverlay.cs
Labels: area:gameplay, size/M, type:UI

#9062 Convert dangerous events to IBindables
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Database/DownloadableArchiveModelManager.cs
  osu.Game/Database/IModelDownloader.cs
  osu.Game/Database/IModelManager.cs
  osu.Game/Online/DownloadTrackingComposite.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
  osu.Game/Screens/Multi/Match/Components/ReadyButton.cs
  osu.Game/Screens/Multi/Match/MatchSubScreen.cs
  osu.Game/Screens/Select/BeatmapCarousel.cs
  osu.Game/Screens/Select/Carousel/TopLocalRank.cs
  osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboard.cs
  osu.Game/Skinning/SkinManager.cs
Labels: size/L

#9057 Fix taiko rim markers incorrectly playing as whistle samples
  osu.Game.Rulesets.Taiko.Tests/TaikoBeatmapConversionTest.cs
  osu.Game.Rulesets.Taiko.Tests/TestSceneSampleOutput.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableHit.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableTaikoHitObject.cs
  osu.Game.Rulesets.Taiko/Resources/Testing/Beatmaps/sample-to-type-conversions-expected-conversion.json
  osu.Game.Rulesets.Taiko/Resources/Testing/Beatmaps/sample-to-type-conversions.osu
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Tests/Beatmaps/BeatmapConversionTest.cs
Labels: ruleset:osu!taiko, size/L

#9064 Add support for storyboard overlay layer
  osu.Game.Tests/Beatmaps/Formats/LegacyStoryboardDecoderTest.cs
  osu.Game/Beatmaps/Legacy/LegacyStoryLayer.cs
  osu.Game/Screens/Play/DimmableStoryboard.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboard.cs
  osu.Game/Storyboards/Storyboard.cs
  osu.Game/Storyboards/StoryboardLayer.cs
Labels: area:storyboard, size/M

#9068 Use DrawableSample in SkinnableSound class
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Skinning/SkinnableSound.cs
Labels: size/M, type:code-quality

#9075 Silence hitsounds during seek operations
  osu.Game.Rulesets.Taiko/UI/InputDrum.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Rulesets/UI/FrameStabilityContainer.cs
  osu.Game/Screens/Play/GameplayClock.cs
Labels: area:gameplay, size/M, type:UX

#9071 Seek to start of placed object, not end
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
Labels: area:editor, size/XS, type:UX

#9080 Fix display start time in sequential scroll algorithm
  osu.Game.Tests/ScrollAlgorithms/SequentialScrollTest.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneScrollingHitObjects.cs
  osu.Game/Rulesets/UI/Scrolling/Algorithms/SequentialScrollAlgorithm.cs
Labels: area:gameplay, ruleset:osu!mania, size/M

#9050 Eliminate floating point inaccuracies when generating bar lines
  osu.Game.Tests/NonVisual/BarLineGeneratorTest.cs
  osu.Game/Rulesets/Objects/BarLineGenerator.cs
Labels: area:gameplay, ruleset:osu!mania, ruleset:osu!taiko, size/M

#9070 Refactor editor snapping logic and add osu!mania beat snapping support
  osu.Game.Rulesets.Mania.Tests/ManiaPlacementBlueprintTestScene.cs
  osu.Game.Rulesets.Mania.Tests/ManiaSelectionBlueprintTestScene.cs
  osu.Game.Rulesets.Mania.Tests/TestSceneManiaHitObjectComposer.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/HoldNotePlacementBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/HoldNoteSelectionBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/ManiaPlacementBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/NotePlacementBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/IManiaHitObjectComposer.cs
  osu.Game.Rulesets.Mania/Edit/ManiaHitObjectComposer.cs
  osu.Game.Rulesets.Mania/Edit/ManiaSelectionHandler.cs
  osu.Game.Rulesets.Mania/Edit/ManiaSnapResult.cs
  osu.Game.Rulesets.Mania/UI/Column.cs
  osu.Game.Rulesets.Mania/UI/DrawableManiaRuleset.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneOsuDistanceSnapGrid.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/HitCircles/HitCirclePlacementBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointPiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderPlacementBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Spinners/SpinnerPlacementBlueprint.cs
  osu.Game.Tests/Visual/Editing/TestSceneDistanceSnapGrid.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Edit/IPositionSnapProvider.cs
  osu.Game/Rulesets/Edit/OverlaySelectionBlueprint.cs
  osu.Game/Rulesets/Edit/PlacementBlueprint.cs
  osu.Game/Rulesets/Edit/SelectionBlueprint.cs
  osu.Game/Rulesets/Edit/SnapResult.cs
  osu.Game/Rulesets/UI/Scrolling/ScrollingPlayfield.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
  osu.Game/Screens/Edit/Compose/Components/ComposeBlueprintContainer.cs
  osu.Game/Screens/Edit/Compose/Components/DistanceSnapGrid.cs
  osu.Game/Screens/Edit/Compose/Components/Timeline/Timeline.cs
  osu.Game/Screens/Edit/Compose/Components/Timeline/TimelineHitObjectBlueprint.cs
  osu.Game/Tests/Visual/PlacementBlueprintTestScene.cs
Labels: area:editor, size/XL, type:code-quality

#9089 Fix beatmap-online-lookup-queue potentially throwing on OsuGameTestScene
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/BeatmapManager_BeatmapOnlineLookupQueue.cs
  osu.Game/OsuGameBase.cs
Labels: size/S, type:testing

#9021 Implement beat snapping grid for mania's editor
  osu.Android.props
  osu.Game.Rulesets.Mania.Tests/TestSceneManiaBeatSnapGrid.cs
  osu.Game.Rulesets.Mania/Edit/ManiaBeatSnapGrid.cs
  osu.Game.Rulesets.Mania/Edit/ManiaHitObjectComposer.cs
  osu.Game.Rulesets.Mania/UI/Column.cs
  osu.Game.Rulesets.Mania/UI/Components/ColumnHitObjectArea.cs
  osu.Game.Rulesets.Mania/UI/ManiaPlayfield.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: area:editor, blocked, ruleset:osu!mania, size/L

#9101 Add the ability to export skins
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
  osu.Game/Skinning/SkinInfo.cs
Labels: area:database, size/M

#9096 Fix running osu.Game.Benchmarks
  osu.Game.Benchmarks/BenchmarkBeatmapParsing.cs
  osu.Game.Benchmarks/osu.Game.Benchmarks.csproj
Labels: size/XS, type:testing

#9088 Fix defaults not being applied correctly to blueprints after StartTime is changed
  osu.Game/Rulesets/Edit/PlacementBlueprint.cs
Labels: area:editor, size/XS

#9078 Move distance snap grid to osu! HitObjectComposer
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
Labels: area:editor, size/L, type:code-quality

#9083 Cache EditorClock as its own type
  osu.Game.Tests/Visual/Editing/TestScenePlaybackControl.cs
  osu.Game.Tests/Visual/Editing/TimelineTestScene.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Edit/PlacementBlueprint.cs
  osu.Game/Screens/Edit/Components/PlaybackControl.cs
  osu.Game/Screens/Edit/Components/TimeInfoContainer.cs
  osu.Game/Screens/Edit/Components/Timelines/Summary/Parts/MarkerPart.cs
  osu.Game/Screens/Edit/Components/Timelines/Summary/SummaryTimeline.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
  osu.Game/Screens/Edit/Compose/Components/Timeline/Timeline.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/EditorClock.cs
  osu.Game/Screens/Edit/Timing/TimingScreen.cs
  osu.Game/Tests/Visual/EditorClockTestScene.cs
  osu.Game/Tests/Visual/PlacementBlueprintTestScene.cs
Labels: area:editor, size/L, type:code-quality

#9084 Transform seeks in editor to allow for better visual context
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Screens/Edit/Components/Timelines/Summary/Parts/MarkerPart.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/EditorClock.cs
  osu.Game/Screens/Edit/Timing/TimingScreen.cs
Labels: area:editor, size/L, type:UX

#9102 Fix OpenInNativeExplorer not working correctly for wrapped storages
  osu.Android.props
  osu.Game/IO/WrappedStorage.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/S

#9107 Remove unnecessary size propagation in HitObjectComposer
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
Labels: area:editor, size/M, type:code-quality

#9033 Add cancellation token support to CreateNestedHitObjects()
  osu.Game.Rulesets.Catch/Objects/BananaShower.cs
  osu.Game.Rulesets.Catch/Objects/JuiceStream.cs
  osu.Game.Rulesets.Mania/Objects/HoldNote.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Rulesets.Taiko/Objects/DrumRoll.cs
  osu.Game.Rulesets.Taiko/Objects/Swell.cs
  osu.Game.Rulesets.Taiko/Objects/TaikoHitObject.cs
  osu.Game.Tests/Beatmaps/SliderEventGenerationTest.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Rulesets/Edit/PlacementBlueprint.cs
  osu.Game/Rulesets/Objects/HitObject.cs
  osu.Game/Rulesets/Objects/SliderEventGenerator.cs
Labels: area:beatmap, blocked, size/L, type:reliability

#9111 Fix test failures on TestSceneUserDimBackgrounds
  osu.Game.Tests/Visual/Background/TestSceneUserDimBackgrounds.cs
Labels: size/M, type:testing

#9112 Allow SelectionHandler to provide custom context menu items without local hover check
  osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs
Labels: area:editor, size/S, type:code-quality

#9108 Simplify scrolling ruleset editor implementation by adding base position support
  osu.Game.Rulesets.Mania.Tests/ManiaPlacementBlueprintTestScene.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/HoldNotePlacementBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/ManiaPlacementBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/ManiaSelectionBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/NotePlacementBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/ManiaHitObjectComposer.cs
  osu.Game.Rulesets.Mania/Edit/ManiaSnapResult.cs
  osu.Game.Rulesets.Mania/UI/Column.cs
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Edit/SnapResult.cs
  osu.Game/Rulesets/UI/Scrolling/ScrollingHitObjectContainer.cs
  osu.Game/Rulesets/UI/Scrolling/ScrollingPlayfield.cs
Labels: area:editor, size/L, type:code-quality

#9114 Allow HandleMovement by default
  osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs
Labels: area:editor, size/S, type:code-quality

#9126 Allow drag selections to occur from outside the playfield
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
Labels: area:editor, size/XS, type:UX

#9124 Hide non-alive selection blueprints by default
  osu.Game.Rulesets.Osu/Edit/Blueprints/OsuSelectionBlueprint.cs
  osu.Game/Rulesets/Edit/OverlaySelectionBlueprint.cs
Labels: area:editor, size/XS

#9125 Fix saving in the editor causing the current beatmap to change
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Database/IModelManager.cs
  osu.Game/Database/MutableDatabaseBackedStore.cs
  osu.Game/Online/DownloadTrackingComposite.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
  osu.Game/Screens/Multi/Match/Components/ReadyButton.cs
  osu.Game/Screens/Multi/Match/MatchSubScreen.cs
  osu.Game/Screens/Select/BeatmapCarousel.cs
  osu.Game/Screens/Select/Carousel/TopLocalRank.cs
Labels: area:database, size/M

#9135 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#9129 Remove necessity for custom mania interface caching
  osu.Game.Rulesets.Mania.Tests/ManiaPlacementBlueprintTestScene.cs
  osu.Game.Rulesets.Mania.Tests/ManiaSelectionBlueprintTestScene.cs
  osu.Game.Rulesets.Mania.Tests/TestSceneManiaBeatSnapGrid.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/HoldNotePlacementBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/Blueprints/ManiaSelectionBlueprint.cs
  osu.Game.Rulesets.Mania/Edit/IManiaHitObjectComposer.cs
  osu.Game.Rulesets.Mania/Edit/ManiaBeatSnapGrid.cs
  osu.Game.Rulesets.Mania/Edit/ManiaHitObjectComposer.cs
  osu.Game.Rulesets.Mania/Edit/ManiaSelectionHandler.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
Labels: size/L, type:code-quality

#9137 Fix minor typo in OsuGameBase
  osu.Game/OsuGameBase.cs
Labels: size/XS, type:code-quality

#9086 Implement contracted score panel and integrate into results screen
  osu.Game.Rulesets.Osu/Scoring/OsuScoreProcessor.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneReplayDownloadButton.cs
  osu.Game.Tests/Visual/Ranking/TestSceneContractedPanelMiddleContent.cs
  osu.Game.Tests/Visual/Ranking/TestSceneExpandedPanelMiddleContent.cs
  osu.Game.Tests/Visual/Ranking/TestSceneExpandedPanelTopContent.cs
  osu.Game.Tests/Visual/Ranking/TestSceneResultsScreen.cs
  osu.Game.Tests/Visual/Ranking/TestSceneScorePanel.cs
  osu.Game.Tests/Visual/Ranking/TestSceneScorePanelList.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/ReplayPlayer.cs
  osu.Game/Screens/Ranking/Contracted/ContractedPanelMiddleContent.cs
  osu.Game/Screens/Ranking/ReplayDownloadButton.cs
  osu.Game/Screens/Ranking/ResultsScreen.cs
  osu.Game/Screens/Ranking/ScorePanel.cs
  osu.Game/Screens/Ranking/ScorePanelList.cs
  osu.Game/Screens/Ranking/SoloResultsScreen.cs
  osu.Game/Screens/Select/PlaySongSelect.cs
  osu.Game/Tests/TestScoreInfo.cs
Labels: area:results, size/XXL

#9149 Fix searching by genre/language not working in beatmap listing overlay
  osu.Game/Online/API/Requests/SearchBeatmapSetsRequest.cs
  osu.Game/Overlays/BeatmapListing/BeatmapListingFilterControl.cs
Labels: area:overlay-beatmap-listing, size/S, type:network

#9160 Fix osu!mania stage-left and stage-right sprites incorrectly scaling horizontallly
  osu.Game.Rulesets.Mania.Tests/Resources/special-skin/mania-stage-left.png
  osu.Game.Rulesets.Mania.Tests/Resources/special-skin/mania-stage-right.png
  osu.Game.Rulesets.Mania/Skinning/LegacyStageBackground.cs
Labels: area:gameplay, ruleset:osu!mania, size/XS
