Repository ppy/osu, pull requests merged in 2020-09, with the labels that each got.

#10016 Add star rating to beatmap wedge
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
Labels: area:song-select, size/S

#9991 Add a very basic initial mania "notelock" implementation
  osu.Game.Rulesets.Mania.Tests/TestSceneOutOfOrderHits.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableHoldNote.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableManiaHitObject.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableNote.cs
  osu.Game.Rulesets.Mania/UI/Column.cs
  osu.Game.Rulesets.Mania/UI/OrderedHitPolicy.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
Labels: area:gameplay, ruleset:osu!mania, size/L

#10022 Do not attempt to complete spinners that are too short in autoplay
  osu.Game.Rulesets.Osu/Replays/OsuAutoGenerator.cs
Labels: area:replay, ruleset:osu!, size/XS

#10023 Revert "Add marker interface for beatmap skins"
  osu.Game.Rulesets.Osu.Tests/TestSceneLegacyBeatmapSkin.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneSkinFallbacks.cs
  osu.Game.Tests/Gameplay/TestSceneStoryboardSamples.cs
  osu.Game/Beatmaps/BeatmapManager_WorkingBeatmap.cs
  osu.Game/Beatmaps/IWorkingBeatmap.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Skinning/BeatmapSkinProvidingContainer.cs
  osu.Game/Skinning/DefaultBeatmapSkin.cs
  osu.Game/Skinning/IBeatmapSkin.cs
  osu.Game/Skinning/LegacyBeatmapSkin.cs
  osu.Game/Tests/Beatmaps/HitObjectSampleTest.cs
Labels: size/M

#10027 Fix potentially incorrect zoom level getting set on very short audio
  osu.Game/Screens/Edit/Compose/Components/Timeline/Timeline.cs
Labels: area:editor, size/XS, type:reliability

#10036 Fix possible nullref when unfocusing date text box in tourney
  osu.Game.Tournament.Tests/Components/TestSceneDateTextBox.cs
  osu.Game.Tournament/Components/DateTextBox.cs
Labels: area:tournament, size/M, type:crash

#9792 Move beatmap track into MusicController
  osu.Game.Rulesets.Osu.Tests/TestSceneSliderSnaking.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneSpinnerRotation.cs
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapEncoderTest.cs
  osu.Game.Tests/Gameplay/TestSceneGameplayClockContainer.cs
  osu.Game.Tests/Gameplay/TestSceneStoryboardSamples.cs
  osu.Game.Tests/Skins/TestSceneBeatmapSkinResources.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneCompletionCancellation.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneGameplayRewinding.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSkipOverlay.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneStoryboard.cs
  osu.Game.Tests/Visual/Menus/TestSceneIntroWelcome.cs
  osu.Game.Tests/Visual/Menus/TestSceneSongTicker.cs
  osu.Game.Tests/Visual/Navigation/TestSceneScreenNavigation.cs
  osu.Game.Tests/Visual/Online/TestSceneNowPlayingCommand.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneBeatSyncedContainer.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneDeleteLocalScore.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneNowPlayingOverlay.cs
  osu.Game.Tests/WaveformTestBeatmap.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/BeatmapManager_WorkingBeatmap.cs
  osu.Game/Beatmaps/DummyWorkingBeatmap.cs
  osu.Game/Beatmaps/IWorkingBeatmap.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Graphics/Containers/BeatSyncedContainer.cs
  osu.Game/OsuGame.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/Music/PlaylistOverlay.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Overlays/NowPlayingOverlay.cs
  osu.Game/Rulesets/Mods/IApplicableToTrack.cs
  osu.Game/Rulesets/Mods/ModDaycore.cs
  osu.Game/Rulesets/Mods/ModNightcore.cs
  osu.Game/Rulesets/Mods/ModRateAdjust.cs
  osu.Game/Rulesets/Mods/ModTimeRamp.cs
  osu.Game/Screens/Edit/Compose/Components/Timeline/Timeline.cs
  osu.Game/Screens/Edit/LegacyEditorBeatmapPatcher.cs
  osu.Game/Screens/Menu/IntroScreen.cs
  osu.Game/Screens/Menu/IntroTriangles.cs
  osu.Game/Screens/Menu/IntroWelcome.cs
  osu.Game/Screens/Menu/MainMenu.cs
  osu.Game/Screens/Menu/OsuLogo.cs
  osu.Game/Screens/Multi/Lounge/LoungeSubScreen.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Select/SongSelect.cs
  osu.Game/Tests/Beatmaps/BeatmapConversionTest.cs
  osu.Game/Tests/Beatmaps/TestWorkingBeatmap.cs
  osu.Game/Tests/Visual/OsuTestScene.cs
Labels: area:music-controller, size/XL

#10037 Add message box in bracket editor explaining how to get started
  osu.Game.Tournament/Screens/Editors/LadderEditorScreen.cs
  osu.Game.Tournament/TournamentGame.cs
  osu.Game.Tournament/WarningBox.cs
Labels: area:tournament, size/M, type:UX

#10038 Add smooth fading between audio tracks on transition
  osu.Game/Overlays/MusicController.cs
  osu.Game/Screens/Menu/IntroScreen.cs
Labels: size/S, type:audio

#10019 Add a bindable to OsuScreen to allow dynamically changing its OverlayActivation mode
  osu.Game.Tests/Visual/Menus/TestSceneToolbar.cs
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Toolbar/Toolbar.cs
  osu.Game/Screens/IOsuScreen.cs
  osu.Game/Screens/Menu/ButtonSystem.cs
  osu.Game/Screens/Menu/MainMenu.cs
  osu.Game/Screens/OsuScreen.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/StartupScreen.cs
Labels: area:overlays, size/M

#10043 Improve music fade on game exit
  osu.Game/Screens/Menu/IntroScreen.cs
Labels: size/S, type:audio

#10020 Add top user score to timeshift leaderboard
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapLeaderboard.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneUserTopScoreContainer.cs
  osu.Game/Online/API/Requests/Responses/APILegacyScores.cs
  osu.Game/Online/API/Requests/Responses/APIUserScoreAggregate.cs
  osu.Game/Online/Leaderboards/Leaderboard.cs
  osu.Game/Online/Leaderboards/UserTopScoreContainer.cs
  osu.Game/Online/Multiplayer/APILeaderboard.cs
  osu.Game/Online/Multiplayer/GetRoomLeaderboardRequest.cs
  osu.Game/Screens/Multi/Match/Components/MatchLeaderboard.cs
  osu.Game/Screens/Multi/Match/Components/MatchLeaderboardScore.cs
  osu.Game/Screens/Multi/Match/MatchSubScreen.cs
  osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboard.cs
Labels: area:multiplayer, size/L

#10044 Update toolbar icons and source titles from overlays directly
  osu.Game.Tests/Visual/Online/TestSceneFullscreenOverlay.cs
  osu.Game/Graphics/Containers/SectionsContainer.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/BeatmapListing/BeatmapListingHeader.cs
  osu.Game/Overlays/BeatmapListingOverlay.cs
  osu.Game/Overlays/BeatmapSet/BeatmapSetHeader.cs
  osu.Game/Overlays/BeatmapSetOverlay.cs
  osu.Game/Overlays/Changelog/ChangelogHeader.cs
  osu.Game/Overlays/ChangelogOverlay.cs
  osu.Game/Overlays/Chat/Selection/ChannelSelectionOverlay.cs
  osu.Game/Overlays/ChatOverlay.cs
  osu.Game/Overlays/Dashboard/DashboardOverlayHeader.cs
  osu.Game/Overlays/DashboardOverlay.cs
  osu.Game/Overlays/FullscreenOverlay.cs
  osu.Game/Overlays/INamedOverlayComponent.cs
  osu.Game/Overlays/News/NewsHeader.cs
  osu.Game/Overlays/NewsOverlay.cs
  osu.Game/Overlays/NotificationOverlay.cs
  osu.Game/Overlays/NowPlayingOverlay.cs
  osu.Game/Overlays/OverlayHeader.cs
  osu.Game/Overlays/OverlayScrollContainer.cs
  osu.Game/Overlays/OverlayTitle.cs
  osu.Game/Overlays/OverlayView.cs
  osu.Game/Overlays/Profile/ProfileHeader.cs
  osu.Game/Overlays/Rankings/RankingsOverlayHeader.cs
  osu.Game/Overlays/RankingsOverlay.cs
  osu.Game/Overlays/SearchableList/SearchableListFilterControl.cs
  osu.Game/Overlays/SearchableList/SearchableListHeader.cs
  osu.Game/Overlays/SearchableList/SearchableListOverlay.cs
  osu.Game/Overlays/Settings/Sidebar.cs
  osu.Game/Overlays/SettingsOverlay.cs
  osu.Game/Overlays/Toolbar/ToolbarBeatmapListingButton.cs
  osu.Game/Overlays/Toolbar/ToolbarButton.cs
  osu.Game/Overlays/Toolbar/ToolbarChangelogButton.cs
  osu.Game/Overlays/Toolbar/ToolbarChatButton.cs
  osu.Game/Overlays/Toolbar/ToolbarHomeButton.cs
  osu.Game/Overlays/Toolbar/ToolbarMusicButton.cs
  osu.Game/Overlays/Toolbar/ToolbarNewsButton.cs
  osu.Game/Overlays/Toolbar/ToolbarNotificationButton.cs
  osu.Game/Overlays/Toolbar/ToolbarOverlayToggleButton.cs
  osu.Game/Overlays/Toolbar/ToolbarRankingsButton.cs
  osu.Game/Overlays/Toolbar/ToolbarRulesetSelector.cs
  osu.Game/Overlays/Toolbar/ToolbarRulesetTabButton.cs
  osu.Game/Overlays/Toolbar/ToolbarSettingsButton.cs
  osu.Game/Overlays/Toolbar/ToolbarSocialButton.cs
  osu.Game/Overlays/UserProfileOverlay.cs
  osu.Game/Overlays/WaveOverlayContainer.cs
  osu.Game/Screens/Multi/Header.cs
  osu.Game/Screens/Multi/Lounge/LoungeSubScreen.cs
  osu.Game/Screens/Multi/Match/Components/MatchSettingsOverlay.cs
Labels: size/XL, type:UI

#10059 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#10060 Fix global mods being retained by rooms
  osu.Game.Tests/Visual/Multiplayer/TestSceneMatchSongSelect.cs
  osu.Game/Screens/Select/MatchSongSelect.cs
Labels: area:mods, size/S

#10045 Update and add missing beatmap statistic icons to info wedge
  osu.Android.props
  osu.Game.Rulesets.Catch/Beatmaps/CatchBeatmap.cs
  osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmap.cs
  osu.Game.Rulesets.Osu/Beatmaps/OsuBeatmap.cs
  osu.Game.Rulesets.Taiko/Beatmaps/TaikoBeatmap.cs
  osu.Game/Beatmaps/BeatmapStatistic.cs
  osu.Game/Beatmaps/BeatmapStatisticSprite.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: area:song-select, size/M, type:UI

#10058 Strongly type and expose default beatmap statistic icons for other rulesets
  osu.Game.Rulesets.Catch/Beatmaps/CatchBeatmap.cs
  osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmap.cs
  osu.Game.Rulesets.Osu/Beatmaps/OsuBeatmap.cs
  osu.Game.Rulesets.Taiko/Beatmaps/TaikoBeatmap.cs
  osu.Game/Beatmaps/BeatmapStatistic.cs
  osu.Game/Beatmaps/BeatmapStatisticIcon.cs
  osu.Game/Beatmaps/BeatmapStatisticSprite.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
Labels: size/M, type:code-quality

#10061 Fix potential hard crash if ruleset settings fail to construct
  osu.Game/Overlays/Settings/Sections/GameplaySection.cs
Labels: size/S, type:reliability

#10062 Fix MusicController raising track changed event twice
  osu.Game/Overlays/MusicController.cs
Labels: size/XS, type:UI

#10072 Make all toolbar tooltips lowercase
  osu.Game/Overlays/BeatmapListing/BeatmapListingHeader.cs
  osu.Game/Overlays/Changelog/ChangelogHeader.cs
  osu.Game/Overlays/Dashboard/DashboardOverlayHeader.cs
  osu.Game/Overlays/News/NewsHeader.cs
  osu.Game/Overlays/NotificationOverlay.cs
  osu.Game/Overlays/NowPlayingOverlay.cs
  osu.Game/Overlays/Rankings/RankingsOverlayHeader.cs
  osu.Game/Overlays/SettingsOverlay.cs
  osu.Game/Overlays/Toolbar/ToolbarHomeButton.cs
  osu.Game/Overlays/Toolbar/ToolbarRulesetTabButton.cs
Labels: area:toolbar, size/S, type:code-quality

#9957 Implement combo colour serializing
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapEncoderTest.cs
  osu.Game.Tests/Editing/LegacyEditorBeatmapPatcherTest.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/Formats/IHasCustomColours.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapEncoder.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/EditorBeatmap.cs
  osu.Game/Screens/Edit/EditorChangeHandler.cs
  osu.Game/Skinning/LegacyManiaSkinConfiguration.cs
  osu.Game/Skinning/SkinConfiguration.cs
Labels: area:beatmap, size/L

#10074 Hide the game-wide cursor on touch input
  osu.Game/Graphics/Cursor/MenuCursorContainer.cs
Labels: platform:mobile, size/XS, type:input

#9766 Disable activation of overlays while in gameplay
  osu.Game.Tests/Visual/Gameplay/TestSceneOverlayActivation.cs
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Screens/Menu/Disclaimer.cs
  osu.Game/Screens/Play/Player.cs
Labels: area:gameplay, size/M, type:UX

#10041 Bring legacy slider border width closer to osu!stable
  osu.Game.Rulesets.Osu/Skinning/LegacySliderBody.cs
Labels: area:skinning, size/XS

#10076 Avoid endless mania beatmap conversion
  osu.Game.Rulesets.Catch.Tests/CatchBeatmapConversionTest.cs
  osu.Game.Rulesets.Mania.Tests/ManiaBeatmapConversionTest.cs
  osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/DistanceObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/Resources/Testing/Beatmaps/zero-length-slider-expected-conversion.json
  osu.Game.Rulesets.Mania/Resources/Testing/Beatmaps/zero-length-slider.osu
  osu.Game.Rulesets.Osu.Tests/OsuBeatmapConversionTest.cs
  osu.Game.Rulesets.Taiko.Tests/TaikoBeatmapConversionTest.cs
Labels: area:beatmap, ruleset:osu!mania, size/M

#10064 Update class exclusion for dynamic compilation
  osu.Android.props
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game.Tests/Visual/Navigation/TestScenePresentScore.cs
  osu.Game/Beatmaps/BeatmapInfo.cs
  osu.Game/Beatmaps/BeatmapMetadata.cs
  osu.Game/Beatmaps/BeatmapSetInfo.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Input/GameIdleTracker.cs
  osu.Game/OsuGame.cs
  osu.Game/Rulesets/Mods/Mod.cs
  osu.Game/Rulesets/Ruleset.cs
  osu.Game/Rulesets/RulesetInfo.cs
  osu.Game/Screens/ScorePresentType.cs
  osu.Game/Tests/Visual/OsuTestScene.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/M, type:testing

#10077 Improve usability of BPM modifying in timing setup view
  osu.Game/Screens/Edit/Timing/TimingSection.cs
Labels: area:editor, size/M

#10080 Lowercase one more toolbar tooltip
  osu.Game/Overlays/ChatOverlay.cs
Labels: area:toolbar, size/XS, type:UI

#10047 Support creating new empty beatmaps
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/BeatmapManager_WorkingBeatmap.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/IO/WrappedStorage.cs
  osu.Game/Screens/Edit/Components/Menus/ScreenSelectionTabControl.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Menu/MainMenu.cs
Labels: area:editor, size/L

#10084 Avoid requiring sending the calling method for CleanRunHeadlessGameHost
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game.Tests/Scores/IO/ImportScoreTest.cs
  osu.Game/Tests/CleanRunHeadlessGameHost.cs
Labels: size/M, type:testing

#10086 Rename drag blueprint selection method for discoverability
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
Labels: size/XS, type:code-quality

#10088 Round the corners of dropdowns when expanded
  osu.Game/Graphics/UserInterface/OsuDropdown.cs
Labels: size/S, type:UI

#10089 Avoid multiple editor screens potentially loading on top of each other
  osu.Game/Screens/Edit/Editor.cs
Labels: area:editor, size/XS

#10090 Add basic metadata info editing support to editor
  osu.Game.Tests/Visual/Editing/TestSceneSetupScreen.cs
  osu.Game/Graphics/UserInterfaceV2/LabelledTextBox.cs
  osu.Game/Screens/Edit/EditorScreen.cs
  osu.Game/Screens/Edit/Setup/SetupScreen.cs
Labels: area:editor, size/L

#10063 Move OsuGame-dependent music functionalities outside of MusicController
  osu.Game.Tests/Visual/Menus/TestSceneMusicActionHandling.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneNowPlayingOverlay.cs
  osu.Game/OsuGame.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/Music/MusicKeyBindingHandler.cs
  osu.Game/Overlays/MusicController.cs
Labels: area:music-controller, size/L

#10087 Fix pause/play operation sometimes displaying incorrectly on OSD
  osu.Game/Overlays/Music/MusicKeyBindingHandler.cs
Labels: size/XS, type:UI

#10093 Fix editor crash on saving more than once
  osu.Game/Beatmaps/BeatmapManager.cs
Labels: area:editor, size/XS, type:reliability

#10100 Move title specification for settings groups to constructor
  osu.Game.Tests/Visual/Gameplay/TestSceneReplaySettingsOverlay.cs
  osu.Game.Tournament/Screens/Ladder/Components/LadderEditorSettings.cs
  osu.Game/Rulesets/Edit/ToolboxGroup.cs
  osu.Game/Screens/Play/PlayerSettings/CollectionSettings.cs
  osu.Game/Screens/Play/PlayerSettings/DiscussionSettings.cs
  osu.Game/Screens/Play/PlayerSettings/InputSettings.cs
  osu.Game/Screens/Play/PlayerSettings/PlaybackSettings.cs
  osu.Game/Screens/Play/PlayerSettings/PlayerSettingsGroup.cs
  osu.Game/Screens/Play/PlayerSettings/VisualSettings.cs
Labels: size/M, type:code-quality

#10103 Disable online beatmap lookups in tests
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/OsuGameBase.cs
Labels: area:beatmap, size/S, type:testing

#10105 Fix broken RollingCounter current value implementation
  osu.Game/Graphics/UserInterface/RollingCounter.cs
Labels: size/S

#10101 Add distance snap toggle (and support for future arbitrary composer toggles)
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Edit/ToolboxGroup.cs
Labels: area:editor, size/M

#10099 Add icons for editor toolbox tools
  osu.Game.Rulesets.Mania/Edit/HoldNoteCompositionTool.cs
  osu.Game.Rulesets.Mania/Edit/NoteCompositionTool.cs
  osu.Game.Rulesets.Osu/Edit/HitCircleCompositionTool.cs
  osu.Game.Rulesets.Osu/Edit/SliderCompositionTool.cs
  osu.Game.Rulesets.Osu/Edit/SpinnerCompositionTool.cs
  osu.Game.Rulesets.Taiko/Edit/DrumRollCompositionTool.cs
  osu.Game.Rulesets.Taiko/Edit/HitCompositionTool.cs
  osu.Game.Rulesets.Taiko/Edit/SwellCompositionTool.cs
  osu.Game.Tests/Visual/Editing/TestSceneEditorComposeRadioButtons.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Edit/Tools/HitObjectCompositionTool.cs
  osu.Game/Rulesets/Edit/Tools/SelectTool.cs
  osu.Game/Screens/Edit/Components/RadioButtons/DrawableRadioButton.cs
  osu.Game/Screens/Edit/Components/RadioButtons/RadioButton.cs
Labels: area:editor, size/M, type:UI

#10097 Fix overlay sound effects playing when open requested while disabled
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
Labels: size/S, type:UI

#10104 Fix leaderboard loading spinner disappearing too early
  osu.Game/Online/Leaderboards/Leaderboard.cs
Labels: area:song-select, size/XS

#10102 Prompt to save changes when exiting the editor
  osu.Game.Tests/Visual/Editing/TestSceneEditorChangeStates.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/EditorChangeHandler.cs
  osu.Game/Screens/Edit/PromptForSaveDialog.cs
  osu.Game/Tests/Beatmaps/TestBeatmap.cs
Labels: area:editor, size/L

#10079 Implement very primitive collection management (imports from stable)
  osu.Game.Tests/Collections/IO/ImportCollectionsTest.cs
  osu.Game.Tests/Resources/Collections/collections.db
  osu.Game.Tests/Visual/Collections/TestSceneManageCollectionsDialog.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneFilterControl.cs
  osu.Game/Collections/BeatmapCollection.cs
  osu.Game/Collections/CollectionManager.cs
  osu.Game/Collections/DeleteCollectionDialog.cs
  osu.Game/Collections/DrawableCollectionList.cs
  osu.Game/Collections/DrawableCollectionListItem.cs
  osu.Game/Collections/ManageCollectionsDialog.cs
  osu.Game/Graphics/Containers/OsuRearrangeableListContainer.cs
  osu.Game/Graphics/Containers/OsuRearrangeableListItem.cs
  osu.Game/Graphics/UserInterface/IconButton.cs
  osu.Game/Graphics/UserInterface/OsuContextMenu.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/GeneralSettings.cs
  osu.Game/Screens/Multi/DrawableRoomPlaylistItem.cs
  osu.Game/Screens/Select/Carousel/CarouselBeatmap.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmap.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmapSet.cs
  osu.Game/Screens/Select/CollectionFilterDropdown.cs
  osu.Game/Screens/Select/CollectionMenuItem.cs
  osu.Game/Screens/Select/FilterControl.cs
  osu.Game/Screens/Select/FilterCriteria.cs
Labels: area:database

#10116 Update framework
  osu.Android.props
  osu.Game.Rulesets.Osu/Statistics/AccuracyHeatmap.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/S

#10106 Implement dynamic score recalculation
  osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyAttributes.cs
  osu.Game.Rulesets.Mania/Difficulty/ManiaDifficultyCalculator.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyAttributes.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoDifficultyAttributes.cs
  osu.Game/Beatmaps/BeatmapDifficultyManager.cs
  osu.Game/Graphics/Sprites/GlowingSpriteText.cs
  osu.Game/Online/Leaderboards/LeaderboardScore.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/BeatmapSet/Scores/ScoreTable.cs
  osu.Game/Overlays/BeatmapSet/Scores/TopScoreStatisticsSection.cs
  osu.Game/Rulesets/Difficulty/DifficultyAttributes.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Scoring/ScoreManager.cs
  osu.Game/Screens/Ranking/Contracted/ContractedPanelMiddleContent.cs
  osu.Game/Screens/Ranking/Expanded/ExpandedPanelMiddleContent.cs
Labels: area:scoring, size/L

#10118 Fix hard crash on deleting a collection with no collection selected
  osu.Game/Screens/Select/FilterControl.cs
Labels: size/S, type:reliability

#10122 Fix maps with only bonus score having NaN scores
  osu.Game.Tests/Gameplay/TestSceneScoreProcessor.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
Labels: area:scoring, size/M

#10131 Import collections on initial import-from-stable step
  osu.Game/Screens/Select/ImportFromStablePopup.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: size/S

#10126 Fix drag handles not showing on now playing playlist items
  osu.Game.Tests/Visual/UserInterface/TestScenePlaylistOverlay.cs
  osu.Game/Graphics/Containers/OsuRearrangeableListItem.cs
Labels: area:overlay-nowplaying, size/M, type:UI

#10121 Fix song select filter ordering
  osu.Game/Screens/Select/FilterControl.cs
Labels: area:song-select, size/L, type:UI

#10082 Update section headers in ProfileOverlay in line with web
  osu.Game.Tests/Visual/Online/TestSceneProfileCounterPill.cs
  osu.Game.Tests/Visual/UserInterface/TestScenePaginatedContainerHeader.cs
  osu.Game/Overlays/Profile/ProfileSection.cs
  osu.Game/Overlays/Profile/Sections/Beatmaps/PaginatedBeatmapContainer.cs
  osu.Game/Overlays/Profile/Sections/BeatmapsSection.cs
  osu.Game/Overlays/Profile/Sections/CounterPill.cs
  osu.Game/Overlays/Profile/Sections/Historical/PaginatedMostPlayedBeatmapContainer.cs
  osu.Game/Overlays/Profile/Sections/HistoricalSection.cs
  osu.Game/Overlays/Profile/Sections/Kudosu/PaginatedKudosuHistoryContainer.cs
  osu.Game/Overlays/Profile/Sections/KudosuSection.cs
  osu.Game/Overlays/Profile/Sections/PaginatedContainer.cs
  osu.Game/Overlays/Profile/Sections/PaginatedContainerHeader.cs
  osu.Game/Overlays/Profile/Sections/Ranks/PaginatedScoreContainer.cs
  osu.Game/Overlays/Profile/Sections/RanksSection.cs
  osu.Game/Overlays/Profile/Sections/Recent/PaginatedRecentActivityContainer.cs
  osu.Game/Overlays/Profile/Sections/RecentSection.cs
Labels: area:overlay-user-profile, size/L, type:UI

#10137 Avoid editor confirm-save dialog looping infinitely when using keyboard shortcut to exit
  osu.Game/Screens/Edit/Editor.cs
Labels: area:editor, size/XS

#10138 Fix editor hitobjects getting masked weirdly
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
Labels: area:editor, size/M

#10134 Add collections filter to the now playing overlay
  osu.Game.Tests/Visual/SongSelect/TestSceneFilterControl.cs
  osu.Game/Collections/CollectionFilterDropdown.cs
  osu.Game/Collections/CollectionFilterMenuItem.cs
  osu.Game/Overlays/Music/CollectionDropdown.cs
  osu.Game/Overlays/Music/FilterControl.cs
  osu.Game/Overlays/Music/FilterCriteria.cs
  osu.Game/Overlays/Music/Playlist.cs
  osu.Game/Overlays/Music/PlaylistItem.cs
  osu.Game/Overlays/Music/PlaylistOverlay.cs
  osu.Game/Screens/Play/PlayerSettings/CollectionSettings.cs
  osu.Game/Screens/Select/FilterControl.cs
Labels: area:overlay-nowplaying, size/L

#10150 Fix anchoring for TeamHeader in TeamDisplay
  osu.Game.Tournament/Screens/Gameplay/Components/TeamDisplay.cs
Labels: area:tournament, size/XS, type:UI

#10139 Fix editor selected hitobjects containing the selection up to five times
  osu.Game.Tests/Visual/Editing/TestSceneEditorChangeStates.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
  osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs
Labels: area:editor, size/S

#10149 Fix mod select overlay absorbing input from toolbar ruleset selector
  osu.Game.Tests/Visual/Navigation/TestSceneScreenNavigation.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
Labels: area:song-select, size/S, type:input

#10152 Fix JSON serialization not working correctly for post-converted beatmaps
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Tests/Beatmaps/Formats/OsuJsonDecoderTest.cs
  osu.Game/Rulesets/Objects/Legacy/ConvertSlider.cs
  osu.Game/Rulesets/Objects/PathControlPoint.cs
  osu.Game/Rulesets/Objects/Types/IHasDuration.cs
Labels: area:beatmap, size/M

#10146 Ensure track is looping in song select immediately
  osu.Game/Screens/Select/SongSelect.cs
Labels: area:song-select, size/S, type:reliability

#10160 Add null check in SongSelect disposal for safety
  osu.Game/Screens/Select/SongSelect.cs
Labels: type:code-quality

#10161 Fix score present tests potentially succeeding a step when they shouldn't
  osu.Game.Tests/Visual/Navigation/TestScenePresentScore.cs
Labels: size/S, type:testing

#10156 Add manage collections button to beatmap options
  osu.Game.Tests/Visual/Navigation/TestSceneScreenNavigation.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapOptionsOverlay.cs
  osu.Game/Screens/Select/Options/BeatmapOptionsButton.cs
  osu.Game/Screens/Select/Options/BeatmapOptionsOverlay.cs
  osu.Game/Screens/Select/PlaySongSelect.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: area:song-select, size/L, type:UX

#9294 Apply morth's taiko SR changes
  osu.Game.Rulesets.Taiko.Tests/TaikoDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Taiko/Difficulty/Preprocessing/StaminaCheeseDetector.cs
  osu.Game.Rulesets.Taiko/Difficulty/Preprocessing/TaikoDifficultyHitObject.cs
  osu.Game.Rulesets.Taiko/Difficulty/Preprocessing/TaikoDifficultyHitObjectRhythm.cs
  osu.Game.Rulesets.Taiko/Difficulty/Skills/Colour.cs
  osu.Game.Rulesets.Taiko/Difficulty/Skills/Rhythm.cs
  osu.Game.Rulesets.Taiko/Difficulty/Skills/Stamina.cs
  osu.Game.Rulesets.Taiko/Difficulty/Skills/Strain.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoDifficultyAttributes.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoDifficultyCalculator.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoPerformanceCalculator.cs
  osu.Game.Tests/NonVisual/LimitedCapacityQueueTest.cs
  osu.Game/Rulesets/Difficulty/Utils/LimitedCapacityQueue.cs
Labels: area:difficulty, ruleset:osu!taiko, size/XXL

#10162 Fix mania scrollspeed slider precision
  osu.Game.Rulesets.Mania/Configuration/ManiaRulesetConfigManager.cs
  osu.Game.Rulesets.Mania/ManiaSettingsSubsection.cs
Labels: size/XS

#10140 Editor clipboard support
  osu.Android.props
  osu.Game.Tests/Beatmaps/TestSceneEditorBeatmap.cs
  osu.Game.Tests/Visual/Editing/TestSceneEditorChangeStates.cs
  osu.Game.Tests/Visual/Editing/TestSceneEditorClipboard.cs
  osu.Game/Screens/Edit/ClipboardContent.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/EditorBeatmap.cs
  osu.Game/Tests/Beatmaps/TestBeatmap.cs
  osu.Game/Tests/Visual/EditorTestScene.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: area:editor, size/L

#10159 Fix headless test storage misdirection
  osu.Game.Tests/Visual/Collections/TestSceneManageCollectionsDialog.cs
  osu.Game.Tests/Visual/Navigation/OsuGameTestScene.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneFilterControl.cs
  osu.Game/Tests/Visual/OsuTestScene.cs
Labels: size/M, type:testing

#10166 Remove beatmap paths from tests where they would result in exceptions
  osu.Game.Tests/Visual/Multiplayer/TestSceneMatchSongSelect.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
Labels: size/XS, type:testing

#10167 Fix potential nullref in FilterControl during asynchronous load
  osu.Game/Screens/Select/FilterControl.cs
Labels: size/M, type:testing

#10170 Remember leaderboard mods filter selection in song select
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Screens/Select/BeatmapDetailArea.cs
  osu.Game/Screens/Select/BeatmapDetailAreaTabControl.cs
  osu.Game/Screens/Select/PlayBeatmapDetailArea.cs
Labels: area:song-select, size/S, type:UX

#10163 Pause playback in present tests to avoid track inadvertently changing at menu
  osu.Game.Tests/Visual/Navigation/TestScenePresentBeatmap.cs
  osu.Game.Tests/Visual/Navigation/TestScenePresentScore.cs
Labels: size/S, type:testing

#10171 Fix global bindings being lost when running tests under headless contexts
  osu.Game/Tests/Visual/OsuTestScene.cs
Labels: size/S, type:testing

#10133 Determine uniqueness of legacy skins based on the author/name combo
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game.Tests/Skins/IO/ImportSkinTest.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Skinning/SkinManager.cs
Labels: area:database, area:skinning, size/L

#10173 Fix profile section tab control not absorbing input from behind
  osu.Game/Overlays/UserProfileOverlay.cs
Labels: area:overlay-user-profile, size/XS, type:input

#10179 Fix spinner not using cancellation token
  osu.Game.Rulesets.Osu/Objects/Spinner.cs
  osu.Game/Rulesets/Objects/HitObject.cs
Labels: ruleset:osu!, size/XS

#10180 Make beatmap conversion support cancellation tokens
  osu.Game.Rulesets.Catch/Beatmaps/CatchBeatmapConverter.cs
  osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs
  osu.Game.Rulesets.Osu/Beatmaps/OsuBeatmapConverter.cs
  osu.Game.Rulesets.Taiko/Beatmaps/TaikoBeatmapConverter.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneDrawableScrollingRuleset.cs
  osu.Game/Beatmaps/BeatmapConverter.cs
  osu.Game/Beatmaps/DummyWorkingBeatmap.cs
  osu.Game/Beatmaps/IBeatmapConverter.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
Labels: area:beatmap, area:ruleset-api, size/M

#10178 Fix potential endless taiko beatmap conversion
  osu.Game.Rulesets.Taiko/Beatmaps/TaikoBeatmapConverter.cs
Labels: area:beatmap, ruleset:osu!taiko, size/XS

#10182 Use new icon in chat overlay
  osu.Game/Overlays/ChatOverlay.cs
  osu.Game/Overlays/OverlayTitle.cs
Labels: area:overlay-chat, size/S, type:UI

#10186 Allow one hitobject in taiko conversion edge case
  osu.Game.Rulesets.Taiko/Beatmaps/TaikoBeatmapConverter.cs
Labels: area:beatmap, ruleset:osu!taiko, size/XS

#10185 Fix hovered tab items not showing hover state when deselected
  osu.Game/Graphics/UserInterface/OsuTabControl.cs
  osu.Game/Overlays/Chat/Tabs/ChannelTabItem.cs
Labels: area:overlay-chat, size/XS, type:UI

#10177 Fix import tests not waiting long enough before performing migration
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game.Tests/Collections/IO/ImportCollectionsTest.cs
  osu.Game.Tests/ImportTest.cs
  osu.Game.Tests/NonVisual/CustomDataDirectoryTest.cs
  osu.Game.Tests/Scores/IO/ImportScoreTest.cs
  osu.Game.Tests/Skins/IO/ImportSkinTest.cs
Labels: size/L, type:testing

#10188 Ensure BeatmapProcessor.PostProcess is run before firing HitObjectUpdated events
  osu.Game/Screens/Edit/EditorBeatmap.cs
Labels: area:editor, size/XS

#10191 Fix n^2 characteristic in taiko diffcalc
  osu.Game.Rulesets.Taiko/Difficulty/Preprocessing/StaminaCheeseDetector.cs
Labels: area:difficulty, ruleset:osu!taiko, size/S

#10193 Change collection deletion notification to be consistent
  osu.Game/Collections/CollectionManager.cs
Labels: area:overlay-notifications, size/XS, type:UI

#10198 Add mention of ruleset templates to readme
  README.md
Labels: size/XS, type:documentation

#10196 Add support for legacy miss & strong hit explosions
  osu.Game.Rulesets.Taiko.Tests/DrawableTestStrongHit.cs
  osu.Game.Rulesets.Taiko.Tests/Skinning/TestSceneHitExplosion.cs
  osu.Game.Rulesets.Taiko.Tests/TestSceneHits.cs
  osu.Game.Rulesets.Taiko/Skinning/TaikoLegacySkinTransformer.cs
  osu.Game.Rulesets.Taiko/TaikoSkinComponents.cs
  osu.Game.Rulesets.Taiko/UI/HitExplosion.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs
Labels: area:skinning, ruleset:osu!taiko, size/L

#9769 Add osu!catch-specific combo counter support
  osu.Game.Rulesets.Catch.Tests/Resources/old-skin/score-0.png
  osu.Game.Rulesets.Catch.Tests/Resources/old-skin/score-1.png
  osu.Game.Rulesets.Catch.Tests/Resources/old-skin/score-2.png
  osu.Game.Rulesets.Catch.Tests/Resources/old-skin/score-3.png
  osu.Game.Rulesets.Catch.Tests/Resources/old-skin/score-4.png
  osu.Game.Rulesets.Catch.Tests/Resources/old-skin/score-5.png
  osu.Game.Rulesets.Catch.Tests/Resources/old-skin/score-6.png
  osu.Game.Rulesets.Catch.Tests/Resources/old-skin/score-7.png
  osu.Game.Rulesets.Catch.Tests/Resources/old-skin/score-8.png
  osu.Game.Rulesets.Catch.Tests/Resources/old-skin/score-9.png
  osu.Game.Rulesets.Catch.Tests/Resources/special-skin/score-0@2x.png
  osu.Game.Rulesets.Catch.Tests/Resources/special-skin/score-1@2x.png
  osu.Game.Rulesets.Catch.Tests/Resources/special-skin/score-2@2x.png
  osu.Game.Rulesets.Catch.Tests/Resources/special-skin/score-3@2x.png
  osu.Game.Rulesets.Catch.Tests/Resources/special-skin/score-4@2x.png
  osu.Game.Rulesets.Catch.Tests/Resources/special-skin/score-5@2x.png
  osu.Game.Rulesets.Catch.Tests/Resources/special-skin/score-6@2x.png
  osu.Game.Rulesets.Catch.Tests/Resources/special-skin/score-7@2x.png
  osu.Game.Rulesets.Catch.Tests/Resources/special-skin/score-8@2x.png
  osu.Game.Rulesets.Catch.Tests/Resources/special-skin/score-9@2x.png
  osu.Game.Rulesets.Catch.Tests/TestSceneCatcherArea.cs
  osu.Game.Rulesets.Catch.Tests/TestSceneComboCounter.cs
  osu.Game.Rulesets.Catch/CatchSkinComponents.cs
  osu.Game.Rulesets.Catch/Skinning/CatchLegacySkinTransformer.cs
  osu.Game.Rulesets.Catch/Skinning/LegacyComboCounter.cs
  osu.Game.Rulesets.Catch/UI/CatchComboDisplay.cs
  osu.Game.Rulesets.Catch/UI/CatchPlayfield.cs
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
  osu.Game.Rulesets.Catch/UI/ICatchComboCounter.cs
  osu.Game.Rulesets.Osu/Skinning/OsuLegacySkinTransformer.cs
  osu.Game/Skinning/LegacyRollingCounter.cs
  osu.Game/Skinning/LegacySkinConfiguration.cs
  osu.Game/Skinning/LegacySkinExtensions.cs
  osu.Game/Tests/Visual/SkinnableTestScene.cs
Labels: area:skinning, ruleset:osu!catch

#10169 Fix gameplay samples potentially playing while player is paused
  osu.Game.Tests/Visual/Gameplay/TestSceneSkinnableSound.cs
  osu.Game/Skinning/SkinnableSound.cs
Labels: area:skinning, size/M, type:audio

#10208 Reduce complexity of AllHitObjects enumerator when nested playfields are not present
  osu.Game/Rulesets/UI/Playfield.cs
Labels: area:editor, size/S, type:performance

#10207 Reduce children levels in RingPiece
  osu.Game.Rulesets.Osu/Edit/Blueprints/Spinners/Components/SpinnerPiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/RingPiece.cs
Labels: size/M, type:code-quality

#10205 Fix compose mode not showing distance snap grid when entering with a selection
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
Labels: area:editor, size/XS

#10203 Fix fail animation breaking on post-fail judgements
  osu.Game/Screens/Play/FailAnimation.cs
Labels: area:gameplay, size/S

#10199 Fix bindings not correctly being cleaned up in OsuHitObjectComposer
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
Labels: area:editor, size/S, type:reliability

#10204 Add editor key bindings to switch between screens
  osu.Game/Input/Bindings/GlobalActionContainer.cs
  osu.Game/Overlays/KeyBinding/GlobalKeyBindingsSection.cs
  osu.Game/Screens/Edit/Editor.cs
Labels: area:editor, size/M, type:input

#10211 Fix editor not using beatmap combo colours initially on load
  osu.Game/Screens/Edit/EditorScreenWithTimeline.cs
  osu.Game/Skinning/BeatmapSkinProvidingContainer.cs
Labels: area:editor, size/M

#10213 Fix typo in log when beatmap fails to load
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Screens/Play/Player.cs
Labels: size/XS, type:documentation

#10212 Fix large construction/disposal overhead on beatmaps with hitobjects at same point in time
  osu.Game.Rulesets.Osu/Objects/Drawables/Connections/FollowPointRenderer.cs
Labels: area:gameplay, size/S, type:performance

#10214 Add the ability to toggle new combo state from composer context menu
  osu.Game.Tests/Gameplay/TestSceneHitObjectAccentColour.cs
  osu.Game/Rulesets/Objects/Types/IHasComboInformation.cs
  osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs
Labels: area:editor, size/M

#10216 Fix taiko change handling
  osu.Game.Rulesets.Taiko/Edit/TaikoSelectionHandler.cs
  osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs
Labels: area:editor, ruleset:osu!taiko, size/S

#10200 Fix HitObjectContainer not correctly unbinding from startTime fast enough
  osu.Game/Rulesets/UI/HitObjectContainer.cs
Labels: area:editor, size/S, type:reliability

#10218 Update framework
  osu.Android.props
  osu.Game.Tests/Visual/Online/TestSceneCommentsContainer.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/S

#10225 Fix extended statistics not being vertically centered
  osu.Game/Screens/Ranking/Statistics/StatisticsPanel.cs
Labels: area:results, size/XS

#10224 Add more descriptive description and download button when statistics not available
  osu.Game.Tests/Visual/Ranking/TestSceneResultsScreen.cs
  osu.Game/Screens/Ranking/Statistics/StatisticsPanel.cs
Labels: area:results, size/S

#10226 Fix score panel being incorrectly vertically aligned on screen resize
  osu.Game/Screens/Ranking/ResultsScreen.cs
  osu.Game/Screens/Ranking/ScorePanelList.cs
Labels: area:results, size/XS

#10227 Fix editor not showing sign when time goes negative
  osu.Game/Screens/Edit/Components/TimeInfoContainer.cs
Labels: area:editor, size/S, type:UI

#10230 Add ability to toggle editor toggles using keyboard shortcuts (Q~P)
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
Labels: area:editor, size/M

#10229 Fix rulesets disposing game-wide texture store
  osu.Game.Tests/Rulesets/TestSceneDrawableRulesetDependencies.cs
  osu.Game/Rulesets/UI/DrawableRulesetDependencies.cs
Labels: area:ruleset-api, size/L

#10232 Avoid destroying editor screens when changing between modes
  osu.Game/Screens/Edit/Compose/ComposeScreen.cs
  osu.Game/Screens/Edit/Design/DesignScreen.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/EditorScreen.cs
  osu.Game/Screens/Edit/EditorScreenWithTimeline.cs
  osu.Game/Screens/Edit/Setup/SetupScreen.cs
  osu.Game/Screens/Edit/Timing/TimingScreen.cs
Labels: area:editor, size/M

#10237 Fix missing HeadlessTest specification in new test
  osu.Game.Tests/Rulesets/TestSceneDrawableRulesetDependencies.cs
Labels: size/XS

#10231 Add editor object to object snapping
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneObjectObjectSnap.cs
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneOsuEditor.cs
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
Labels: area:editor, size/L

#10238 Fix hard crash on hitting an out of range key (Q~P)
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
Labels: size/XS

#10233 Add a basic file selector with extension filtering support
  osu.Game.Tests/Visual/Settings/TestSceneDirectorySelector.cs
  osu.Game.Tests/Visual/Settings/TestSceneFileSelector.cs
  osu.Game.Tournament/Screens/StablePathSelectScreen.cs
  osu.Game/Graphics/UserInterfaceV2/DirectorySelector.cs
  osu.Game/Graphics/UserInterfaceV2/FileSelector.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/MigrationSelectScreen.cs
Labels: size/L, type:UI

#10240 Ensure setup screen text boxes commit on losing focus
  osu.Game/Graphics/UserInterfaceV2/LabelledTextBox.cs
Labels: size/XS

#10217 Fix changing rim/strong types in taiko editor not applying correctly
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableHit.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableTaikoHitObject.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: area:editor, ruleset:osu!taiko, size/M

#10241 Rework ternary states to fix context menus not updating after already displayed
  osu.Game.Rulesets.Taiko/Edit/TaikoSelectionHandler.cs
  osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs
Labels: area:editor, size/L, type:code-quality

#10244 Avoid consuming keystrokes in editor when a modifier key is held down
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
Labels: area:editor, size/XS, type:input

#10239 Add new combo toggle to main compose interface
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/Edit/PlacementBlueprint.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
  osu.Game/Screens/Edit/Compose/Components/ComposeBlueprintContainer.cs
  osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs
Labels: area:editor, size/L, type:UX

#10246 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#10247 Forcefully re-apply DrawableHitObject state transforms on post-load DefaultsApplied
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
Labels: area:editor, size/XS

#10243 Add ternary toggle buttons to editor toolbox selection
  osu.Game.Rulesets.Osu/Edit/OsuHitObjectComposer.cs
  osu.Game/Audio/HitSampleInfo.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Screens/Edit/Components/TernaryButtons/DrawableTernaryButton.cs
  osu.Game/Screens/Edit/Components/TernaryButtons/TernaryButton.cs
  osu.Game/Screens/Edit/Compose/Components/ComposeBlueprintContainer.cs
  osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs
Labels: area:editor, size/L, type:UI

#10248 Move all ruleset editor tests to their own namespace
  osu.Game.Rulesets.Mania.Tests/Editor/ManiaPlacementBlueprintTestScene.cs
  osu.Game.Rulesets.Mania.Tests/Editor/ManiaSelectionBlueprintTestScene.cs
  osu.Game.Rulesets.Mania.Tests/Editor/TestSceneEditor.cs
  osu.Game.Rulesets.Mania.Tests/Editor/TestSceneHoldNotePlacementBlueprint.cs
  osu.Game.Rulesets.Mania.Tests/Editor/TestSceneHoldNoteSelectionBlueprint.cs
  osu.Game.Rulesets.Mania.Tests/Editor/TestSceneManiaBeatSnapGrid.cs
  osu.Game.Rulesets.Mania.Tests/Editor/TestSceneManiaHitObjectComposer.cs
  osu.Game.Rulesets.Mania.Tests/Editor/TestSceneNotePlacementBlueprint.cs
  osu.Game.Rulesets.Mania.Tests/Editor/TestSceneNoteSelectionBlueprint.cs
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneHitCirclePlacementBlueprint.cs
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneHitCircleSelectionBlueprint.cs
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneOsuDistanceSnapGrid.cs
  osu.Game.Rulesets.Osu.Tests/Editor/TestScenePathControlPointVisualiser.cs
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneSliderPlacementBlueprint.cs
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneSliderSelectionBlueprint.cs
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneSpinnerPlacementBlueprint.cs
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneSpinnerSelectionBlueprint.cs
  osu.Game.Rulesets.Taiko.Tests/Editor/TestSceneEditor.cs
  osu.Game.Rulesets.Taiko.Tests/Editor/TestSceneTaikoHitObjectComposer.cs
Labels: size/M, type:testing

#10234 Add audio track selection to editor setup screen
  osu.Game.Tests/Visual/Editing/TestSceneEditorBeatmapCreation.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Graphics/UserInterfaceV2/LabelledTextBox.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Screens/Edit/Components/BottomBarContainer.cs
  osu.Game/Screens/Edit/Components/PlaybackControl.cs
  osu.Game/Screens/Edit/Components/Timelines/Summary/Parts/TimelinePart.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/EditorClock.cs
  osu.Game/Screens/Edit/Setup/SetupScreen.cs
  osu.Game/Tests/Visual/EditorTestScene.cs
  osu.sln.DotSettings
Labels: area:editor, size/L

#10245 Add sample toggle buttons to toolbox
  osu.Game/Screens/Edit/Compose/Components/ComposeBlueprintContainer.cs
Labels: area:editor, size/M

#10250 Fix potential taiko crash on rewind
  osu.Game.Rulesets.Taiko.Tests/DrawableTestHit.cs
  osu.Game.Rulesets.Taiko.Tests/DrawableTestStrongHit.cs
  osu.Game.Rulesets.Taiko.Tests/Skinning/TestSceneHitExplosion.cs
  osu.Game.Rulesets.Taiko/UI/DefaultHitExplosion.cs
  osu.Game.Rulesets.Taiko/UI/HitExplosion.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs
Labels: ruleset:osu!taiko, size/M, type:testing

#10253 Fix HP drain edgecase potentially causing insta-fails
  osu.Game.Tests/Gameplay/TestSceneDrainingHealthProcessor.cs
  osu.Game/Rulesets/Scoring/DrainingHealthProcessor.cs
Labels: area:gameplay, size/M

#10259 Fix visual brokenness in taiko tests using DrawableTestHit
  osu.Game.Rulesets.Taiko.Tests/DrawableTestHit.cs
  osu.Game.Rulesets.Taiko.Tests/Skinning/TestSceneDrawableTaikoMascot.cs
  osu.Game.Rulesets.Taiko.Tests/Skinning/TestSceneHitExplosion.cs
  osu.Game.Rulesets.Taiko.Tests/TestSceneHits.cs
Labels: ruleset:osu!taiko, size/S, type:testing

#10260 Extract base taiko drawable ruleset scene
  osu.Game.Rulesets.Taiko.Tests/DrawableTaikoRulesetTestScene.cs
  osu.Game.Rulesets.Taiko.Tests/TestSceneHits.cs
Labels: ruleset:osu!taiko, size/L, type:testing

#10261 Fix drum rolls only spawning centre flying hits
  osu.Game.Rulesets.Taiko.Tests/TestSceneFlyingHits.cs
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableFlyingHit.cs
Labels: area:gameplay, ruleset:osu!taiko, size/M

#10265 Fix potential instability of overlay activation tests
  osu.Game.Tests/Visual/Gameplay/TestSceneOverlayActivation.cs
Labels: area:overlays, size/S, type:reliability, type:testing

#10254 Fix scroll container's scrollbar not respecting minimum size on first resize
  osu.Game/Graphics/Containers/OsuScrollContainer.cs
Labels: size/XS, type:UI

#10271 Avoid unnecessary object updates from SelectionHandlers
  osu.Game.Rulesets.Taiko/Edit/TaikoSelectionHandler.cs
  osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs
Labels: area:editor, size/S

#10275 Allow attaching a replay to a FrameStabilityContainer when FrameStablePlayback is off
  osu.Game/Rulesets/UI/FrameStabilityContainer.cs
Labels: area:replay, size/M

#10274 Fix autoplay generators failing on empty hitobjects lists
  osu.Game.Rulesets.Catch/Replays/CatchAutoGenerator.cs
  osu.Game.Rulesets.Mania/Replays/ManiaAutoGenerator.cs
  osu.Game.Rulesets.Osu/Replays/OsuAutoGenerator.cs
  osu.Game.Rulesets.Taiko/Replays/TaikoAutoGenerator.cs
Labels: area:replay, size/S

#10273 Trigger a hitobject update after blueprint drag ends
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
Labels: area:editor, size/XS

#10270 Avoid saving state changes if nothing has changed (via binary comparison)
  osu.Game.Tests/Editing/EditorChangeHandlerTest.cs
  osu.Game/Screens/Edit/EditorChangeHandler.cs
Labels: area:editor, size/M

#10277 Add autoplay support to editor
  osu.Game.Rulesets.Osu/Edit/DrawableOsuEditRuleset.cs
  osu.Game/Rulesets/Edit/DrawableEditRulesetWrapper.cs
  osu.Game/Rulesets/Edit/HitObjectComposer.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Screens/Edit/Compose/Components/ComposeBlueprintContainer.cs
Labels: area:editor, size/M

#10272 Fix new placement hitobjects in the editor not getting the default sample added
  osu.Game/Screens/Edit/Compose/Components/ComposeBlueprintContainer.cs
Labels: area:editor, size/XS

#10281 Fix sliders not dragging correctly after snaking has begun
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/SliderBodyPiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderSelectionBlueprint.cs
Labels: area:editor, size/XS

#10280 Fix extending spinners in editor causing them to disappear temporarily
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/DefaultSpinnerDisc.cs
  osu.Game.Rulesets.Osu/Skinning/LegacyNewStyleSpinner.cs
  osu.Game.Rulesets.Osu/Skinning/LegacyOldStyleSpinner.cs
Labels: area:editor, size/M

#10299 Standardise time display formats across the editor
  osu.Game/Extensions/EditorDisplayExtensions.cs
  osu.Game/Screens/Edit/Components/TimeInfoContainer.cs
  osu.Game/Screens/Edit/Timing/ControlPointTable.cs
Labels: area:editor, size/M, type:UX

#10201 Fix SPM changing incorrectly with playback rate changes
  osu.Game.Rulesets.Osu.Tests/TestSceneSpinnerRotation.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Pieces/SpinnerRotationTracker.cs
  osu.Game/Rulesets/UI/FrameStabilityContainer.cs
  osu.Game/Screens/Play/GameplayClock.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
Labels: area:gameplay, ruleset:osu!, size/M

#10305 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#10289 Improve the usability of the editor timeline with combo colour and indices
  osu.Game/Screens/Edit/Compose/Components/Timeline/TimelineHitObjectBlueprint.cs
  osu.Game/Screens/Edit/Compose/ComposeScreen.cs
Labels: area:editor, size/L, type:UI

#10302 Fix timing screen tests and add simple view of control points to timeline
  osu.Game.Tests/Visual/Editing/TestSceneTimingScreen.cs
  osu.Game/Screens/Edit/Compose/Components/Timeline/TimelineArea.cs
  osu.Game/Screens/Edit/EditorScreenWithTimeline.cs
  osu.Game/Screens/Edit/Timing/TimingScreen.cs
  osu.Game/Screens/Edit/Timing/TimingSection.cs
  osu.Game/Tests/Visual/EditorClockTestScene.cs
Labels: size/M, type:code-quality

#10282 Fix hit samples playing while paused / seeking in the editor
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs
  osu.Game.Rulesets.Taiko/Audio/DrumSampleContainer.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSkinnableSound.cs
  osu.Game/Rulesets/Mods/ModNightcore.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/EditorClock.cs
  osu.Game/Screens/Play/GameplayClock.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
  osu.Game/Screens/Play/ISamplePlaybackDisabler.cs
  osu.Game/Skinning/PausableSkinnableSound.cs
  osu.Game/Skinning/SkinnableSound.cs
Labels: area:editor, size/L

#10285 Fix storyboard samples not pausing
  osu.Game.Tests/Gameplay/TestSceneStoryboardSamples.cs
  osu.Game.Tests/Visual/Gameplay/TestScenePause.cs
  osu.Game/Rulesets/Mods/IApplicableToSample.cs
  osu.Game/Rulesets/Mods/ModRateAdjust.cs
  osu.Game/Rulesets/Mods/ModTimeRamp.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Skinning/SkinnableSound.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardSample.cs
Labels: area:storyboard, size/L, type:audio

#10304 Fix control point timeline display not updating with changes
  osu.Game/Screens/Edit/Components/Timelines/Summary/Parts/ControlPointPart.cs
  osu.Game/Screens/Edit/Components/Timelines/Summary/Parts/GroupVisualisation.cs
Labels: area:editor, size/L

#10268 Rework legacy taiko strong explosions to not require frame-perfect hits to show
  osu.Game.Rulesets.Taiko/Skinning/LegacyHitExplosion.cs
  osu.Game.Rulesets.Taiko/Skinning/TaikoLegacySkinTransformer.cs
  osu.Game.Rulesets.Taiko/TaikoSkinComponents.cs
  osu.Game.Rulesets.Taiko/UI/HitExplosion.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs
Labels: area:skinning, ruleset:osu!taiko, size/L
