Repository ppy/osu, pull requests merged in 2021-02, with the labels that each got.

#11626 Ensure spinners only handle input during their hittable time
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs
  osu.Game.Rulesets.Osu/Skinning/Default/SpinnerSpmCounter.cs
Labels: area:gameplay, ruleset:osu!, size/M

#11636 Fix incorrect speed change calculation in time ramp mods
  osu.Game.Tests/Rulesets/Mods/ModTimeRampTest.cs
  osu.Game/Rulesets/Mods/ModTimeRamp.cs
Labels: area:mods, size/L

#11561 Fix storyboard samples continuing to play when the beatmap is paused or intro is skipped
  osu.Game.Tests/Visual/Gameplay/TestSceneStoryboardSamplePlayback.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Skinning/PausableSkinnableSound.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardSample.cs
Labels: area:storyboard, size/L, type:audio

#11569 Fix a potential crash when exiting the editor before a new beatmap is added to the database
  osu.Game/Screens/Edit/Editor.cs
Labels: area:editor, size/S, type:crash

#11658 Make playlist settings area taller to better match screen aspect ratio
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsMatchSettingsOverlay.cs
Labels: area:playlists, size/XS

#11657 Fix PlaylistLoungeTestScene appearing very narrow
  osu.Game.Tests/Visual/Playlists/TestScenePlaylistsLoungeSubScreen.cs
Labels: size/XS, type:testing

#11637 Improve auto-scrolling logic for drawable channels
  osu.Game.Tests/Visual/Online/TestSceneStandAloneChatDisplay.cs
  osu.Game/Graphics/Containers/UserTrackingScrollContainer.cs
  osu.Game/Overlays/Chat/DrawableChannel.cs
Labels: area:overlay-chat, size/L, type:UX

#11640 Add ModUtils class for validating mod usages
  osu.Game.Tests.Android/osu.Game.Tests.Android.csproj
  osu.Game.Tests.iOS/osu.Game.Tests.iOS.csproj
  osu.Game.Tests/Mods/ModUtilsTest.cs
  osu.Game.Tests/osu.Game.Tests.csproj
  osu.Game/Utils/ModUtils.cs
Labels: area:mods, size/L

#11642 Fix invalid mod combinations potentially being selectable at a game level
  osu.Game.Tests/Mods/ModUtilsTest.cs
  osu.Game/OsuGame.cs
  osu.Game/Utils/ModUtils.cs
Labels: area:mods, size/M

#11662 Refactor mod sections and make them overridable
  osu.Game/Overlays/Mods/ModSection.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Overlays/Mods/Sections/AutomationSection.cs
  osu.Game/Overlays/Mods/Sections/ConversionSection.cs
  osu.Game/Overlays/Mods/Sections/DifficultyIncreaseSection.cs
  osu.Game/Overlays/Mods/Sections/DifficultyReductionSection.cs
  osu.Game/Overlays/Mods/Sections/FunSection.cs
Labels: area:mods, size/L, type:UI

#11659 Improve appearance of playlist items display
  osu.Game.Tests/Visual/Multiplayer/TestSceneDrawableRoomPlaylist.cs
  osu.Game/Graphics/UserInterface/DownloadButton.cs
  osu.Game/Graphics/UserInterface/GrayButton.cs
  osu.Game/Screens/OnlinePlay/DrawableRoomPlaylistItem.cs
Labels: area:playlists, size/L

#11667 Fix ModIcon not updating background colour correctly
  osu.Game.Tests/Visual/UserInterface/TestSceneModIcon.cs
  osu.Game/Rulesets/UI/ModIcon.cs
Labels: area:mods, size/M, type:UI

#11663 Allow mod buttons to not be stacked
  osu.Game.Tests/Visual/UserInterface/TestSceneModSelectOverlay.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
Labels: area:mods, size/M, type:UI

#11632 Fix ongoing operation tracker double-returning internal lease after screen exit
  osu.Game.Tests/NonVisual/OngoingOperationTrackerTest.cs
  osu.Game/Screens/OnlinePlay/OngoingOperationTracker.cs
Labels: area:multiplayer, size/M, type:reliability

#11664 Make it possible to change IsValidMod in mod selection
  osu.Game.Tests/Visual/UserInterface/TestSceneModSelectOverlay.cs
  osu.Game/Overlays/Mods/ModSection.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSongSelect.cs
  osu.Game/Screens/Select/MatchSongSelect.cs
Labels: area:mods, size/L

#11665 Move incompatible mod deselection into SoloModSelectOverlay
  osu.Game.Tests/Visual/UserInterface/TestSceneModSelectOverlay.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneModSettings.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Overlays/Mods/SoloModSelectOverlay.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSongSelect.cs
  osu.Game/Screens/Select/MatchSongSelect.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: area:mods, size/M

#11673 Add custom MessagePack resolver for mod settings dictionary
  osu.Game.Tests/Online/TestAPIModJsonSerialization.cs
  osu.Game.Tests/Online/TestAPIModMessagePackSerialization.cs
  osu.Game/Online/API/APIMod.cs
  osu.Game/Online/API/ModSettingsDictionaryFormatter.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/L

#11666 Implement the freemod selection overlay
  osu.Game.Tests/Visual/Multiplayer/TestSceneFreeModSelectOverlay.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneModSelectOverlay.cs
  osu.Game/Graphics/UserInterface/OsuCheckbox.cs
  osu.Game/Overlays/Mods/ModSection.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Screens/OnlinePlay/FreeModSelectOverlay.cs
Labels: area:mods, size/L

#11670 Implement mania constant speed mod
  osu.Game.Rulesets.Mania.Tests/Mods/TestSceneManiaModConstantSpeed.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModConstantSpeed.cs
  osu.Game.Rulesets.Mania/UI/DrawableManiaRuleset.cs
  osu.Game/Rulesets/UI/Scrolling/DrawableScrollingRuleset.cs
Labels: area:mods, ruleset:osu!mania, size/M

#11677 Fix readme version badge not linking to correct page
  README.md
Labels: size/XS, type:documentation

#11676 Fix codefactor style issues
  osu.Game.Rulesets.Catch/Skinning/Default/BorderPiece.cs
  osu.Game.Rulesets.Catch/Skinning/Default/HyperBorderPiece.cs
Labels: size/XS, type:code-quality

#11675 Remove old alpha hack from nub fill
  osu.Game/Graphics/UserInterface/Nub.cs
Labels: size/XS, type:code-quality

#11515 Add beatmap availability tracker component for multiplayer and playlists
  osu.Game.Tests/Online/TestSceneOnlinePlayBeatmapAvailabilityTracker.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Online/API/APIDownloadRequest.cs
  osu.Game/Online/API/ArchiveDownloadRequest.cs
  osu.Game/Online/DownloadTrackingComposite.cs
  osu.Game/Online/Rooms/BeatmapAvailability.cs
  osu.Game/Online/Rooms/OnlinePlayBeatmapAvailablilityTracker.cs
  osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
Labels: area:multiplayer, area:playlists, size/L

#11641 Add support for optional per-user mods in multiplayer (aka freemod)
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerParticipantsList.cs
  osu.Game.Tests/Visual/Multiplayer/TestScenePlaylistsSongSelect.cs
  osu.Game/Online/Multiplayer/IMultiplayerClient.cs
  osu.Game/Online/Multiplayer/IMultiplayerRoomServer.cs
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
  osu.Game/Online/Multiplayer/MultiplayerRoomSettings.cs
  osu.Game/Online/Multiplayer/MultiplayerRoomUser.cs
  osu.Game/Online/Multiplayer/StatefulMultiplayerClient.cs
  osu.Game/Screens/OnlinePlay/FooterButtonFreeMods.cs
  osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSongSelect.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Participants/ParticipantPanel.cs
  osu.Game/Screens/OnlinePlay/OnlinePlaySongSelect.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsRoomSubScreen.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsSongSelect.cs
  osu.Game/Screens/Select/Footer.cs
  osu.Game/Screens/Select/SongSelect.cs
  osu.Game/Tests/Visual/Multiplayer/TestMultiplayerClient.cs
Labels: area:multiplayer, size/XL

#11516 Replace ready button beatmap logic with using `MultiplayerBeatmapTracker` instead
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerReadyButton.cs
  osu.Game/Screens/OnlinePlay/Components/ReadyButton.cs
  osu.Game/Screens/OnlinePlay/Match/Components/Footer.cs
  osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Match/MultiplayerMatchFooter.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Match/MultiplayerReadyButton.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsReadyButton.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsRoomSubScreen.cs
Labels: area:multiplayer, size/L

#11681 Fix crashes when setting a mod in free mod select overlay which requires deselection of another mod
  osu.Game.Tests/Visual/UserInterface/TestSceneModSelectOverlay.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneModSettings.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Mods/LocalPlayerModSelectOverlay.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs
  osu.Game/Screens/OnlinePlay/OnlinePlaySongSelect.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: size/S

#11684 Fix mods on participant panels flashing when changed
  osu.Game/Screens/OnlinePlay/Multiplayer/Participants/ParticipantPanel.cs
Labels: area:multiplayer, size/S, type:UI

#11661 Add support for setting the maximum attempt count for a playlist
  osu.Game/Screens/OnlinePlay/Components/ModeTypeInfo.cs
  osu.Game/Screens/OnlinePlay/Components/RoomLocalUserInfo.cs
  osu.Game/Screens/OnlinePlay/Lounge/Components/ParticipantInfo.cs
  osu.Game/Screens/OnlinePlay/Lounge/Components/RoomInfo.cs
  osu.Game/Screens/OnlinePlay/OnlinePlayComposite.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsMatchSettingsOverlay.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsPlayer.cs
Labels: area:playlists, size/L

#11698 Fix player loader metadata not being centred
  osu.Game/Screens/Play/BeatmapMetadataDisplay.cs
Labels: size/M, type:UI

#11565 Rewrite connection logic to better handle failure cases
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
Labels: area:multiplayer, size/L

#11552 Fix being able to set zero or negative hitobject duration via timeline
  osu.Game.Tests/Visual/Editing/TestSceneTimelineHitObjectBlueprint.cs
  osu.Game.Tests/Visual/Editing/TimelineTestScene.cs
  osu.Game/Screens/Edit/Compose/Components/Timeline/TimelineHitObjectBlueprint.cs
Labels: area:editor, size/M

#11680 Make pausing on window focus loss instantaneous
  osu.Game/Screens/Play/BreakTracker.cs
  osu.Game/Screens/Play/HUD/HoldForMenuButton.cs
  osu.Game/Screens/Play/Player.cs
Labels: area:gameplay, size/M

#11701 Disable failing test temporarily pending resolution
  osu.Game.Tests/Visual/Multiplayer/TestScenePlaylistsSongSelect.cs
Labels: size/XS

#11702 Fix incorrect multiplayer connection building
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
Labels: area:multiplayer, size/M, type:online

#11551 Fix client potentially not leaving a room on exiting multiplayer
  osu.Game.Tests/NonVisual/TaskChainTest.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerRoomManager.cs
  osu.Game/Extensions/TaskExtensions.cs
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
  osu.Game/Online/Multiplayer/StatefulMultiplayerClient.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerRoomManager.cs
  osu.Game/Tests/Visual/Multiplayer/MultiplayerTestScene.cs
  osu.Game/Tests/Visual/Multiplayer/TestMultiplayerClient.cs
  osu.Game/Utils/TaskChain.cs
Labels: area:multiplayer, size/L

#11703 Fix attributes header not being aligned with content in editor timing mode
  osu.Game/Screens/Edit/Timing/ControlPointTable.cs
Labels: area:editor, size/XS, type:UI

#11495 Make most common BPM more accurate
  osu.Game/Beatmaps/Beatmap.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/ControlPoints/ControlPointInfo.cs
  osu.Game/Beatmaps/IBeatmap.cs
  osu.Game/Screens/Edit/EditorBeatmap.cs
  osu.Game/Screens/Play/GameplayBeatmap.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
Labels: area:beatmap, size/M

#11705 Fix missing using
  osu.Game/Online/Multiplayer/StatefulMultiplayerClient.cs
Labels: size/XS, type:code-quality

#11706 Fix failing test
  osu.Game/Screens/Play/Player.cs
Labels: size/XS, type:testing

#11679 Refactor osu! ruleset hit policies for extensibility
  osu.Game.Rulesets.Osu.Tests/TestSceneStartTimeOrderedHitPolicy.cs
  osu.Game.Rulesets.Osu/UI/IHitPolicy.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game.Rulesets.Osu/UI/StartTimeOrderedHitPolicy.cs
  osu.Game/Rulesets/UI/HitObjectContainer.cs
  osu.Game/Rulesets/UI/IHitObjectContainer.cs
Labels: ruleset:osu!, size/M, type:code-quality

#11707 Fix editor effect attribute tooltip having unnecessary whitespace when only one is enabled
  osu.Game/Screens/Edit/Timing/ControlPointTable.cs
Labels: area:editor, size/XS, type:UI

#11527 Implement OnlineOverlay component
  osu.Game.Tests/Visual/Online/TestSceneFullscreenOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneRankingsOverlay.cs
  osu.Game/Overlays/BeatmapListingOverlay.cs
  osu.Game/Overlays/BeatmapSetOverlay.cs
  osu.Game/Overlays/ChangelogOverlay.cs
  osu.Game/Overlays/DashboardOverlay.cs
  osu.Game/Overlays/FullscreenOverlay.cs
  osu.Game/Overlays/NewsOverlay.cs
  osu.Game/Overlays/OnlineOverlay.cs
  osu.Game/Overlays/RankingsOverlay.cs
  osu.Game/Overlays/TabbableOnlineOverlay.cs
  osu.Game/Overlays/UserProfileOverlay.cs
Labels: area:overlays, size/XL, type:code-quality

#11712 Fix AutoPilot mod failing to block touch input
  osu.Game.Rulesets.Osu/OsuInputManager.cs
Labels: size/XS

#11716 Defer playlist load to improve load time of the now playing overlay
  osu.Game/Overlays/NowPlayingOverlay.cs
Labels: size/M, type:performance

#11530 Add UI state display for multiplayer client's beatmap availability
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerParticipantsList.cs
  osu.Game/Graphics/UserInterface/ProgressBar.cs
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
  osu.Game/Online/Rooms/OnlinePlayBeatmapAvailablilityTracker.cs
  osu.Game/Overlays/BeatmapListing/Panels/DownloadProgressBar.cs
  osu.Game/Overlays/NowPlayingOverlay.cs
  osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Participants/ParticipantPanel.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Participants/StateDisplay.cs
Labels: area:multiplayer, size/L, type:UI

#11718 Fix incorrect header depth in OnlineOverlay
  osu.Game/Overlays/OnlineOverlay.cs
Labels: size/XS

#11710 Fix incorrect mod copying behaviour when settings arrive from external change
  osu.Game.Tests/Visual/Multiplayer/TestScenePlaylistsSongSelect.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneModSelectOverlay.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/Mods/ModButton.cs
  osu.Game/Overlays/Mods/ModSection.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Rulesets/Mods/Mod.cs
  osu.Game/Rulesets/Mods/ModDifficultyAdjust.cs
Labels: area:mods, size/L

#11726 Add Messagepack support for serialising unknown bindable types
  osu.Game.Tests/Online/TestAPIModMessagePackSerialization.cs
  osu.Game/Online/API/ModSettingsDictionaryFormatter.cs
Labels: area:mods, size/M, type:online

#11733 Update resources with new samples
  osu.Android.props
  osu.Game.Tests/Visual/UserInterface/TestSceneNotificationOverlay.cs
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
  osu.Game/Graphics/UserInterface/HoverSounds.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/DialogOverlay.cs
  osu.Game/Overlays/Notifications/Notification.cs
  osu.Game/Overlays/Notifications/NotificationSection.cs
  osu.Game/Overlays/Notifications/ProgressNotification.cs
  osu.Game/Overlays/Notifications/SimpleErrorNotification.cs
  osu.Game/Overlays/NowPlayingOverlay.cs
  osu.Game/Overlays/OSD/TrackedSettingToast.cs
  osu.Game/Overlays/SettingsPanel.cs
  osu.Game/Overlays/Toolbar/ToolbarButton.cs
  osu.Game/Overlays/WaveOverlayContainer.cs
  osu.Game/Screens/Menu/OsuLogo.cs
  osu.Game/Screens/Select/Carousel/CarouselHeader.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/L, type:audio

#11719 Allow overlays to override generic pop-in/pop-out samples (and specify new samples for certain overlays)
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
  osu.Game/Overlays/DialogOverlay.cs
  osu.Game/Overlays/NowPlayingOverlay.cs
  osu.Game/Overlays/SettingsPanel.cs
  osu.Game/Overlays/WaveOverlayContainer.cs
Labels: size/S, type:UI, type:audio

#11721 Add pitch randomisation to HoverSounds' on-hover sample playback
  osu.Game/Graphics/UserInterface/HoverSounds.cs
Labels: size/S, type:audio

#11722 Use a separate sample set for Toolbar buttons
  osu.Game/Graphics/UserInterface/HoverSounds.cs
  osu.Game/Overlays/Toolbar/ToolbarButton.cs
Labels: size/XS, type:audio

#11723 Replace CarouselHeader's multiple on-hover samples with a single one
  osu.Game/Screens/Select/Carousel/CarouselHeader.cs
Labels: size/XS, type:audio

#11724 Use alternate sample on the downbeat while hovering OsuLogo
  osu.Game/Screens/Menu/OsuLogo.cs
Labels: size/S, type:audio

#11729 Add audio feedback for OSD value changes
  osu.Game/Overlays/OSD/TrackedSettingToast.cs
Labels: size/M, type:audio

#11732 Add sounds to notifications
  osu.Game.Tests/Visual/UserInterface/TestSceneNotificationOverlay.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Notifications/Notification.cs
  osu.Game/Overlays/Notifications/NotificationSection.cs
  osu.Game/Overlays/Notifications/ProgressNotification.cs
  osu.Game/Overlays/Notifications/SimpleErrorNotification.cs
Labels: size/M

#11720 Use unique sample for edit button click (ButtonSystem)
  osu.Game/Screens/Menu/ButtonSystem.cs
Labels: size/XS, type:UI, type:audio

#11725 Add local user customisation for freemod mod settings
  osu.Game/Configuration/ModSettingChangeTracker.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Screens/OnlinePlay/FreeModSelectOverlay.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSongSelect.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs
  osu.Game/Screens/Select/Details/AdvancedStats.cs
Labels: area:multiplayer, size/L

#11734 Prevent the default on-click sample from playing for OsuCheckbox
  osu.Game/Graphics/UserInterface/OsuCheckbox.cs
Labels: size/XS

#11133 Allow ModDifficultyAdjustment to extend beyond the sane limits of the game
  osu.Game.Rulesets.Catch/Mods/CatchModDifficultyAdjust.cs
  osu.Game.Rulesets.Osu/Mods/OsuModDifficultyAdjust.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/Connections/FollowPointConnection.cs
  osu.Game.Rulesets.Osu/Objects/OsuHitObject.cs
  osu.Game.Tests/Online/TestAPIModJsonSerialization.cs
  osu.Game/Rulesets/Mods/ModDifficultyAdjust.cs
Labels: area:mods, size/L

#11683 Add classic mod for the osu! ruleset
  osu.Game.Rulesets.Osu.Tests/TestSceneObjectOrderedHitPolicy.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderCircleSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Judgements/SliderTickJudgement.cs
  osu.Game.Rulesets.Osu/Mods/OsuModClassic.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableHitCircle.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuJudgement.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderHead.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Rulesets.Osu/Objects/SliderHeadCircle.cs
  osu.Game.Rulesets.Osu/Objects/SliderTick.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Osu/Skinning/Default/PlaySliderBody.cs
  osu.Game.Rulesets.Osu/Skinning/Default/SliderBall.cs
  osu.Game.Rulesets.Osu/UI/ObjectOrderedHitPolicy.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
Labels: area:mods, ruleset:osu!, size/XL

#11697 Adjust osu! autoplay generation to ensure constant SPM with rate-changing mods
  osu.Game.Rulesets.Catch/Mods/CatchModAutoplay.cs
  osu.Game.Rulesets.Catch/Mods/CatchModCinema.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModAutoplay.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModCinema.cs
  osu.Game.Rulesets.Osu.Tests/Mods/TestSceneOsuModAutoplay.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneMissHitWindowJudgements.cs
  osu.Game.Rulesets.Osu/Mods/OsuModAutopilot.cs
  osu.Game.Rulesets.Osu/Mods/OsuModAutoplay.cs
  osu.Game.Rulesets.Osu/Mods/OsuModCinema.cs
  osu.Game.Rulesets.Osu/Replays/OsuAutoGenerator.cs
  osu.Game.Rulesets.Osu/Replays/OsuAutoGeneratorBase.cs
  osu.Game.Rulesets.Taiko/Mods/TaikoModAutoplay.cs
  osu.Game.Rulesets.Taiko/Mods/TaikoModCinema.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneReplay.cs
  osu.Game/Rulesets/Mods/IApplicableToRate.cs
  osu.Game/Rulesets/Mods/ModAutoplay.cs
  osu.Game/Rulesets/Mods/ModCinema.cs
  osu.Game/Rulesets/Mods/ModRateAdjust.cs
  osu.Game/Rulesets/Mods/ModTimeRamp.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
Labels: area:mods, ruleset:osu!, size/L

#11741 Update resources
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#11739 Display descriptions in tooltips of mod settings adjustments
  osu.Game/Configuration/SettingSourceAttribute.cs
  osu.Game/Overlays/Settings/SettingsItem.cs
Labels: size/S, type:UI

#11735 Decrease the game-wide track playback volume to give samples some head-room
  osu.Game/OsuGameBase.cs
Labels: size/XS, type:audio

#11748 Fix hover sounds playing too often
  osu.Game/Graphics/UserInterface/HoverSampleDebounceComponent.cs
  osu.Game/Graphics/UserInterface/HoverSounds.cs
  osu.Game/Screens/Select/Carousel/CarouselHeader.cs
Labels: size/L

#11740 Fix newly placed sliders in the editor not playing hitsounds
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game/Rulesets/Edit/PlacementBlueprint.cs
  osu.Game/Screens/Edit/Compose/Components/ComposeBlueprintContainer.cs
Labels: size/S

#11757 Fix osu-web beatmap links not linking to specific beatmap
  osu.Game.Tests/Chat/MessageFormatterTests.cs
  osu.Game/Online/Chat/MessageFormatter.cs
Labels: size/M

#11755 Fix MessageFormatter not working for custom endpoints
  osu.Game.Tests/Visual/Online/TestSceneChatLink.cs
  osu.Game/Online/Chat/MessageFormatter.cs
  osu.Game/OsuGameBase.cs
Labels: area:overlay-chat, size/M

#11758 Fix header background being invisible in multiplayer/playlists
  osu.Game/Beatmaps/Drawables/UpdateableBeatmapBackgroundSprite.cs
Labels: area:multiplayer, area:playlists, size/XS, type:UI

#11759 Show URLs in tooltips when custom text has replaced the link
  osu.Game/Graphics/Containers/LinkFlowContainer.cs
Labels: area:overlay-chat, size/XS

#11603 Handle beatmap import from a stable installation with a custom Songs directory
  osu.Desktop/OsuGameDesktop.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/IO/StableStorage.cs
  osu.Game/OsuGame.cs
  osu.Game/Scoring/ScoreManager.cs
Labels: area:settings, size/L

#11761 Fix classic "welcome" intro not looping as expected
  osu.Game/Screens/Menu/IntroWelcome.cs
Labels: size/XS, type:UI

#11766 Set static locally in test to ensure tests always run correctly
  osu.Game.Tests/Chat/MessageFormatterTests.cs
Labels: size/S

#11771 Fix mod settings showing scrollbar when screen is offset
  osu.Game/Overlays/Mods/ModSettingsContainer.cs
Labels: size/XS, type:UI

#11770 Fix extra mod settings overflowing from screen in multi room
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs
Labels: area:multiplayer, size/XS, type:UI

#11762 Add loading spinner while tournament bracket is loading / retrieving data
  osu.Game.Tournament.Tests/TournamentTestBrowser.cs
  osu.Game.Tournament.Tests/TournamentTestScene.cs
  osu.Game.Tournament/TournamentGame.cs
  osu.Game.Tournament/TournamentGameBase.cs
Labels: area:tournament, size/M

#11709 Share connection logic between SignalR clients
  osu.Game.Tests/Visual/Gameplay/TestSceneSpectator.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerGameplayLeaderboard.cs
  osu.Game/Online/HubClientConnector.cs
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
  osu.Game/Online/Multiplayer/StatefulMultiplayerClient.cs
  osu.Game/Online/Spectator/SpectatorStreamingClient.cs
Labels: size/XL, type:code-quality

#11742 Add more MIME types to Android share intent filter
  osu.Android/OsuGameActivity.cs
Labels: platform:android, size/XS

#11780 Ensure the tournament test runner is ready before performing the test run
  osu.Game.Tournament.Tests/TournamentTestScene.cs
Labels: size/XS, type:testing

#11784 Fix test failures in PerformFromScreen tests
  osu.Game/Overlays/Volume/VolumeMeter.cs
  osu.Game/Screens/BackgroundScreen.cs
Labels: size/S, type:testing

#11782 Move HubClientConnector retrieval to IAPIProvider
  osu.Game.Tests/Visual/Gameplay/TestSceneSpectator.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerGameplayLeaderboard.cs
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Online/API/DummyAPIAccess.cs
  osu.Game/Online/API/IAPIProvider.cs
  osu.Game/Online/HubClientConnector.cs
  osu.Game/Online/IHubClientConnector.cs
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
  osu.Game/Online/Spectator/SpectatorStreamingClient.cs
Labels: size/M, type:code-quality, type:online

#11783 Send client version hash on hub connection
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Online/HubClientConnector.cs
  osu.Game/OsuGameBase.cs
Labels: size/S, type:online

#11789 Fix comment edited at date not showing tooltip
  osu.Game/Overlays/Comments/DrawableComment.cs
Labels: area:comments, size/M, type:UI

#11792 Fix current selection not updating visually after creating a new playlist
  osu.Game/Screens/OnlinePlay/Lounge/Components/RoomsContainer.cs
Labels: size/S

#11791 Add the ability to deselect the currently selected room via clicking away
  osu.Game.Tests/Visual/Multiplayer/TestSceneLoungeRoomsContainer.cs
  osu.Game/Screens/OnlinePlay/Lounge/Components/RoomsContainer.cs
Labels: area:multiplayer, size/S, type:UX

#11790 Display remaining attempts for playlist rooms with room-level attempt limits
  osu.Game/Online/Rooms/ItemAttemptsCount.cs
  osu.Game/Online/Rooms/PlaylistAggregateScore.cs
  osu.Game/Online/Rooms/Room.cs
  osu.Game/Screens/OnlinePlay/Components/RoomLocalUserInfo.cs
  osu.Game/Screens/OnlinePlay/OnlinePlayComposite.cs
Labels: area:playlists, size/M

#11798 Use long type where required in multiplayer
  osu.Game/Online/API/Requests/Responses/APIUserScoreAggregate.cs
  osu.Game/Online/Multiplayer/StatefulMultiplayerClient.cs
  osu.Game/Online/Rooms/CreateRoomScoreRequest.cs
  osu.Game/Online/Rooms/GetRoomLeaderboardRequest.cs
  osu.Game/Online/Rooms/GetRoomRequest.cs
  osu.Game/Online/Rooms/IndexPlaylistScoresRequest.cs
  osu.Game/Online/Rooms/MultiplayerScore.cs
  osu.Game/Online/Rooms/PlaylistItem.cs
  osu.Game/Online/Rooms/Room.cs
  osu.Game/Online/Rooms/ShowPlaylistUserScoreRequest.cs
  osu.Game/Online/Rooms/SubmitRoomScoreRequest.cs
  osu.Game/Screens/OnlinePlay/Components/RoomManager.cs
  osu.Game/Screens/OnlinePlay/Match/Components/MatchChatDisplay.cs
  osu.Game/Screens/OnlinePlay/Match/Components/MatchLeaderboard.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Match/MultiplayerMatchSettingsOverlay.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerResultsScreen.cs
  osu.Game/Screens/OnlinePlay/OnlinePlayComposite.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsPlayer.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsResultsScreen.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsRoomSubScreen.cs
Labels: area:multiplayer, size/M

#11738 Make server authoritative in which mods the client should be using when gameplay starts
  osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs
Labels: area:multiplayer, size/S

#11801 Fix intro beatmap always being imported even if already in a good state
  osu.Game/Screens/Menu/IntroScreen.cs
Labels: size/XS, type:performance

#11809 Fix audio previews not being adjusted in volume correctly
  osu.Game/Audio/PreviewTrackManager.cs
  osu.Game/OsuGameBase.cs
Labels: size/S

#11802 Fix long-running import tasks holding up user interactive imports
  osu.Game.Tests/Online/TestSceneOnlinePlayBeatmapAvailabilityTracker.cs
  osu.Game/Database/ArchiveModelManager.cs
Labels: size/M

#11811 Fix ModDisplay potentially being operated on before loaded completely
  osu.Game/Screens/Play/HUD/ModDisplay.cs
Labels: size/S, type:reliability

#11818 Fix preview point not being set correctly for beatmaps which don't specify an explicit time value
  osu.Game/Beatmaps/BeatmapMetadata.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Screens/Menu/IntroScreen.cs
  osu.Game/Screens/Menu/MainMenu.cs
  osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: size/M, type:audio

#11821 Fix carousel items' borders getting blown out when selected and hovered
  osu.Game/Screens/Select/Carousel/CarouselHeader.cs
Labels: area:song-select, size/M

#11822 Add login placeholder for chat overlay
  osu.Game/Online/OnlineViewContainer.cs
  osu.Game/Overlays/ChatOverlay.cs
Labels: area:overlay-chat, size/M, type:UX

#11820 Fix collections being imported from BDL thread
  osu.Game/Collections/CollectionManager.cs
Labels: area:database, size/M

#11799 Fix multiple issues with user population in tournament client
  osu.Game.Tournament/TournamentGameBase.cs
Labels: area:tournament, size/S

#11817 Fix potential crash from cross-thread drawable manipulation in CollectionFilterDropdown
  osu.Game/Collections/CollectionFilterDropdown.cs
  osu.Game/Collections/CollectionFilterMenuItem.cs
  osu.Game/Screens/Select/FilterControl.cs
Labels: size/M, type:reliability

#11823 Add login placeholder logic to OnlineOverlay
  osu.Game/Overlays/ChangelogOverlay.cs
  osu.Game/Overlays/NewsOverlay.cs
  osu.Game/Overlays/OnlineOverlay.cs
  osu.Game/Overlays/TabbableOnlineOverlay.cs
Labels: area:overlays, size/S, type:UX

#11826 Fix misordered hit error in score meter types
  osu.Game/Configuration/ScoreMeterType.cs
Labels: area:settings, size/XS

#11808 Rework multiplayer playlist handling to support multiple items
  osu.Game/Online/Multiplayer/MultiplayerRoomSettings.cs
  osu.Game/Online/Multiplayer/StatefulMultiplayerClient.cs
  osu.Game/Online/Rooms/PlaylistItem.cs
  osu.Game/Online/Rooms/Room.cs
  osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Match/BeatmapSelectionControl.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs
  osu.Game/Screens/OnlinePlay/OnlinePlayComposite.cs
  osu.Game/Screens/OnlinePlay/OnlinePlaySongSelect.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsRoomSubScreen.cs
  osu.Game/Screens/OnlinePlay/RoomSubScreenComposite.cs
Labels: area:multiplayer, size/L

#11827 Allow beatmap imports from any derived version of SongSelect, rather than only PlaySongSelect
  osu.Game/OsuGame.cs
  osu.Game/PerformFromMenuRunner.cs
Labels: size/XS, type:code-quality

#11793 Add "free mod" user mod selection support to the playlists system
  osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs
  osu.Game/Screens/OnlinePlay/OnlinePlaySongSelect.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsRoomSubScreen.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsSongSelect.cs
Labels: area:playlists, size/L

#11819 Update implementation of AdjustableAudioComponents in line with framework changes
  osu.Android.props
  osu.Game.Tests/Rulesets/TestSceneDrawableRulesetDependencies.cs
  osu.Game/Rulesets/UI/DrawableRulesetDependencies.cs
  osu.Game/Skinning/PoolableSkinnableSample.cs
  osu.Game/Skinning/SkinnableSound.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/S

#11708 Display user global rank for multiplayer room participants
  osu.Desktop/DiscordRichPresence.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerParticipantsList.cs
  osu.Game.Tests/Visual/Online/TestSceneRankGraph.cs
  osu.Game.Tests/Visual/Online/TestSceneUserProfileOverlay.cs
  osu.Game.Tournament.Tests/TournamentTestScene.cs
  osu.Game.Tournament/Models/TournamentTeam.cs
  osu.Game.Tournament/Screens/TeamIntro/SeedingScreen.cs
  osu.Game.Tournament/TournamentGameBase.cs
  osu.Game/Overlays/Profile/Header/CentreHeaderContainer.cs
  osu.Game/Overlays/Profile/Header/DetailHeaderContainer.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Participants/ParticipantPanel.cs
  osu.Game/Users/User.cs
  osu.Game/Users/UserStatistics.cs
Labels: area:multiplayer, size/L, type:UI

#11832 Show compact leaderboard during gameplay to reduce distractions
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerGameplayLeaderboard.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerPlayer.cs
  osu.Game/Screens/Play/HUD/GameplayLeaderboard.cs
  osu.Game/Screens/Play/HUD/GameplayLeaderboardScore.cs
Labels: area:multiplayer, size/L

#11713 Fix a potential crash when exiting play during the results screen transition
  osu.Game.Tests/Visual/Gameplay/TestScenePause.cs
  osu.Game.Tests/Visual/Navigation/OsuGameTestScene.cs
  osu.Game.Tests/Visual/Navigation/TestSceneScreenNavigation.cs
  osu.Game/Screens/Play/Player.cs
Labels: size/L, type:reliability

#11844 Fix support for instant exit if pausing is not allowed in the current game mode
  osu.Game.Tests/Visual/Gameplay/TestScenePause.cs
  osu.Game/Screens/Play/Player.cs
Labels: size/M

#11846 Add tests for clockrate adjusted difficulty calculations
  osu.Game.Rulesets.Catch.Tests/CatchDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Mania.Tests/ManiaDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Osu.Tests/OsuDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Taiko.Tests/TaikoDifficultyCalculatorTest.cs
Labels: area:difficulty, size/S, type:testing

#11848 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#11842 Update OsuGameActivity manifest in preparation for Android 12
  osu.Android/OsuGameActivity.cs
Labels: platform:android, size/XS

#11834 Add the ability for PerformFromMenuRunner to inspect nested screen stacks
  osu.Game/PerformFromMenuRunner.cs
  osu.Game/Screens/IHasSubScreenStack.cs
  osu.Game/Screens/OnlinePlay/OnlinePlayScreen.cs
Labels: size/M

#11866 Update framework
  osu.Android.props
  osu.Game.Tests/Rulesets/TestSceneDrawableRulesetDependencies.cs
  osu.Game/Rulesets/UI/DrawableRulesetDependencies.cs
  osu.Game/Skinning/PoolableSkinnableSample.cs
  osu.Game/Skinning/SkinnableSound.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/M

#11870 Increase beatmapset download timeout
  osu.Game/Online/API/Requests/DownloadBeatmapSetRequest.cs
Labels: size/XS, type:online

#11868 Fix PlaylistResults tests performing delays in real-time when headless
  osu.Game.Tests/Visual/Playlists/TestScenePlaylistsResultsScreen.cs
Labels: size/M, type:testing

#11833 Keep pausing gameplay on focus loss if cannot on first attempt
  osu.Game.Tests/Visual/Gameplay/TestScenePauseWhenInactive.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Tests/Visual/TestPlayer.cs
Labels: area:gameplay, size/M, type:UX

#11881 Disable multiplayer/spectator on iOS until it can be supported again
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Screens/Menu/ButtonSystem.cs
Labels: platform:iOS, size/S

#11867 Fix test failures due to beatmap taking too long to complete autoplay/replay
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game.Tests/Online/TestSceneOnlinePlayBeatmapAvailabilityTracker.cs
  osu.Game.Tests/Resources/Archives/241526 Soleily - Renatus_virtual_quick.osz
  osu.Game.Tests/Resources/TestResources.cs
  osu.Game.Tests/Visual/Background/TestSceneUserDimBackgrounds.cs
  osu.Game.Tests/Visual/Collections/TestSceneManageCollectionsDialog.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerReadyButton.cs
  osu.Game.Tests/Visual/Navigation/TestSceneScreenNavigation.cs
  osu.Game.Tests/Visual/Online/TestSceneDirectDownloadButton.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneFilterControl.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneDeleteLocalScore.cs
Labels: type:testing

#11880 When disable mouse buttons during gameplay is selected, disable more globally
  osu.Game/Rulesets/UI/RulesetInputManager.cs
Labels: area:gameplay, area:settings, size/XS, type:input

#11882 Fix importing collections twice from stable causing a hard crash
  osu.Game/Collections/CollectionManager.cs
Labels: size/XS, type:reliability

#11891 Add more mod incompatibilities
  osu.Game.Rulesets.Mania/Mods/ManiaModFadeIn.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModHidden.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModPlayfieldCover.cs
  osu.Game.Rulesets.Osu/Mods/OsuModAutopilot.cs
  osu.Game/Rulesets/Mods/ModAutoplay.cs
  osu.Game/Rulesets/Mods/ModFailCondition.cs
  osu.Game/Rulesets/Mods/ModNoFail.cs
  osu.Game/Rulesets/Mods/ModPerfect.cs
  osu.Game/Rulesets/Mods/ModRelax.cs
  osu.Game/Rulesets/Mods/ModSuddenDeath.cs
Labels: area:mods, size/L

#11864 Fix being able to select incompatible freemods
  osu.Game.Rulesets.Osu/Mods/OsuModTraceable.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerMatchSongSelect.cs
  osu.Game/Overlays/Mods/ModSection.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Screens/OnlinePlay/FreeModSelectOverlay.cs
  osu.Game/Screens/OnlinePlay/OnlinePlaySongSelect.cs
Labels: area:multiplayer, size/M

#11893 Fix requests being indefinitely queued when user is offline
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Screens/Ranking/SoloResultsScreen.cs
Labels: size/S, type:online, type:performance

#11892 Fix crash on two collections existing with the same name
  osu.Game.Tests/Visual/Collections/TestSceneManageCollectionsDialog.cs
  osu.Game/Collections/CollectionFilterMenuItem.cs
Labels: size/M, type:UI, type:reliability

#11888 Extend the rate setting range of values for TimeRamp mods
  osu.Game.Tests/Gameplay/TestSceneStoryboardSamples.cs
  osu.Game/Rulesets/Mods/ModRateAdjust.cs
  osu.Game/Rulesets/Mods/ModTimeRamp.cs
  osu.Game/Rulesets/Mods/ModWindDown.cs
  osu.Game/Rulesets/Mods/ModWindUp.cs
Labels: area:mods, size/M

#11894 Fix global hotkeys not working from main menu before toolbar is initially shown
  osu.Game.Tests/Visual/Navigation/TestSceneScreenNavigation.cs
  osu.Game/Overlays/Toolbar/Toolbar.cs
Labels: area:main menu, size/S, type:input

#11895 Update analyser package
  Directory.Build.props
Labels: area:tooling, size/XS

#11871 Update localisation in line with framework-side refactor
  osu.Android.props
  osu.Game.Rulesets.Osu/Skinning/Default/NumberPiece.cs
  osu.Game.Tests/Visual/Ranking/TestSceneExpandedPanelMiddleContent.cs
  osu.Game.Tests/Visual/Settings/TestSceneKeyBindingPanel.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapInfoWedge.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneDeleteLocalScore.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneFooterButtonMods.cs
  osu.Game.Tournament/Components/TournamentBeatmapPanel.cs
  osu.Game/Collections/CollectionFilterDropdown.cs
  osu.Game/Configuration/SettingSourceAttribute.cs
  osu.Game/Graphics/Sprites/GlowingSpriteText.cs
  osu.Game/Graphics/UserInterface/DrawableOsuMenuItem.cs
  osu.Game/Graphics/UserInterface/OsuButton.cs
  osu.Game/Graphics/UserInterface/OsuDropdown.cs
  osu.Game/Graphics/UserInterface/OsuTabControlCheckbox.cs
  osu.Game/Graphics/UserInterface/ShowMoreButton.cs
  osu.Game/Graphics/UserInterface/TriangleButton.cs
  osu.Game/Overlays/BeatmapListing/Panels/GridBeatmapPanel.cs
  osu.Game/Overlays/BeatmapListing/Panels/ListBeatmapPanel.cs
  osu.Game/Overlays/BeatmapSet/BasicStats.cs
  osu.Game/Overlays/BeatmapSet/Scores/TopScoreStatisticsSection.cs
  osu.Game/Overlays/Chat/Selection/ChannelSection.cs
  osu.Game/Overlays/Chat/Selection/ChannelSelectionOverlay.cs
  osu.Game/Overlays/Comments/Buttons/CommentRepliesButton.cs
  osu.Game/Overlays/KeyBinding/KeyBindingRow.cs
  osu.Game/Overlays/Music/PlaylistItem.cs
  osu.Game/Overlays/Notifications/NotificationSection.cs
  osu.Game/Overlays/NowPlayingOverlay.cs
  osu.Game/Overlays/OverlaySortTabControl.cs
  osu.Game/Overlays/Profile/Sections/Historical/DrawableMostPlayedBeatmap.cs
  osu.Game/Overlays/Profile/Sections/Ranks/DrawableProfileScore.cs
  osu.Game/Overlays/Settings/Sections/Audio/AudioDevicesSettings.cs
  osu.Game/Overlays/Settings/Sections/Graphics/LayoutSettings.cs
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
  osu.Game/Overlays/Settings/SettingsCheckbox.cs
  osu.Game/Overlays/Settings/SettingsItem.cs
  osu.Game/Overlays/Toolbar/ToolbarButton.cs
  osu.Game/Screens/Menu/SongTicker.cs
  osu.Game/Screens/OnlinePlay/Components/BeatmapTitle.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsMatchSettingsOverlay.cs
  osu.Game/Screens/Play/BeatmapMetadataDisplay.cs
  osu.Game/Screens/Ranking/Expanded/ExpandedPanelMiddleContent.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
  osu.Game/Screens/Select/Carousel/SetPanelContent.cs
  osu.Game/Screens/Select/Details/AdvancedStats.cs
  osu.Game/Screens/Select/FooterButton.cs
  osu.Game/Screens/Select/Options/BeatmapOptionsButton.cs
  osu.Game/Skinning/SkinnableSpriteText.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/L, type:localisation

#11896 Change Enum.HasFlag to use HasFlagFast extension method
  .editorconfig
  CodeAnalysis/BannedSymbols.txt
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Mania.Tests/TestSceneNotes.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/DistanceObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/HitObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Graphics/UserInterface/BarGraph.cs
  osu.Game/Graphics/UserInterface/TwoLayerButton.cs
  osu.Game/Overlays/Toolbar/ToolbarButton.cs
  osu.Game/Replays/Legacy/LegacyReplayFrame.cs
  osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardAnimation.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardSprite.cs
Labels: size/L, type:performance

#11897 Fix the star rating display at song select flashing to zero when changing mods
  osu.Game/Screens/Select/Details/AdvancedStats.cs
Labels: area:song-select, size/S

#11900 Update the displayed BPM at song select with rate adjust mods
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapInfoWedge.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
Labels: area:mods, area:song-select, size/L

#11898 Allow determining a BeatmapDifficultyCache's bindable return's completion state via nullability
  osu.Game/Beatmaps/BeatmapDifficultyCache.cs
  osu.Game/Beatmaps/Drawables/DifficultyIcon.cs
  osu.Game/Scoring/ScoreManager.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmap.cs
Labels: size/M, type:code-quality

#11906 Reduce allocation overhead when notification overlay has visible notifications
  osu.Game/Overlays/Notifications/NotificationSection.cs
Labels: size/S, type:performance

#11907 Fix "failed to import" message showing when importing from a stable install with no beatmaps
  osu.Game/Database/ArchiveModelManager.cs
Labels: area:overlay-notifications, size/XS

#11903 Show API human readable error message when chat posting fails
  osu.Game/Online/Chat/ChannelManager.cs
Labels: area:overlay-chat, size/S, type:UX

#11904 Centralise cases of performing actions on the current selection
  osu.Game.Rulesets.Mania/Edit/ManiaSelectionHandler.cs
  osu.Game.Rulesets.Taiko/Edit/TaikoSelectionHandler.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
  osu.Game/Screens/Edit/Compose/Components/SelectionHandler.cs
  osu.Game/Screens/Edit/EditorBeatmap.cs
Labels: area:editor, size/M

#11908 Fix tournament drawings screen flags being too big
  osu.Game.Tournament.Tests/Screens/TestSceneDrawingsScreen.cs
  osu.Game.Tournament/Screens/Drawings/Components/ScrollingTeamContainer.cs
Labels: area:tournament, size/M

#11909 Update framework
  osu.Android.props
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#11918 Fix multiple enumerations when ordering setting sources
  osu.Game.Tests/Mods/SettingsSourceAttributeTest.cs
  osu.Game/Configuration/SettingSourceAttribute.cs
Labels: area:mods, size/M

#11916 Fix restore default button potentially mutating transforms during load
  osu.Game/Overlays/Settings/SettingsItem.cs
Labels: area:settings, size/XS, type:reliability
