Repository ppy/osu, pull requests merged in 2021-11, with the labels that each got.

#15377 Fix star rating not updating for some mods on details tab in song select
  osu.Game/Screens/Select/Details/AdvancedStats.cs
Labels: area:song-select, type:UI, size/XS

#15382 Reduce fail animation tint slightly
  osu.Game/Screens/Play/FailAnimation.cs
Labels: area:gameplay, size/XS

#15383 Fix potential infinite loop when trying to rewrite skin metadata with non-lowercase `skin.ini`
  osu.Game.Tests/Skins/IO/ImportSkinTest.cs
  osu.Game/Skinning/Skin.cs
  osu.Game/Skinning/SkinManager.cs
Labels: area:database, size/M

#15384 Fix beatmap creator showing twice in tournament map pool panels
  osu.Game.Tournament/Components/TournamentBeatmapPanel.cs
  osu.Game/Beatmaps/BeatmapInfoExtensions.cs
  osu.Game/Beatmaps/BeatmapMetadataInfoExtensions.cs
Labels: area:tournament, size/S

#15321 Replace `DownloadTrackingComposite` with instantiable `DownloadTracker` components
  osu.Game.Tests/Online/TestSceneOnlinePlayBeatmapAvailabilityTracker.cs
  osu.Game/Beatmaps/BeatmapModelDownloader.cs
  osu.Game/Database/ModelDownloader.cs
  osu.Game/Online/BeatmapDownloadTracker.cs
  osu.Game/Online/DownloadTracker.cs
  osu.Game/Online/DownloadTrackingComposite.cs
  osu.Game/Online/Rooms/OnlinePlayBeatmapAvailabilityTracker.cs
  osu.Game/Online/ScoreDownloadTracker.cs
  osu.Game/Overlays/BeatmapDownloadTrackingComposite.cs
  osu.Game/Overlays/BeatmapListing/Panels/BeatmapPanelDownloadButton.cs
  osu.Game/Overlays/BeatmapListing/Panels/DownloadProgressBar.cs
  osu.Game/Overlays/BeatmapSet/BeatmapSetHeaderContent.cs
  osu.Game/Overlays/BeatmapSet/Buttons/HeaderDownloadButton.cs
  osu.Game/Scoring/ScoreModelDownloader.cs
  osu.Game/Screens/OnlinePlay/DrawableRoomPlaylistItem.cs
  osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
  osu.Game/Screens/Ranking/ReplayDownloadButton.cs
Labels: type:online, size/XL

#15358 Add a note about `OnlineID` potentially being zero in non-autoincrement cases
  osu.Game/Database/IHasOnlineID.cs
Labels: size/XS, type:documentation

#15385 Update dashboard components to use `APIBeatmapSet`
  osu.Game.Tests/Visual/UserInterface/TestSceneDashboardBeatmapListing.cs
  osu.Game/Overlays/Dashboard/Home/DashboardBeatmapListing.cs
  osu.Game/Overlays/Dashboard/Home/DashboardBeatmapPanel.cs
  osu.Game/Overlays/Dashboard/Home/DashboardNewBeatmapPanel.cs
  osu.Game/Overlays/Dashboard/Home/DashboardPopularBeatmapPanel.cs
  osu.Game/Overlays/Dashboard/Home/DrawableBeatmapList.cs
  osu.Game/Overlays/Dashboard/Home/DrawableNewBeatmapList.cs
  osu.Game/Overlays/Dashboard/Home/DrawablePopularBeatmapList.cs
Labels: type:code-quality, size/L

#15387 Fix incorrect state transition in score download tracker
  osu.Game/Online/ScoreDownloadTracker.cs
Labels: type:online, size/XS

#15363 Update `GetScoreRequest` and `PresentBeatmap` to accept interface types
  osu.Game/Online/API/Requests/GetScoresRequest.cs
  osu.Game/OsuGame.cs
Labels: type:code-quality, size/S

#15364 Update all beatmap overlay views to use `APIBeatmap`/`APIBeatmapSet`
  osu.Game.Tests/Visual/Online/TestSceneBeatmapAvailability.cs
  osu.Game.Tests/Visual/Online/TestSceneBeatmapRulesetSelector.cs
  osu.Game.Tests/Visual/Online/TestSceneBeatmapSetOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneBeatmapSetOverlayDetails.cs
  osu.Game.Tests/Visual/Online/TestSceneBeatmapSetOverlaySuccessRate.cs
  osu.Game.Tests/Visual/Online/TestSceneDirectDownloadButton.cs
  osu.Game.Tests/Visual/Online/TestSceneDirectPanel.cs
  osu.Game.Tests/Visual/Online/TestSceneFavouriteButton.cs
  osu.Game.Tests/Visual/Online/TestSceneLeaderboardModSelector.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneAdvancedStats.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapDetails.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneBeatmapListingSearchControl.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneUpdateableBeatmapBackgroundSprite.cs
  osu.Game/Online/API/Requests/Responses/APIBeatmap.cs
  osu.Game/Overlays/BeatmapListing/BeatmapListingFilterControl.cs
  osu.Game/Overlays/BeatmapListing/BeatmapListingSearchControl.cs
  osu.Game/Overlays/BeatmapListing/Panels/BeatmapPanel.cs
  osu.Game/Overlays/BeatmapListing/Panels/BeatmapPanelDownloadButton.cs
  osu.Game/Overlays/BeatmapListing/Panels/DownloadProgressBar.cs
  osu.Game/Overlays/BeatmapListing/Panels/GridBeatmapPanel.cs
  osu.Game/Overlays/BeatmapListing/Panels/ListBeatmapPanel.cs
  osu.Game/Overlays/BeatmapListing/Panels/PlayButton.cs
  osu.Game/Overlays/BeatmapListingOverlay.cs
  osu.Game/Overlays/BeatmapSet/AuthorInfo.cs
  osu.Game/Overlays/BeatmapSet/BasicStats.cs
  osu.Game/Overlays/BeatmapSet/BeatmapAvailability.cs
  osu.Game/Overlays/BeatmapSet/BeatmapPicker.cs
  osu.Game/Overlays/BeatmapSet/BeatmapRulesetSelector.cs
  osu.Game/Overlays/BeatmapSet/BeatmapRulesetTabItem.cs
  osu.Game/Overlays/BeatmapSet/BeatmapSetHeader.cs
  osu.Game/Overlays/BeatmapSet/BeatmapSetHeaderContent.cs
  osu.Game/Overlays/BeatmapSet/Buttons/FavouriteButton.cs
  osu.Game/Overlays/BeatmapSet/Buttons/HeaderDownloadButton.cs
  osu.Game/Overlays/BeatmapSet/Buttons/PreviewButton.cs
  osu.Game/Overlays/BeatmapSet/Details.cs
  osu.Game/Overlays/BeatmapSet/Info.cs
  osu.Game/Overlays/BeatmapSet/LeaderboardModSelector.cs
  osu.Game/Overlays/BeatmapSet/Scores/ScoresContainer.cs
  osu.Game/Overlays/BeatmapSet/SuccessRate.cs
  osu.Game/Overlays/BeatmapSetOverlay.cs
  osu.Game/Overlays/Profile/Sections/Beatmaps/PaginatedBeatmapContainer.cs
  osu.Game/Overlays/Profile/Sections/Historical/DrawableMostPlayedBeatmap.cs
  osu.Game/Overlays/Rankings/SpotlightsLayout.cs
  osu.Game/Screens/Play/SoloSpectator.cs
  osu.Game/Screens/Select/BeatmapDetails.cs
  osu.Game/Screens/Select/Details/AdvancedStats.cs
Labels: type:code-quality, size/XXL

#15399 Update dependencies
  Directory.Build.props
  Templates/Rulesets/ruleset-empty/osu.Game.Rulesets.EmptyFreeform.Tests/osu.Game.Rulesets.EmptyFreeform.Tests.csproj
  Templates/Rulesets/ruleset-example/osu.Game.Rulesets.Pippidon.Tests/osu.Game.Rulesets.Pippidon.Tests.csproj
  Templates/Rulesets/ruleset-scrolling-empty/osu.Game.Rulesets.EmptyScrolling.Tests/osu.Game.Rulesets.EmptyScrolling.Tests.csproj
  Templates/Rulesets/ruleset-scrolling-example/osu.Game.Rulesets.Pippidon.Tests/osu.Game.Rulesets.Pippidon.Tests.csproj
  osu.Game.Rulesets.Catch.Tests/osu.Game.Rulesets.Catch.Tests.csproj
  osu.Game.Rulesets.Mania.Tests/osu.Game.Rulesets.Mania.Tests.csproj
  osu.Game.Rulesets.Osu.Tests/osu.Game.Rulesets.Osu.Tests.csproj
  osu.Game.Rulesets.Taiko.Tests/osu.Game.Rulesets.Taiko.Tests.csproj
  osu.Game.Tests/osu.Game.Tests.csproj
  osu.Game.Tournament.Tests/osu.Game.Tournament.Tests.csproj
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: dependencies, size/M

#15403 Add android intent filter for osu! replays
  osu.Android/OsuGameActivity.cs
Labels: platform:android, size/XS

#15279 Fix spinner judgements on old beatmaps get incorrectly stacked
  osu.Game.Rulesets.Osu.Tests/TestSceneNoSpinnerStacking.cs
  osu.Game.Rulesets.Osu/Objects/OsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Spinner.cs
Labels: ruleset:osu!, area:gameplay, size/M

#15407 Remove trailing exclamation marks from autoplay character names
  osu.Game.Rulesets.Catch/Mods/CatchModAutoplay.cs
  osu.Game.Rulesets.Catch/Mods/CatchModCinema.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModAutoplay.cs
  osu.Game.Rulesets.Mania/Mods/ManiaModCinema.cs
Labels: size/XS

#15406 Avoid any potential infinite loops when re-writing `skin.ini` files
  osu.Game/Skinning/SkinManager.cs
Labels: area:database, size/M

#15405 Default legacy decoder to `General` section, rather than none
  osu.Game.Tests/Skins/IO/ImportSkinTest.cs
  osu.Game/Beatmaps/Formats/LegacyDecoder.cs
Labels: area:database, area:skinning, size/S

#15410 Fix multiplayer room participants display not updating as new users join/leave
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayer.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerParticipantsList.cs
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
  osu.Game/Tests/Visual/Multiplayer/TestMultiplayerClient.cs
  osu.Game/Tests/Visual/TestUserLookupCache.cs
Labels: type:UI, area:multiplayer, size/M

#15409 Fix PP counter showing incorrect values with rate adjustment mods
  osu.Game/Rulesets/Difficulty/DifficultyCalculator.cs
  osu.Game/Rulesets/Difficulty/TimedDifficultyAttributes.cs
Labels: area:gameplay, type:UI, size/S

#14845 osu! Difficulty Aim Overhaul: base change
  osu.Game.Rulesets.Osu.Tests/OsuDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Osu/Difficulty/Preprocessing/OsuDifficultyHitObject.cs
  osu.Game.Rulesets.Osu/Difficulty/Skills/Aim.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
Labels: ruleset:osu!, area:difficulty, size/L

#15425 Fix crash when attempting to view global leaderboards
  osu.Game/Online/API/Requests/Responses/APIScoreInfo.cs
Labels: type:online, area:song-select, size/XS, type:reliability, area:overlay-beatmap

#15430 Fix multiplayer score submission not working
  osu.Game/Online/Rooms/SubmitRoomScoreRequest.cs
Labels: type:online, area:multiplayer, size/XS, area:playlists

#15427 Fix multiplayer panels not correctly showing star rating
  osu.Game/Beatmaps/BeatmapDifficultyCache.cs
  osu.Game/Beatmaps/Drawables/DifficultyIcon.cs
  osu.Game/Screens/OnlinePlay/DrawableRoomPlaylistItem.cs
Labels: type:UI, area:multiplayer, size/XS, area:playlists

#15431 Fix unauthenticated API requests no longer working
  osu.Game/Online/API/APIRequest.cs
Labels: type:online, size/XS

#15429 Fix beatmap download notifications not showing beatmap name correctly
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Overlays/BeatmapListing/Panels/BeatmapPanelDownloadButton.cs
  osu.Game/Overlays/BeatmapSet/Buttons/HeaderDownloadButton.cs
Labels: type:UI, area:overlay-notifications, size/S

#15432 Fix multiplayer potentially getting incorrect beatmap availability state after changing beatmaps
  osu.Game/Online/Rooms/OnlinePlayBeatmapAvailabilityTracker.cs
Labels: area:multiplayer, size/XS

#15439 Fix score tracker not tracking non-online scores correctly
  osu.Game/Online/ScoreDownloadTracker.cs
Labels: area:replay, size/XS

#15398 Add basic elements of new beatmap cards
  osu.Game.Tests/Visual/Beatmaps/TestSceneBeatmapCard.cs
  osu.Game/Beatmaps/Drawables/Cards/BeatmapCard.cs
  osu.Game/Beatmaps/Drawables/Cards/BeatmapCardContentBackground.cs
Labels: type:UI, size/XL, area:overlay-beatmap-listing

#15440 Update `TextFlowContainer` usages to consume `LocalisableString`s
  osu.Android.props
  osu.Game/Graphics/Containers/LinkFlowContainer.cs
  osu.Game/Graphics/UserInterface/OsuCheckbox.cs
  osu.Game/Graphics/UserInterfaceV2/LabelledDrawable.cs
  osu.Game/Online/Placeholders/ClickablePlaceholder.cs
  osu.Game/Online/Placeholders/MessagePlaceholder.cs
  osu.Game/Overlays/AccountCreation/ScreenEntry.cs
  osu.Game/Overlays/Changelog/ChangelogSupporterPromo.cs
  osu.Game/Overlays/Dialog/PopupDialog.cs
  osu.Game/Overlays/Music/PlaylistItem.cs
  osu.Game/Overlays/Notifications/ProgressNotification.cs
  osu.Game/Overlays/Notifications/SimpleNotification.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/DirectorySelectScreen.cs
  osu.Game/Overlays/Settings/SettingsCheckbox.cs
  osu.Game/Overlays/Settings/SettingsItem.cs
  osu.Game/Screens/Edit/Timing/SliderWithTextBoxInput.cs
  osu.Game/Screens/OnlinePlay/Components/BeatmapTitle.cs
  osu.Game/Screens/OnlinePlay/DrawableRoomPlaylistItem.cs
  osu.Game/Screens/OnlinePlay/Lounge/Components/PlaylistCountPill.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: type:localisation, size/L

#15455 Fix multiplayer text flow usages incorrectly wrapping text
  osu.Game.Tests/Visual/Multiplayer/TestSceneDrawableRoom.cs
  osu.Game/Screens/OnlinePlay/DrawableRoomPlaylistItem.cs
  osu.Game/Screens/OnlinePlay/Lounge/Components/DrawableRoom.cs
Labels: type:UI, area:multiplayer, size/M, area:playlists

#15447 Fix beatmaps being exported with malformed filenames inside `.osz` zip files
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/BeatmapModelManager.cs
  osu.Game/Database/ArchiveModelManager.cs
Labels: area:database, size/M

#15456 Enable nullable support on `BeatmapMetadata`
  osu.Game.Tests/Editing/Checks/CheckAudioQualityTest.cs
  osu.Game.Tests/Editing/Checks/CheckBackgroundQualityTest.cs
  osu.Game.Tests/Editing/Checks/CheckFilePresenceTest.cs
  osu.Game.Tests/NonVisual/Filtering/FilterMatchingTest.cs
  osu.Game.Tests/Visual/Editing/TestSceneMetadataSection.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneReplayRecording.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/BeatmapMetadata.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapEncoder.cs
  osu.Game/Beatmaps/WorkingBeatmapCache.cs
  osu.Game/Rulesets/Edit/Checks/CheckAudioQuality.cs
  osu.Game/Rulesets/Edit/Checks/CheckFilePresence.cs
  osu.Game/Screens/Select/Carousel/CarouselBeatmapSet.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmap.cs
  osu.Game/Storyboards/Storyboard.cs
Labels: type:code-quality, size/M

#15460 Upgrade to nvika 1.0.4
  .config/dotnet-tools.json
Labels: area:tooling, size/XS

#15312 Fix editor context menu requiring two right-clicks to display
  osu.Game.Tests/Visual/Editing/TestSceneComposerSelection.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
Labels: area:editor, type:UI, size/M

#15461 Fix a few more "maybe null" inspections
  osu.Game.Tests/Online/TestAPIModJsonSerialization.cs
  osu.Game/Screens/Select/BeatmapDeleteDialog.cs
Labels: type:code-quality, size/S

#15464 Fix crash on gameplay startup if beatmap has no background
  osu.Game/Storyboards/Storyboard.cs
Labels: size/XS, type:reliability

#15458 Refactor `PlaylistItem` to allow `Beatmap` to be an interfaced type
  osu.Game.Tests/Visual/Beatmaps/TestSceneBeatmapCard.cs
  osu.Game.Tests/Visual/Beatmaps/TestSceneDifficultySpectrumDisplay.cs
  osu.Game.Tests/Visual/Online/TestSceneBeatmapRulesetSelector.cs
  osu.Game.Tests/Visual/Online/TestSceneBeatmapSetOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneBeatmapSetOverlayDetails.cs
  osu.Game.Tests/Visual/Online/TestSceneDirectPanel.cs
  osu.Game/Beatmaps/BeatmapInfo.cs
  osu.Game/Beatmaps/BeatmapInfoExtensions.cs
  osu.Game/Beatmaps/IBeatmapInfo.cs
  osu.Game/Online/API/Requests/Responses/APIBeatmapSet.cs
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
  osu.Game/Online/Multiplayer/OnlineMultiplayerClient.cs
  osu.Game/Online/Rooms/MultiplayerScore.cs
  osu.Game/Online/Rooms/OnlinePlayBeatmapAvailabilityTracker.cs
  osu.Game/Online/Rooms/PlaylistItem.cs
  osu.Game/Overlays/BeatmapListing/Panels/BeatmapPanel.cs
  osu.Game/Screens/OnlinePlay/Components/OnlinePlayBackgroundScreen.cs
  osu.Game/Screens/OnlinePlay/Components/PlaylistItemBackground.cs
  osu.Game/Screens/OnlinePlay/Components/RoomManager.cs
  osu.Game/Screens/OnlinePlay/Components/StarRatingRangeDisplay.cs
  osu.Game/Screens/OnlinePlay/DrawableRoomPlaylistItem.cs
  osu.Game/Screens/OnlinePlay/Lounge/Components/DrawableRoom.cs
  osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsPlayer.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsResultsScreen.cs
  osu.Game/Screens/Play/SoloSpectator.cs
  osu.Game/Tests/Visual/Multiplayer/TestMultiplayerClient.cs
Labels: type:code-quality, size/L, area:playlists

#15467 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#15468 Use official nvika package again
  .config/dotnet-tools.json
Labels: type:code-quality, size/XS

#15478 Fix labelled drawable descriptions not showing
  osu.Game.Tests/Visual/UserInterface/TestSceneLabelledDrawable.cs
  osu.Game/Graphics/UserInterfaceV2/LabelledDrawable.cs
Labels: type:UI, size/XS

#15479 Fix scaling of skin components being too sensitive after rotation
  osu.Game/Skinning/Editor/SkinSelectionHandler.cs
Labels: area:skinning, size/S

#15459 Remove `IOnlineInfo` implementations from database models
  osu.Game.Tests/NonVisual/BeatmapSetInfoEqualityTest.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneDrawableRoomPlaylist.cs
  osu.Game.Tests/Visual/Online/TestSceneDirectDownloadButton.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapDetails.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneUpdateableBeatmapSetCover.cs
  osu.Game/Beatmaps/BeatmapInfo.cs
  osu.Game/Beatmaps/BeatmapSetInfo.cs
  osu.Game/Beatmaps/Drawables/UpdateableBeatmapBackgroundSprite.cs
  osu.Game/Online/API/Requests/Responses/APIBeatmapSet.cs
  osu.Game/Screens/Select/BeatmapDetails.cs
  osu.Game/Tests/Beatmaps/TestBeatmap.cs
  osu.Game/Tests/Visual/OsuTestScene.cs
Labels: type:code-quality, size/L

#15463 Remove all remaining calls to `ToBeatmapInfo`/`ToBeatmapSetInfo`
  osu.Game/Online/API/Requests/Responses/APIBeatmap.cs
  osu.Game/Online/API/Requests/Responses/APIBeatmapSet.cs
  osu.Game/Online/API/Requests/Responses/APIScoreInfo.cs
  osu.Game/Overlays/BeatmapSet/Scores/ScoresContainer.cs
Labels: type:code-quality, size/M

#15489 Allow downloads via interface types (and remove `IModelManager:IModelImporter`)
  osu.Game.Tests/Online/TestSceneOnlinePlayBeatmapAvailabilityTracker.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/BeatmapModelDownloader.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Database/IModelDownloader.cs
  osu.Game/Database/IModelManager.cs
  osu.Game/Database/ModelDownloader.cs
  osu.Game/Online/API/Requests/DownloadBeatmapSetRequest.cs
  osu.Game/Online/API/Requests/DownloadReplayRequest.cs
  osu.Game/Online/BeatmapDownloadTracker.cs
  osu.Game/Online/ScoreDownloadTracker.cs
  osu.Game/Scoring/ScoreManager.cs
  osu.Game/Scoring/ScoreModelDownloader.cs
Labels: type:code-quality, size/L

#15488 Update usages of `BufferedContainer` in line with framework changes
  osu.Android.props
  osu.Game.Rulesets.Mania/Skinning/Default/DefaultBodyPiece.cs
  osu.Game.Rulesets.Osu/Statistics/AccuracyHeatmap.cs
  osu.Game/Graphics/Backgrounds/Background.cs
  osu.Game/Graphics/Sprites/GlowingSpriteText.cs
  osu.Game/Overlays/NowPlayingOverlay.cs
  osu.Game/Screens/Menu/IntroTriangles.cs
  osu.Game/Screens/Play/Break/BlurredIcon.cs
  osu.Game/Screens/Play/SquareGraph.cs
  osu.Game/Screens/Ranking/Expanded/Accuracy/RankText.cs
  osu.Game/Screens/Select/BeatmapInfoWedgeBackground.cs
  osu.Game/Screens/Select/Carousel/SetPanelBackground.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/M

#15480 Fix more occurring "possible null reference exception" inspections
  osu.Game.Tests/Mods/ModDifficultyAdjustTest.cs
  osu.Game.Tests/NonVisual/FirstAvailableHitWindowsTest.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneHitErrorMeter.cs
  osu.Game/Graphics/UserInterface/LoadingButton.cs
  osu.Game/Overlays/BeatmapListing/BeatmapSearchMultipleSelectionFilterRow.cs
  osu.Game/Overlays/Changelog/ChangelogHeader.cs
  osu.Game/Overlays/Comments/CommentEditor.cs
  osu.Game/Overlays/OverlayScrollContainer.cs
Labels: type:code-quality, size/L

#15512 Remove obsolete method in `ModAutoplay`
  osu.Game/Rulesets/Mods/ModAutoplay.cs
Labels: type:code-quality, size/XS

#14846 osu! Difficulty Aim Overhaul: slider change
  osu.Game.Rulesets.Osu.Tests/OsuDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Osu/Difficulty/Preprocessing/OsuDifficultyHitObject.cs
  osu.Game.Rulesets.Osu/Difficulty/Skills/Aim.cs
Labels: ruleset:osu!, area:difficulty, size/M

#15507 Add sanity check in Relax's effectiveMissCount calculation
  osu.Game.Rulesets.Osu/Difficulty/OsuPerformanceCalculator.cs
Labels: ruleset:osu!, area:difficulty, size/XS, type:reliability

#14847 osu! Difficulty Aim Overhaul: velocity change
  osu.Game.Rulesets.Osu.Tests/OsuDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Osu/Difficulty/Skills/Aim.cs
Labels: ruleset:osu!, area:difficulty, size/M

#15227 osu! Difficulty Aim Overhaul: PP Calc Changes
  osu.Game.Rulesets.Osu/Difficulty/OsuPerformanceCalculator.cs
Labels: area:difficulty, size/S

#15514 Change currentStrain to 0 for standard mode skills
  osu.Game.Rulesets.Osu.Tests/OsuDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Osu/Difficulty/Skills/Aim.cs
  osu.Game.Rulesets.Osu/Difficulty/Skills/Flashlight.cs
  osu.Game.Rulesets.Osu/Difficulty/Skills/Speed.cs
Labels: size/S

#15515 Fix loading spinner potentially showing on statistics unavailable message
  osu.Game/Screens/Ranking/Statistics/StatisticsPanel.cs
Labels: type:UI, area:results, size/XS

#15466 Clean up `User` class
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Beatmaps/Formats/OsuJsonDecoderTest.cs
  osu.Game.Tests/Beatmaps/IO/OszArchiveReaderTest.cs
  osu.Game.Tests/Database/BeatmapImporterTests.cs
  osu.Game.Tests/Visual/Online/TestSceneRankGraph.cs
  osu.Game.Tests/Visual/Online/TestSceneUserProfileOverlay.cs
  osu.Game.Tests/Visual/Ranking/TestSceneExpandedPanelMiddleContent.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs
  osu.Game.Tournament/Components/TournamentBeatmapPanel.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/BeatmapMetadata.cs
  osu.Game/Beatmaps/BeatmapMetadataInfoExtensions.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapEncoder.cs
  osu.Game/Beatmaps/IBeatmapMetadataInfo.cs
  osu.Game/Database/RealmContextFactory.cs
  osu.Game/Graphics/Containers/LinkFlowContainer.cs
  osu.Game/Models/RealmBeatmapMetadata.cs
  osu.Game/Models/RealmUser.cs
  osu.Game/Online/API/Requests/Responses/APIBeatmapSet.cs
  osu.Game/Online/API/Requests/Responses/APIRankHistory.cs
  osu.Game/Online/API/Requests/Responses/APIUser.cs
  osu.Game/Online/API/Requests/Responses/APIUserAchievement.cs
  osu.Game/Screens/Edit/Setup/MetadataSection.cs
  osu.Game/Screens/OnlinePlay/DrawableRoomPlaylistItem.cs
  osu.Game/Screens/Play/BeatmapMetadataDisplay.cs
  osu.Game/Screens/Ranking/Expanded/ExpandedPanelMiddleContent.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
  osu.Game/Screens/Select/Carousel/CarouselBeatmap.cs
  osu.Game/Screens/Select/Carousel/CarouselBeatmapSet.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmap.cs
  osu.Game/Skinning/LegacyBeatmapSkin.cs
  osu.Game/Stores/BeatmapImporter.cs
  osu.Game/Tests/Visual/OsuTestScene.cs
  osu.Game/Users/IUser.cs
  osu.Game/Users/UserStatistics.cs
Labels: type:code-quality, size/L

#15487 Support open profile overlay from username in more places
  osu.Game.Tests/Visual/Online/TestSceneUserProfileOverlay.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/UserProfileOverlay.cs
  osu.Game/Users/Drawables/ClickableAvatar.cs
Labels: type:online, size/M

#15513 Add statistics display to beatmap card
  osu.Game.Tests/Visual/Beatmaps/TestSceneBeatmapCard.cs
  osu.Game/Beatmaps/BeatmapSetHypeStatus.cs
  osu.Game/Beatmaps/BeatmapSetNominationStatus.cs
  osu.Game/Beatmaps/Drawables/Cards/BeatmapCard.cs
  osu.Game/Beatmaps/Drawables/Cards/Statistics/BeatmapCardDateStatistic.cs
  osu.Game/Beatmaps/Drawables/Cards/Statistics/BeatmapCardStatistic.cs
  osu.Game/Beatmaps/Drawables/Cards/Statistics/FavouritesStatistic.cs
  osu.Game/Beatmaps/Drawables/Cards/Statistics/HypesStatistic.cs
  osu.Game/Beatmaps/Drawables/Cards/Statistics/NominationsStatistic.cs
  osu.Game/Beatmaps/Drawables/Cards/Statistics/PlayCountStatistic.cs
  osu.Game/Beatmaps/IBeatmapSetOnlineInfo.cs
  osu.Game/Online/API/Requests/Responses/APIBeatmapSet.cs
Labels: type:UI, size/L, area:overlay-beatmap-listing

#15517 Fix `LinkFlowContainer` not creating user links supporting full `IUser` specification
  osu.Game/Graphics/Containers/LinkFlowContainer.cs
  osu.Game/Online/Chat/MessageFormatter.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Chat/ChatLine.cs
  osu.Game/Overlays/Profile/Sections/Recent/DrawableRecentActivity.cs
Labels: type:online, size/M

#15491 Revert weird event flow in model manager/importers
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneReplayDownloadButton.cs
  osu.Game.Tests/Visual/Online/TestSceneDirectDownloadButton.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/BeatmapModelManager.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Database/IModelDownloader.cs
  osu.Game/Database/IModelManager.cs
  osu.Game/Database/ModelDownloader.cs
  osu.Game/Online/BeatmapDownloadTracker.cs
  osu.Game/Online/ScoreDownloadTracker.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
  osu.Game/Scoring/ScoreManager.cs
  osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
  osu.Game/Screens/Select/BeatmapCarousel.cs
  osu.Game/Screens/Select/Carousel/TopLocalRank.cs
  osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboard.cs
  osu.Game/Screens/Spectate/SpectatorScreen.cs
Labels: type:code-quality, size/XL

#15519 Start initialising `RealmRulesetStore` on startup
  osu.Game/OsuGameBase.cs
  osu.Game/Stores/RealmRulesetStore.cs
Labels: area:database, size/L

#15518 Update usages of `KeyCombination.ReadableString()` to use `ReadableKeyCombinationProvider`
  osu.Android.props
  osu.Game.Tests/Database/TestRealmKeyBindingStore.cs
  osu.Game/Input/RealmKeyBindingStore.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/Settings/Sections/Input/KeyBindingRow.cs
  osu.Game/Overlays/Toolbar/ToolbarButton.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: type:UI, size/M

#15520 Add favourite button to beatmap card
  osu.Game.Tests/Visual/Beatmaps/TestSceneBeatmapCard.cs
  osu.Game.Tests/Visual/Beatmaps/TestSceneBeatmapCardFavouriteButton.cs
  osu.Game/Beatmaps/Drawables/Cards/BeatmapCard.cs
  osu.Game/Beatmaps/Drawables/Cards/BeatmapSetFavouriteState.cs
  osu.Game/Beatmaps/Drawables/Cards/Buttons/BeatmapCardIconButton.cs
  osu.Game/Beatmaps/Drawables/Cards/Buttons/DownloadButton.cs
  osu.Game/Beatmaps/Drawables/Cards/Buttons/FavouriteButton.cs
  osu.Game/Beatmaps/Drawables/Cards/Statistics/FavouritesStatistic.cs
  osu.Game/Online/API/Requests/PostBeatmapFavouriteRequest.cs
Labels: type:UI, size/L, area:overlay-beatmap-listing

#15522 Fix taiko beatmap scroll speed increasing after every save in editor
  osu.Game.Rulesets.Taiko.Tests/Editor/TestSceneEditorSaving.cs
  osu.Game.Rulesets.Taiko/Beatmaps/TaikoBeatmapConverter.cs
  osu.Game/Beatmaps/BeatmapModelManager.cs
Labels: ruleset:osu!taiko, area:editor, size/L

#15526 Move `HoverClickSounds` to cover only the clickable button in `KeyBindingRow`
  osu.Game/Overlays/Settings/Sections/Input/KeyBindingRow.cs
Labels: type:UI, size/XS

#15470 Add unstable rate counter to HUD
  osu.Game.Tests/Visual/Gameplay/TestSceneUnstableRateCounter.cs
  osu.Game/Screens/Play/HUD/UnstableRateCounter.cs
Labels: type:UI, area:skinning, size/L

#15533 Fix realm migration potentially failing for users that haven't run osu! in a long time
  osu.Game/Database/RealmContextFactory.cs
Labels: area:database, size/XS, type:reliability

#15535 Rewrite `PreviewTrackManager` to avoid constructing `TrackBass` locally
  osu.Game.Tests/Visual/Components/TestScenePreviewTrackManager.cs
  osu.Game/Audio/PreviewTrackManager.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/WorkingBeatmapCache.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Tests/Visual/EditorTestScene.cs
Labels: type:code-quality, size/L

#15551 Fix `TeamDisplay` not showing after changing to team versus
  osu.Game.Tests/Visual/Multiplayer/TestSceneTeamVersus.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Participants/TeamDisplay.cs
Labels: size/M

#15552 Use disposal in `CheckBackgroundQuality`
  osu.Game.Tests/Editing/Checks/CheckBackgroundQualityTest.cs
  osu.Game/Rulesets/Edit/Checks/CheckBackgroundQuality.cs
Labels: size/M

#15540 Add "No Scope" mod implementation for Catch
  osu.Game.Rulesets.Catch.Tests/Mods/TestSceneCatchModNoScope.cs
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Catch/Mods/CatchModNoScope.cs
  osu.Game.Rulesets.Osu/Mods/OsuModNoScope.cs
  osu.Game/Rulesets/Mods/ModNoScope.cs
Labels: ruleset:osu!catch, area:mods, size/L

#15557 Fix logo sample always playing in main menu when initially logged out
  osu.Game/Screens/Menu/MainMenu.cs
Labels: area:main menu, size/S, type:audio

#15539 Fix model download notifications not formatting model correctly
  osu.Game.Tests/Models/DisplayStringTest.cs
  osu.Game.Tests/Online/TestSceneBeatmapManager.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneReplayDownloadButton.cs
  osu.Game/Beatmaps/BeatmapInfoExtensions.cs
  osu.Game/Beatmaps/BeatmapMetadataInfoExtensions.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Database/ModelDownloader.cs
  osu.Game/Extensions/ModelExtensions.cs
  osu.Game/Overlays/Notifications/ProgressNotification.cs
  osu.Game/Scoring/ScoreInfo.cs
  osu.Game/Scoring/ScoreInfoExtensions.cs
Labels: type:UI, size/L

#15545 Move clipboard operation implementations to individual editor subscreens
  osu.Game.Rulesets.Mania.Tests/Editor/TestSceneManiaComposeScreen.cs
  osu.Game.Tests/Visual/Editing/TestSceneComposeScreen.cs
  osu.Game/Screens/Edit/Compose/ComposeScreen.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/EditorClipboard.cs
  osu.Game/Screens/Edit/EditorScreen.cs
Labels: area:editor, size/L, type:reliability

#15556 Reset combo different way in NoScope mod tests (osu! ruleset)
  osu.Game.Rulesets.Osu.Tests/Mods/TestSceneOsuModNoScope.cs
Labels: type:code-quality, size/XS

#15547 Add a catch specific beatmap spinner gap check
  osu.Game.Rulesets.Catch.Tests/Editor/Checks/TestCheckBananaShowerGap.cs
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Catch/Edit/CatchBeatmapVerifier.cs
  osu.Game.Rulesets.Catch/Edit/Checks/CheckBananaShowerGap.cs
Labels: ruleset:osu!catch, area:editor, size/L

#15567 Replace usage of `TypeNameHandling.All` with custom type converter
  osu.Game/Online/HubClientConnector.cs
  osu.Game/Online/Multiplayer/MatchRoomState.cs
  osu.Game/Online/Multiplayer/MatchUserState.cs
  osu.Game/Online/SignalRDerivedTypeWorkaroundJsonConverter.cs
  osu.Game/Online/SignalRUnionWorkaroundResolver.cs
Labels: type:online, size/M

#15571 Fix being able to switch own team by clicking other players' team indicators
  osu.Game.Tests/Visual/Multiplayer/TestSceneTeamVersus.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Participants/TeamDisplay.cs
  osu.Game/Tests/Visual/Multiplayer/TestMultiplayerClient.cs
Labels: type:UI, area:multiplayer, size/S

#15569 Gracefully handle missing type rather than triggering `ArgumentNullException`
  osu.Game/Rulesets/RulesetLoadException.cs
  osu.Game/Rulesets/RulesetStore.cs
  osu.Game/Stores/RealmRulesetStore.cs
Labels: type:code-quality, size/M

#15573 Fix Android builds failing due to Xamarin-side regression
  .github/workflows/ci.yml
Labels: area:tooling, platform:android, size/S

#15572 Rename EF properties to match underlying interface
  osu.Game.Rulesets.Taiko.Tests/Editor/TestSceneEditorSaving.cs
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game.Tests/Beatmaps/ToStringFormattingTest.cs
  osu.Game.Tests/NonVisual/Filtering/FilterMatchingTest.cs
  osu.Game.Tests/Visual/Editing/TestSceneEditorSaving.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneDrawableRoom.cs
  osu.Game.Tests/Visual/Multiplayer/TestScenePlaylistsSongSelect.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneStarRatingRangeDisplay.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneAdvancedStats.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapInfoWedge.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapMetadataDisplay.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapRecommendations.cs
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneDeleteLocalScore.cs
  osu.Game/Beatmaps/Beatmap.cs
  osu.Game/Beatmaps/BeatmapInfo.cs
  osu.Game/Beatmaps/BeatmapModelManager.cs
  osu.Game/Beatmaps/BeatmapSetInfo.cs
  osu.Game/Beatmaps/DifficultyRecommender.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapEncoder.cs
  osu.Game/Screens/Edit/Components/Menus/DifficultyMenuItem.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/Setup/MetadataSection.cs
  osu.Game/Screens/Play/BeatmapMetadataDisplay.cs
  osu.Game/Screens/Ranking/Expanded/ExpandedPanelMiddleContent.cs
  osu.Game/Screens/Select/BeatmapInfoWedge.cs
  osu.Game/Screens/Select/Carousel/CarouselBeatmap.cs
  osu.Game/Screens/Select/Carousel/CarouselBeatmapSet.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmap.cs
  osu.Game/Stores/BeatmapImporter.cs
  osu.Game/Tests/Visual/OsuTestScene.cs
Labels: type:code-quality, size/L

#15576 Fix unstable rate counter not including judgements before show in calculations
  osu.Game.Tests/NonVisual/Ranking/UnstableRateTest.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneUnstableRateCounter.cs
  osu.Game/Rulesets/Scoring/HitEventExtensions.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Screens/Play/HUD/UnstableRateCounter.cs
  osu.Game/Screens/Ranking/Statistics/UnstableRate.cs
Labels: type:code-quality, area:gameplay, type:UI, size/L

#15579 Fix PP counter not updating until next judgement when shown for the first time
  osu.Game.Tests/Visual/Gameplay/TestScenePerformancePointsCounter.cs
  osu.Game/Screens/Play/HUD/PerformancePointsCounter.cs
Labels: area:gameplay, type:UI, size/M

#15583 Add slider-to-stream conversion operation to osu! editor
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneSliderStreamConversion.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderSelectionBlueprint.cs
Labels: ruleset:osu!, area:editor, size/L

#15582 Add method of testing gameplay from editor
  osu.Game.Tests/Visual/Editing/TestSceneEditorTestGameplay.cs
  osu.Game.Tests/Visual/Editing/TestSceneSetupScreen.cs
  osu.Game.Tests/Visual/Editing/TestSceneTimingScreen.cs
  osu.Game/Input/Bindings/GlobalActionContainer.cs
  osu.Game/Localisation/GlobalActionKeyBindingStrings.cs
  osu.Game/Screens/Edit/Components/Timelines/Summary/TestGameplayButton.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/EditorPlayer.cs
  osu.Game/Screens/Edit/EditorRoundedScreen.cs
  osu.Game/Screens/Edit/EditorScreen.cs
  osu.Game/Screens/Edit/SaveBeforeGameplayTestDialog.cs
Labels: area:gameplay, area:editor, size/L

#15587 Use fixed width font for performance points counter
  osu.Game/Screens/Play/HUD/PerformancePointsCounter.cs
  osu.Game/Screens/Play/HUD/UnstableRateCounter.cs
Labels: area:gameplay, type:UI, size/XS

#15589 Add fallback case for `GetDisplayString` if called on a null reference
  osu.Game.Tests/Models/DisplayStringTest.cs
  osu.Game/Extensions/ModelExtensions.cs
Labels: size/S, type:reliability

#15590 Fix failed imports being incorrectly considered as successfully importing for notification purposes
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game.Tests/Database/BeatmapImporterTests.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Database/IModelImporter.cs
Labels: area:database, size/M

#15564 Nerf dropped sliders in osu! difficulty calculation
  osu.Game.Rulesets.Osu.Tests/OsuDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyAttributes.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyCalculator.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuPerformanceCalculator.cs
  osu.Game.Rulesets.Osu/Difficulty/Preprocessing/OsuDifficultyHitObject.cs
  osu.Game.Rulesets.Osu/Difficulty/Skills/Aim.cs
Labels: ruleset:osu!, area:difficulty, size/M

#15595 Rename `OnlineID` storage to match interface
  osu.Game.Tests/Beatmaps/Formats/LegacyBeatmapDecoderTest.cs
  osu.Game.Tests/Beatmaps/Formats/OsuJsonDecoderTest.cs
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game.Tests/Beatmaps/IO/OszArchiveReaderTest.cs
  osu.Game.Tests/NonVisual/BeatmapSetInfoEqualityTest.cs
  osu.Game.Tests/NonVisual/Filtering/FilterMatchingTest.cs
  osu.Game.Tests/Online/TestSceneBeatmapManager.cs
  osu.Game.Tests/Online/TestSceneOnlinePlayBeatmapAvailabilityTracker.cs
  osu.Game.Tests/Visual/Gameplay/TestScenePlayerScoreSubmission.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSpectator.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiSpectatorScreen.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerGameplayLeaderboard.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerGameplayLeaderboardTeams.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerMatchSongSelect.cs
  osu.Game.Tests/Visual/Multiplayer/TestScenePlaylistsSongSelect.cs
  osu.Game.Tests/Visual/Navigation/TestScenePerformFromScreen.cs
  osu.Game.Tests/Visual/Navigation/TestScenePresentBeatmap.cs
  osu.Game.Tests/Visual/Navigation/TestScenePresentScore.cs
  osu.Game.Tests/Visual/Online/TestSceneDirectDownloadButton.cs
  osu.Game.Tests/Visual/Online/TestSceneNowPlayingCommand.cs
  osu.Game.Tests/Visual/Playlists/TestScenePlaylistsRoomCreation.cs
  osu.Game.Tests/Visual/Ranking/TestSceneResultsScreen.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapLeaderboard.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapRecommendations.cs
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
  osu.Game/Beatmaps/BeatmapDifficultyCache.cs
  osu.Game/Beatmaps/BeatmapInfo.cs
  osu.Game/Beatmaps/BeatmapModelManager.cs
  osu.Game/Beatmaps/BeatmapOnlineLookupQueue.cs
  osu.Game/Beatmaps/BeatmapSetInfo.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapDecoder.cs
  osu.Game/Beatmaps/Formats/LegacyBeatmapEncoder.cs
  osu.Game/Database/OsuDbContext.cs
  osu.Game/Online/BeatmapDownloadTracker.cs
  osu.Game/Online/Chat/NowPlayingCommand.cs
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
  osu.Game/Online/Rooms/OnlinePlayBeatmapAvailabilityTracker.cs
  osu.Game/Online/Spectator/SpectatorClient.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/BeatmapListing/Panels/BeatmapPanelDownloadButton.cs
  osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsPlayer.cs
  osu.Game/Screens/Play/SoloPlayer.cs
  osu.Game/Screens/Play/SoloSpectator.cs
  osu.Game/Screens/Ranking/SoloResultsScreen.cs
  osu.Game/Screens/Select/BeatmapDetails.cs
  osu.Game/Screens/Select/Carousel/CarouselBeatmap.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmap.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmapSet.cs
  osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboard.cs
  osu.Game/Screens/Spectate/SpectatorScreen.cs
  osu.Game/Stores/BeatmapImporter.cs
  osu.Game/Tests/Beatmaps/TestBeatmap.cs
  osu.Game/Tests/Visual/Multiplayer/TestMultiplayerClient.cs
  osu.Game/Tests/Visual/OsuTestScene.cs
Labels: type:code-quality, size/L

#15555 Audio feedback improvements for song select
  osu.Android.props
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/Screens/Play/SkipOverlay.cs
  osu.Game/Screens/Select/Carousel/CarouselHeader.cs
  osu.Game/Screens/Select/SongSelect.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/M, type:audio

#15591 Fix android score imports not working
  osu.Game/Database/ImportTask.cs
  osu.Game/IO/Archives/LegacyByteArrayReader.cs
  osu.Game/Utils/ZipUtils.cs
Labels: area:database, platform:android, size/M

#15597 Update difficulty colour spectrum
  osu.Game/Graphics/OsuColour.cs
Labels: type:UI, size/S

#15559 Fix settings header localised text potentially overflowing out of the settings panel
  osu.Game/Overlays/Settings/SettingsHeader.cs
Labels: type:UI, type:localisation, size/M

#15607 Improve transition between editor and gameplay test screens
  osu.Game.Tests/Visual/Editing/TestSceneEditorTestGameplay.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/GameplayTest/EditorPlayer.cs
  osu.Game/Screens/Edit/GameplayTest/EditorPlayerLoader.cs
  osu.Game/Screens/Edit/GameplayTest/SaveBeforeGameplayTestDialog.cs
  osu.Game/Screens/Play/PlayerLoader.cs
Labels: area:editor, type:UX, size/L

#15601 Allow adjusting slider velocities of multiple objects at once
  osu.Game.Tests/Visual/Editing/TestSceneHitObjectDifficultyPointAdjustments.cs
  osu.Game/Graphics/UserInterface/OsuSliderBar.cs
  osu.Game/Screens/Edit/Compose/Components/Timeline/DifficultyPointPiece.cs
  osu.Game/Screens/Edit/Timing/IndeterminateSliderWithTextBoxInput.cs
  osu.Game/Utils/FormatUtils.cs
Labels: area:editor, type:UX, size/L

#15614 Fix frequency ramping a second time incorrectly after fail animation
  osu.Game.Tests/Visual/Gameplay/TestSceneFailAnimation.cs
  osu.Game/Screens/Play/FailAnimation.cs
Labels: area:gameplay, size/S, type:audio

#15609 Transfer beatmap track time between editor and gameplay test screens
  osu.Game.Tests/Visual/Editing/TestSceneEditorTestGameplay.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/GameplayTest/EditorPlayer.cs
  osu.Game/Screens/Edit/GameplayTest/EditorPlayerLoader.cs
Labels: area:gameplay, area:editor, size/M

#15608 Allow adjusting sample volume & bank of multiple objects at once
  osu.Game.Tests/Visual/Editing/TestSceneHitObjectSamplePointAdjustments.cs
  osu.Game/Screens/Edit/Compose/Components/Timeline/SamplePointPiece.cs
  osu.Game/Screens/Edit/Timing/IndeterminateSliderWithTextBoxInput.cs
Labels: area:editor, type:UX, size/L

#15631 Expose more of `WorkingBeatmap` via interface
  osu.Game/Beatmaps/IWorkingBeatmap.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
Labels: type:code-quality, size/M

#15594 Add `IBeatmapInfo`/`IBeatmapSetInfo` equality support and update `BeatmapCollection` to use interface types
  osu.Game.Tests/NonVisual/BeatmapSetInfoEqualityTest.cs
  osu.Game/Beatmaps/BeatmapInfo.cs
  osu.Game/Beatmaps/BeatmapSetInfo.cs
  osu.Game/Beatmaps/IBeatmapInfo.cs
  osu.Game/Beatmaps/IBeatmapSetInfo.cs
  osu.Game/Collections/BeatmapCollection.cs
  osu.Game/Collections/CollectionFilterDropdown.cs
  osu.Game/Database/IHasOnlineID.cs
  osu.Game/Extensions/ModelExtensions.cs
  osu.Game/Models/RealmBeatmap.cs
  osu.Game/Models/RealmBeatmapSet.cs
  osu.Game/Online/API/Requests/Responses/APIBeatmap.cs
  osu.Game/Online/API/Requests/Responses/APIBeatmapSet.cs
  osu.Game/Online/API/Requests/Responses/APIUser.cs
  osu.Game/Overlays/BeatmapListing/Panels/BeatmapPanelDownloadButton.cs
  osu.Game/Overlays/BeatmapSet/BeatmapPicker.cs
  osu.Game/Overlays/BeatmapSet/BeatmapRulesetTabItem.cs
  osu.Game/Overlays/Music/Playlist.cs
  osu.Game/Screens/OnlinePlay/Lounge/Components/RoomsContainer.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsPlayer.cs
  osu.sln.DotSettings
Labels: type:code-quality, size/L

#15627 Update `PlaylistItem` to use `IRulesetInfo`
  osu.Game/Online/Rooms/MultiplayerScore.cs
  osu.Game/Online/Rooms/PlaylistItem.cs
  osu.Game/Screens/OnlinePlay/DrawableRoomPlaylistItem.cs
  osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsResultsScreen.cs
Labels: type:code-quality, size/S

#15630 Fix `TestSceneBeatmapRecommendations` testing with an online ID of 0
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapRecommendations.cs
Labels: type:code-quality, size/S

#15632 Update `DifficultyCalculator` to take an `IRulesetInfo` and `IWorkingBeatmap`
  Templates/Rulesets/ruleset-empty/osu.Game.Rulesets.EmptyFreeform/EmptyFreeformDifficultyCalculator.cs
  Templates/Rulesets/ruleset-empty/osu.Game.Rulesets.EmptyFreeform/EmptyFreeformRuleset.cs
  Templates/Rulesets/ruleset-example/osu.Game.Rulesets.Pippidon/PippidonDifficultyCalculator.cs
  Templates/Rulesets/ruleset-example/osu.Game.Rulesets.Pippidon/PippidonRuleset.cs
  Templates/Rulesets/ruleset-scrolling-empty/osu.Game.Rulesets.EmptyScrolling/EmptyScrollingDifficultyCalculator.cs
  Templates/Rulesets/ruleset-scrolling-empty/osu.Game.Rulesets.EmptyScrolling/EmptyScrollingRuleset.cs
  Templates/Rulesets/ruleset-scrolling-example/osu.Game.Rulesets.Pippidon/PippidonDifficultyCalculator.cs
  Templates/Rulesets/ruleset-scrolling-example/osu.Game.Rulesets.Pippidon/PippidonRuleset.cs
  osu.Game.Rulesets.Catch.Tests/CatchDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyCalculator.cs
  osu.Game.Rulesets.Mania.Tests/ManiaDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Mania/Difficulty/ManiaDifficultyCalculator.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Osu.Tests/OsuDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyCalculator.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Taiko.Tests/TaikoDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoDifficultyCalculator.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game.Tests/Mods/ModDifficultyAdjustTest.cs
  osu.Game.Tests/Online/TestAPIModJsonSerialization.cs
  osu.Game.Tests/Online/TestAPIModMessagePackSerialization.cs
  osu.Game.Tests/Testing/TestSceneRulesetDependencies.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneDrawableScrollingRuleset.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneKeyBindings.cs
  osu.Game.Tests/Visual/Gameplay/TestScenePoolingRuleset.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneModSettings.cs
  osu.Game/Beatmaps/DummyWorkingBeatmap.cs
  osu.Game/Beatmaps/IWorkingBeatmap.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Rulesets/Difficulty/DifficultyCalculator.cs
  osu.Game/Rulesets/Ruleset.cs
  osu.Game/Screens/Play/HUD/PerformancePointsCounter.cs
  osu.Game/Tests/Beatmaps/DifficultyCalculatorTest.cs
Labels: type:code-quality, size/M

#15649 Fix song select leaderboard potentially displaying outdated or incorrect content
  osu.Game/Screens/Select/Leaderboards/BeatmapLeaderboard.cs
Labels: size/XS, type:reliability

#15650 Fix `StandAloneChatDisplay`'s `TextBox` having different corner radius
  osu.Game/Online/Chat/StandAloneChatDisplay.cs
Labels: type:UI

#15633 Add difficulty attribute formatting
  osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyAttributes.cs
  osu.Game.Rulesets.Mania/Difficulty/ManiaDifficultyAttributes.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyAttributes.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoDifficultyAttributes.cs
  osu.Game/Rulesets/Difficulty/DifficultyAttributes.cs
Labels: type:code-quality, area:difficulty, size/L

#15655 Disable cancelling of update via notification
  osu.Desktop/Updater/SquirrelUpdateManager.cs
Labels: type:UI, size/S

#15634 Update all simple cases of switching to `IWorkingBeatmap`
  osu.Game.Rulesets.Catch.Tests/TestSceneDrawableHitObjects.cs
  osu.Game.Rulesets.Taiko.Tests/DrawableTaikoRulesetTestScene.cs
  osu.Game.Tests/Skins/TestSceneBeatmapSkinResources.cs
  osu.Game.Tests/Visual/Editing/TestSceneHitObjectComposer.cs
  osu.Game.Tests/Visual/Editing/TestSceneWaveform.cs
  osu.Game.Tests/Visual/Gameplay/TestScenePlayerLoader.cs
  osu.Game.Tests/Visual/Gameplay/TestScenePlayerReferenceLeaking.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneStoryboard.cs
  osu.Game.Tests/Visual/Menus/TestSceneMusicActionHandling.cs
  osu.Game.Tests/Visual/Navigation/TestScenePresentBeatmap.cs
  osu.Game.Tests/Visual/Navigation/TestSceneScreenNavigation.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapMetadataDisplay.cs
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
  osu.Game/Beatmaps/BeatmapDifficultyCache.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/Drawables/BeatmapBackgroundSprite.cs
  osu.Game/Online/Chat/NowPlayingCommand.cs
  osu.Game/Screens/Play/BeatmapMetadataDisplay.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Select/BeatmapInfoWedgeBackground.cs
  osu.Game/Screens/Select/Carousel/SetPanelBackground.cs
  osu.Game/Screens/Select/SongSelect.cs
  osu.Game/Storyboards/Storyboard.cs
  osu.Game/Users/UserActivity.cs
Labels: type:code-quality, size/L

#15648 Highlight invalid playlist items during room creation
  osu.Game.Tests/Visual/Multiplayer/TestSceneDrawableRoomPlaylist.cs
  osu.Game.Tests/Visual/Playlists/TestScenePlaylistsMatchSettingsOverlay.cs
  osu.Game/Online/Rooms/PlaylistItem.cs
  osu.Game/Screens/OnlinePlay/DrawableRoomPlaylistItem.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsRoomSettingsOverlay.cs
Labels: type:UX, size/L, area:playlists

#15657 Expose LegacyScoreDecoder.PopulateAccuracy()
  osu.Game/Scoring/Legacy/LegacyScoreDecoder.cs
Labels: type:code-quality, size/S

#15664 Link osu!supporter icon to its web page
  osu.Game/Overlays/Profile/Header/Components/SupporterIcon.cs
Labels: type:UI, area:overlay-user-profile, size/M

#15668 Update `KeyBindingContainer` usage to block key repeat where applicable
  osu.Android.props
  osu.Game.Tests/Visual/Gameplay/TestSceneKeyBindings.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneReplayRecorder.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneReplayRecording.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSpectatorPlayback.cs
  osu.Game/Extensions/DrawableExtensions.cs
  osu.Game/Graphics/Containers/OsuFocusedOverlayContainer.cs
  osu.Game/Graphics/ScreenshotManager.cs
  osu.Game/Graphics/UserInterface/BackButton.cs
  osu.Game/Graphics/UserInterface/FocusedTextBox.cs
  osu.Game/Graphics/UserInterfaceV2/OsuPopover.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/ChangelogOverlay.cs
  osu.Game/Overlays/DialogOverlay.cs
  osu.Game/Overlays/Music/MusicKeyBindingHandler.cs
  osu.Game/Overlays/Volume/VolumeControlReceptor.cs
  osu.Game/Rulesets/UI/RulesetInputManager.cs
  osu.Game/Rulesets/UI/Scrolling/DrawableScrollingRuleset.cs
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Menu/ButtonSystem.cs
  osu.Game/Screens/Menu/ExitConfirmOverlay.cs
  osu.Game/Screens/OnlinePlay/Lounge/Components/RoomsContainer.cs
  osu.Game/Screens/OnlinePlay/Lounge/DrawableLoungeRoom.cs
  osu.Game/Screens/OnlinePlay/Match/Components/CreateRoomButton.cs
  osu.Game/Screens/OnlinePlay/Match/Components/RoomSettingsOverlay.cs
  osu.Game/Screens/Play/HUD/HoldForMenuButton.cs
  osu.Game/Screens/Play/HUDOverlay.cs
  osu.Game/Screens/Play/HotkeyExitOverlay.cs
  osu.Game/Screens/Play/HotkeyRetryOverlay.cs
  osu.Game/Screens/Play/ReplayPlayer.cs
  osu.Game/Screens/Play/SkipOverlay.cs
  osu.Game/Screens/Ranking/ResultsScreen.cs
  osu.Game/Screens/Select/BeatmapCarousel.cs
  osu.Game/Screens/Select/SongSelect.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: type:input, size/L

#15670 Fix score panels sometimes jumping when toggling statistics fast
  osu.Game/Screens/Ranking/ResultsScreen.cs
Labels: type:UI, area:results, size/XS

#15494 Add support for cancellation tokens for beatmap difficulty calculation
  osu.Game.Tests/Beatmaps/WorkingBeatmapTest.cs
  osu.Game/Beatmaps/BeatmapDifficultyCache.cs
  osu.Game/Beatmaps/IWorkingBeatmap.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Rulesets/Difficulty/DifficultyCalculator.cs
  osu.Game/Rulesets/Difficulty/TimedDifficultyAttributes.cs
  osu.Game/Screens/Play/HUD/PerformancePointsCounter.cs
Labels: type:performance, area:difficulty, size/L

#15624 Fix banana showers not clearing the plate when missing the last banana
  osu.Game.Rulesets.Catch.Tests/TestSceneCatcher.cs
  osu.Game.Rulesets.Catch/UI/Catcher.cs
  osu.Game.Rulesets.Catch/UI/CatcherArea.cs
Labels: ruleset:osu!catch, size/M

#15678 Fix potential null reference in `FadeAccessibleBackground` test class
  osu.Game.Tests/Visual/Background/TestSceneUserDimBackgrounds.cs
Labels: size/XS

#15680 Run nunit in blame mode
  .github/workflows/ci.yml
Labels: type:testing, size/XS

#15677 Only show user displayable portion of server errors when selecting a song in multiplayer
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSongSelect.cs
Labels: type:UX, area:multiplayer, size/S

#15676 Show better error message when selecting an unavailable beatmap during multiplayer room creation
  osu.Game/Migrations/20180628011956_RemoveNegativeSetIDs.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Match/MultiplayerMatchSettingsOverlay.cs
Labels: area:multiplayer, size/S

#15687 Update all dependencies
  Templates/Rulesets/ruleset-empty/osu.Game.Rulesets.EmptyFreeform.Tests/osu.Game.Rulesets.EmptyFreeform.Tests.csproj
  Templates/Rulesets/ruleset-example/osu.Game.Rulesets.Pippidon.Tests/osu.Game.Rulesets.Pippidon.Tests.csproj
  Templates/Rulesets/ruleset-scrolling-empty/osu.Game.Rulesets.EmptyScrolling.Tests/osu.Game.Rulesets.EmptyScrolling.Tests.csproj
  Templates/Rulesets/ruleset-scrolling-example/osu.Game.Rulesets.Pippidon.Tests/osu.Game.Rulesets.Pippidon.Tests.csproj
  osu.Game.Benchmarks/osu.Game.Benchmarks.csproj
  osu.Game.Rulesets.Catch.Tests/osu.Game.Rulesets.Catch.Tests.csproj
  osu.Game.Rulesets.Mania.Tests/osu.Game.Rulesets.Mania.Tests.csproj
  osu.Game.Rulesets.Osu.Tests/osu.Game.Rulesets.Osu.Tests.csproj
  osu.Game.Rulesets.Taiko.Tests/osu.Game.Rulesets.Taiko.Tests.csproj
  osu.Game.Tests/osu.Game.Tests.csproj
  osu.Game.Tournament.Tests/osu.Game.Tournament.Tests.csproj
  osu.Game/osu.Game.csproj
Labels: size/M

#15689 Update dependencies in mobile props files
  osu.Android.props
  osu.iOS.props
Labels: size/S

#15581 Update iOS native references and linker flags in line with framework changes
  .idea/.idea.osu.iOS/.idea/.name
  .idea/.idea.osu.iOS/.idea/indexLayout.xml
  .idea/.idea.osu.iOS/.idea/misc.xml
  .idea/.idea.osu.iOS/.idea/projectSettingsUpdater.xml
  .idea/.idea.osu.iOS/.idea/vcs.xml
  osu.Game.Rulesets.Catch.Tests.iOS/Application.cs
  osu.Game.Rulesets.Mania.Tests.iOS/Application.cs
  osu.Game.Rulesets.Osu.Tests.iOS/Application.cs
  osu.Game.Rulesets.Taiko.Tests.iOS/Application.cs
  osu.Game.Tests.iOS/Application.cs
  osu.iOS.props
  osu.iOS/Application.cs
Labels: platform:iOS, size/M

#15679 Move `StoragePath` implementation to an extension method
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game.Tests/Database/BeatmapImporterTests.cs
  osu.Game.Tests/Database/FileStoreTests.cs
  osu.Game/Beatmaps/BeatmapModelManager.cs
  osu.Game/Beatmaps/BeatmapSetInfo.cs
  osu.Game/Database/ArchiveModelManager.cs
  osu.Game/Extensions/ModelExtensions.cs
  osu.Game/IO/FileInfo.cs
  osu.Game/IO/FileStore.cs
  osu.Game/Models/RealmBeatmapSet.cs
  osu.Game/Models/RealmFile.cs
  osu.Game/Rulesets/Edit/Checks/CheckTooShortAudioFiles.cs
  osu.Game/Rulesets/Edit/Checks/CheckZeroByteFiles.cs
  osu.Game/Scoring/LegacyDatabasedScore.cs
  osu.Game/Scoring/ScoreModelManager.cs
  osu.Game/Skinning/LegacySkinResourceStore.cs
  osu.Game/Skinning/Skin.cs
  osu.Game/Skinning/SkinManager.cs
  osu.Game/Stores/BeatmapImporter.cs
  osu.Game/Stores/RealmArchiveModelImporter.cs
  osu.Game/Stores/RealmFileStore.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardVideo.cs
  osu.Game/Storyboards/Storyboard.cs
Labels: type:code-quality, size/M

#15705 Fix zero star difficulty values being cached when diffcalc was interrupted
  osu.Game.Tests/Beatmaps/TestSceneBeatmapDifficultyCache.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapMetadataDisplay.cs
  osu.Game/Beatmaps/BeatmapDifficultyCache.cs
  osu.Game/Scoring/ScoreManager.cs
  osu.Game/Scoring/ScorePerformanceCache.cs
  osu.Game/Screens/Ranking/Expanded/ExpandedPanelMiddleContent.cs
  osu.Game/Screens/Select/Details/AdvancedStats.cs
Labels: area:beatmap, size/M, type:reliability

#15711 Stop persisting `Skill`s in `DifficultyAttributes`
  Templates/Rulesets/ruleset-empty/osu.Game.Rulesets.EmptyFreeform/EmptyFreeformDifficultyCalculator.cs
  Templates/Rulesets/ruleset-example/osu.Game.Rulesets.Pippidon/PippidonDifficultyCalculator.cs
  Templates/Rulesets/ruleset-scrolling-empty/osu.Game.Rulesets.EmptyScrolling/EmptyScrollingDifficultyCalculator.cs
  Templates/Rulesets/ruleset-scrolling-example/osu.Game.Rulesets.Pippidon/PippidonDifficultyCalculator.cs
  osu.Game.Rulesets.Catch/Difficulty/CatchDifficultyCalculator.cs
  osu.Game.Rulesets.Mania/Difficulty/ManiaDifficultyCalculator.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyCalculator.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoDifficultyCalculator.cs
  osu.Game/Rulesets/Difficulty/DifficultyAttributes.cs
  osu.Game/Rulesets/Difficulty/Skills/Skill.cs
Labels: size/M

#15684 Fix MessagePack workaround formatter potentially initializing on iOS
  osu.Game/Online/SignalRDerivedTypeWorkaroundJsonConverter.cs
  osu.Game/Online/SignalRUnionWorkaroundResolver.cs
  osu.Game/Online/SignalRWorkaroundTypes.cs
Labels: type:online, platform:iOS, size/M

#15707 Clean up cancellation handling in `WorkingBeatmap.GetPlayableBeatmap()`
  osu.Game.Tests/Beatmaps/WorkingBeatmapTest.cs
  osu.Game/Beatmaps/BeatmapDifficultyCache.cs
  osu.Game/Beatmaps/IWorkingBeatmap.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Screens/Play/HUD/PerformancePointsCounter.cs
Labels: type:code-quality, area:beatmap, size/M, type:reliability

#15529 Implement behaviour of beatmap card download button
  osu.Game.Tests/Visual/Beatmaps/TestSceneBeatmapCard.cs
  osu.Game.Tests/Visual/Beatmaps/TestSceneBeatmapCardDownloadButton.cs
  osu.Game/Beatmaps/Drawables/Cards/BeatmapCard.cs
  osu.Game/Beatmaps/Drawables/Cards/BeatmapCardDownloadProgressBar.cs
  osu.Game/Beatmaps/Drawables/Cards/Buttons/BeatmapCardIconButton.cs
  osu.Game/Beatmaps/Drawables/Cards/Buttons/DownloadButton.cs
  osu.Game/Beatmaps/Drawables/Cards/Buttons/GoToBeatmapButton.cs
Labels: type:UI, size/XL, area:overlay-beatmap-listing

#15640 Add ability to change multiplayer queue modes
  osu.Game.Tests/Visual/Multiplayer/QueueModeTestScene.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneAllPlayersQueueMode.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneDrawableRoomPlaylist.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneHostOnlyQueueMode.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayer.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerMatchSubScreen.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerPlayer.cs
  osu.Game/Online/Multiplayer/IMultiplayerClient.cs
  osu.Game/Online/Multiplayer/IMultiplayerRoomServer.cs
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
  osu.Game/Online/Multiplayer/MultiplayerRoom.cs
  osu.Game/Online/Multiplayer/MultiplayerRoomSettings.cs
  osu.Game/Online/Multiplayer/MultiplayerRoomUser.cs
  osu.Game/Online/Multiplayer/OnlineMultiplayerClient.cs
  osu.Game/Online/Multiplayer/QueueMode.cs
  osu.Game/Online/Rooms/MultiplayerPlaylistItem.cs
  osu.Game/Online/Rooms/PlaylistItem.cs
  osu.Game/Online/Rooms/Room.cs
  osu.Game/Screens/OnlinePlay/Components/ReadyButton.cs
  osu.Game/Screens/OnlinePlay/DrawableRoomPlaylist.cs
  osu.Game/Screens/OnlinePlay/DrawableRoomPlaylistItem.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Match/BeatmapSelectionControl.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Match/MultiplayerMatchSettingsOverlay.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Match/MultiplayerReadyButton.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSongSelect.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Participants/ParticipantPanel.cs
  osu.Game/Screens/OnlinePlay/OnlinePlayComposite.cs
  osu.Game/Screens/OnlinePlay/OnlinePlayScreen.cs
  osu.Game/Tests/Visual/Multiplayer/TestMultiplayerClient.cs
  osu.Game/Utils/ModUtils.cs
Labels: type:online, area:multiplayer, size/XXL

#15733 Fix queue mode dropdown not updated on change
  osu.Game.Tests/Visual/Multiplayer/TestSceneHostOnlyQueueMode.cs
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
Labels: area:multiplayer, size/S

#15737 Use `Equals` in carousel tests for better realm compatibility
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
Labels: type:testing, size/M

#15739 Fix realm applying migrations from one version too early
  osu.Game/Database/RealmContextFactory.cs
Labels: area:database, size/XS

#15736 Use `Ruleset`'s `ShortName` for mod caching purposes
  osu.Game/Rulesets/Ruleset.cs
Labels: area:database, size/XS

#15735 Remove subclassing of `RulesetInfo`
  osu.Game.Tests/Visual/Gameplay/TestSceneReplayRecorder.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneReplayRecording.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSpectatorPlayback.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneModSettings.cs
  osu.Game/Beatmaps/DummyWorkingBeatmap.cs
  osu.Game/Rulesets/RulesetInfo.cs
Labels: type:code-quality, area:database, size/L

#15734 Add helper property to access a realm beatmap's beatmap file
  osu.Game.Tests/Database/BeatmapImporterTests.cs
  osu.Game/Database/RealmContextFactory.cs
  osu.Game/Models/RealmBeatmap.cs
Labels: area:database, size/M

#15752 Rename `Debug` namespace to avoid collisions
  osu.Game/Overlays/Settings/Sections/DebugSection.cs
  osu.Game/Overlays/Settings/Sections/DebugSettings/GeneralSettings.cs
  osu.Game/Overlays/Settings/Sections/DebugSettings/MemorySettings.cs
Labels: type:code-quality, size/XS

#15756 Remove usage of `Nuget.Packaging` extension methods for `IList.AddRange`
  CodeAnalysis/BannedSymbols.txt
  osu.Game/Extensions/CollectionExtensions.cs
  osu.Game/Stores/BeatmapImporter.cs
  osu.Game/Stores/RealmArchiveModelImporter.cs
Labels: type:code-quality, size/S

#15753 Restructure how the headless storage is used / documented to hopefully make more sense
  osu.Game/Tests/Visual/OsuTestScene.cs
Labels: size/M

#15745 Fix crashes on trying to play back replays of seeded mods with seed value over 1 billion
  osu.Game.Tests/Visual/Settings/TestSceneSettingsNumberBox.cs
  osu.Game/Overlays/Settings/SettingsNumberBox.cs
Labels: area:mods, size/M, type:reliability

#15754 Fix tournament tests potentially using data left over from previous runs
  osu.Game.Tournament.Tests/NonVisual/CustomTourneyDirectoryTest.cs
  osu.Game.Tournament.Tests/NonVisual/IPCLocationTest.cs
  osu.Game.Tournament.Tests/NonVisual/TournamentHostTest.cs
Labels: type:testing, size/M

#15740 Switch realm ruleset configuration to use ruleset's `ShortName` as key
  osu.Game/Configuration/RealmRulesetSetting.cs
  osu.Game/Database/RealmContextFactory.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Rulesets/Configuration/RulesetConfigManager.cs
Labels: area:database, size/M

#15757 Fix several intermittent multiplayer test failures
  osu.Game.Tests/NonVisual/Multiplayer/StatefulMultiplayerClientTest.cs
  osu.Game.Tests/Visual/Multiplayer/QueueModeTestScene.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayer.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerMatchSubScreen.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerReadyButton.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneTeamVersus.cs
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerLoungeSubScreen.cs
  osu.Game/Tests/Visual/Multiplayer/MultiplayerTestScene.cs
  osu.Game/Tests/Visual/Multiplayer/TestMultiplayerRoomManager.cs
Labels: type:testing, area:multiplayer, size/L

#15768 Remove nullability of `Ruleset.CreateInstance`
  osu.Game/Beatmaps/Drawables/DifficultySpectrumDisplay.cs
  osu.Game/Models/RealmRuleset.cs
  osu.Game/Overlays/Settings/Sections/Input/RulesetBindingsSection.cs
  osu.Game/Rulesets/IRulesetInfo.cs
  osu.Game/Rulesets/RulesetInfo.cs
  osu.Game/Screens/Edit/Setup/SetupScreen.cs
  osu.Game/Screens/Edit/Verify/IssueList.cs
  osu.Game/Stores/BeatmapImporter.cs
Labels: size/M

#15769 Update cases where equality can be used instead of primary key equality
  osu.Game.Tests/Scores/IO/ImportScoreTest.cs
  osu.Game.Tests/Visual/Navigation/TestScenePresentBeatmap.cs
  osu.Game.Tests/Visual/Navigation/TestScenePresentScore.cs
  osu.Game/Beatmaps/BeatmapDifficultyCache.cs
  osu.Game/Beatmaps/BeatmapModelManager.cs
  osu.Game/Beatmaps/WorkingBeatmapCache.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Overlays/Music/PlaylistOverlay.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Overlays/Profile/Header/Components/ProfileRulesetSelector.cs
  osu.Game/Overlays/Settings/Sections/SkinSection.cs
  osu.Game/Screens/Select/BeatmapCarousel.cs
Labels: size/M

#15770 Fix incorrect usage of `ID` in `TestSceneMultiplayerResults`
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerResults.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerTeamResults.cs
Labels: size/XS

#15741 Switch realm ruleset key bindings to use ruleset's `ShortName` as key
  osu.Game/Database/RealmContextFactory.cs
  osu.Game/Input/Bindings/DatabasedKeyBindingContainer.cs
  osu.Game/Input/Bindings/RealmKeyBinding.cs
  osu.Game/Input/RealmKeyBindingStore.cs
  osu.Game/Overlays/Settings/Sections/Input/KeyBindingRow.cs
  osu.Game/Overlays/Settings/Sections/Input/KeyBindingsSubsection.cs
  osu.Game/Overlays/Toolbar/ToolbarButton.cs
Labels: area:database, size/M

#15775 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#15771 Update `RulesetConfigCache` to cache via `ShortName` instead of `ID`
  osu.Game/Rulesets/RulesetConfigCache.cs
Labels: size/S

#15777 Revert "Run nunit in blame mode"
  .github/workflows/ci.yml
Labels: type:testing, size/XS

#15760 Move realm data migrations inside the `RealmContextFactory`
  osu.Game/Database/RealmContextFactory.cs
  osu.Game/OsuGameBase.cs
  osu.sln.DotSettings
Labels: size/M

#15772 Initialise `BeatmapSet.Beatmaps` list at construction time
  osu.Game.Tests/Beatmaps/IO/ImportBeatmapTest.cs
  osu.Game.Tests/Online/TestSceneOnlinePlayBeatmapAvailabilityTracker.cs
  osu.Game.Tests/Visual/Menus/TestSceneMusicActionHandling.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerMatchSongSelect.cs
  osu.Game.Tests/Visual/Multiplayer/TestScenePlaylistsSongSelect.cs
  osu.Game.Tests/Visual/Navigation/TestScenePresentBeatmap.cs
  osu.Game.Tests/Visual/Navigation/TestScenePresentScore.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapRecommendations.cs
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/BeatmapModelManager.cs
  osu.Game/Beatmaps/BeatmapSetInfo.cs
  osu.Game/Beatmaps/WorkingBeatmapCache.cs
  osu.Game/Overlays/Music/PlaylistOverlay.cs
  osu.Game/Tests/Beatmaps/TestBeatmap.cs
  osu.Game/Tests/Visual/OsuTestScene.cs
Labels: type:code-quality, size/L

#15776 Make `BeatmapSet.Metadata` non-null
  osu.Game.Tests/Models/DisplayStringTest.cs
  osu.Game/Beatmaps/BeatmapSetInfo.cs
  osu.Game/Beatmaps/IBeatmapSetInfo.cs
  osu.Game/Extensions/ModelExtensions.cs
  osu.Game/Models/RealmBeatmapSet.cs
Labels: size/S
