Repository ppy/osu, pull requests merged in 2022-08, with the labels that each got.

#19507 Prevent capturing arrow keys on playlist creation.
  osu.Game/Screens/OnlinePlay/DrawableRoomPlaylist.cs
Labels: type:UX, size/XS, area:playlists

#19510 Add persistence of mod presets to realm
  osu.Game.Tests/Visual/UserInterface/TestSceneModPresetColumn.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneModPresetPanel.cs
  osu.Game/Database/RealmAccess.cs
  osu.Game/Overlays/Mods/ModPresetColumn.cs
  osu.Game/Overlays/Mods/ModPresetPanel.cs
  osu.Game/Overlays/Mods/ModPresetTooltip.cs
  osu.Game/Rulesets/Mods/ModPreset.cs
Labels: area:database, size/L, area:overlay-modselect

#19407 Remove nullable disable annotation in mods for osu ruleset.
  osu.Game.Rulesets.Osu.Tests/Mods/OsuModTestScene.cs
  osu.Game.Rulesets.Osu.Tests/Mods/TestSceneOsuModAlternate.cs
  osu.Game.Rulesets.Osu.Tests/Mods/TestSceneOsuModAutoplay.cs
  osu.Game.Rulesets.Osu.Tests/Mods/TestSceneOsuModDifficultyAdjust.cs
  osu.Game.Rulesets.Osu.Tests/Mods/TestSceneOsuModDoubleTime.cs
  osu.Game.Rulesets.Osu.Tests/Mods/TestSceneOsuModHidden.cs
  osu.Game.Rulesets.Osu.Tests/Mods/TestSceneOsuModMagnetised.cs
  osu.Game.Rulesets.Osu.Tests/Mods/TestSceneOsuModMuted.cs
  osu.Game.Rulesets.Osu.Tests/Mods/TestSceneOsuModNoScope.cs
  osu.Game.Rulesets.Osu.Tests/Mods/TestSceneOsuModPerfect.cs
  osu.Game.Rulesets.Osu.Tests/Mods/TestSceneOsuModSpunOut.cs
  osu.Game.Rulesets.Osu/Mods/IHidesApproachCircles.cs
  osu.Game.Rulesets.Osu/Mods/IRequiresApproachCircles.cs
  osu.Game.Rulesets.Osu/Mods/OsuModApproachDifferent.cs
  osu.Game.Rulesets.Osu/Mods/OsuModAutopilot.cs
  osu.Game.Rulesets.Osu/Mods/OsuModAutoplay.cs
  osu.Game.Rulesets.Osu/Mods/OsuModBarrelRoll.cs
  osu.Game.Rulesets.Osu/Mods/OsuModBlinds.cs
  osu.Game.Rulesets.Osu/Mods/OsuModCinema.cs
  osu.Game.Rulesets.Osu/Mods/OsuModClassic.cs
  osu.Game.Rulesets.Osu/Mods/OsuModDaycore.cs
  osu.Game.Rulesets.Osu/Mods/OsuModDeflate.cs
  osu.Game.Rulesets.Osu/Mods/OsuModDifficultyAdjust.cs
  osu.Game.Rulesets.Osu/Mods/OsuModDoubleTime.cs
  osu.Game.Rulesets.Osu/Mods/OsuModEasy.cs
  osu.Game.Rulesets.Osu/Mods/OsuModFlashlight.cs
  osu.Game.Rulesets.Osu/Mods/OsuModGrow.cs
  osu.Game.Rulesets.Osu/Mods/OsuModHalfTime.cs
  osu.Game.Rulesets.Osu/Mods/OsuModHardRock.cs
  osu.Game.Rulesets.Osu/Mods/OsuModHidden.cs
  osu.Game.Rulesets.Osu/Mods/OsuModMagnetised.cs
  osu.Game.Rulesets.Osu/Mods/OsuModMirror.cs
  osu.Game.Rulesets.Osu/Mods/OsuModMuted.cs
  osu.Game.Rulesets.Osu/Mods/OsuModNightcore.cs
  osu.Game.Rulesets.Osu/Mods/OsuModNoFail.cs
  osu.Game.Rulesets.Osu/Mods/OsuModNoScope.cs
  osu.Game.Rulesets.Osu/Mods/OsuModObjectScaleTween.cs
  osu.Game.Rulesets.Osu/Mods/OsuModPerfect.cs
  osu.Game.Rulesets.Osu/Mods/OsuModRelax.cs
  osu.Game.Rulesets.Osu/Mods/OsuModSpinIn.cs
  osu.Game.Rulesets.Osu/Mods/OsuModSpunOut.cs
  osu.Game.Rulesets.Osu/Mods/OsuModStrictTracking.cs
  osu.Game.Rulesets.Osu/Mods/OsuModSuddenDeath.cs
  osu.Game.Rulesets.Osu/Mods/OsuModTarget.cs
  osu.Game.Rulesets.Osu/Mods/OsuModTouchDevice.cs
  osu.Game.Rulesets.Osu/Mods/OsuModTraceable.cs
  osu.Game.Rulesets.Osu/Mods/OsuModTransform.cs
  osu.Game.Rulesets.Osu/Mods/OsuModWiggle.cs
Labels: type:code-quality, ruleset:osu!, area:mods, size/L

#19467 Allow osu!taiko hitsounds to fall back to classic skin rather than use non-taiko samples
  osu.Game.Rulesets.Taiko.Tests/TestSceneTaikoHitObjectSamples.cs
  osu.Game.Rulesets.Taiko/Skinning/Legacy/TaikoLegacySkinTransformer.cs
Labels: ruleset:osu!taiko, area:gameplay, size/S, type:audio

#19504 Add test coverage of deserialisation of skin layouts
  osu.Game.Tests/Resources/Archives/modified-classic-20220723.osk
  osu.Game.Tests/Resources/Archives/modified-classic-20220801.osk
  osu.Game.Tests/Resources/Archives/modified-default-20220723.osk
  osu.Game.Tests/Skins/SkinDeserialisationTest.cs
  osu.Game/Screens/Play/HUD/SkinnableInfo.cs
  osu.Game/Skinning/Editor/SkinComponentToolbox.cs
Labels: type:testing, area:skinning, size/L

#19513 Isolate development builds' storage from release builds
  osu.Desktop/Program.cs
  osu.Game/OsuGameBase.cs
Labels: area:tooling, size/XS

#19514 Fix migration failing on single file copy failure
  osu.Game/IO/MigratableStorage.cs
Labels: size/S, type:reliability

#19517 Add more missing realm `Refresh()` calls to new beatmap import tests
  osu.Game.Tests/Database/BeatmapImporterTests.cs
Labels: size/XS

#19516 Fix editor potentially playing a track post-disposal
  osu.Game.Tests/Visual/Editing/TestSceneEditorBeatmapCreation.cs
  osu.Game/Overlays/MusicController.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/Setup/ResourcesSection.cs
Labels: size/M, type:reliability

#19508 Prevent tags overflowing on beatmap info overlay
  osu.Game/Overlays/BeatmapSet/Info.cs
Labels: type:UI, size/XS, area:overlay-beatmap

#19262 Imitate stable's slider followcircle tick-based behavior
  osu.Game.Rulesets.Osu/Skinning/Default/DefaultFollowCircle.cs
  osu.Game.Rulesets.Osu/Skinning/FollowCircle.cs
  osu.Game.Rulesets.Osu/Skinning/Legacy/LegacyFollowCircle.cs
Labels: ruleset:osu!, area:skinning, size/L

#19500 Remove nullable disable annotation in audio namespace
  osu.Game.Tests/Audio/SampleInfoEqualityTest.cs
  osu.Game/Audio/Effects/AudioFilter.cs
  osu.Game/Audio/Effects/ITransformableFilter.cs
  osu.Game/Audio/IPreviewTrackOwner.cs
  osu.Game/Audio/ISampleInfo.cs
  osu.Game/Audio/ISamplePlaybackDisabler.cs
  osu.Game/Audio/PreviewTrack.cs
  osu.Game/Audio/PreviewTrackManager.cs
  osu.Game/Audio/SampleInfo.cs
Labels: type:code-quality, size/M

#16589 Add strength setting for wiggle mod
  osu.Game.Rulesets.Osu/Mods/OsuModWiggle.cs
Labels: ruleset:osu!, area:mods, size/S

#19479 Fix song select not updating selected beatmap card on editor resume
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: area:song-select, size/M

#19532 Fix newly imported beatmaps not using correct comparer for sorting
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs
  osu.Game/Screens/Select/Carousel/CarouselGroup.cs
Labels: area:song-select, type:UX, size/M

#19538 Fix broken sheared button autosizing logic
  osu.Game.Tests/Visual/UserInterface/TestSceneShearedButtons.cs
  osu.Game/Graphics/UserInterface/ShearedButton.cs
Labels: type:UI, size/S

#19534 Update nullability specifications in osu!catch and osu!taiko mods
  osu.Game.Rulesets.Catch/Mods/CatchModFlashlight.cs
  osu.Game.Rulesets.Catch/Mods/CatchModRelax.cs
  osu.Game.Rulesets.Taiko/Mods/TaikoModFlashlight.cs
  osu.Game.Rulesets.Taiko/Mods/TaikoModHidden.cs
Labels: type:code-quality, ruleset:osu!taiko, ruleset:osu!catch, area:mods, size/S

#19535 Hide F rank from the beatmap overlay
  osu.Game/Overlays/BeatmapListing/BeatmapSearchScoreFilterRow.cs
Labels: size/XS, area:overlay-beatmap

#19536 Fix playlist settings reference leak due to unsafe binding
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsRoomSettingsOverlay.cs
Labels: size/M, type:reliability, area:playlists

#19543 Avoid clearing chat overlay textbox when pressing "back" key binding
  osu.Game/Graphics/UserInterface/FocusedTextBox.cs
  osu.Game/Overlays/Chat/ChatTextBox.cs
Labels: area:overlay-chat, size/XS

#19563 Change migration logic to ignore realm pipe files regardless of database filename
  osu.Game/IO/MigratableStorage.cs
  osu.Game/IO/OsuStorage.cs
Labels: area:database, size/S

#19564 Fix `LegacySongProgress` incorrectly blocking mouse input from gameplay
  osu.Game/Screens/Play/HUD/DefaultSongProgress.cs
  osu.Game/Screens/Play/HUD/SongProgress.cs
Labels: area:gameplay, size/XS

#19522 Display readable error message when reaching download limit
  osu.Game/Database/ModelDownloader.cs
  osu.Game/Database/TooManyDownloadsNotification.cs
  osu.Game/Localisation/CommonStrings.cs
Labels: type:online, type:UX, size/M

#19548 Improve `IBeatSyncProvider` interface and reduce beatmap track dependence
  osu.Game/Beatmaps/BeatSyncProviderExtensions.cs
  osu.Game/Beatmaps/IBeatSyncProvider.cs
  osu.Game/Graphics/Containers/BeatSyncedContainer.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Menu/LogoVisualisation.cs
  osu.Game/Screens/Menu/OsuLogo.cs
  osu.Game/Screens/Play/MasterGameplayClockContainer.cs
Labels: type:code-quality, size/L

#19570 Change all filter control button state test to until steps
  osu.Game.Tests/Visual/SongSelect/TestSceneFilterControl.cs
Labels: type:testing, size/S

#19552 Remove nullable disable in the osu.Desktop
  osu.Desktop/DiscordRichPresence.cs
  osu.Desktop/LegacyIpc/LegacyIpcDifficultyCalculationRequest.cs
  osu.Desktop/LegacyIpc/LegacyIpcDifficultyCalculationResponse.cs
  osu.Desktop/LegacyIpc/LegacyIpcMessage.cs
  osu.Desktop/Program.cs
  osu.Desktop/Security/ElevatedPrivilegesChecker.cs
  osu.Desktop/Updater/SquirrelUpdateManager.cs
  osu.Desktop/Windows/GameplayWinKeyBlocker.cs
  osu.Desktop/Windows/WindowsKey.cs
Labels: type:code-quality, size/M

#19558 Add flow for creating new mod presets
  osu.Game.Tests/Visual/UserInterface/TestSceneModPresetColumn.cs
  osu.Game/Graphics/UserInterface/ShearedToggleButton.cs
  osu.Game/Localisation/CommonStrings.cs
  osu.Game/Localisation/ModSelectOverlayStrings.cs
  osu.Game/Overlays/Mods/AddPresetButton.cs
  osu.Game/Overlays/Mods/AddPresetPopover.cs
  osu.Game/Overlays/Mods/ModPresetColumn.cs
  osu.Game/Overlays/Mods/ModSelectPanel.cs
Labels: type:UI, size/L, area:overlay-modselect

#19574 Ensure skin samples are looked up in correct order
  osu.Game.Tests/Skins/TestSceneSkinResources.cs
  osu.Game/Skinning/Skin.cs
Labels: area:skinning, size/M, type:audio

#19575 Clean up SoloScoreInfo serialised output
  osu.Game/Online/API/Requests/Responses/SoloScoreInfo.cs
Labels: area:scoring, size/S

#19583 Fix `PreviewTrack`s not being disposed correctly
  osu.Game/Audio/PreviewTrack.cs
  osu.Game/Beatmaps/Drawables/Cards/Buttons/PlayButton.cs
  osu.Game/Overlays/BeatmapSet/Buttons/PlayButton.cs
Labels: size/S

#19529 Show "locally modified" pill when local modifications have been made
  osu.Game.Tests/Visual/Editing/TestSceneEditorBeatmapCreation.cs
  osu.Game/Beatmaps/BeatmapInfo.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/BeatmapOnlineStatus.cs
  osu.Game/Beatmaps/BeatmapUpdaterMetadataLookup.cs
  osu.Game/Beatmaps/Drawables/BeatmapSetOnlineStatusPill.cs
  osu.Game/Graphics/OsuColour.cs
  osu.Game/Localisation/SongSelectStrings.cs
Labels: area:song-select, type:UX, size/L

#19587 Adjust pooling to reduce stutters during gameplay on unique hit objects
  osu.Game.Rulesets.Osu/Objects/Drawables/Connections/FollowPointRenderer.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
Labels: type:performance, size/M

#19323 Add missing icons to UserProfileRecentSection
  osu.Game.Tests/Visual/Online/TestSceneUserProfileRecentSection.cs
  osu.Game/Overlays/Profile/Sections/Recent/DrawableRecentActivity.cs
  osu.Game/Overlays/Profile/Sections/Recent/RecentActivityIcon.cs
Labels: type:UI, area:overlay-user-profile, size/L

#19612 Unify implementations of deletion dialogs
  osu.Game.Tests/Visual/Collections/TestSceneManageCollectionsDialog.cs
  osu.Game/Collections/DeleteCollectionDialog.cs
  osu.Game/Localisation/DeleteConfirmationDialogStrings.cs
  osu.Game/Overlays/Dialog/DeleteConfirmationDialog.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/MassDeleteConfirmationDialog.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/MassVideoDeleteConfirmationDialog.cs
  osu.Game/Screens/Select/BeatmapClearScoresDialog.cs
  osu.Game/Screens/Select/BeatmapDeleteDialog.cs
  osu.Game/Screens/Select/LocalScoreDeleteDialog.cs
  osu.Game/Screens/Select/SkinDeleteDialog.cs
Labels: type:code-quality, type:UX, type:localisation, size/L

#19613 Add flow for deleting mod presets
  osu.Game.Tests/Visual/UserInterface/TestSceneModPresetColumn.cs
  osu.Game/Database/RealmAccess.cs
  osu.Game/Overlays/Mods/DeleteModPresetDialog.cs
  osu.Game/Overlays/Mods/ModPresetPanel.cs
Labels: size/L, area:overlay-modselect

#19621 Implement selection logic for mod preset panels
  osu.Game.Tests/Visual/UserInterface/TestSceneModPresetPanel.cs
  osu.Game/Overlays/Mods/ModPresetPanel.cs
Labels: type:UI, size/L, area:overlay-modselect

#19622 Add mod preset column to solo mod select overlay
  osu.Game.Tests/Visual/UserInterface/TestSceneModSelectOverlay.cs
  osu.Game/Localisation/MaintenanceSettingsStrings.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/ModPresetSettings.cs
  osu.Game/Overlays/Settings/Sections/MaintenanceSection.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: size/L, area:overlay-modselect

#19635 Fix possible null assignment inspection in `TestScenePreviewTrackManager`
  osu.Game.Tests/Visual/Components/TestScenePreviewTrackManager.cs
Labels: type:code-quality, size/XS

#19582 Don't serialise empty mod settings
  osu.Game.Tests/Online/TestAPIModJsonSerialization.cs
  osu.Game/Online/API/APIMod.cs
Labels: type:online, area:scoring, size/S

#19560 Apply `IRenderer` changes
  Templates/Rulesets/ruleset-example/osu.Game.Rulesets.Pippidon/PippidonRuleset.cs
  Templates/Rulesets/ruleset-example/osu.Game.Rulesets.Pippidon/PippidonRulesetIcon.cs
  Templates/Rulesets/ruleset-scrolling-example/osu.Game.Rulesets.Pippidon/PippidonRuleset.cs
  Templates/Rulesets/ruleset-scrolling-example/osu.Game.Rulesets.Pippidon/PippidonRulesetIcon.cs
  osu.Android.props
  osu.Game.Rulesets.Mania/Skinning/Legacy/LegacyBodyPiece.cs
  osu.Game.Rulesets.Mania/Skinning/Legacy/LegacyNotePiece.cs
  osu.Game.Rulesets.Osu.Tests/LegacyMainCirclePieceTest.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneCursorTrail.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneGameplayCursor.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneSkinFallbacks.cs
  osu.Game.Rulesets.Osu/UI/Cursor/CursorTrail.cs
  osu.Game.Rulesets.Taiko/Skinning/Legacy/LegacyDrumRoll.cs
  osu.Game.Tests/Editing/Checks/CheckBackgroundQualityTest.cs
  osu.Game.Tests/Gameplay/TestSceneHitObjectAccentColour.cs
  osu.Game.Tests/Gameplay/TestSceneStoryboardSamples.cs
  osu.Game.Tests/NonVisual/Skinning/LegacySkinAnimationTest.cs
  osu.Game.Tests/NonVisual/Skinning/LegacySkinTextureFallbackTest.cs
  osu.Game.Tests/Rulesets/TestSceneDrawableRulesetDependencies.cs
  osu.Game.Tests/Rulesets/TestSceneRulesetSkinProvidingContainer.cs
  osu.Game.Tests/Skins/SkinDeserialisationTest.cs
  osu.Game.Tests/Skins/TestSceneBeatmapSkinLookupDisables.cs
  osu.Game.Tests/Skins/TestSceneSkinConfigurationLookup.cs
  osu.Game.Tests/Skins/TestSceneSkinProvidingContainer.cs
  osu.Game.Tests/Skins/TestSceneSkinResources.cs
  osu.Game.Tests/Visual/Background/TestSceneBackgroundScreenDefault.cs
  osu.Game.Tests/Visual/Background/TestSceneSeasonalBackgroundLoader.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSkinnableDrawable.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSkinnableSound.cs
  osu.Game/Beatmaps/WorkingBeatmapCache.cs
  osu.Game/Graphics/Backgrounds/Triangles.cs
  osu.Game/Graphics/OpenGL/Vertices/PositionAndColourVertex.cs
  osu.Game/Graphics/ParticleExplosion.cs
  osu.Game/Graphics/ParticleSpewer.cs
  osu.Game/Graphics/Sprites/LogoAnimation.cs
  osu.Game/IO/IStorageResourceProvider.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Rulesets/Mods/ModFlashlight.cs
  osu.Game/Rulesets/UI/DrawableRulesetDependencies.cs
  osu.Game/Screens/Edit/EditorBeatmapSkin.cs
  osu.Game/Screens/Menu/LogoVisualisation.cs
  osu.Game/Screens/OnlinePlay/DrawableRoomPlaylistItem.cs
  osu.Game/Skinning/DefaultSkin.cs
  osu.Game/Skinning/IAnimationTimeReference.cs
  osu.Game/Skinning/ISkin.cs
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/Skinning/LegacySkinExtensions.cs
  osu.Game/Skinning/LegacySkinTransformer.cs
  osu.Game/Skinning/ResourceStoreBackedSkin.cs
  osu.Game/Skinning/Skin.cs
  osu.Game/Skinning/SkinManager.cs
  osu.Game/Skinning/SkinProvidingContainer.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboard.cs
  osu.Game/Tests/Beatmaps/HitObjectSampleTest.cs
  osu.Game/Tests/Visual/SkinnableTestScene.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: type:code-quality, size/L

#19637 Fix FPS counter disappearing when hovered over
  osu.Game/Graphics/UserInterface/FPSCounter.cs
Labels: type:UX, size/XS

#19640 Simplify task logic in `ModPresetColumn`
  osu.Game/Overlays/Mods/ModColumn.cs
  osu.Game/Overlays/Mods/ModPresetColumn.cs
Labels: type:code-quality, size/M

#19638 Fix collection import not showing progress notification
  osu.Game/Database/LegacyImportManager.cs
Labels: type:UX, size/M

#19651 Fix spurious sample playbacks from already-removed mod preset panels
  osu.Game.Tests/Visual/UserInterface/TestSceneModPresetColumn.cs
  osu.Game/Overlays/Mods/ModPresetColumn.cs
Labels: size/S, type:audio, area:overlay-modselect

#19642 Adjust visuals of osu!mania barlines to be less present
  osu.Game.Rulesets.Mania.Tests/Skinning/TestSceneBarLine.cs
  osu.Game.Rulesets.Mania/Objects/Drawables/DrawableBarLine.cs
Labels: ruleset:osu!mania, size/L

#19656 Fix gameplay tests crashing when run multiple times
  osu.Game/Tests/Visual/TestPlayer.cs
Labels: type:testing, size/S

#19639 Fix incorrect FPS damping implementation
  osu.Game/Graphics/UserInterface/FPSCounter.cs
Labels: type:UX, size/S

#19658 Display connecting / failing states on toolbar user display
  osu.Game.Tests/Visual/Menus/TestSceneToolbarUserButton.cs
  osu.Game/Graphics/UserInterface/LoadingLayer.cs
  osu.Game/Localisation/ToolbarStrings.cs
  osu.Game/Overlays/Login/LoginPanel.cs
  osu.Game/Overlays/Toolbar/ToolbarUserButton.cs
Labels: type:UI, size/L

#19597 Fix multi-spectator potentially getting stuck for passed players (hotfix)
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiSpectatorScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/MultiSpectatorScreen.cs
Labels: area:multiplayer, size/XS

#19668 Fix host room status showing ended after playing
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
Labels: area:multiplayer, size/XS

#19664 Update multiple tests to use new assert output for easier to understand failures
  osu.Game.Tests/Editing/TestSceneHitObjectComposerDistanceSnapping.cs
  osu.Game.Tests/Visual/Editing/TestSceneEditorClock.cs
  osu.Game.Tests/Visual/Editing/TestSceneEditorSeekSnapping.cs
  osu.Game.Tests/Visual/Editing/TestSceneEditorSeeking.cs
Labels: size/L

#19670 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/S

#19662 Use a placeholder user with the correct username during login process
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Overlays/BeatmapListingOverlay.cs
Labels: type:online, type:UX, size/S

#19669 Handle cancellation at more points during `Player` initialisation
  osu.Game/Screens/Play/Player.cs
Labels: size/XS, type:reliability

#19677 Fix crash when attempting to import on mobile platforms
  osu.Game/Database/LegacyImportManager.cs
Labels: size/XS, type:reliability

#19646 Add missing localisation for settings enums
  osu.Game/Configuration/BackgroundSource.cs
  osu.Game/Configuration/DiscordRichPresenceMode.cs
  osu.Game/Configuration/HUDVisibilityMode.cs
  osu.Game/Configuration/RandomSelectAlgorithm.cs
  osu.Game/Configuration/ScalingMode.cs
  osu.Game/Configuration/ScreenshotFormat.cs
  osu.Game/Configuration/SeasonalBackgroundMode.cs
  osu.Game/Input/OsuConfineMouseMode.cs
  osu.Game/Localisation/CommonStrings.cs
  osu.Game/Localisation/GameplaySettingsStrings.cs
  osu.Game/Localisation/GraphicsSettingsStrings.cs
  osu.Game/Localisation/LayoutSettingsStrings.cs
  osu.Game/Localisation/MouseSettingsStrings.cs
  osu.Game/Localisation/OnlineSettingsStrings.cs
  osu.Game/Localisation/RulesetSettingsStrings.cs
  osu.Game/Localisation/UserInterfaceStrings.cs
  osu.Game/Overlays/Mods/Input/ModSelectHotkeyStyle.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Rulesets/UI/PlayfieldBorderStyle.cs
Labels: size/L

#19678 Fix audio track not correctly advancing when changing between certain beatmaps
  osu.Game.Tests/NonVisual/BeatmapSetInfoEqualityTest.cs
  osu.Game/Beatmaps/BeatmapInfo.cs
  osu.Game/Beatmaps/BeatmapInfoExtensions.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Beatmaps/BeatmapSetInfo.cs
  osu.Game/Beatmaps/BeatmapSetInfoExtensions.cs
  osu.Game/Database/IHasRealmFiles.cs
  osu.Game/Database/ModelManager.cs
  osu.Game/Rulesets/Edit/Checks/CheckAudioInVideo.cs
  osu.Game/Rulesets/Edit/Checks/CheckBackgroundQuality.cs
  osu.Game/Screens/Edit/Setup/ResourcesSection.cs
  osu.Game/Skinning/SkinImporter.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboardVideo.cs
  osu.Game/Storyboards/Storyboard.cs
Labels: size/L

#19586 Version realm files for debug executions
  osu.Game/Database/RealmAccess.cs
Labels: size/M, area:toolbar

#19661 Reorganise global bindings and split out overlay bindings to make things easier to find
  osu.Game/Input/Bindings/GlobalActionContainer.cs
  osu.Game/Localisation/InputSettingsStrings.cs
  osu.Game/Overlays/Settings/Sections/Input/GlobalKeyBindingsSection.cs
  osu.Game/Tests/Visual/TestPlayer.cs
Labels: type:UX, size/M

#19702 Add thread safety to `APIAccess.LocalUser`
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Online/API/IAPIProvider.cs
Labels: size/S, type:reliability

#15666 Add slider bonus to Flashlight skill
  osu.Game.Rulesets.Osu/Difficulty/Evaluators/AimEvaluator.cs
  osu.Game.Rulesets.Osu/Difficulty/Evaluators/FlashlightEvaluator.cs
  osu.Game.Rulesets.Osu/Difficulty/Preprocessing/OsuDifficultyHitObject.cs
Labels: ruleset:osu!, area:difficulty, size/M

#19706 Fix avatar potentially not loading in `LoginOverlay` due to misordered events
  osu.Game/Online/API/APIAccess.cs
Labels: type:online, size/S

#19707 Refactor `APIAccess` main loop to read better
  osu.Game/Online/API/APIAccess.cs
Labels: type:code-quality, size/L

#19001 osu! performance points balancing pass
  osu.Game.Rulesets.Osu.Tests/OsuDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Osu/Difficulty/Evaluators/AimEvaluator.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyCalculator.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuPerformanceCalculator.cs
  osu.Game.Rulesets.Osu/Difficulty/Skills/Aim.cs
Labels: ruleset:osu!, area:difficulty, size/M

#19708 Fix possible null reference inspection
  osu.Game/Input/Bindings/GlobalActionContainer.cs
Labels: area:tooling, size/XS

#19657 Add keybind for showing profile
  osu.Game/Input/Bindings/GlobalActionContainer.cs
  osu.Game/Localisation/GlobalActionKeyBindingStrings.cs
  osu.Game/OsuGame.cs
Labels: size/S

#19717 Update interactive visual test runs to use development directory
  osu.Game/Tests/VisualTestRunner.cs
Labels: type:testing, size/XS

#19715 Adjust various mod multipliers to avoid competition with normal scores
  osu.Game.Rulesets.Mania/Mods/ManiaModConstantSpeed.cs
  osu.Game.Rulesets.Osu/Mods/OsuModAutopilot.cs
  osu.Game.Rulesets.Osu/Mods/OsuModMagnetised.cs
  osu.Game/Rulesets/Mods/ModAdaptiveSpeed.cs
  osu.Game/Rulesets/Mods/ModDifficultyAdjust.cs
  osu.Game/Rulesets/Mods/ModRelax.cs
Labels: area:gameplay, size/S

#19718 Fix playlist overlay showing new imports when they don't match collection filter
  osu.Game.Tests/Resources/TestResources.cs
  osu.Game.Tests/Visual/UserInterface/TestScenePlaylistOverlay.cs
  osu.Game/Overlays/Music/Playlist.cs
  osu.Game/Overlays/Music/PlaylistOverlay.cs
Labels: size/L, area:music-controller

#19746 Make `CommentMarkdownTextFlowContainer` render images
  osu.Game/Overlays/Comments/CommentMarkdownContainer.cs
Labels: size/XS, area:comments

#19768 Fix div-by-zero in `SongProgress` when no object duration could be calculated
  osu.Game/Screens/Play/HUD/SongProgress.cs
Labels: type:testing, size/XS

#19773 Update some clock tests to use constraint-based assertions
  osu.Game.Rulesets.Osu.Tests/TestSceneSpinnerRotation.cs
  osu.Game.Tests/Visual/Editing/TestSceneEditorClock.cs
Labels: type:testing, size/M

#19775 Move all usage of `GameplayClock` to `IGameplayClock`
  osu.Game.Rulesets.Osu.Tests/Mods/TestSceneOsuModDoubleTime.cs
  osu.Game.Rulesets.Osu/Skinning/Default/SpinnerRotationTracker.cs
  osu.Game.Tests/Gameplay/TestSceneMasterGameplayClockContainer.cs
  osu.Game.Tests/Gameplay/TestSceneStoryboardSamples.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneBeatmapSkinFallbacks.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneHUDOverlay.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneLeadIn.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneOverlayActivation.cs
  osu.Game.Tests/Visual/Gameplay/TestScenePause.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSkinEditorMultipleSkins.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSkinnableHUDOverlay.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSkipOverlay.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSongProgress.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneStoryboardWithOutro.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiSpectatorScreen.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayer.cs
  osu.Game/Rulesets/UI/FrameStabilityContainer.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/MultiSpectatorPlayer.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/MultiSpectatorScreen.cs
  osu.Game/Screens/Play/ComboEffects.cs
  osu.Game/Screens/Play/GameplayClock.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
  osu.Game/Screens/Play/HUD/SongProgress.cs
  osu.Game/Screens/Play/HUD/SongProgressInfo.cs
  osu.Game/Screens/Play/IGameplayClock.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/ScreenSuspensionHandler.cs
  osu.Game/Screens/Play/SkipOverlay.cs
  osu.Game/Storyboards/Drawables/DrawableStoryboard.cs
Labels: type:code-quality, size/L

#19776 Remove `FrameStableClock` (and redirect usages to `FrameStabilityContainer`)
  osu.Game.Tests/NonVisual/GameplayClockTest.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneFrameStabilityContainer.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneGameplaySamplePlayback.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSpectator.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Rulesets/UI/FrameStabilityContainer.cs
  osu.Game/Rulesets/UI/IFrameStableClock.cs
  osu.Game/Screens/Play/GameplayClock.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
  osu.Game/Screens/Play/IGameplayClock.cs
  osu.Game/Screens/Play/MasterGameplayClockContainer.cs
Labels: type:code-quality, size/L

#19777 Tidy up and document `FrameStabilityContainer`
  osu.Game/Rulesets/UI/FrameStabilityContainer.cs
Labels: type:code-quality, size/M

#19796 Fix running `TestScenePlayerLoader` interactively leaving volume in a bad state
  osu.Game.Tests/Visual/Gameplay/TestScenePlayerLoader.cs
Labels: type:testing, size/M

#19801 Fix re-importing existing collections not correctly adding new items
  osu.Game/Database/LegacyCollectionImporter.cs
Labels: area:database, size/XS

#19802 Improve intro timings when not using osu! theme
  osu.Game/Screens/Menu/IntroCircles.cs
  osu.Game/Screens/Menu/IntroScreen.cs
  osu.Game/Screens/Menu/IntroTriangles.cs
Labels: type:UI, size/M, area:intro

#19594 Skip song intro on quick restart
  osu.Game.Tests/Visual/Gameplay/TestScenePlayerLoader.cs
  osu.Game.Tests/Visual/Mods/TestSceneModFailCondition.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/PlayerConfiguration.cs
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/Screens/Play/SkipOverlay.cs
  osu.Game/Screens/Ranking/ResultsScreen.cs
Labels: area:gameplay, size/M

#19530 Add `BeatmapInfo.LastUpdate` to track the time of local changes
  osu.Game/Beatmaps/BeatmapInfo.cs
  osu.Game/Beatmaps/BeatmapManager.cs
  osu.Game/Database/RealmAccess.cs
Labels: area:database, size/S

#19547 Fix multiple cases of mutations at editor setup screen not triggering a state save
  osu.Game.Rulesets.Mania/Edit/Setup/ManiaSetupSection.cs
  osu.Game.Rulesets.Osu/Edit/Setup/OsuSetupSection.cs
  osu.Game/Screens/Edit/EditorBeatmap.cs
  osu.Game/Screens/Edit/Setup/DesignSection.cs
  osu.Game/Screens/Edit/Setup/DifficultySection.cs
  osu.Game/Screens/Edit/Setup/MetadataSection.cs
Labels: area:editor, size/S

#19812 Tweak intro timings more and ensure non-theme tracks play from preview point
  osu.Game/Beatmaps/IWorkingBeatmap.cs
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Screens/Menu/IntroCircles.cs
  osu.Game/Screens/Menu/IntroScreen.cs
  osu.Game/Screens/Menu/IntroTriangles.cs
  osu.Game/Screens/Menu/MainMenu.cs
  osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: type:UI, size/M

#19800 Fix slider ticks playing back at infinite rate while making changes to a slider in the editor
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/EditorBeatmap.cs
Labels: area:editor, size/M

#19782 Add ability to merge hit objects in osu! editor to create sliders
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneObjectMerging.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderSelectionBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/OsuSelectionHandler.cs
Labels: ruleset:osu!, area:editor, size/L

#19815 Fix flaky quick retry test
  osu.Game.Tests/Visual/Gameplay/TestScenePlayerLoader.cs
Labels: type:testing, size/XS

#19804 Clamp effective miss count to maximum amount of possible breaks
  osu.Game.Rulesets.Osu/Difficulty/OsuPerformanceCalculator.cs
Labels: ruleset:osu!, area:difficulty, size/XS

#19814 Update framework (and other dependencies)
  osu.Android.props
  osu.Game.Rulesets.Osu.Tests/osu.Game.Rulesets.Osu.Tests.csproj
  osu.Game.Tests/osu.Game.Tests.csproj
  osu.Game/Database/RealmAccess.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/M

#19120 Fix mania star rating varying by order of notes in a chord
  osu.Game.Rulesets.Mania.Tests/ManiaDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Mania/Difficulty/Skills/Strain.cs
Labels: ruleset:osu!mania, area:difficulty, size/M

#19817 Refactor some tests
  osu.Game.Rulesets.Taiko.Tests/Skinning/TestSceneDrawableTaikoMascot.cs
  osu.Game.Tests/Visual/Editing/TestSceneEditorSeekSnapping.cs
  osu.Game.Tests/Visual/Editing/TestScenePlaybackControl.cs
Labels: type:testing, size/M

#19827 Upgrade LocalisationAnalyser and disable warning
  .config/dotnet-tools.json
  .globalconfig
  osu.Game/osu.Game.csproj
Labels: area:tooling, size/XS

#19831 Fix taiko drum rolls with zero length being placeable in editor
  osu.Game.Rulesets.Taiko/Edit/Blueprints/TaikoSpanPlacementBlueprint.cs
Labels: ruleset:osu!taiko, area:editor, size/XS

#19832 Fix taiko blueprints displaying incorrectly for drum rolls
  osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableDrumRoll.cs
  osu.Game.Rulesets.Taiko/Skinning/Legacy/LegacyCirclePiece.cs
  osu.Game.Rulesets.Taiko/Skinning/Legacy/LegacyDrumRoll.cs
Labels: ruleset:osu!taiko, area:editor, size/S

#19833 Fix some backwards asserts
  osu.Game.Rulesets.Osu.Tests/TestSceneSpinnerRotation.cs
Labels: type:testing, size/XS

#19779 Remove all remaining usage of `GameplayClock`
  osu.Game.Tests/NonVisual/GameplayClockContainerTest.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneHUDOverlay.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSkinEditorMultipleSkins.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSkinnableHUDOverlay.cs
  osu.Game/Screens/Play/GameplayClock.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
  osu.Game/Screens/Play/MasterGameplayClockContainer.cs
Labels: type:code-quality, size/L

#19838 Update `TestSceneLeadIn` to use new assert style
  osu.Game.Tests/Visual/Gameplay/TestSceneLeadIn.cs
Labels: type:testing, size/M

#19836 Split `OffsetCorrectionClock` out of `MasterGameplayClockContainer`
  osu.Game/Screens/Play/MasterGameplayClockContainer.cs
  osu.Game/Screens/Play/OffsetCorrectionClock.cs
Labels: type:code-quality, size/L

#19851 Update framework and resources
  osu.Android.props
  osu.Game/Online/PollingComponent.cs
  osu.Game/Online/Rooms/OnlinePlayBeatmapAvailabilityTracker.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: area:tooling, size/S

#19693 Add localisation support for beatmap editor setup
  osu.Game/Graphics/UserInterfaceV2/ColourPalette.cs
  osu.Game/Graphics/UserInterfaceV2/LabelledColourPalette.cs
  osu.Game/Localisation/EditorSetupStrings.cs
  osu.Game/Screens/Edit/Setup/ColoursSection.cs
  osu.Game/Screens/Edit/Setup/DesignSection.cs
  osu.Game/Screens/Edit/Setup/DifficultySection.cs
  osu.Game/Screens/Edit/Setup/MetadataSection.cs
  osu.Game/Screens/Edit/Setup/ResourcesSection.cs
  osu.Game/Screens/Edit/Setup/RulesetSetupSection.cs
  osu.Game/Screens/Edit/Setup/SetupScreenHeader.cs
Labels: type:localisation, size/L

#19865 Fix flipping a slider sometimes changing the curve type from "Perfect" to "Bezier"
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneSliderSnapping.cs
  osu.Game.Rulesets.Osu/Edit/OsuSelectionHandler.cs
Labels: area:editor, size/M

#19898 Adjust rounding in mod select difficulty multiplier to match song select footer
  osu.Game/Overlays/Mods/DifficultyMultiplierDisplay.cs
Labels: area:song-select, type:UI, size/XS

#19868 Add safeties to avoid deadlock in `SubmittingPlayer`
  osu.Game/Online/API/DummyAPIAccess.cs
  osu.Game/Screens/Play/SubmittingPlayer.cs
Labels: size/S

#19905 Fix language change removing mod column bold text
  osu.Game/Overlays/Mods/ModSelectColumn.cs
Labels: area:mods, type:UI, size/XS

#19830 Test ruleset compatibility during initial startup to avoid runtime errors
  Templates/Rulesets/ruleset-scrolling-example/osu.Game.Rulesets.Pippidon/Beatmaps/PippidonBeatmapConverter.cs
  osu.Game/Rulesets/RealmRulesetStore.cs
  osu.Game/Rulesets/RulesetStore.cs
Labels: size/M, area:ruleset-api

#19783 Fix selecting preset containing Difficulty Adjust automatically opening customisation panel
  osu.Game.Tests/Visual/UserInterface/TestSceneModSelectOverlay.cs
  osu.Game/Overlays/Mods/ModColumn.cs
  osu.Game/Overlays/Mods/ModPanel.cs
  osu.Game/Overlays/Mods/ModPresetPanel.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Overlays/Mods/ModSelectPanel.cs
  osu.Game/Overlays/Mods/ModState.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: type:UX, size/L, area:overlay-modselect

#19906 Fix editor crashing on mobile releases
  osu.Game/Rulesets/UI/FrameStabilityContainer.cs
Labels: size/XS, type:reliability

#19911 Invert creation of clocks in multi-spectator
  osu.Game.Tests/OnlinePlay/TestSceneCatchUpSyncManager.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/CatchUpSpectatorPlayerClock.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/CatchUpSyncManager.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/ISpectatorPlayerClock.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/ISyncManager.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/MultiSpectatorScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/PlayerArea.cs
Labels: type:code-quality, area:multiplayer, size/L

#19933 Tidy up spectator clock/manager naming and interfaces
  osu.Game.Tests/OnlinePlay/TestSceneCatchUpSyncManager.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiSpectatorScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/ISpectatorPlayerClock.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/ISyncManager.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/MultiSpectatorPlayer.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/MultiSpectatorScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/PlayerArea.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/SpectatorPlayerClock.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/SpectatorSyncManager.cs
Labels: type:code-quality, size/L

#19936 Move `MasterClockState` handling in to `SpectatorSyncManager`
  osu.Game.Tests/OnlinePlay/TestSceneCatchUpSyncManager.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/MultiSpectatorPlayer.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/MultiSpectatorScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/SpectatorPlayerClock.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/SpectatorSyncManager.cs
Labels: type:code-quality, size/L

#19934 Add profile url context menu to user container
  osu.Game/Overlays/Profile/Header/TopHeaderContainer.cs
Labels: type:UI, size/L

#19904 Add date submitted sorting
  osu.Game/Screens/Select/Carousel/CarouselBeatmap.cs
  osu.Game/Screens/Select/Carousel/CarouselBeatmapSet.cs
  osu.Game/Screens/Select/Filter/SortMode.cs
Labels: area:song-select, size/S

#19937 Add option to copy URL rather than open an external link
  osu.Game/Online/Chat/ExternalLinkOpener.cs
  osu.Game/Overlays/Chat/ExternalLinkDialog.cs
Labels: type:UI, size/M

#19951 No "gameplayClock" usage with playfield update mods
  osu.Game.Rulesets.Osu/Mods/OsuModAutopilot.cs
  osu.Game.Rulesets.Osu/Mods/OsuModMagnetised.cs
  osu.Game.Rulesets.Osu/Mods/OsuModRepel.cs
Labels: type:code-quality, size/M

#19571 Rewrite of the colour skill & refactoring of difficulty calculation within osu!taiko
  osu.Game.Rulesets.Taiko.Tests/TaikoDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Taiko/Difficulty/Evaluators/ColourEvaluator.cs
  osu.Game.Rulesets.Taiko/Difficulty/Evaluators/StaminaEvaluator.cs
  osu.Game.Rulesets.Taiko/Difficulty/Preprocessing/Colour/Data/AlternatingMonoPattern.cs
  osu.Game.Rulesets.Taiko/Difficulty/Preprocessing/Colour/Data/MonoStreak.cs
  osu.Game.Rulesets.Taiko/Difficulty/Preprocessing/Colour/Data/RepeatingHitPatterns.cs
  osu.Game.Rulesets.Taiko/Difficulty/Preprocessing/Colour/TaikoColourDifficultyPreprocessor.cs
  osu.Game.Rulesets.Taiko/Difficulty/Preprocessing/Colour/TaikoDifficultyHitObjectColour.cs
  osu.Game.Rulesets.Taiko/Difficulty/Preprocessing/Rhythm/TaikoDifficultyHitObjectRhythm.cs
  osu.Game.Rulesets.Taiko/Difficulty/Preprocessing/TaikoDifficultyHitObject.cs
  osu.Game.Rulesets.Taiko/Difficulty/Skills/Colour.cs
  osu.Game.Rulesets.Taiko/Difficulty/Skills/Peaks.cs
  osu.Game.Rulesets.Taiko/Difficulty/Skills/SingleKeyStamina.cs
  osu.Game.Rulesets.Taiko/Difficulty/Skills/Stamina.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoDifficultyAttributes.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoDifficultyCalculator.cs
Labels: ruleset:osu!taiko, area:difficulty, size/XXL

#19853 osu!taiko performance point adjustments & effective misses
  osu.Game.Rulesets.Taiko/Difficulty/TaikoPerformanceAttributes.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoPerformanceCalculator.cs
Labels: ruleset:osu!taiko, area:difficulty, size/M

#19956 Fix some `BeatmapCarousel` tests not correctly reinitialising local data per run
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs
Labels: type:testing, size/L

#19939 Add `maximum_statistics` to `ScoreInfo`
  osu.Game/Database/RealmAccess.cs
  osu.Game/Online/API/Requests/Responses/SoloScoreInfo.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Scoring/ScoreImporter.cs
  osu.Game/Scoring/ScoreInfo.cs
Labels: area:scoring, size/M

#19959 Fix `SliderPath.Version` bindings not being correctly cleaned up on path changes
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointVisualiser.cs
Labels: type:performance, area:editor, size/XS

#19940 Add `legacy_combo_increase` hit result type for legacy scores
  osu.Game.Tests/Rulesets/Scoring/ScoreProcessorTest.cs
  osu.Game/Rulesets/Scoring/HitResult.cs
  osu.Game/Rulesets/Scoring/JudgementProcessor.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
Labels: area:scoring, size/L

#19858 Add ability to split sliders in osu! editor
  osu.Game.Rulesets.Osu.Tests/Editor/TestScenePathControlPointVisualiser.cs
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneSliderSplitting.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointVisualiser.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderSelectionBlueprint.cs
Labels: ruleset:osu!, area:editor, size/L

#19964 Fix hitobjects merge feature in editor not adding any hitsounds
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneObjectMerging.cs
  osu.Game.Rulesets.Osu/Edit/OsuSelectionHandler.cs
Labels: ruleset:osu!, area:editor, size/S, type:audio

#19828 Introduce `FramedBeatmapClock` (and use in gameplay flow)
  osu.Android.props
  osu.Game.Tests/Gameplay/TestSceneStoryboardSamples.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneLeadIn.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSpectator.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiSpectatorScreen.cs
  osu.Game/Beatmaps/FramedBeatmapClock.cs
  osu.Game/Rulesets/UI/FrameStabilityContainer.cs
  osu.Game/Screens/Edit/GameplayTest/EditorPlayer.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/MultiSpectatorScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/PlayerArea.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/SpectatorPlayerClock.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
  osu.Game/Screens/Play/HUD/SongProgress.cs
  osu.Game/Screens/Play/IGameplayClock.cs
  osu.Game/Screens/Play/MasterGameplayClockContainer.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: type:code-quality, size/XL, next-release

#19938 Fix multi-spectator potentially getting stuck for passed players
  osu.Game/Online/Spectator/SpectatorClient.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/MultiSpectatorScreen.cs
  osu.Game/Screens/Play/SoloSpectator.cs
  osu.Game/Screens/Spectate/SpectatorScreen.cs
Labels: area:multiplayer, size/L, area:spectator, next-release

#19203 Ensure all mods are incompatible in both ways
  osu.Game.Tests/Visual/Gameplay/TestSceneModValidity.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneNoConflictingModAcronyms.cs
Labels: type:testing, area:mods, size/M, next-release

#19909 Include framework configuration in sentry output
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Utils/SentryLogger.cs
Labels: area:tooling, size/S, next-release

#19924 Fix intermittent test failures in `TestScenePlaylistOverlay`
  osu.Game.Tests/Visual/UserInterface/TestScenePlaylistOverlay.cs
  osu.Game/Collections/CollectionDropdown.cs
  osu.Game/Overlays/Music/Playlist.cs
Labels: type:testing, size/M, next-release

#19850 Add audio feedback for text selection
  osu.Game/Graphics/UserInterface/OsuTextBox.cs
Labels: size/M, type:audio, next-release

#19958 Ensure fail animation sequence isn't run after the player exit sequence has started
  osu.Game/Beatmaps/WorkingBeatmap.cs
  osu.Game/Screens/Play/FailAnimation.cs
  osu.Game/Screens/Play/Player.cs
Labels: area:gameplay, size/M, next-release

#19995 Fix crash with legacy import from incomplete installs
  osu.Game/Database/LegacyBeatmapImporter.cs
Labels: size/XS, type:reliability

#20008 Refactor/merge `ScoreProcessor.ComputeScore()` methods
  osu.Game.Tests/Rulesets/Scoring/ScoreProcessorTest.cs
  osu.Game/Rulesets/Difficulty/PerformanceBreakdownCalculator.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Scoring/ScoreManager.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsPlayer.cs
Labels: area:scoring, size/M

#20010 Don't include misses in failed score statistics
  osu.Game.Tests/Gameplay/TestSceneScoreProcessor.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
Labels: area:scoring, size/M

#19409 Fix beatmap carousel not maintaining selection if currently selected beatmap is updated
  osu.Game.Tests/Visual/SongSelect/TestScenePlaySongSelect.cs
  osu.Game/Screens/Select/BeatmapCarousel.cs
Labels: area:song-select, size/M, next-release

#20012 Add setting to toggle metronome in "Target" mod
  osu.Game.Rulesets.Osu/Mods/OsuModTarget.cs
Labels: ruleset:osu!, area:mods, size/XS

#19907 Add ruleset API versioning
  Templates/Rulesets/ruleset-empty/osu.Game.Rulesets.EmptyFreeform/EmptyFreeformRuleset.cs
  Templates/Rulesets/ruleset-example/osu.Game.Rulesets.Pippidon/PippidonRuleset.cs
  Templates/Rulesets/ruleset-scrolling-empty/osu.Game.Rulesets.EmptyScrolling/EmptyScrollingRuleset.cs
  Templates/Rulesets/ruleset-scrolling-example/osu.Game.Rulesets.Pippidon/PippidonRuleset.cs
  osu.Game.Rulesets.Catch/CatchRuleset.cs
  osu.Game.Rulesets.Mania/ManiaRuleset.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game.Tests/Database/RulesetStoreTests.cs
  osu.Game/Rulesets/RealmRulesetStore.cs
  osu.Game/Rulesets/Ruleset.cs
Labels: size/L, area:ruleset-api

#20013 Always reprocess beatmaps after a user update request
  osu.Game/Beatmaps/BeatmapImporter.cs
Labels: area:database, size/XS

#19973 Fix beat synced components not applying offsets
  osu.Game/OsuGameBase.cs
Labels: type:UI, size/S, next-release

#19974 Fix editor not applying offsets
  osu.Game.Rulesets.Catch.Tests/Editor/CatchSelectionBlueprintTestScene.cs
  osu.Game.Rulesets.Mania.Tests/Editor/TestSceneManiaHitObjectComposer.cs
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneOsuDistanceSnapGrid.cs
  osu.Game.Rulesets.Taiko.Tests/Editor/TestSceneTaikoHitObjectComposer.cs
  osu.Game.Tests/Editing/TestSceneHitObjectComposerDistanceSnapping.cs
  osu.Game.Tests/Visual/Editing/TestSceneEditorClock.cs
  osu.Game.Tests/Visual/Editing/TestSceneEditorSeekSnapping.cs
  osu.Game.Tests/Visual/Editing/TestSceneTapTimingControl.cs
  osu.Game.Tests/Visual/Editing/TestSceneTimelineBlueprintContainer.cs
  osu.Game.Tests/Visual/Editing/TestSceneTimelineZoom.cs
  osu.Game.Tests/Visual/Editing/TestSceneTimingScreen.cs
  osu.Game.Tests/Visual/Editing/TimelineTestScene.cs
  osu.Game/Beatmaps/FramedBeatmapClock.cs
  osu.Game/Screens/Edit/Compose/Components/Timeline/Timeline.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/EditorClock.cs
  osu.Game/Tests/Visual/EditorClockTestScene.cs
  osu.Game/Tests/Visual/PlacementBlueprintTestScene.cs
  osu.Game/Tests/Visual/SelectionBlueprintTestScene.cs
Labels: area:editor, size/L, next-release

#19716 Nerf repeated angles in Flashlight skill
  osu.Game.Rulesets.Osu/Difficulty/Evaluators/FlashlightEvaluator.cs
  osu.Game.Rulesets.Osu/Difficulty/Skills/Flashlight.cs
Labels: ruleset:osu!, area:difficulty, size/S

#19982 Fixed 0 length merge being allowed
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneObjectMerging.cs
  osu.Game.Rulesets.Osu/Edit/OsuSelectionHandler.cs
Labels: ruleset:osu!, area:editor, size/M, type:reliability

#20024 Populate `MaximumStatistics` for test scores
  osu.Game.Tests/Resources/TestResources.cs
  osu.Game.Tests/Visual/Playlists/TestScenePlaylistsResultsScreen.cs
Labels: type:testing, area:scoring, size/S

#20028 Add LegacyTotalScore to SoloScoreInfo
  osu.Game/Online/API/Requests/Responses/SoloScoreInfo.cs
Labels: area:scoring, size/XS

#20026 Apply NRT to notification classes
  osu.Game.Tests/Visual/UserInterface/TestSceneNotificationOverlay.cs
  osu.Game/Database/ImportProgressNotification.cs
  osu.Game/Overlays/NotificationOverlay.cs
  osu.Game/Overlays/Notifications/Notification.cs
  osu.Game/Overlays/Notifications/NotificationSection.cs
  osu.Game/Overlays/Notifications/ProgressNotification.cs
  osu.Game/Overlays/Notifications/SimpleNotification.cs
Labels: type:code-quality, size/M

#20029 Assert non-null in `ProfileHeader` to appease r#
  osu.Game/Overlays/Profile/ProfileHeader.cs
Labels: type:code-quality, size/XS

#20031 Fix crash when attempting to watch a replay when the storage file doesn't exist
  osu.Game/Scoring/LegacyDatabasedScore.cs
Labels: size/XS, type:reliability

#20025 Fix audio glitching when showing results screen with many scores
  osu.Game/Screens/Ranking/ScorePanel.cs
Labels: area:results, size/XS, type:audio

#20009 Adjust weirdly back-to-front fallback comparison in `HitObjectOrderedSelectionContainer`
  osu.Game/Screens/Edit/Compose/Components/HitObjectOrderedSelectionContainer.cs
Labels: area:editor, size/XS

#20039 Fix skip button getting stuck on screen for certain beatmaps
  osu.Game.Tests/Visual/Gameplay/TestSceneSkipOverlay.cs
  osu.Game/Screens/Play/SkipOverlay.cs
Labels: area:gameplay, size/M, next-release

#20041 Add toggle for tournament client "auto progression" behaviour
  osu.Game.Tournament/Models/LadderInfo.cs
  osu.Game.Tournament/Screens/Gameplay/GameplayScreen.cs
  osu.Game.Tournament/Screens/MapPool/MapPoolScreen.cs
  osu.Game.Tournament/Screens/Setup/SetupScreen.cs
Labels: area:tournament, size/M

#20042 Test editor `ComposeScreen` tests not adding beatmap to hierarchy
  osu.Game.Rulesets.Mania.Tests/Editor/TestSceneManiaComposeScreen.cs
  osu.Game.Tests/Visual/Editing/TestSceneComposeScreen.cs
Labels: size/S

#20030 Update notification overlay design
  osu.Desktop/Security/ElevatedPrivilegesChecker.cs
  osu.Game/Database/TooManyDownloadsNotification.cs
  osu.Game/Online/Chat/MessageNotifier.cs
  osu.Game/Overlays/NotificationOverlay.cs
  osu.Game/Overlays/Notifications/Notification.cs
  osu.Game/Overlays/Notifications/ProgressCompletionNotification.cs
  osu.Game/Overlays/Notifications/ProgressNotification.cs
  osu.Game/Overlays/Notifications/SimpleNotification.cs
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/Updater/UpdateManager.cs
Labels: area:overlay-notifications, size/L, next-release

#20014 Fix gameplay skipping forward during resume operation
  osu.Game.Tests/Visual/Gameplay/TestScenePause.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
  osu.Game/Screens/Play/MasterGameplayClockContainer.cs
Labels: area:gameplay, size/M, next-release
