Repository ppy/osu, pull requests merged in 2022-04, with the labels that each got.

#17194 Extract the hit object positioning logic of random mod to a separate class
  osu.Game.Rulesets.Osu/Mods/OsuModRandom.cs
  osu.Game.Rulesets.Osu/Utils/OsuHitObjectGenerationUtils.cs
  osu.Game.Rulesets.Osu/Utils/OsuHitObjectGenerationUtils_Reposition.cs
Labels: ruleset:osu!, area:mods, size/XL

#17581 Remove BPM slider
  osu.Game/Screens/Edit/Timing/TimingSection.cs
Labels: area:editor, type:UI, size/M

#17559 Implement sheared toggle button
  osu.Game.Tests/Visual/UserInterface/TestSceneShearedToggleButton.cs
  osu.Game/Graphics/UserInterface/ShearedToggleButton.cs
Labels: type:UI, size/L

#17579 Make the toolbar clock feel more like a button
  osu.Game/Overlays/Toolbar/ToolbarClock.cs
Labels: proposal, type:UI, size/M, area:toolbar

#17589 Add ability to switch between most common tournament scenes using key bindings
  osu.Game.Tournament/TournamentSceneManager.cs
Labels: area:tournament, size/M

#17588 Rename "Aim Assist" to "Magnetised" to better suit the mod's behaviour
  osu.Game.Rulesets.Osu.Tests/Mods/TestSceneOsuModMagnetised.cs
  osu.Game.Rulesets.Osu/Mods/OsuModAutopilot.cs
  osu.Game.Rulesets.Osu/Mods/OsuModAutoplay.cs
  osu.Game.Rulesets.Osu/Mods/OsuModCinema.cs
  osu.Game.Rulesets.Osu/Mods/OsuModMagnetised.cs
  osu.Game.Rulesets.Osu/Mods/OsuModRelax.cs
  osu.Game.Rulesets.Osu/Mods/OsuModTransform.cs
  osu.Game.Rulesets.Osu/Mods/OsuModWiggle.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
Labels: ruleset:osu!, area:gameplay, size/M

#17593 Disable ability to use random skin shortcut from within the skin editor
  osu.Game/OsuGame.cs
Labels: size/XS, area:skin-editor

#17490 Apply minor changes to the issue report template
  .github/ISSUE_TEMPLATE/bug-issue.yml
Labels: size/S

#17592 Fix automatically created "(modified)" skins getting conflicting names
  osu.Game/Skinning/SkinManager.cs
Labels: size/S, area:skin-editor

#17609 Add test coverage for toolbar clock mode cycling
  osu.Game.Tests/Visual/Menus/TestSceneToolbarClock.cs
Labels: type:testing, size/S

#17615 Store beatmap listing card size in game configuration
  osu.Game.Tests/Visual/Online/TestSceneBeatmapListingOverlay.cs
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Overlays/BeatmapListing/BeatmapListingFilterControl.cs
Labels: size/M, area:overlay-beatmap-listing

#17613 Display pass/play count in success rate percentage tooltip
  osu.Game.Tests/Visual/Online/TestSceneBeatmapSetOverlaySuccessRate.cs
  osu.Game/Overlays/BeatmapSet/SuccessRate.cs
Labels: type:UI, size/S, area:overlay-beatmap

#17545 Implement `ChatTextBox` for new chat design
  osu.Game.Tests/Visual/Online/TestSceneChatTextBox.cs
  osu.Game/Overlays/Chat/ChatTextBar.cs
  osu.Game/Overlays/Chat/ChatTextBox.cs
Labels: type:UI, area:overlay-chat, size/L

#17617 Make overlay shortcuts able to be toggled instead of repeatable
  osu.Game/Overlays/Toolbar/ToolbarButton.cs
Labels: type:UX, size/XS, area:toolbar

#16575 Fix max combo calculation in osu diffcalc and add tests
  osu.Game.Rulesets.Catch.Tests/CatchDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Mania.Tests/ManiaDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Osu.Tests/OsuDifficultyCalculatorTest.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyCalculator.cs
  osu.Game.Rulesets.Taiko.Tests/TaikoDifficultyCalculatorTest.cs
  osu.Game/Beatmaps/IBeatmap.cs
  osu.Game/Rulesets/Difficulty/DifficultyCalculator.cs
  osu.Game/Tests/Beatmaps/DifficultyCalculatorTest.cs
Labels: ruleset:osu!, area:difficulty, size/L

#17598 Fix playlist refreshing all items on order change
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerPlaylist.cs
  osu.Game/Online/Rooms/PlaylistItem.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Match/Playlist/MultiplayerPlaylist.cs
  osu.Game/Tests/Visual/Multiplayer/TestMultiplayerClient.cs
Labels: type:UX, area:multiplayer, size/L

#17643 Stabilise countdown updates to be based on when whole seconds change
  osu.Game/Screens/OnlinePlay/Multiplayer/Match/MultiplayerReadyButton.cs
Labels: type:UI, area:multiplayer, size/M

#17653 Handle repeated `OnPressed()` on `FooterButton` (without `FooterButtonRandom`)
  osu.Game/Screens/Select/FooterButton.cs
Labels: size/XS

#17651 Fix various breakage in delete local score test scene
  osu.Game.Tests/Visual/UserInterface/TestSceneDeleteLocalScore.cs
Labels: type:testing, size/M

#17619 Adjust osu!taiko hit size and strong scale to exactly match osu!(stable)
  osu.Game.Rulesets.Taiko/Objects/TaikoHitObject.cs
  osu.Game.Rulesets.Taiko/Objects/TaikoStrongableHitObject.cs
  osu.Game.Rulesets.Taiko/Skinning/Default/CirclePiece.cs
Labels: ruleset:osu!taiko, area:gameplay, size/XS

#17621 Adjust osu!taiko legacy hit target size to match osu!(stable)
  osu.Game.Rulesets.Taiko/Skinning/Legacy/TaikoLegacyHitTarget.cs
Labels: ruleset:osu!taiko, area:skinning, size/XS

#17650 Make several delete confirmation buttons dangerous buttons
  osu.Game.Tests/Visual/UserInterface/TestSceneDeleteLocalScore.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/MassDeleteConfirmationDialog.cs
  osu.Game/Screens/Select/BeatmapDeleteDialog.cs
  osu.Game/Screens/Select/LocalScoreDeleteDialog.cs
Labels: proposal, type:UX, size/S

#17604 Add SFX for multiplayer lobby countdown timer
  osu.Android.props
  osu.Game/Screens/OnlinePlay/Multiplayer/Match/MultiplayerReadyButton.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: area:multiplayer, size/M, type:audio

#17596 Allow importing sprites into a skin via drag-and-drop
  osu.Game/Configuration/SettingSourceAttribute.cs
  osu.Game/Overlays/Settings/SettingsItem.cs
  osu.Game/Skinning/DefaultSkin.cs
  osu.Game/Skinning/Editor/SkinEditor.cs
  osu.Game/Skinning/LegacyBeatmapSkin.cs
  osu.Game/Skinning/LegacySkinTransformer.cs
  osu.Game/Skinning/RealmBackedResourceStore.cs
  osu.Game/Skinning/Skin.cs
  osu.Game/Skinning/SkinManager.cs
  osu.Game/Skinning/SkinnableDrawable.cs
  osu.Game/Skinning/SkinnableSprite.cs
Labels: size/L, area:skin-editor

#17597 Import new skin editor sprites to the cursor location
  osu.Game/Skinning/Editor/SkinEditor.cs
  osu.Game/Skinning/Editor/SkinSelectionHandler.cs
Labels: size/M, area:skin-editor

#17679 Ensure intro beatmap has protected flag set
  osu.Game/Screens/Menu/IntroScreen.cs
Labels: size/XS

#17677 Fix dangerous realm operation in `TestSceneMultiplayerMatchSongSelect`
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerMatchSongSelect.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneDeleteLocalScore.cs
Labels: type:testing, size/M

#17576 Centralise exception handling of `MultiplayerClient` calls
  osu.Game/Online/Multiplayer/MultiplayerClientExtensions.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Match/MatchStartControl.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Match/Playlist/MultiplayerQueueList.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Multiplayer.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSongSelect.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Participants/ParticipantPanel.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Participants/TeamDisplay.cs
Labels: type:code-quality, size/L

#17678 Change `WorkingBeatmap.GetVirtualTrack` to use length provided by `BeatmapInfo`
  osu.Game/Beatmaps/WorkingBeatmap.cs
Labels: type:testing, size/S

#17683 Remove some outdated packages
  Directory.Build.props
  osu.Desktop/osu.Desktop.csproj
  osu.Game/osu.Game.csproj
Labels: dependencies, size/S

#17631 Implement basic layout & behaviour of new mod select screen
  osu.Android.props
  osu.Game.Tests/Visual/UserInterface/TestSceneModSelectScreen.cs
  osu.Game/Overlays/Mods/DifficultyMultiplierDisplay.cs
  osu.Game/Overlays/Mods/ModColumn.cs
  osu.Game/Overlays/Mods/ModSelectScreen.cs
  osu.Game/Overlays/Mods/ModSettingsArea.cs
  osu.Game/Overlays/Mods/NestedVerticalScrollContainer.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: type:UI, size/XL, area:overlay-modselect

#17699 Add MP lobby 'warning' SFX for the final seconds of countdown
  osu.Android.props
  osu.Game/Screens/OnlinePlay/Multiplayer/Match/MultiplayerReadyButton.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: area:multiplayer, size/S, type:audio

#17698 Fix replay button being disabled when available locally but not online
  osu.Game.Tests/Visual/Gameplay/TestSceneReplayDownloadButton.cs
  osu.Game/Screens/Ranking/ReplayDownloadButton.cs
Labels: type:UI, area:results, size/S

#17701 Fix storyboard animations getting incorrect positioning due to size not being set
  osu.Game/Storyboards/Drawables/DrawableStoryboardAnimation.cs
Labels: area:storyboard, size/S

#17700 Fix filename lookups on `LegacySkin`s going awry when extension is specified
  osu.Game.Tests/NonVisual/Skinning/LegacySkinTextureFallbackTest.cs
  osu.Game/Skinning/LegacySkin.cs
Labels: area:skinning, area:storyboard, size/S

#17670 Add support for 12-hour time on toolbar clock
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Localisation/GeneralSettingsStrings.cs
  osu.Game/Overlays/Settings/Sections/General/LanguageSettings.cs
  osu.Game/Overlays/Toolbar/DigitalClockDisplay.cs
  osu.Game/Overlays/Toolbar/ToolbarClock.cs
Labels: type:UX, size/M, area:toolbar

#17704 Fix multiple issues with bindable safety in `SkinEditor` components
  osu.Game/Skinning/Editor/SkinBlueprintContainer.cs
  osu.Game/Skinning/Editor/SkinEditor.cs
Labels: size/S, type:reliability, area:skin-editor

#17721 Add and assert thread safety of `MultiplayerClient.Room`
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerPlayer.cs
Labels: type:code-quality, size/M

#17714 Ensure that mods grouped into multi mods are pairwise incompatible
  osu.Game.Rulesets.Osu/Mods/OsuModBlinds.cs
  osu.Game.Rulesets.Osu/Mods/OsuModFlashlight.cs
  osu.Game.Rulesets.Osu/Mods/OsuModObjectScaleTween.cs
  osu.Game.Tests/Mods/MultiModIncompatibilityTest.cs
  osu.Game/Rulesets/Mods/ModDoubleTime.cs
  osu.Game/Rulesets/Mods/ModHalfTime.cs
  osu.Game/Rulesets/Mods/ModRateAdjust.cs
  osu.Game/Utils/ModUtils.cs
Labels: area:mods, size/M

#17724 Fix potential assert failure due to `Room` access from disconnection event
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
Labels: size/XS, type:reliability

#17726 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#17725 Avoid multiplayer crashes when events arrive in unexpected order
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
Labels: area:multiplayer, size/S

#17728 Remove some incorrectly-firing asserts
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
Labels: priority:0, area:multiplayer, size/XS

#17731 Fix crash when clicking chat mention notification before opening chat overlay
  osu.Game.Tests/Visual/Online/TestSceneChatOverlay.cs
  osu.Game/Online/Chat/MessageNotifier.cs
  osu.Game/Overlays/ChatOverlay.cs
Labels: area:overlay-chat, size/M, type:reliability

#17743 Fix ParticleSpewer outputting NaN values in vertices
  osu.Game/Graphics/ParticleSpewer.cs
Labels: area:gameplay, size/XS, type:reliability

#17762 Avoid throwing unobserved exception when `PerformancePointsCounter` requests timed attributes
  osu.Game/Screens/Play/HUD/PerformancePointsCounter.cs
Labels: type:testing, size/XS

#17764 Fix incorrect cursor parameterisation in test scene
  osu.Game.Tests/Visual/Playlists/TestScenePlaylistsResultsScreen.cs
Labels: type:testing, size/S, area:playlists

#17773 Fix skins getting duplicated when importing after export
  osu.Game.Tests/Skins/IO/ImportSkinTest.cs
  osu.Game/Skinning/SkinModelManager.cs
Labels: area:skinning, size/S

#17767 Refactor multiplayer gameplay leaderboard tests to remove reliance on `Test` implementations
  osu.Game.Tests/Visual/Multiplayer/MultiplayerGameplayLeaderboardTestScene.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerGameplayLeaderboard.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerGameplayLeaderboardTeams.cs
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
  osu.Game/Online/Spectator/SpectatorClient.cs
Labels: type:testing, size/L

#17776 Fix dialog dangerous button being clickable at edges
  osu.Game.Tests/Visual/UserInterface/TestScenePopupDialog.cs
  osu.Game/Overlays/Dialog/PopupDialogDangerousButton.cs
Labels: type:UX, size/M

#17791 Refactor `GameplayChatDisplay` test scene to not require `MultiplayerTestScene` inheritance
  osu.Game.Tests/Visual/Multiplayer/TestSceneGameplayChatDisplay.cs
Labels: type:testing, size/XS

#17789 Refactor `TestSceneRankRangePill` to not depend on `TestMultiplayerClient`
  osu.Game.Tests/Visual/Multiplayer/TestSceneRankRangePill.cs
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
Labels: type:testing, size/M

#17792 Fix `MultiplayerMatchFooter` test crash due to missing `PopoverContainer`
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerMatchFooter.cs
Labels: type:testing, size/S

#17790 Remove usages of binary serialization
  osu.Game/IO/Legacy/SerializationReader.cs
  osu.Game/IO/Legacy/SerializationWriter.cs
Labels: type:code-quality, size/L

#17788 Fix multiple issues in `ReplayDownloadButton` test scene
  osu.Game.Tests/Visual/Gameplay/TestSceneReplayDownloadButton.cs
  osu.Game/Online/ScoreDownloadTracker.cs
  osu.Game/Stores/RealmArchiveModelImporter.cs
Labels: type:testing, size/S

#17786 Fix multiple issues with gameplay leaderboard (and tests)
  osu.Game.Tests/Visual/Multiplayer/MultiplayerGameplayLeaderboardTestScene.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerGameplayLeaderboardTeams.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerTeamResults.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerTeamResultsScreen.cs
  osu.Game/Screens/Play/HUD/MatchScoreDisplay.cs
  osu.Game/Screens/Play/HUD/MultiplayerGameplayLeaderboard.cs
Labels: type:UI, area:multiplayer, size/M

#17814 Upgrade Resharper to 2022.1.0-eap10
  .config/dotnet-tools.json
  .github/workflows/ci.yml
  InspectCode.ps1
  InspectCode.sh
  Templates/Rulesets/ruleset-empty/osu.Game.Rulesets.EmptyFreeform/EmptyFreeformDifficultyCalculator.cs
  Templates/Rulesets/ruleset-example/osu.Game.Rulesets.Pippidon/PippidonDifficultyCalculator.cs
  Templates/Rulesets/ruleset-scrolling-empty/osu.Game.Rulesets.EmptyScrolling/EmptyScrollingDifficultyCalculator.cs
  Templates/Rulesets/ruleset-scrolling-example/osu.Game.Rulesets.Pippidon/PippidonDifficultyCalculator.cs
  osu.Game.Rulesets.Taiko.Tests/TestSceneFlyingHits.cs
  osu.Game.Tests/Online/TestAPIModJsonSerialization.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneGameplaySamplePlayback.cs
  osu.Game.Tournament/Screens/Ladder/Components/ProgressionPath.cs
  osu.Game/Overlays/BeatmapSet/Scores/ScoresContainer.cs
  osu.Game/Screens/Play/BeatmapMetadataDisplay.cs
  osu.sln.DotSettings
Labels: area:tooling, size/M

#17816 Add inspectcode CI cache
  .github/workflows/ci.yml
Labels: area:tooling, size/XS

#17815 Adjust hold to confirm animation curve to better show intention
  osu.Game/Graphics/Containers/HoldToConfirmContainer.cs
Labels: type:UX, size/XS

#17818 Handle virtual track string to avoid throwing later in lookup
  osu.Game/Beatmaps/WorkingBeatmapCache.cs
Labels: type:code-quality, size/S

#17819 Fix UI scale being applied unevenly, causing elements to move around relative to each other
  osu.Game.Tests/Visual/UserInterface/TestSceneScalingContainer.cs
  osu.Game/Graphics/Containers/ScalingContainer.cs
Labels: type:UI, size/L

#17821 Apply new rider metadata changes
  .idea/.idea.osu.Desktop/.idea/misc.xml
Labels: area:tooling, size/XS

#17820 Add keyword "delay" to hold-to-confirm activation time setting
  osu.Game/Overlays/Settings/Sections/UserInterface/GeneralSettings.cs
Labels: area:settings, size/XS

#17822 Add background dim effect to inactive settings sections
  osu.Game/Overlays/Settings/SettingsSection.cs
  osu.Game/Overlays/SettingsPanel.cs
Labels: type:UI, area:settings, size/M

#17802 Refactor `TestSceneMatchStartControl` to avoid usage of `TestMultiplayerClient`
  osu.Game.Tests/Visual/Multiplayer/TestSceneMatchStartControl.cs
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
  osu.Game/Online/Rooms/OnlinePlayBeatmapAvailabilityTracker.cs
  osu.Game/Tests/Visual/Multiplayer/TestMultiplayerClient.cs
Labels: type:testing, size/L

#17302 Fix spectator not starting from current player position
  osu.Game.Tests/Gameplay/TestSceneMasterGameplayClockContainer.cs
  osu.Game.Tests/Gameplay/TestSceneStoryboardSamples.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneFailAnimation.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneLeadIn.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiSpectatorScreen.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayer.cs
  osu.Game/Rulesets/UI/DrawableRuleset.cs
  osu.Game/Screens/Edit/GameplayTest/EditorPlayer.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/ISpectatorPlayerClock.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/MultiSpectatorPlayer.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Spectate/MultiSpectatorScreen.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
  osu.Game/Screens/Play/MasterGameplayClockContainer.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/SpectatorPlayer.cs
Labels: size/L, area:spectator

#17828 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/S

#17829 UI SFX Tweaks
  osu.Game/Screens/Menu/MainMenuButton.cs
  osu.Game/Screens/Menu/OsuLogo.cs
Labels: size/S, type:audio

#17817 Fix run-from-menu operations not working correctly when initiated from inside multiplayer
  osu.Game.Tests/Visual/Navigation/TestScenePerformFromScreen.cs
  osu.Game/Overlays/Dialog/PopupDialog.cs
  osu.Game/PerformFromMenuRunner.cs
Labels: type:UX, size/M

#17785 Use zh-Hant instead of zh-TW
  osu.Android.props
  osu.Game/Localisation/Language.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: type:localisation, size/XS

#17856 Fix editor legacy beatmap skins not wrapped in `LegacySkinTransformer`s
  osu.Game.Tests/Visual/Editing/TestSceneComposeScreen.cs
  osu.Game/Screens/Edit/EditorBeatmapSkin.cs
  osu.Game/Screens/Edit/EditorSkinProvidingContainer.cs
Labels: area:editor, area:skinning, size/M

#17863 Split out `IPerformFromScreenRunner` to allow for easier testing
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Dashboard/CurrentlyPlayingDisplay.cs
  osu.Game/Overlays/Settings/Sections/DebugSettings/GeneralSettings.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/StableDirectoryLocationDialog.cs
  osu.Game/Screens/IPerformFromScreenRunner.cs
  osu.Game/Screens/Menu/MainMenu.cs
  osu.Game/Skinning/Editor/SkinEditorSceneLibrary.cs
Labels: type:testing, size/M

#17862 Split out `IDialogOverlay` to allow for easier testing
  osu.Game.Tests/Visual/Collections/TestSceneManageCollectionsDialog.cs
  osu.Game.Tests/Visual/Navigation/TestSceneOsuGame.cs
  osu.Game.Tests/Visual/Navigation/TestScenePerformFromScreen.cs
  osu.Game.Tests/Visual/Navigation/TestSceneScreenNavigation.cs
  osu.Game.Tests/Visual/Online/TestSceneChatLink.cs
  osu.Game.Tests/Visual/Settings/TestSceneSettingsPanel.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapLeaderboard.cs
  osu.Game.Tests/Visual/SongSelect/TestSceneUserTopScoreContainer.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneDeleteLocalScore.cs
  osu.Game/Collections/DrawableCollectionListItem.cs
  osu.Game/Database/LegacyImportManager.cs
  osu.Game/Online/Chat/ExternalLinkOpener.cs
  osu.Game/Online/Leaderboards/LeaderboardScore.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/Dialog/PopupDialog.cs
  osu.Game/Overlays/DialogOverlay.cs
  osu.Game/Overlays/IDialogOverlay.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/GeneralSettings.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/MigrationSelectScreen.cs
  osu.Game/PerformFromMenuRunner.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Menu/MainMenu.cs
  osu.Game/Screens/Menu/StorageErrorDialog.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmapSet.cs
  osu.Game/Screens/Select/SongSelect.cs
  osu.Game/Tests/Visual/EditorTestScene.cs
  osu.Game/Tests/Visual/ScreenTestScene.cs
Labels: type:testing, size/L

#17865 Split out `INotificationOverlay` to allow for easier testing
  osu.Desktop/Security/ElevatedPrivilegesChecker.cs
  osu.Desktop/Updater/SquirrelUpdateManager.cs
  osu.Game.Tests/Visual/Gameplay/TestScenePlayerLoader.cs
  osu.Game.Tests/Visual/Menus/IntroTestScene.cs
  osu.Game.Tests/Visual/Menus/TestSceneToolbar.cs
  osu.Game.Tests/Visual/Navigation/TestSceneOsuGame.cs
  osu.Game.Tests/Visual/Online/TestSceneMessageNotifier.cs
  osu.Game.Tests/Visual/Settings/TestSceneMigrationScreens.cs
  osu.Game/Database/EFToRealmMigrator.cs
  osu.Game/Graphics/ScreenshotManager.cs
  osu.Game/Online/Chat/MessageNotifier.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/BeatmapSet/Buttons/FavouriteButton.cs
  osu.Game/Overlays/INotificationOverlay.cs
  osu.Game/Overlays/NotificationOverlay.cs
  osu.Game/Overlays/Settings/Sections/General/UpdateSettings.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/MigrationRunScreen.cs
  osu.Game/Overlays/Toolbar/ToolbarNotificationButton.cs
  osu.Game/PerformFromMenuRunner.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Menu/ButtonSystem.cs
  osu.Game/Screens/Menu/IntroScreen.cs
  osu.Game/Screens/Play/HUDOverlay.cs
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/Screens/Select/PlaySongSelect.cs
  osu.Game/Updater/UpdateManager.cs
Labels: type:testing, size/L

#17879 Add debug language to help with localisation efforts
  osu.Game/Localisation/DebugLocalisationStore.cs
  osu.Game/Localisation/Language.cs
  osu.Game/OsuGame.cs
Labels: area:tooling, size/M

#17873 Update paginated profile subsections to display items inline with web
  osu.Game/Online/API/Requests/GetUserBeatmapsRequest.cs
  osu.Game/Online/API/Requests/GetUserKudosuHistoryRequest.cs
  osu.Game/Online/API/Requests/GetUserMostPlayedBeatmapsRequest.cs
  osu.Game/Online/API/Requests/GetUserRecentActivitiesRequest.cs
  osu.Game/Online/API/Requests/GetUserScoresRequest.cs
  osu.Game/Online/API/Requests/PaginatedAPIRequest.cs
  osu.Game/Online/API/Requests/PaginationParameters.cs
  osu.Game/Overlays/Profile/Sections/Beatmaps/PaginatedBeatmapContainer.cs
  osu.Game/Overlays/Profile/Sections/Historical/PaginatedMostPlayedBeatmapContainer.cs
  osu.Game/Overlays/Profile/Sections/Kudosu/PaginatedKudosuHistoryContainer.cs
  osu.Game/Overlays/Profile/Sections/PaginatedProfileSubsection.cs
  osu.Game/Overlays/Profile/Sections/Ranks/PaginatedScoreContainer.cs
  osu.Game/Overlays/Profile/Sections/Recent/PaginatedRecentActivityContainer.cs
Labels: type:UX, area:overlay-user-profile, size/L

#17880 Show login prompt directly when attempting to enter multiplayer
  osu.Game/Screens/Menu/ButtonSystem.cs
Labels: type:UX, area:multiplayer, size/S, area:playlists

#17894 Split out the base design of sheared overlay into its own abstract class
  osu.Game.Tests/Visual/UserInterface/TestSceneShearedOverlayHeader.cs
  osu.Game/Graphics/UserInterface/ShearedOverlayHeader.cs
  osu.Game/Overlays/Mods/DifficultyMultiplierDisplay.cs
  osu.Game/Overlays/Mods/ModColumn.cs
  osu.Game/Overlays/Mods/ModPanel.cs
  osu.Game/Overlays/Mods/ModSelectScreen.cs
  osu.Game/Overlays/Mods/ShearedOverlayContainer.cs
Labels: type:code-quality, type:UI, size/L

#17853 Add extension points to new mod select screen required to replace old design
  osu.Game.Tests/Visual/Multiplayer/TestSceneFreeModSelectScreen.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneModSelectScreen.cs
  osu.Game/Overlays/Mods/IncompatibilityDisplayingModPanel.cs
  osu.Game/Overlays/Mods/ModColumn.cs
  osu.Game/Overlays/Mods/ModPanel.cs
  osu.Game/Overlays/Mods/ModSelectScreen.cs
  osu.Game/Overlays/Mods/UserModSelectScreen.cs
  osu.Game/Screens/OnlinePlay/FreeModSelectScreen.cs
Labels: size/L, area:overlay-modselect

#17903 Move Code Quality check to top of list + fix inspection
  .github/workflows/ci.yml
  osu.Game/Overlays/Dashboard/CurrentlyPlayingDisplay.cs
Labels: area:tooling, size/L

#17833 Implement `ChannelList` for new chat design
  osu.Game.Tests/Visual/Online/TestSceneChannelList.cs
  osu.Game.Tests/Visual/Online/TestSceneChannelListItem.cs
  osu.Game/Overlays/Chat/ChannelList/ChannelList.cs
  osu.Game/Overlays/Chat/ChannelList/ChannelListItem.cs
  osu.Game/Overlays/Chat/ChannelList/ChannelListSelector.cs
Labels: type:UI, area:overlay-chat, size/XL

#17904 Visually improve AnchorOriginVisualiser
  osu.Game/Skinning/Editor/SkinBlueprint.cs
Labels: type:UI, size/XS

#17914 Update framework
  osu.Android.props
  osu.Game.Tests/Visual/Background/TestSceneUserDimBackgrounds.cs
  osu.Game.Tests/Visual/Gameplay/TestScenePause.cs
  osu.Game.Tests/Visual/Navigation/TestScenePerformFromScreen.cs
  osu.Game.Tests/Visual/TestMultiplayerComponents.cs
  osu.Game/Graphics/Containers/ScalingContainer.cs
  osu.Game/Overlays/AccountCreation/AccountCreationScreen.cs
  osu.Game/Overlays/AccountCreation/ScreenEntry.cs
  osu.Game/Overlays/AccountCreation/ScreenWarning.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/DirectorySelectScreen.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/MigrationRunScreen.cs
  osu.Game/Overlays/Settings/Sections/Maintenance/StableDirectorySelectScreen.cs
  osu.Game/Screens/BackgroundScreen.cs
  osu.Game/Screens/Backgrounds/BackgroundScreenBlack.cs
  osu.Game/Screens/Edit/Editor.cs
  osu.Game/Screens/Edit/GameplayTest/EditorPlayer.cs
  osu.Game/Screens/Edit/GameplayTest/EditorPlayerLoader.cs
  osu.Game/Screens/Import/FileImportScreen.cs
  osu.Game/Screens/Loader.cs
  osu.Game/Screens/Menu/Disclaimer.cs
  osu.Game/Screens/Menu/IntroCircles.cs
  osu.Game/Screens/Menu/IntroScreen.cs
  osu.Game/Screens/Menu/IntroTriangles.cs
  osu.Game/Screens/Menu/IntroWelcome.cs
  osu.Game/Screens/Menu/MainMenu.cs
  osu.Game/Screens/OnlinePlay/Components/OnlinePlayBackgroundScreen.cs
  osu.Game/Screens/OnlinePlay/Lounge/LoungeBackgroundScreen.cs
  osu.Game/Screens/OnlinePlay/Lounge/LoungeSubScreen.cs
  osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Multiplayer.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerLoungeSubScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerPlayerLoader.cs
  osu.Game/Screens/OnlinePlay/OnlinePlayScreen.cs
  osu.Game/Screens/OnlinePlay/OnlinePlaySongSelect.cs
  osu.Game/Screens/OnlinePlay/OnlinePlaySubScreen.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsPlayer.cs
  osu.Game/Screens/OsuScreen.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/Screens/Play/ReplayPlayerLoader.cs
  osu.Game/Screens/Play/SoloSpectator.cs
  osu.Game/Screens/Play/SoloSpectatorPlayer.cs
  osu.Game/Screens/Play/SpectatorPlayer.cs
  osu.Game/Screens/Play/SpectatorPlayerLoader.cs
  osu.Game/Screens/Play/SubmittingPlayer.cs
  osu.Game/Screens/Ranking/ResultsScreen.cs
  osu.Game/Screens/ScreenWhiteBox.cs
  osu.Game/Screens/Select/PlaySongSelect.cs
  osu.Game/Screens/Select/SongSelect.cs
  osu.Game/Tests/Visual/EditorTestScene.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/L

#17860 Calculate sample playback position using screen-space drawable rectangles
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableOsuHitObject.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
Labels: ruleset:osu!, size/S, type:audio

#17881 Add first run setup dialog
  osu.Game.Tests/Visual/UserInterface/TestSceneFirstRunScreenUIScale.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneFirstRunSetupOverlay.cs
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Graphics/Containers/ScalingContainer.cs
  osu.Game/Localisation/CommonStrings.cs
  osu.Game/Localisation/FirstRunSetupOverlayStrings.cs
  osu.Game/Localisation/GeneralSettingsStrings.cs
  osu.Game/OsuGame.cs
  osu.Game/Overlays/FirstRunSetup/FirstRunSetupScreen.cs
  osu.Game/Overlays/FirstRunSetup/ScreenUIScale.cs
  osu.Game/Overlays/FirstRunSetup/ScreenWelcome.cs
  osu.Game/Overlays/FirstRunSetupOverlay.cs
  osu.Game/Overlays/Settings/Sections/GeneralSection.cs
  osu.Game/Screens/Menu/ButtonSystem.cs
  osu.Game/Screens/Menu/MainMenu.cs
  osu.Game/Screens/OsuScreen.cs
  osu.Game/Tests/Visual/OsuGameTestScene.cs
Labels: type:UX, size/XXL

#17902 Specify web proxy in SignalR connection building
  osu.Game/Online/HubClientConnector.cs
Labels: type:online, size/XS

#17917 Fix flaky test in free mod select test scene
  osu.Game.Tests/Visual/Multiplayer/TestSceneFreeModSelectScreen.cs
Labels: type:testing, size/XS

#17921 Display beatmap guest participations in user profile
  osu.Android.props
  osu.Game/Online/API/Requests/GetUserBeatmapsRequest.cs
  osu.Game/Online/API/Requests/Responses/APIUser.cs
  osu.Game/Overlays/Profile/Sections/Beatmaps/PaginatedBeatmapContainer.cs
  osu.Game/Overlays/Profile/Sections/BeatmapsSection.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: area:overlay-user-profile, size/S

#17823 Fix incorrect settings state if searching too quickly (during load process)
  osu.Game.Tests/Visual/Settings/TestSceneSettingsPanel.cs
  osu.Game/Graphics/Containers/SectionsContainer.cs
  osu.Game/Overlays/Settings/SettingsItem.cs
  osu.Game/Overlays/Settings/SettingsSection.cs
  osu.Game/Overlays/SettingsPanel.cs
Labels: area:settings, size/M

#17923 Fix high star ratings not being easily visible on tooltips
  osu.Game/Beatmaps/Drawables/DifficultyIconTooltip.cs
Labels: type:UI, size/M

#17931 Fix regression in settings filter display
  osu.Game/Graphics/Containers/SectionsContainer.cs
Labels: size/XS

#17918 Allow selecting mods regardless of incompatibility state on new mod select
  osu.Game.Tests/Visual/UserInterface/TestSceneModPanel.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneModSelectScreen.cs
  osu.Game/Overlays/Mods/IncompatibilityDisplayingModPanel.cs
  osu.Game/Overlays/Mods/ModPanel.cs
  osu.Game/Overlays/Mods/ModSelectScreen.cs
  osu.Game/Overlays/Mods/UserModSelectScreen.cs
Labels: size/L, area:overlay-modselect

#17905 Add better click-to-dismiss logic for sheared overlays
  osu.Game.Tests/Visual/UserInterface/TestSceneShearedOverlayContainer.cs
  osu.Game/Graphics/InputBlockingContainer.cs
  osu.Game/Graphics/UserInterface/ShearedOverlayHeader.cs
  osu.Game/Overlays/Mods/DifficultyMultiplierDisplay.cs
  osu.Game/Overlays/Mods/ShearedOverlayContainer.cs
Labels: type:UI, size/L

#17906 Convert first run setup to use new `ShearedOverlayContainer`
  osu.Game.Tests/Visual/UserInterface/TestSceneFirstRunSetupOverlay.cs
  osu.Game/Overlays/FirstRunSetupOverlay.cs
Labels: type:UI, size/L

#17939 Fix legacy skin hit animation lookup falling back to `LookupName`
  osu.Game/Skinning/LegacySkin.cs
Labels: area:skinning, size/XS

#17956 Fix page up / down in `SectionsContainer` with fixed header skipping content
  osu.Game.Tests/Visual/UserInterface/TestSceneSectionsContainer.cs
  osu.Game/Graphics/Containers/SectionsContainer.cs
Labels: type:UX, size/L

#17950 Allow any key to trigger the osu! cookie in the initial state
  osu.Game.Tests/Visual/Navigation/TestSceneButtonSystemNavigation.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneButtonSystem.cs
  osu.Game/Screens/Menu/ButtonSystem.cs
Labels: type:UX, area:main menu, size/L

#17957 Disable first run screen from appearing on startup until it is more complete
  osu.Game.Tests/Visual/UserInterface/TestSceneFirstRunSetupOverlay.cs
  osu.Game/Overlays/FirstRunSetupOverlay.cs
Labels: size/XS

#17958 Remove localisation of "hide" string to fix incorrect case
  osu.Game/Overlays/Login/LoginForm.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmap.cs
Labels: type:localisation, size/XS

#17942 Add joystick/gamepad deadzone setting
  osu.Android.props
  osu.Game/Localisation/JoystickSettingsStrings.cs
  osu.Game/Overlays/Settings/Sections/Input/JoystickSettings.cs
  osu.Game/Overlays/Settings/Sections/InputSection.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: type:input, area:settings, size/M

#17937 Fix settings overlay components not invalidating presence on filter change
  osu.Game.Tests/Visual/Settings/TestSceneSettingsPanel.cs
  osu.Game/Graphics/Containers/SectionsContainer.cs
  osu.Game/Overlays/Settings/SettingsItem.cs
  osu.Game/Overlays/Settings/SettingsSection.cs
Labels: type:UI, area:settings, size/M

#17930 Fix nested song select in first-run dialog fiddling with global audio
  osu.Game/Overlays/FirstRunSetup/ScreenUIScale.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: type:UX, size/M, area:overlay-first-run

#17962 Fix context menus not working
  osu.Game/Graphics/UserInterface/OsuDropdown.cs
  osu.Game/Graphics/UserInterface/OsuMenu.cs
Labels: size/M

#17952 Deselect mods incompatible with "Autoplay" when entering gameplay via scene library
  osu.Game.Tests/Visual/Navigation/TestSceneChangeAndUseGameplayBindings.cs
  osu.Game.Tests/Visual/Navigation/TestSceneMouseWheelVolumeAdjust.cs
  osu.Game.Tests/Visual/Navigation/TestSceneScreenNavigation.cs
  osu.Game.Tests/Visual/Navigation/TestSceneSkinEditorSceneLibrary.cs
  osu.Game/Skinning/Editor/SkinEditorSceneLibrary.cs
  osu.Game/Tests/Visual/OsuGameTestScene.cs
Labels: size/L, area:skin-editor

#17941 Handle all legacy skin component types explicitly and remove texture fallback
  osu.Game.Rulesets.Catch/Skinning/Legacy/CatchLegacySkinTransformer.cs
  osu.Game.Rulesets.Mania/Skinning/Legacy/ManiaLegacySkinTransformer.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneSliderApplication.cs
  osu.Game.Rulesets.Osu/Skinning/Legacy/OsuLegacySkinTransformer.cs
  osu.Game.Rulesets.Taiko/Skinning/Legacy/TaikoLegacySkinTransformer.cs
  osu.Game/Skinning/DefaultSkin.cs
  osu.Game/Skinning/LegacySkin.cs
  osu.Game/Skinning/SkinnableSprite.cs
  osu.Game/Skinning/UnsupportedSkinComponentException.cs
  osu.Game/Tests/Visual/SkinnableTestScene.cs
Labels: type:code-quality, area:skinning, size/M

#17976 Change score accuracy grading logic to be inclusive
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Screens/Ranking/Expanded/Accuracy/AccuracyCircle.cs
  osu.Game/Screens/Ranking/Expanded/Accuracy/RankBadge.cs
Labels: area:scoring, size/S

#17977 Change conditions for HUD being shown to include pause/fail states
  osu.Game.Tests/Visual/Gameplay/TestSceneFailJudgement.cs
  osu.Game.Tests/Visual/Gameplay/TestScenePause.cs
  osu.Game/Screens/Play/HUDOverlay.cs
  osu.Game/Screens/Play/Player.cs
Labels: area:gameplay, type:UX, size/S

#17972 Fix windows taskbar context menu not popping up correctly
  osu.Desktop/Program.cs
Labels: size/XS, platform:windows

#17979 Improve displayed text on first run setup back/next buttons
  osu.Game/Localisation/CommonStrings.cs
  osu.Game/Localisation/FirstRunSetupOverlayStrings.cs
  osu.Game/Overlays/FirstRunSetupOverlay.cs
Labels: type:UI, size/M

#17981 Fix all buttons gamewide not animating properly on click
  osu.Game/Graphics/UserInterface/OsuButton.cs
Labels: type:UI, size/XS

#17980 Fix joystick settings changing enabled state of config level bindables
  osu.Game/Overlays/Settings/Sections/Input/JoystickSettings.cs
Labels: size/S, type:reliability

#17913 Fix mania SR inflation for hold note releases in quick succession
  osu.Game.Rulesets.Mania/Difficulty/Skills/Strain.cs
Labels: ruleset:osu!mania, area:difficulty, size/S

#17982 Add basic sheared button implementation
  osu.Game.Tests/Visual/UserInterface/TestSceneShearedButtons.cs
  osu.Game/Graphics/UserInterface/ShearedButton.cs
  osu.Game/Graphics/UserInterface/ShearedToggleButton.cs
Labels: type:UI, size/L

#17988 Use correct translation for "Accuracy" label in break overlay
  osu.Game/Screens/Play/Break/BreakInfo.cs
Labels: area:gameplay, type:localisation, size/XS

#17991 Fix `HealthProcessor` fail conditions not handling multiple invocations
  osu.Game.Rulesets.Osu/Mods/OsuModSuddenDeath.cs
  osu.Game.Rulesets.Osu/Mods/OsuModTarget.cs
  osu.Game.Tests/Gameplay/TestSceneDrainingHealthProcessor.cs
  osu.Game/Rulesets/Scoring/HealthProcessor.cs
Labels: area:gameplay, size/M

#17997 Remove weird duplicated code
  osu.Game/Beatmaps/Drawables/DownloadProgressBar.cs
Labels: size/XS

#17994 Fix mod panels not ignoring super key presses
  osu.Game/Overlays/Mods/ModColumn.cs
Labels: type:input, size/XS, area:overlay-modselect

#18004 Update framework
  osu.Android.props
  osu.Game/Extensions/TimeDisplayExtensions.cs
  osu.Game/Graphics/UserInterface/OsuDropdown.cs
  osu.Game/Graphics/UserInterface/OsuMenu.cs
  osu.Game/Overlays/BeatmapSet/Scores/TopScoreStatisticsSection.cs
  osu.Game/Overlays/FirstRunSetupOverlay.cs
  osu.Game/Overlays/Profile/Header/Components/LevelProgressBar.cs
  osu.Game/Overlays/Rankings/SpotlightSelector.cs
  osu.Game/Overlays/Rankings/Tables/PerformanceTable.cs
  osu.Game/Screens/Play/PlayerSettings/BeatmapOffsetControl.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/M

#18006 Move `FastRandom` to `LegacyRandom` in `osu.Game` project
  osu.Game.Rulesets.Catch/Beatmaps/CatchBeatmapProcessor.cs
  osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/DistanceObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/EndTimeObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/HitObjectPatternGenerator.cs
  osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/PatternGenerator.cs
  osu.Game.Rulesets.Mania/MathUtils/FastRandom.cs
  osu.Game/Utils/LegacyRandom.cs
Labels: type:code-quality, size/L

#18005 Fix some missing/incorrect UI SFX
  osu.Game/Graphics/UserInterfaceV2/SwitchButton.cs
  osu.Game/Overlays/BeatmapListing/BeatmapListingCardSizeTabControl.cs
  osu.Game/Overlays/OverlaySortTabControl.cs
Labels: size/S, type:audio

#17996 Add header text to first run setup screens
  osu.Game.Tests/Visual/UserInterface/TestSceneFirstRunScreenUIScale.cs
  osu.Game/Overlays/FirstRunSetup/FirstRunSetupScreen.cs
  osu.Game/Overlays/FirstRunSetup/ScreenUIScale.cs
  osu.Game/Overlays/FirstRunSetup/ScreenWelcome.cs
  osu.Game/Overlays/FirstRunSetupOverlay.cs
Labels: type:UI, size/M, area:overlay-first-run

#18009 Allow dragging the osu! logo
  osu.Game/Screens/Menu/OsuLogo.cs
Labels: type:UX, area:main menu, size/S

#17973 Dim offscreen columns on new mod select overlay
  osu.Game.Tests/Visual/UserInterface/TestSceneModSelectScreen.cs
  osu.Game/Graphics/Containers/OsuScrollContainer.cs
  osu.Game/Overlays/Mods/ModColumn.cs
  osu.Game/Overlays/Mods/ModSelectScreen.cs
  osu.Game/Overlays/Mods/NestedVerticalScrollContainer.cs
Labels: type:UI, size/L, area:overlay-modselect

#18016 Don't block clicks when dragging on the osu! logo
  osu.Game/Screens/Menu/OsuLogo.cs
Labels: type:UX, area:main menu, size/XS

#18008 Add first run "beatmaps" screen
  .editorconfig
  osu.Game.Tests/Visual/Online/TestSceneBundledBeatmapDownloader.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneFirstRunScreenBundledBeatmaps.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneFirstRunSetupOverlay.cs
  osu.Game/.editorconfig
  osu.Game/Beatmaps/Drawables/BundledBeatmapDownloader.cs
  osu.Game/Graphics/UserInterfaceV2/RoundedButton.cs
  osu.Game/Localisation/FirstRunSetupBeatmapScreenStrings.cs
  osu.Game/Overlays/FirstRunSetup/FirstRunSetupScreen.cs
  osu.Game/Overlays/FirstRunSetup/ScreenBeatmaps.cs
  osu.Game/Overlays/FirstRunSetupOverlay.cs
Labels: type:UI, type:UX, size/XL

#18018 Remove placeholder UI pieces to avoid user confusion
  osu.Game/Overlays/Profile/ProfileHeader.cs
  osu.Game/Screens/Select/Filter/SortMode.cs
Labels: type:UX, size/XS

#17933 Force start/abort multiplayer games after a timeout
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerPlayer.cs
  osu.Game/Online/Multiplayer/ForceGameplayStartCountdown.cs
  osu.Game/Online/Multiplayer/IMultiplayerClient.cs
  osu.Game/Online/Multiplayer/MultiplayerClient.cs
  osu.Game/Online/Multiplayer/MultiplayerCountdown.cs
  osu.Game/Online/Multiplayer/MultiplayerRoomUser.cs
  osu.Game/Online/Multiplayer/MultiplayerUserState.cs
  osu.Game/Online/Multiplayer/OnlineMultiplayerClient.cs
  osu.Game/Online/SignalRWorkaroundTypes.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Match/MultiplayerCountdownButton.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Match/MultiplayerReadyButton.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Multiplayer.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerPlayer.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerPlayerLoader.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/Participants/StateDisplay.cs
  osu.Game/Screens/Play/PlayerLoader.cs
  osu.Game/Tests/Visual/Multiplayer/TestMultiplayerClient.cs
Labels: area:multiplayer, size/L

#18011 Allow rewinding random in song select with "Shift + Left Click"
  osu.Game.Tests/Visual/SongSelect/TestSceneSongSelectFooter.cs
  osu.Game/Screens/Select/FooterButtonRandom.cs
Labels: area:song-select, type:UX, size/L

#18002 Make some mods incompatible with `OsuModTarget`
  osu.Game.Rulesets.Osu/Mods/OsuModClassic.cs
  osu.Game.Rulesets.Osu/Mods/OsuModRandom.cs
  osu.Game.Rulesets.Osu/Mods/OsuModSpunOut.cs
  osu.Game.Rulesets.Osu/Mods/OsuModStrictTracking.cs
  osu.Game.Rulesets.Osu/Mods/OsuModTarget.cs
Labels: ruleset:osu!, area:mods, size/S

#18022 Update first-run overlay footer buttons to use new sheared design
  osu.Game.Tests/Visual/UserInterface/TestSceneFirstRunSetupOverlay.cs
  osu.Game/Overlays/FirstRunSetupOverlay.cs
Labels: type:UI, size/M, area:overlay-first-run

#18029 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS
