Repository ppy/osu, pull requests merged in 2024-01, with the labels that each got.

#26281 Fix beats being counted incorrectly in the timing editor
  osu.Game/Screens/Edit/Timing/WaveformComparisonDisplay.cs
Labels: area:editor, size/XS

#26248 Increase slider tails' worth to 150 points (up from 30)
  osu.Game.Rulesets.Osu.Tests/TestSceneSliderEarlyHitJudgement.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneSliderInput.cs
  osu.Game.Rulesets.Osu.Tests/TestSceneSliderLateHitJudgement.cs
  osu.Game.Rulesets.Osu/Objects/SliderTailCircle.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Osu/Scoring/OsuHealthProcessor.cs
  osu.Game.Rulesets.Osu/Scoring/OsuLegacyHealthProcessor.cs
  osu.Game.Tests/Rulesets/Scoring/ScoreProcessorTest.cs
  osu.Game/Rulesets/Judgements/Judgement.cs
  osu.Game/Rulesets/Scoring/HitResult.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Scoring/ScoreInfo.cs
Labels: ruleset/osu!, area:scoring, size/M

#26332 Fix standardised score conversion failing for some taiko scores due to overestimating accuracy portion
  osu.Game/Database/StandardisedScoreMigrationTools.cs
Labels: ruleset/osu!taiko, area:scoring, size/XS

#26336 Fix backwards z-ordering of fruits in juice streams and banana showers
  osu.Game.Rulesets.Catch.Tests/TestSceneCatchModHidden.cs
  osu.Game.Rulesets.Catch/Objects/Drawables/DrawableBananaShower.cs
  osu.Game.Rulesets.Catch/Objects/Drawables/DrawableJuiceStream.cs
  osu.Game.Rulesets.Catch/Objects/Drawables/NestedFruitContainer.cs
Labels: ruleset/osu!catch, area:gameplay, size/M

#26333 Fix possible double score submission when auto-retrying via perfect mod
  osu.Game/Screens/Play/SubmittingPlayer.cs
Labels: blocked, type:online, area:gameplay, size/S, type:reliability

#26343 update the current activity when the multiplayer room updates
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs
Labels: size/XS

#26337 Store user online state in config for next launch
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Online/Metadata/OnlineMetadataClient.cs
  osu.Game/Overlays/Login/LoginPanel.cs
Labels: type:online, size/M

#26353 Fix crash when dragging rotation control in editor with both mouse buttons
  osu.Game/Screens/Edit/Compose/Components/SelectionBoxRotationHandle.cs
Labels: area:editor, size/XS, type:reliability

#26354 Change threaded optimisations setting to "Auto" on startup
  osu.Desktop/NVAPI.cs
  osu.Desktop/Program.cs
Labels: type:performance, size/XL

#26378 Fix wiki link path inconsistencies
  osu.Game.Tests/Visual/Online/TestSceneWikiMarkdownContainer.cs
  osu.Game/Overlays/Wiki/WikiHeader.cs
  osu.Game/Overlays/WikiOverlay.cs
Labels: type:code-quality, size/XS

#26379 Make chat command names case-insensitive
  osu.Game.Tests/Chat/TestSceneChannelManager.cs
  osu.Game/Online/Chat/ChannelManager.cs
Labels: size/S

#26384 Fix multiplayer scores being submitted as pass even if failed
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayer.cs
  osu.Game/Rulesets/Mods/ModFlashlight.cs
  osu.Game/Rulesets/Mods/ModHidden.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerPlayer.cs
  osu.Game/Screens/Play/BreakOverlay.cs
  osu.Game/Screens/Play/GameplayState.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/PlayerConfiguration.cs
Labels: area:multiplayer, size/L, next release

#26140 Fix mod score multiplier rounding to 1.00x with specific mod combinations
  osu.Game.Tests/Mods/ModUtilsTest.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneFooterButtonMods.cs
  osu.Game/Overlays/Mods/ScoreMultiplierDisplay.cs
  osu.Game/Screens/Select/FooterButtonMods.cs
  osu.Game/Utils/ModUtils.cs
Labels: area:song-select, type:cosmetic, size/M, area:overlay-mod-select

#26381 Flash blocking ongoing operations dialog when trying to force quit
  osu.Game.Tests/Visual/Navigation/TestSceneScreenNavigation.cs
  osu.Game/Overlays/Dialog/PopupDialog.cs
  osu.Game/Screens/Menu/MainMenu.cs
Labels: type:cosmetic, size/S, area:overlays

#26410 Remove scores from song select leaderboard when leaving the screen
  osu.Game/Online/Leaderboards/Leaderboard.cs
  osu.Game/Screens/Select/PlaySongSelect.cs
Labels: area:song-select, size/S

#26409 Fix overall ranking text overlapping at some aspect ratios
  osu.Game/Screens/Ranking/Statistics/SoloStatisticsPanel.cs
Labels: area:results, size/XS

#26411 Disable pausing music during intro sequence
  osu.Game.Tests/Visual/Menus/TestSceneIntroMusicActionHandling.cs
  osu.Game/Screens/Menu/IntroScreen.cs
  osu.Game/Screens/Menu/MainMenu.cs
  osu.Game/Tests/Visual/OsuGameTestScene.cs
Labels: area:main-menu, size/M

#26385 Fix beatmap carousel not preloading panels when off-screen
  osu.Game/Screens/Select/BeatmapCarousel.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmapSet.cs
Labels: area:song-select, size/M

#26438 Fix Cinema mod being compatible with mods that can force failure
  osu.Game/Rulesets/Mods/ModCinema.cs
  osu.Game/Rulesets/Mods/ModFailCondition.cs
Labels: area:mods, size/XS

#26439 Do not attempt to recalculate non-legacy scores or scores set on custom rulesets
  osu.Game.Tests/Database/BackgroundDataStoreProcessorTests.cs
  osu.Game/BackgroundDataStoreProcessor.cs
Labels: realm, type:behavioural, area:scoring, size/M

#26440 Fix score conversion incorrectly assuming zero combo score in certain cases
  osu.Game/Database/StandardisedScoreMigrationTools.cs
Labels: area:scoring, size/S

#26382 Keep editor in frame stable mode when possible
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneEditorAutoplayFastStreams.cs
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneOsuComposerSelection.cs
  osu.Game/Rulesets/Edit/DrawableEditorRulesetWrapper.cs
Labels: area:editor, size/M

#26441 Fix wiki main page not displaying custom layout
  osu.Game.Tests/Visual/Online/TestSceneWikiHeader.cs
  osu.Game.Tests/Visual/Online/TestSceneWikiMainPage.cs
  osu.Game.Tests/Visual/Online/TestSceneWikiMarkdownContainer.cs
  osu.Game.Tests/Visual/Online/TestSceneWikiOverlay.cs
  osu.Game/Overlays/Wiki/WikiHeader.cs
  osu.Game/Overlays/WikiOverlay.cs
Labels: type:cosmetic, size/M, area:overlay-wiki

#26437 Fix crash when clicking osu! logo in song select immediately after exiting
  osu.Game.Tests/Visual/Navigation/TestSceneScreenNavigation.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: area:song-select, size/M, type:reliability

#26451 Use native query to avoid huge overheads when cleaning up realm files
  osu.Game/Database/RealmFileStore.cs
  osu.Game/Models/RealmFile.cs
Labels: type:performance, size/S

#26434 Fix mania score conversion using score V1 accuracy
  osu.Game/Database/StandardisedScoreMigrationTools.cs
  osu.Game/Scoring/Legacy/LegacyScoreEncoder.cs
Labels: ruleset/osu!mania, area:scoring, size/S

#26422 Preliminary fixes for off-the-charts allocations
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderRepeat.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/ITrackSnaking.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Screens/Play/HUD/ArgonAccuracyCounter.cs
  osu.Game/Screens/Play/HUD/ArgonComboCounter.cs
  osu.Game/Screens/Play/HUD/ArgonCounterTextComponent.cs
  osu.Game/Screens/Play/HUD/ArgonHealthDisplay.cs
  osu.Game/Screens/Play/HUD/ArgonScoreCounter.cs
  osu.Game/Screens/Play/HUD/ComboCounter.cs
  osu.Game/Screens/Play/HUD/HealthDisplay.cs
  osu.Game/Skinning/LegacySpriteText.cs
  osu.Game/Skinning/SkinnableSound.cs
Labels: type:performance, size/L, next release

#26405 Adjust catch scoring to match stable score V2
  osu.Game.Rulesets.Catch/Scoring/CatchScoreProcessor.cs
  osu.Game/Database/StandardisedScoreMigrationTools.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Scoring/Legacy/LegacyScoreEncoder.cs
Labels: ruleset/osu!catch, area:scoring, size/L

#26467 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#26455 Remove bindable overheads of health displays
  osu.Game.Tests/Visual/Gameplay/TestSceneArgonHealthDisplay.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneFailingLayer.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSkinnableHealthDisplay.cs
  osu.Game/Screens/Play/HUD/ArgonHealthDisplay.cs
  osu.Game/Screens/Play/HUD/FailingLayer.cs
  osu.Game/Screens/Play/HUD/HealthDisplay.cs
  osu.Game/Skinning/LegacyHealthDisplay.cs
Labels: type:performance, size/L, next release

#26468 Fix mania skin array decoder not handling malformed entries rigorously
  osu.Game.Tests/Resources/mania-skin-broken-array.ini
  osu.Game.Tests/Skins/LegacyManiaSkinDecoderTest.cs
  osu.Game/Skinning/LegacyManiaSkinDecoder.cs
Labels: ruleset/osu!mania, area:skinning, size/M

#26471 Fix incorrect score conversion on selected beatmaps due to incorrect `difficultyPeppyStars` rounding
  osu.Game.Rulesets.Catch/Difficulty/CatchLegacyScoreSimulator.cs
  osu.Game.Rulesets.Osu/Difficulty/OsuLegacyScoreSimulator.cs
  osu.Game.Rulesets.Taiko/Difficulty/TaikoLegacyScoreSimulator.cs
  osu.Game/Rulesets/Objects/Legacy/LegacyRulesetExtensions.cs
  osu.Game/Scoring/Legacy/LegacyScoreEncoder.cs
Labels: area:scoring, size/M, next release

#26484 Only validate playback rate when in submission context
  osu.Game.Tests/Visual/Gameplay/TestScenePlayerScoreSubmission.cs
  osu.Game/Screens/Play/MasterGameplayClockContainer.cs
  osu.Game/Screens/Play/SubmittingPlayer.cs
Labels: area:replay, type:behavioural, size/S, audio

#26486 Update framework
  osu.Android.props
  osu.Game/Overlays/Settings/Sections/Input/KeyBindingRow_KeyButton.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#26511 Fix broken windows installer
  osu.Desktop/Program.cs
Labels: area:installer, size/S, platform/windows, next release

#26520 Fix scores not showing up on leaderboards during gameplay
  osu.Game/Screens/Select/PlaySongSelect.cs
Labels: area:gameplay, size/XS

#26521 Revert "Keep editor in frame stable mode when possible"
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneEditorAutoplayFastStreams.cs
  osu.Game.Rulesets.Osu.Tests/Editor/TestSceneOsuComposerSelection.cs
  osu.Game/Rulesets/Edit/DrawableEditorRulesetWrapper.cs
Labels: area:editor, size/M, next release

#26525 Fix flashlight dim being applied before slider start time
  osu.Game.Rulesets.Osu.Tests/Mods/TestSceneOsuModFlashlight.cs
  osu.Game.Rulesets.Osu/Mods/OsuModFlashlight.cs
Labels: ruleset/osu!, area:mods, size/M

#26526 Fix date failing to display on leaderboard for some scores with weird datetimes
  osu.Game/Extensions/TimeDisplayExtensions.cs
Labels: area:song-select, size/XS, type:reliability

#26522 Show "slider end" statistic next to slider ticks on results screen (and use correct colour)
  osu.Game/Graphics/OsuColour.cs
  osu.Game/Rulesets/Scoring/HitResult.cs
Labels: type:cosmetic, area:results, size/S

#26528 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#26530 Fix toolbar buttons not being clickable at screen edges
  osu.Game/Overlays/Toolbar/ToolbarButton.cs
  osu.Game/Overlays/Toolbar/ToolbarClock.cs
  osu.Game/Overlays/Toolbar/ToolbarHomeButton.cs
  osu.Game/Overlays/Toolbar/ToolbarMusicButton.cs
  osu.Game/Overlays/Toolbar/ToolbarRulesetTabButton.cs
  osu.Game/Overlays/Toolbar/ToolbarSettingsButton.cs
  osu.Game/Overlays/Toolbar/ToolbarUserButton.cs
Labels: size/L, area:toolbar

#26512 Fix glitchy path type correction for sliders in the editor
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointPiece.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointVisualiser.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderPlacementBlueprint.cs
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderSelectionBlueprint.cs
Labels: size/L

#26166 Add osu! setting to control automatic minimising on focus loss in fullscreen mode
  osu.Game/Input/ConfineMouseTracker.cs
  osu.Game/Localisation/GraphicsSettingsStrings.cs
  osu.Game/Overlays/Settings/Sections/Graphics/LayoutSettings.cs
  osu.Game/Overlays/Settings/Sections/Input/MouseSettings.cs
Labels: area:settings, size/M

#26356 Add `Statistics` bindable to `IAPIProvider` and update it from `SoloStatisticsWatcher`
  osu.Game.Tests/Visual/Online/TestSceneSoloStatisticsWatcher.cs
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Online/API/DummyAPIAccess.cs
  osu.Game/Online/API/IAPIProvider.cs
  osu.Game/Online/Solo/SoloStatisticsWatcher.cs
Labels: size/M

#26492 Fix touch device mod getting selected as a free mod in playlists
  osu.Game.Tests/Visual/Multiplayer/TestSceneFreeModSelectOverlay.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
  osu.Game/Overlays/Mods/SelectAllModsButton.cs
Labels: type:behavioural, size/M, area:playlists, area:overlay-mod-select

#26496 Fix multiplayer potentially selecting mods of wrong ruleset when starting match
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayer.cs
  osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerMatchSubScreen.cs
Labels: area:multiplayer, size/M, next release

#26536 Fix gameplay counter textures not being cached ahead of time
  osu.Game/Screens/Play/HUD/ArgonCounterTextComponent.cs
  osu.Game/Skinning/LegacySpriteText.cs
Labels: type:performance, area:skinning

#26541 Fix collection dropdown crashing when all collections are deleted at once
  osu.Game.Tests/Visual/SongSelect/TestSceneFilterControl.cs
  osu.Game/Collections/CollectionDropdown.cs
Labels: size/S, type:reliability

#26540 De-dupe displayed hits in judgement counter
  osu.Game.Tests/Visual/Gameplay/TestSceneJudgementCounter.cs
  osu.Game/Screens/Play/HUD/JudgementCounter/JudgementCountController.cs
  osu.Game/Screens/Play/HUD/JudgementCounter/JudgementCounter.cs
  osu.Game/Screens/Play/HUD/JudgementCounter/JudgementCounterDisplay.cs
Labels: area:gameplay, size/M

#26546 Fix judgement pooling not working correctly in osu!taiko and osu!mania
  osu.Game.Rulesets.Mania/UI/Stage.cs
  osu.Game.Rulesets.Osu/UI/OsuPlayfield.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs
  osu.Game/Rulesets/UI/JudgementPooler.cs
Labels: type:performance, area:gameplay, size/L

#26544 Fix background dim occasionally getting in a bad state when exiting gameplay
  osu.Game/Screens/Backgrounds/BackgroundScreenBeatmap.cs
  osu.Game/Screens/Play/Player.cs
Labels: area:gameplay, size/S

#26449 Allow interacting with playlist item buttons when not selected
  osu.Game.Tests/Visual/Multiplayer/TestSceneDrawableRoomPlaylist.cs
  osu.Game/Screens/OnlinePlay/DrawableRoomPlaylist.cs
  osu.Game/Screens/OnlinePlay/DrawableRoomPlaylistItem.cs
Labels: size/M, area:playlists

#26543 Only display offset toast when in local gameplay
  osu.Game/Screens/Play/Player.cs
  osu.Game/Screens/Play/SubmittingPlayer.cs
Labels: area:gameplay, type:cosmetic, size/S

#26287 Don't leave scores screen empty if no scores are present yet
  osu.Game.Tests/Visual/Playlists/TestScenePlaylistsResultsScreen.cs
  osu.Game/Screens/Ranking/ResultsScreen.cs
  osu.Game/Screens/Ranking/ScorePanelList.cs
Labels: area:results, size/M, area:playlists

#26538 Remember multiplayer room filter mode
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Screens/OnlinePlay/Lounge/LoungeSubScreen.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerLoungeSubScreen.cs
Labels: area:multiplayer, size/S

#26545 Fix pop-in scale transition in resume overlay affecting input area
  osu.Game.Rulesets.Osu/UI/Cursor/OsuCursor.cs
  osu.Game.Rulesets.Osu/UI/OsuResumeOverlay.cs
Labels: ruleset/osu!, area:gameplay, type:behavioural, size/M

#26178 Make mod search box text be selected when a new mod is selected/deselected
  osu.Game.Tests/Visual/UserInterface/TestSceneModSelectOverlay.cs
  osu.Game/Graphics/UserInterface/ShearedSearchTextBox.cs
  osu.Game/Overlays/Mods/ModSelectOverlay.cs
Labels: size/S, area:overlay-mod-select

#26499 Fix lag when dragging first slider control point in editor
  osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/Components/PathControlPointConnectionPiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
  osu.Game.Rulesets.Osu/Objects/SliderEndCircle.cs
  osu.Game.Rulesets.Osu/Skinning/Default/PlaySliderBody.cs
Labels: type:performance, area:editor, size/S

#26479 Rework `ArgonHealthDisplay` to use shaders
  osu.Game/Screens/Play/HUD/ArgonHealthDisplay.cs
  osu.Game/Screens/Play/HUD/ArgonHealthDisplayParts/ArgonHealthDisplayBackground.cs
  osu.Game/Screens/Play/HUD/ArgonHealthDisplayParts/ArgonHealthDisplayBar.cs
  osu.Game/osu.Game.csproj
Labels: type:performance, area:gameplay, size/L

#26557 Fix silver S/SS not being awarded correctly
  osu.Game.Tests/Rulesets/Scoring/ScoreProcessorTest.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
Labels: area:scoring, size/M, next release

#26560 Fix skin potentially being lost when opening and closing skin editor rapidly
  osu.Game.Tests/Visual/Navigation/TestSceneScreenNavigation.cs
  osu.Game/Overlays/SkinEditor/SkinEditor.cs
  osu.Game/Overlays/SkinEditor/SkinEditorOverlay.cs
Labels: size/M, area:skin-editor, next release

#26561 Fix argon health bar showing "miss" bar for bananas
  osu.Game/Rulesets/Judgements/JudgementResult.cs
  osu.Game/Rulesets/Scoring/HealthProcessor.cs
  osu.Game/Screens/Play/HUD/ArgonHealthDisplay.cs
Labels: area:gameplay, size/S

#26565 Fix some elements not showing on leaderboard scores when almost off-screen
  osu.Game/Online/Leaderboards/LeaderboardScore.cs
Labels: area:song-select, size/XS

#26562 Make spinner-top and spinner-middle2 spin at different speeds to match stable
  osu.Game.Rulesets.Osu/Skinning/Legacy/LegacyNewStyleSpinner.cs
Labels: ruleset/osu!, size/XS

#26575 Fix touch device not always activating when it should
  osu.Game.Rulesets.Osu.Tests/Mods/TestSceneOsuModTouchDevice.cs
  osu.Game/Screens/Play/PlayerTouchInputDetector.cs
Labels: type:online, area:multiplayer, size/S, next release

#26573 Fix multiple issues with `GlowingSpriteText`
  osu.Game/Graphics/Sprites/GlowingSpriteText.cs
  osu.Game/Online/Leaderboards/LeaderboardScore.cs
Labels: type:performance, size/M

#26564 Allow adjusting volume controls via a drag
  osu.Game.Tests/Visual/UserInterface/TestSceneVolumePieces.cs
  osu.Game/Overlays/Volume/VolumeMeter.cs
Labels: area:settings, size/M

#26340 Add user card with global/country ranks to login overlay
  osu.Game.Tests/Visual/Online/TestSceneUserPanel.cs
  osu.Game/Overlays/Login/LoginPanel.cs
  osu.Game/Users/ExtendedUserPanel.cs
  osu.Game/Users/UserGridPanel.cs
  osu.Game/Users/UserPanel.cs
  osu.Game/Users/UserRankPanel.cs
Labels: size/L

#26549 Fix `ColourHitErrorMeter` not loading pooled drawables ahead of time
  osu.Game/Screens/Play/HUD/HitErrorMeters/ColourHitErrorMeter.cs
Labels: type:performance, area:gameplay, size/S

#26576 Fix flashlight not dimming if slider head is hit early
  osu.Game.Rulesets.Osu.Tests/Mods/TestSceneOsuModFlashlight.cs
  osu.Game.Rulesets.Osu/Mods/OsuModFlashlight.cs
Labels: ruleset/osu!, area:mods, size/M, next release

#26579 Fix incorrect accuracy and rank population when decoding lazer replays
  osu.Game.Tests/Beatmaps/Formats/LegacyScoreDecoderTest.cs
  osu.Game/Scoring/Legacy/LegacyScoreDecoder.cs
Labels: size/L, area:import

#26502 Add guard against submitting score with invalid mod instances
  osu.Game.Tests/Mods/ModUtilsTest.cs
  osu.Game.Tests/Visual/Gameplay/TestScenePlayerLoader.cs
  osu.Game.Tests/Visual/Gameplay/TestScenePlayerScoreSubmission.cs
  osu.Game.Tests/Visual/Mods/TestSceneModAccuracyChallenge.cs
  osu.Game/Screens/Play/Player.cs
  osu.Game/Utils/ModUtils.cs
Labels: type:online, area:gameplay, size/M

#26585 Fix timing point changes not applying after selecting another one
  osu.Game.Tests/Visual/Editing/TestSceneTimingScreen.cs
  osu.Game/Screens/Edit/Timing/ControlPointTable.cs
Labels: area:editor, type:behavioural, size/M

#26578 Fix taiko maps containing only drum rolls / swells not being passable without mods
  osu.Game.Rulesets.Taiko.Tests/TaikoHealthProcessorTest.cs
  osu.Game.Rulesets.Taiko/Scoring/TaikoHealthProcessor.cs
Labels: ruleset/osu!taiko, area:gameplay, size/L

#26589 Change key overlay to use the ordering provided by rulesets
  osu.Game.Rulesets.Taiko/TaikoRuleset.cs
  osu.Game/Rulesets/UI/RulesetInputManager.cs
Labels: ruleset/osu!mania, size/XS

#26593 Change rolling counters to use quicker easing types
  osu.Game/Graphics/UserInterface/PercentageCounter.cs
  osu.Game/Graphics/UserInterface/RollingCounter.cs
  osu.Game/Overlays/Mods/BeatmapAttributesDisplay.cs
  osu.Game/Overlays/Mods/ScoreMultiplierDisplay.cs
  osu.Game/Overlays/Mods/VerticalAttributeDisplay.cs
  osu.Game/Screens/Play/HUD/ArgonAccuracyCounter.cs
  osu.Game/Screens/Play/HUD/ArgonComboCounter.cs
  osu.Game/Screens/Play/HUD/ArgonScoreCounter.cs
  osu.Game/Screens/Play/HUD/BPMCounter.cs
  osu.Game/Screens/Play/HUD/ClicksPerSecond/ClicksPerSecondCounter.cs
  osu.Game/Screens/Play/HUD/PerformancePointsCounter.cs
  osu.Game/Screens/Play/HUD/UnstableRateCounter.cs
  osu.Game/Screens/Ranking/Expanded/Statistics/AccuracyStatistic.cs
Labels: area:gameplay, type:cosmetic, size/M

#26594 Change legacy beatmap skins to not handle `@2x` textures (to match stable)
  osu.Game.Tests/NonVisual/Skinning/LegacySkinTextureFallbackTest.cs
  osu.Game/Skinning/LegacyBeatmapSkin.cs
  osu.Game/Skinning/LegacySkin.cs
Labels: area:skinning, size/M

#26603 Fix `ConstrainedIconContainer` always using masking without a reason
  osu.Game/Beatmaps/Drawables/DifficultyIcon.cs
  osu.Game/Graphics/Containers/ConstrainedIconContainer.cs
  osu.Game/Overlays/Toolbar/ToolbarRulesetTabButton.cs
Labels: size/M

#26542 Fade hold-for-menu button out completely on non-touch devices
  osu.Game/Screens/Play/HUD/HoldForMenuButton.cs
Labels: area:gameplay, size/S

#26618 Fix revert-to-default button appearing on disabled settings regardless of value
  osu.Game.Tests/Visual/Settings/TestSceneSettingsItem.cs
  osu.Game/Overlays/RevertToDefaultButton.cs
Labels: type:cosmetic, area:settings, size/S

#26587 Fix tournament beatmap backgrounds occasionally not loading
  osu.Game.Tournament/Components/SongBar.cs
  osu.Game.Tournament/Components/TournamentBeatmapPanel.cs
Labels: area:tournament, size/S

#26626 Fix changelog stream user count only accounting for latest build
  osu.Game/Online/API/Requests/Responses/APIUpdateStream.cs
  osu.Game/Overlays/Changelog/ChangelogUpdateStreamItem.cs
Labels: area:overlay-changelog, size/XS

#26636 Remove local vertex batching from triangles backgrounds
  osu.Game/Graphics/Backgrounds/Triangles.cs
  osu.Game/Graphics/Backgrounds/TrianglesV2.cs
Labels: type:performance, size/S

#26647 Enable masking for `Triangles` backgrounds where possible
  osu.Game.Rulesets.Osu/Skinning/Default/TrianglesPiece.cs
  osu.Game.Tests/Visual/Background/TestSceneTrianglesBackground.cs
  osu.Game.Tests/Visual/Background/TestSceneTrianglesV2Background.cs
  osu.Game/Graphics/Backgrounds/Triangles.cs
  osu.Game/Graphics/Backgrounds/TrianglesV2.cs
  osu.Game/Graphics/UserInterface/DialogButton.cs
  osu.Game/Overlays/Mods/ModSelectColumn.cs
Labels: type:performance, size/S

#26617 Update framework
  Templates/Rulesets/ruleset-empty/osu.Game.Rulesets.EmptyFreeform.Tests/VisualTestRunner.cs
  Templates/Rulesets/ruleset-empty/osu.Game.Rulesets.EmptyFreeform.Tests/osu.Game.Rulesets.EmptyFreeform.Tests.csproj
  Templates/Rulesets/ruleset-example/osu.Game.Rulesets.Pippidon.Tests/VisualTestRunner.cs
  Templates/Rulesets/ruleset-example/osu.Game.Rulesets.Pippidon.Tests/osu.Game.Rulesets.Pippidon.Tests.csproj
  Templates/Rulesets/ruleset-scrolling-empty/osu.Game.Rulesets.EmptyScrolling.Tests/VisualTestRunner.cs
  Templates/Rulesets/ruleset-scrolling-empty/osu.Game.Rulesets.EmptyScrolling.Tests/osu.Game.Rulesets.EmptyScrolling.Tests.csproj
  Templates/Rulesets/ruleset-scrolling-example/osu.Game.Rulesets.Pippidon.Tests/VisualTestRunner.cs
  Templates/Rulesets/ruleset-scrolling-example/osu.Game.Rulesets.Pippidon.Tests/osu.Game.Rulesets.Pippidon.Tests.csproj
  osu.Desktop/Program.cs
  osu.Desktop/osu.Desktop.csproj
  osu.Game.Benchmarks/osu.Game.Benchmarks.csproj
  osu.Game.Rulesets.Catch.Tests/osu.Game.Rulesets.Catch.Tests.csproj
  osu.Game.Rulesets.Mania.Tests/Skinning/TestSceneBarLine.cs
  osu.Game.Rulesets.Mania.Tests/osu.Game.Rulesets.Mania.Tests.csproj
  osu.Game.Rulesets.Osu.Tests/TestSceneDrawableJudgement.cs
  osu.Game.Rulesets.Osu.Tests/osu.Game.Rulesets.Osu.Tests.csproj
  osu.Game.Rulesets.Taiko.Tests/osu.Game.Rulesets.Taiko.Tests.csproj
  osu.Game.Tests/Visual/Navigation/TestSceneInterProcessCommunication.cs
  osu.Game.Tests/osu.Game.Tests.csproj
  osu.Game.Tournament.Tests/TournamentTestRunner.cs
  osu.Game.Tournament.Tests/osu.Game.Tournament.Tests.csproj
  osu.Game/OsuGame.cs
  osu.Game/Tests/CleanRunHeadlessGameHost.cs
  osu.Game/Tests/VisualTestRunner.cs
  osu.Game/osu.Game.csproj
Labels: size/L, next release

#26660 Reduce allocation overhead in `BeatmapCarousel`
  osu.Game/Screens/Select/BeatmapCarousel.cs
Labels: type:performance, area:song-select, size/XS

#26605 Simplify gameplay pause sequence
  osu.Game.Tests/Visual/Gameplay/TestScenePause.cs
  osu.Game/Beatmaps/FramedBeatmapClock.cs
  osu.Game/Screens/Play/GameplayClockContainer.cs
  osu.Game/Screens/Play/MasterGameplayClockContainer.cs
  osu.Game/Screens/Play/OffsetCorrectionClock.cs
Labels: area:gameplay, size/L

#26661 Fix blueprint container not handling right clicks correctly while moving a blueprint
  osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs
Labels: area:editor, type:behavioural, size/XS

#26659 Fix slider sometimes not updating anchor position of nested objects
  osu.Game.Rulesets.Osu.Tests/TestSceneSliderApplication.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
Labels: ruleset/osu!, size/M

#26598 Remove handling for non-legacy texture lookup paths in `LegacySkin`
  osu.Game.Rulesets.Osu/Skinning/Default/DefaultApproachCircle.cs
  osu.Game.Rulesets.Osu/Skinning/Legacy/LegacyApproachCircle.cs
  osu.Game.Rulesets.Osu/Skinning/Legacy/LegacyReverseArrow.cs
  osu.Game.Rulesets.Osu/Skinning/Legacy/OsuLegacySkinTransformer.cs
  osu.Game.Tests/NonVisual/Skinning/LegacySkinTextureFallbackTest.cs
  osu.Game/Skinning/GameplaySkinComponentLookup.cs
  osu.Game/Skinning/LegacySkin.cs
Labels: area:skinning, size/L

#26599 Fix storyboard animations stripping path directory on skin lookup
  osu.Game/Storyboards/Drawables/DrawableStoryboardAnimation.cs
Labels: area:skinning, area:storyboard, size/XS

#26607 Add ability to step forward/backwards single frames when watching replays
  osu.Game/Configuration/OsuConfigManager.cs
  osu.Game/Input/Bindings/GlobalActionContainer.cs
  osu.Game/Localisation/GlobalActionKeyBindingStrings.cs
  osu.Game/Localisation/PlayerSettingsOverlayStrings.cs
  osu.Game/Screens/Play/PlayerSettings/PlaybackSettings.cs
  osu.Game/Screens/Play/ReplayPlayer.cs
Labels: area:replay, size/L

#26662 Fix potential null reference in player screen transition handling
  osu.Game/Screens/Play/Player.cs
Labels: size/XS, type:reliability

#26600 Change frame stable catch-up method to allow for much faster sync
  osu.Game.Tests/Visual/Gameplay/TestSceneFrameStabilityContainer.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneSongProgress.cs
  osu.Game/Rulesets/UI/FrameStabilityContainer.cs
Labels: area:gameplay, size/S

#26669 Fix score submission test failures due to checking audio playback validity (again)
  osu.Game.Tests/Visual/Gameplay/TestScenePlayerScoreSubmission.cs
Labels: type:testing, size/XS

#26649 Remove `FillFlow` overhead of argon counters
  osu.Game/Screens/Play/HUD/ArgonCounterTextComponent.cs
Labels: type:performance, next release

#26648 Fix `FollowPointConnection` pool filling up when follow points are hidden
  osu.Game/Rulesets/Objects/Pooling/PooledDrawableWithLifetimeContainer.cs
Labels: type:performance, size/XS

#26591 Show offset explanation tooltip on settings offset adjust slider bar
  osu.Game/Localisation/BeatmapOffsetControlStrings.cs
  osu.Game/Overlays/Settings/Sections/Audio/AudioOffsetAdjustControl.cs
  osu.Game/Screens/Play/PlayerSettings/BeatmapOffsetControl.cs
Labels: type:cosmetic, size/S

#26609 Fix gameplay elements not correctly offsetting to avoid per-ruleset skin layout
  osu.Game/Screens/Play/HUDOverlay.cs
Labels: area:skinning, size/M

#26668 Adjust slider tick / end miss animations to be less busy
  osu.Game.Rulesets.Osu/Skinning/Argon/ArgonJudgementPiece.cs
  osu.Game/Rulesets/Judgements/DefaultJudgementPiece.cs
  osu.Game/Skinning/LegacyJudgementPieceOld.cs
Labels: area:gameplay, type:cosmetic, size/M

#26667 Fix star fountains sometimes resetting visually
  osu.Game/Screens/Menu/StarFountain.cs
Labels: type:cosmetic, size/S

#26608 Fix taiko legacy input drum animation fade not matching osu!stable
  osu.Game.Rulesets.Taiko/Skinning/Legacy/LegacyInputDrum.cs
Labels: ruleset/osu!taiko, size/S

#26677 Implement per-axis clamping in `Triangles` backgrounds
  osu.Game.Rulesets.Osu/Skinning/Default/TrianglesPiece.cs
  osu.Game.Tests/Visual/Background/TestSceneTrianglesBackground.cs
  osu.Game.Tests/Visual/Background/TestSceneTrianglesV2Background.cs
  osu.Game/Graphics/Backgrounds/Triangles.cs
  osu.Game/Graphics/Backgrounds/TrianglesV2.cs
  osu.Game/Graphics/UserInterface/DialogButton.cs
  osu.Game/Overlays/Mods/ModSelectColumn.cs
Labels: size/L

#26674 Reduce enumerator overhead in `GameplayLeaderboard`
  osu.Desktop.slnf
  osu.Game/Graphics/Containers/WaveContainer.cs
  osu.Game/Graphics/UserInterface/BreadcrumbControl.cs
  osu.Game/Graphics/UserInterface/OsuTabControl.cs
  osu.Game/Graphics/UserInterface/StarCounter.cs
  osu.Game/Online/Leaderboards/Leaderboard.cs
  osu.Game/Overlays/Chat/Listing/ChannelListing.cs
  osu.Game/Overlays/OverlayStreamControl.cs
  osu.Game/Screens/Menu/ButtonSystem.cs
  osu.Game/Screens/Play/HUD/GameplayLeaderboard.cs
  osu.Game/Screens/Play/HUD/JudgementCounter/JudgementCounterDisplay.cs
  osu.Game/Screens/Select/Carousel/DrawableCarouselBeatmapSet.cs
Labels: type:performance, size/M

#26630 Change S rank to require no miss
  osu.Game.Rulesets.Catch/Scoring/CatchScoreProcessor.cs
  osu.Game.Rulesets.Osu/Scoring/OsuScoreProcessor.cs
  osu.Game.Rulesets.Taiko/Scoring/TaikoScoreProcessor.cs
  osu.Game.Tests/Beatmaps/Formats/LegacyScoreDecoderTest.cs
  osu.Game.Tests/Database/BackgroundDataStoreProcessorTests.cs
  osu.Game.Tests/Visual/Ranking/TestSceneAccuracyCircle.cs
  osu.Game.Tests/Visual/Ranking/TestSceneResultsScreen.cs
  osu.Game/Database/BackgroundDataStoreProcessor.cs
  osu.Game/Database/StandardisedScoreMigrationTools.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Scoring/Legacy/LegacyScoreDecoder.cs
  osu.Game/Scoring/Legacy/LegacyScoreEncoder.cs
  osu.Game/Scoring/ScoreImporter.cs
  osu.Game/Scoring/ScoreManager.cs
  osu.Game/Screens/Ranking/Expanded/Accuracy/AccuracyCircle.cs
  osu.Game/Screens/Ranking/Expanded/Accuracy/RankBadge.cs
Labels: ruleset/osu!taiko, ruleset/osu!, area:scoring, size/XL

#26695 Reduce localisation overhead in `ScoreCounter`
  osu.Game/Graphics/UserInterface/ScoreCounter.cs
  osu.Game/Screens/Play/HUD/ArgonScoreCounter.cs
Labels: size/XS

#26697 Crop screenshots to scaling container
  osu.Game/Graphics/ScreenshotManager.cs
Labels: size/M

#26700 Fix crash at results screen when hidden is enabled and S rank becomes A due to miss
  osu.Game.Tests/Visual/Ranking/TestSceneAccuracyCircle.cs
  osu.Game/Screens/Ranking/Expanded/Accuracy/AccuracyCircle.cs
Labels: size/S, type:reliability, next release

#26699 Add retry loop to avoid log export failing occasionally on windows
  osu.Game/IO/MigratableStorage.cs
  osu.Game/Overlays/Settings/Sections/General/UpdateSettings.cs
  osu.Game/Utils/FileUtils.cs
Labels: area:settings, size/L

#26689 Prevent custom divisor ranges from halting divisor preset cycling
  osu.Game.Tests/Visual/Editing/TestSceneBeatDivisorControl.cs
  osu.Game/Screens/Edit/BindableBeatDivisor.cs
  osu.Game/Screens/Edit/Compose/Components/BeatDivisorControl.cs
Labels: area:editor, type:behavioural, size/S

#26711 Remove LINQ cast in `HUDOverlay`
  osu.Game/Screens/Play/HUDOverlay.cs
Labels: type:performance, size/S

#26631 Rewrite osu!taiko playfield adjustment container to keep playfield height constant
  osu.Game.Rulesets.Taiko.Tests/Skinning/TestSceneTaikoPlayfield.cs
  osu.Game.Rulesets.Taiko/Edit/Blueprints/HitPlacementBlueprint.cs
  osu.Game.Rulesets.Taiko/Edit/Blueprints/TaikoSpanPlacementBlueprint.cs
  osu.Game.Rulesets.Taiko/Mods/TaikoModFlashlight.cs
  osu.Game.Rulesets.Taiko/Skinning/Legacy/TaikoLegacyHitTarget.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfieldAdjustmentContainer.cs
Labels: type:code-quality, ruleset/osu!taiko, area:gameplay, size/L

#26632 Define constant input drum width for osu!taiko
  osu.Game.Rulesets.Taiko.Tests/Skinning/TestSceneInputDrum.cs
  osu.Game.Rulesets.Taiko/Skinning/Argon/ArgonInputDrum.cs
  osu.Game.Rulesets.Taiko/Skinning/Default/DefaultInputDrum.cs
  osu.Game.Rulesets.Taiko/Skinning/Legacy/LegacyInputDrum.cs
  osu.Game.Rulesets.Taiko/UI/InputDrum.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs
Labels: ruleset/osu!taiko, area:gameplay, area:skinning, size/M

#26634 Change hit target position in osu!taiko to always match stable
  osu.Game.Rulesets.Taiko/Mods/TaikoModClassic.cs
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs
Labels: ruleset/osu!taiko, area:gameplay, size/S

#26721 Reduce allocation overhead in `SliderInputManager.updateTracking`
  osu.Game.Rulesets.Osu/Objects/Drawables/SliderInputManager.cs
Labels: size/S

#26635 Move osu!taiko playfield down a nudge to match stable visually
  osu.Game.Rulesets.Taiko/UI/TaikoPlayfieldAdjustmentContainer.cs
Labels: ruleset/osu!taiko, area:gameplay, size/XS

#26740 Update README.md to link to new development project
  README.md
Labels: size/XS

#26704 Update logo
  Directory.Build.props
  LICENCE
  Templates/osu.Game.Templates.csproj
  assets/lazer-nuget.png
  assets/lazer.png
  osu.Android/AndroidManifest.xml
  osu.Android/Resources/drawable/ic_launcher_background.xml
  osu.Android/Resources/drawable/lazer.png
  osu.Android/Resources/drawable/monochrome.xml
  osu.Android/Resources/mipmap-anydpi-v26/ic_launcher.xml
  osu.Android/Resources/mipmap-hdpi/ic_launcher.png
  osu.Android/Resources/mipmap-hdpi/ic_launcher_foreground.png
  osu.Android/Resources/mipmap-mdpi/ic_launcher.png
  osu.Android/Resources/mipmap-mdpi/ic_launcher_foreground.png
  osu.Android/Resources/mipmap-xhdpi/ic_launcher.png
  osu.Android/Resources/mipmap-xhdpi/ic_launcher_foreground.png
  osu.Android/Resources/mipmap-xxhdpi/ic_launcher.png
  osu.Android/Resources/mipmap-xxhdpi/ic_launcher_foreground.png
  osu.Android/Resources/mipmap-xxxhdpi/ic_launcher.png
  osu.Android/Resources/mipmap-xxxhdpi/ic_launcher_foreground.png
  osu.Desktop/lazer.ico
  osu.Desktop/osu.nuspec
  osu.Game/Graphics/Backgrounds/TrianglesV2.cs
  osu.Game/Screens/Menu/OsuLogo.cs
  osu.Game/osu.Game.csproj
  osu.iOS/Assets.xcassets/AppIcon.appiconset/300076680-5cbe0121-ed68-414f-9ddc-dd993ac97e62.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iOSAppStore.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iPadApp1x.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iPadApp2x.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iPadNotification1x.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iPadNotification2x.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iPadProApp2x.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iPadSettings1x.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iPadSettings2x.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iPadSpotlight1x.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iPadSpotlight2x.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iPhoneApp2x.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iPhoneApp3x.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iPhoneNotification2x.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iPhoneNotification3x.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iPhoneSettings2x.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iPhoneSettings3x.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iPhoneSpotlight2x.png
  osu.iOS/Assets.xcassets/AppIcon.appiconset/iPhoneSpotlight3x.png
  osu.iOS/iTunesArtwork
  osu.iOS/iTunesArtwork@2x
Labels: area:main-menu, size/XL, next release

#26744 Update framework
  osu.Android.props
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/XS

#26750 Clamp logo triangles along both axes
  osu.Game/Screens/Menu/OsuLogo.cs
Labels: size/XS

#26723 Reduce allocation overhead of song progress bars
  osu.Game/Screens/Play/HUD/ArgonSongProgress.cs
  osu.Game/Screens/Play/HUD/ArgonSongProgressBar.cs
  osu.Game/Screens/Play/HUD/DefaultSongProgress.cs
  osu.Game/Screens/Play/HUD/DefaultSongProgressBar.cs
  osu.Game/Screens/Play/HUD/SongProgress.cs
  osu.Game/Screens/Play/HUD/SongProgressBar.cs
Labels: type:performance, size/L

#26724 Decouple notifications websocket handling from chat operations
  osu.Game.Tests/Chat/TestSceneChannelManager.cs
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Online/API/DummyAPIAccess.cs
  osu.Game/Online/API/IAPIProvider.cs
  osu.Game/Online/Chat/ChannelManager.cs
  osu.Game/Online/Chat/IChatClient.cs
  osu.Game/Online/Chat/WebSocketChatClient.cs
  osu.Game/Online/Notifications/NotificationsClientConnector.cs
  osu.Game/Online/Notifications/WebSocket/DummyNotificationsClient.cs
  osu.Game/Online/Notifications/WebSocket/INotificationsClient.cs
  osu.Game/Online/Notifications/WebSocket/WebSocketNotificationsClient.cs
  osu.Game/Online/Notifications/WebSocket/WebSocketNotificationsClientConnector.cs
  osu.Game/Tests/PollingChatClient.cs
  osu.Game/Tests/PollingNotificationsClient.cs
  osu.Game/Tests/PollingNotificationsClientConnector.cs
  osu.Game/Tests/TestChatClientConnector.cs
Labels: type:code-quality, type:online, size/XL

#26770 Fix `OsuPlayfield` being retained indefinitely after gameplay
  osu.Game.Rulesets.Osu/OsuInputManager.cs
  osu.Game.Tests/Visual/Gameplay/TestSceneAutoplay.cs
  osu.Game.Tests/Visual/Gameplay/TestScenePlayerLocalScoreImport.cs
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayer.cs
  osu.Game.Tests/Visual/Navigation/TestScenePresentScore.cs
  osu.Game.Tests/Visual/Playlists/TestScenePlaylistsResultsScreen.cs
  osu.Game.Tests/Visual/Ranking/TestSceneResultsScreen.cs
  osu.Game/OsuGameBase.cs
  osu.Game/Rulesets/Difficulty/PerformanceBreakdownCalculator.cs
  osu.Game/Rulesets/Difficulty/PerformanceCalculator.cs
  osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs
  osu.Game/Rulesets/Objects/HitObject.cs
  osu.Game/Rulesets/UI/RulesetInputManager.cs
  osu.Game/Scoring/ScorePerformanceCache.cs
  osu.Game/Screens/OnlinePlay/Playlists/PlaylistsResultsScreen.cs
  osu.Game/Screens/Play/SpectatorResultsScreen.cs
  osu.Game/Screens/Ranking/Expanded/Statistics/PerformanceStatistic.cs
  osu.Game/Screens/Ranking/ResultsScreen.cs
  osu.Game/Screens/Ranking/SoloResultsScreen.cs
  osu.Game/Screens/Ranking/Statistics/PerformanceBreakdownChart.cs
Labels: priority:0, size/L, next release

#25480 Add two factor authentication flow
  osu.Game.Tests/Visual/Gameplay/TestScenePlayerLocalScoreImport.cs
  osu.Game.Tests/Visual/Menus/TestSceneLoginOverlay.cs
  osu.Game.Tests/Visual/Menus/TestSceneToolbarUserButton.cs
  osu.Game.Tests/Visual/Online/TestSceneAccountCreationOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneCommentActions.cs
  osu.Game.Tests/Visual/Online/TestSceneFavouriteButton.cs
  osu.Game.Tests/Visual/Online/TestSceneSoloStatisticsWatcher.cs
  osu.Game.Tests/Visual/Online/TestSceneUserProfileOverlay.cs
  osu.Game.Tests/Visual/Online/TestSceneVotePill.cs
  osu.Game.Tests/Visual/UserInterface/TestSceneCommentEditor.cs
  osu.Game/Online/API/APIAccess.cs
  osu.Game/Online/API/DummyAPIAccess.cs
  osu.Game/Online/API/IAPIProvider.cs
  osu.Game/Online/API/Requests/GetMeRequest.cs
  osu.Game/Online/API/Requests/GetUserRequest.cs
  osu.Game/Online/API/Requests/ReissueVerificationCodeRequest.cs
  osu.Game/Online/API/Requests/Responses/APIMe.cs
  osu.Game/Online/API/Requests/VerifySessionRequest.cs
  osu.Game/Online/OnlineStatusNotifier.cs
  osu.Game/Online/OnlineViewContainer.cs
  osu.Game/Overlays/AccountCreationOverlay.cs
  osu.Game/Overlays/Login/LoginForm.cs
  osu.Game/Overlays/Login/LoginPanel.cs
  osu.Game/Overlays/Login/SecondFactorAuthForm.cs
  osu.Game/Overlays/Toolbar/ToolbarUserButton.cs
  osu.Game/Tests/Visual/OsuGameTestScene.cs
Labels: type:online, size/XL

#26751 Fix score processor no longer applying results when failing in multiplayer match
  osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerPlayer.cs
  osu.Game/Rulesets/Scoring/ScoreProcessor.cs
  osu.Game/Screens/OnlinePlay/Multiplayer/MultiplayerPlayer.cs
Labels: area:gameplay, area:multiplayer, size/M, next release

#26772 Update framework
  osu.Android.props
  osu.Game/Screens/Backgrounds/BackgroundScreenDefault.cs
  osu.Game/osu.Game.csproj
  osu.iOS.props
Labels: size/S

#26698 Reduce sliding sample allocations in `DrawableSlider`
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSpinner.cs
Labels: type:performance, size/XS

#26616 Remove rounding of slider velocity (when applied as scroll speed)
  osu.Game/Beatmaps/ControlPoints/EffectControlPoint.cs
  osu.Game/Screens/Edit/Timing/EffectSection.cs
Labels: area:gameplay, size/S, next release

#26703 Adjust slider tick / end defaults again
  osu.Game.Rulesets.Mania/Skinning/Argon/ArgonJudgementPiece.cs
  osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderTick.cs
  osu.Game.Rulesets.Osu/OsuRuleset.cs
  osu.Game.Rulesets.Osu/Skinning/Argon/ArgonJudgementPiece.cs
  osu.Game.Rulesets.Osu/Skinning/Argon/ArgonJudgementPieceSliderTickMiss.cs
  osu.Game.Rulesets.Osu/Skinning/Argon/ArgonSliderScorePoint.cs
  osu.Game.Rulesets.Osu/Skinning/Argon/OsuArgonSkinTransformer.cs
  osu.Game.Rulesets.Osu/Skinning/Default/DefaultJudgementPieceSliderTickMiss.cs
  osu.Game.Rulesets.Osu/Skinning/Default/OsuTrianglesSkinTransformer.cs
  osu.Game.Rulesets.Taiko/Skinning/Argon/ArgonJudgementPiece.cs
  osu.Game/Graphics/OsuColour.cs
  osu.Game/Rulesets/Judgements/DefaultJudgementPiece.cs
  osu.Game/Rulesets/Judgements/TextJudgementPiece.cs
  osu.Game/Rulesets/Scoring/HitResult.cs
  osu.Game/Skinning/LegacyJudgementPieceOld.cs
Labels: ruleset/osu!, size/L, next release

#26773 Fix osu! logo being mispositioned in song select on very wide resolutions
  osu.Game/Screens/Menu/OsuLogo.cs
  osu.Game/Screens/OsuScreen.cs
  osu.Game/Screens/Select/SongSelect.cs
Labels: area:song-select, type:cosmetic, size/S, next release

#26780 Fix incorrect handling of `StartChatRequest` in websocket chat client
  osu.Game/Online/Chat/WebSocketChatClient.cs
Labels: type:online, area:overlay-chat, size/M, type:reliability, next release

#26785 Make `LegacyScoreDecoder.PopulateMaximumStatistics()` public
  osu.Game/Scoring/Legacy/LegacyScoreDecoder.cs
Labels: area:scoring, size/XS

#26790 Reduce allocation overhead in mania's `ColumnFlow`
  osu.Game.Rulesets.Mania.Tests/TestSceneStage.cs
  osu.Game.Rulesets.Mania/UI/ColumnFlow.cs
  osu.Game.Rulesets.Mania/UI/ManiaPlayfield.cs
  osu.Game.Rulesets.Mania/UI/Stage.cs
Labels: type:performance, size/M

#26788 Reduce allocation overhead in `ScrollingHitObjectContainer`
  osu.Game/Rulesets/UI/Scrolling/ScrollingHitObjectContainer.cs
Labels: size/XS

#26797 Update endpoints to final production endpoints
  osu.Game/Online/EndpointConfiguration.cs
  osu.Game/Online/ExperimentalEndpointConfiguration.cs
  osu.Game/OsuGameBase.cs
Labels: type:online, size/M

#26839 Fix legacy animated judgements not fading out correctly
  osu.Game/Skinning/LegacyJudgementPieceOld.cs
Labels: ruleset/osu!, area:skinning, size/XS

#26871 Show a better message when score submission fails due to system clock being set wrong
  osu.Game/Screens/Play/SubmittingPlayer.cs
Labels: type:online, size/S, next release

#26870 Adjust default min result of SliderTailHit, remove override
  osu.Game.Rulesets.Osu/Objects/SliderTailCircle.cs
  osu.Game/Rulesets/Judgements/Judgement.cs
  osu.Game/Rulesets/Scoring/HitResult.cs
Labels: type:code-quality, area:scoring, size/XS

#26834 Fix crash when logging out during 2FA email verification
  osu.Game/Online/API/OAuth.cs
Labels: type:online, size/S, type:reliability, next release

#26876 Adjust slider tick / end misses to show slightly longer
  osu.Game.Rulesets.Osu/Skinning/Argon/ArgonJudgementPieceSliderTickMiss.cs
  osu.Game.Rulesets.Osu/Skinning/Default/DefaultJudgementPieceSliderTickMiss.cs
  osu.Game/Skinning/LegacyJudgementPieceOld.cs
Labels: ruleset/osu!, size/XS, next release

#26837 Fix 2FA verification via link not working correctly
  osu.Game/Online/Notifications/WebSocket/WebSocketNotificationsClientConnector.cs
  osu.Game/Online/PersistentEndpointClientConnector.cs
Labels: type:online, size/S, next release

#26885 Fix slider end judgements appearing at incorrect locations when mods that flip playfield are active
  osu.Game.Rulesets.Osu.Tests/OsuHitObjectGenerationUtilsTest.cs
  osu.Game.Rulesets.Osu/Objects/Slider.cs
Labels: ruleset/osu!, area:gameplay, size/S, next release

#26889 Fix menu banner not updating as often as we want it to
  osu.Game/Online/API/Requests/GetSystemTitleRequest.cs
Labels: size/XS
